JENKINS-29780 - added flatten option for ArtifactArchiver and new flattening DirScanner
jenkinsci/jenkins pull request #1948
Opened 2015-12-07 17:44 UTC by abayer

cc @reviewbybees

I'm not 100% confident in the `DirScanner.FlattenGlob` behavior - it makes sense on the face of it, but something doesn't quite smell right.

2015-12-07 17:46 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2015-12-07 17:50 UTC, daniel-beck commented
Please don't include changelog entries in your PRs, they only lead to merge conflicts or wrong insertion points after a week. Also, changelog entries should, if relevant to users, be understandable to them.

2015-12-07 17:51 UTC, daniel-beck commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +            flattenDirectories = false;
Could just be a `boolean` then. This is only needed if the default isn't `false`.

2015-12-07 17:52 UTC, daniel-beck commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        String simpleFile = soloFile.getKey().replaceFirst(".+/", "");
Does the pattern support Windows-style backslashes?

2015-12-07 17:53 UTC, daniel-beck commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                            throw new AbortException("Attempted to add duplicate filenames to flattened archive. " +
Seems to me this should be configurable (e.g. use deterministic first, use deterministic last, abort)

2015-12-07 17:53 UTC, daniel-beck commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        msg = ws.validateAntFileMask(artifacts, FilePath.VALIDATE_ANT_FILE_MASK_BOUND, caseSensitive);
Unnecessary whitespace changes.

2015-12-07 17:54 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/config.jelly
> +      <f:checkbox title="${%flattenDirectories" default="false"/>
Missing closing curly brace.

2015-12-07 17:54 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-flattenDirectories.html
> +  Optionally flatten directories to be archived, so that all archived files are
Inconsistent indentation.

2015-12-07 17:55 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-flattenDirectories.html
> +    there are files with identical filenames to be archived.
Could this be improved by writing *multiple files with the same name* or something similar?

2015-12-07 17:56 UTC, KostyaSha commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> -import org.kohsuke.stapler.StaplerRequest;
don't reorder?;)

2015-12-07 17:57 UTC, KostyaSha commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    private Boolean flattenDirectories = false;
After deserialization and before first assignment it will be null, so `Nonnull` lies.

2015-12-07 17:57 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +            flattenDirectories = false;
Okiedokie.

2015-12-07 17:57 UTC, KostyaSha commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    private Boolean flattenDirectories = false;
Found, readResolve, it was collapsed.

2015-12-07 17:58 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        String simpleFile = soloFile.getKey().replaceFirst(".+/", "");
Yes! `ListFiles.invoke(...)` converts `File.separatorChar` to `/`.

2015-12-07 17:58 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                            throw new AbortException("Attempted to add duplicate filenames to flattened archive. " +
Good thought.

2015-12-07 17:59 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        msg = ws.validateAntFileMask(artifacts, FilePath.VALIDATE_ANT_FILE_MASK_BOUND, caseSensitive);
Argh, whitespace formatting standards + intellij...I'll see what I can do.

2015-12-07 17:59 UTC, abayer commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/config.jelly
> +      <f:checkbox title="${%flattenDirectories" default="false"/>
durrr.

2015-12-07 17:59 UTC, oleg-nenashev commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    @DataBoundSetter public final void setFlattenDirectories(boolean flattenDirectories) {
This file uses different codestyle. Keep the annotation on a separate line

2015-12-07 17:59 UTC, abayer commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-flattenDirectories.html
> +  Optionally flatten directories to be archived, so that all archived files are
Battling Intellij's indent styles. I'll edit it outside of Intellij to get that right.

2015-12-07 18:00 UTC, daniel-beck commented on core/src/main/java/hudson/util/DirScanner.java
> +     * the {@code relativePath} sent to the {@link FileVisitor} will be {@code dir/file} if {@code includes} is blank
This entire comment seems to be copy&pasted without actually applying to this class (or does it?)

2015-12-07 18:00 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> -import org.kohsuke.stapler.StaplerRequest;
Intellij. =) Will see what I can do to straighten that out.

2015-12-07 18:00 UTC, oleg-nenashev commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                            throw new AbortException("Attempted to add duplicate filenames to flattened archive. " +
I would expect it to be a warning by default

2015-12-07 18:00 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    private Boolean flattenDirectories = false;
Yeah, I'll be redoing this as just a `boolean` at @daniel-beck's suggestion.

2015-12-07 18:00 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/DirScanner.java
> +     */
Add <code>@since TODO</code>

2015-12-07 18:01 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    @DataBoundSetter public final void setFlattenDirectories(boolean flattenDirectories) {
Look up - I copy-pasted/edited it, and the other setters have it on the same line.

2015-12-07 18:01 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/DirScanner.java
> +            if(dir.exists()) {
Should it throw an error if the directory does not exist?

2015-12-07 18:01 UTC, abayer commented on core/src/main/java/hudson/util/DirScanner.java
> +     * the {@code relativePath} sent to the {@link FileVisitor} will be {@code dir/file} if {@code includes} is blank
...yes. Oops. Will edit.

2015-12-07 18:01 UTC, abayer commented on core/src/main/java/hudson/util/DirScanner.java
> +     */
Yarp. Rewriting it.

2015-12-07 18:02 UTC, abayer commented on core/src/main/java/hudson/util/DirScanner.java
> +            if(dir.exists()) {
Good question. `DirScanner.Glob` doesn't - should we change that behavior?

2015-12-07 18:43 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        msg = ws.validateAntFileMask(artifacts, FilePath.VALIDATE_ANT_FILE_MASK_BOUND, caseSensitive);
Arrrrrrgh. Is this really worth worrying about? These weren't indented by the standard depth in the first place...

2015-12-07 18:44 UTC, abayer commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-flattenDirectories.html
> +    there are files with identical filenames to be archived.
Yeah, makes sense.

2015-12-07 18:45 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> -import org.kohsuke.stapler.StaplerRequest;
Ok, legitimate question - Intellij is going to reorder this crap in some way so long as it's set to handle imports for me. Unsurprisingly, our imports are chaotic as is. Should I really be worrying about this or just shrug and move on, accepting the diffs?

2015-12-07 18:46 UTC, abayer commented
FYI, squashed, fixed some of the concerns (more to come), force-pushed.

2016-01-27 17:26 UTC, abayer commented
ping @reviewbybees

2016-01-27 17:33 UTC, jtnord commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        String simpleFile = soloFile.getKey().replaceFirst(".+/", "");
surely `.*/`  - you may be trying to archive directly from root (lord knows why but `/bob` should map to `bob` and not `/bob`)....

2016-01-27 17:35 UTC, jtnord commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                            throw new AbortException("Attempted to add duplicate filenames to flattened archive. " +
I disagree with oleg :-)
Aborting is the right thing by default in the abscence of anything else.  Logs don;t get read and often by the time out find out someone else introduced a "updateDB.sh" its too late and your production server is messed up as it picked the wrong one and continued the rest of the pipeline...

2016-01-27 17:42 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +                        String simpleFile = soloFile.getKey().replaceFirst(".+/", "");
Hrm. I guess so?

2016-01-27 17:47 UTC, abayer commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-flattenDirectories.html
> +  Optionally flatten directories to be archived, so that all archived files are
Screw it, indent hell...

2016-01-27 17:48 UTC, abayer commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> -import org.kohsuke.stapler.StaplerRequest;
Yeah, screw it, Intellij orders stuff like Intelilj orders stuff.

2016-06-10 07:30 UTC, oleg-nenashev commented
merge conflict

2016-10-14 12:49 UTC, abayer commented
Just remembered this, resolved the merge conflict.

2016-10-15 20:06 UTC, oleg-nenashev commented
Is it still WiP? Seems "no"

2016-10-15 20:11 UTC, oleg-nenashev requested changes
@abayer Thanks for pinging. Minor 🐛 , but mostly ready to go

2016-10-15 20:11 UTC, oleg-nenashev commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    public boolean isFlattenDirectories() {
Javadoc is missing

2016-10-15 20:11 UTC, oleg-nenashev commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    @DataBoundSetter public final void setFlattenDirectories(boolean flattenDirectories) {
Up to you. I'd rather fix it

2016-10-15 20:11 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/DirScanner.java
> +        public FlattenGlob(String includes, String excludes, boolean useDefaultExcludes) {
Explicit <code>@Nonnull</code>?

2016-10-15 20:11 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/DirScanner.java
> +            if(dir.exists()) {
I would just add TODO to think about it in the future.
But 🐛 since the code does not ensure the file is actually a directory

2016-10-15 20:11 UTC, oleg-nenashev commented on core/src/main/java/hudson/tasks/ArtifactArchiver.java
> +    public boolean isFlattenDirectories() {
🐜

2017-04-25 15:41 UTC, abayer commented
Closing this off - `archiveArtifacts` does the trick in the modern world.

2017-04-25 15:41 UTC, closed without merging

2017-04-25 20:37 UTC, jglick commented
How is that related?

2017-04-26 13:20 UTC, daniel-beck commented
> modern world

A reminder of what the real world looks like: http://stats.jenkins.io/jenkins-stats/svg/201703-jobs.svg