JENKINS-18349, JENKINS-15512,  Added Apache Ivy as a plugin to Jenkin…
jenkinsci/jenkins pull request #2374
Opened 2016-05-25 20:33 UTC by KrestenKjaer

Adding Ivy as a dependency to Jenkins Core will allow @Grab annotations (part of core groovy) to work in the Jenkins Script console.

Example:
```
@Grab(group='org.codehaus.groovy.modules.http-builder', module='http-builder', version='0.7' )
def http = new groovyx.net.http.HTTPBuilder('http://www.codehaus.org')
println http
```

Before:

> java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
> 	at java.lang.Class.getMethods(Class.java:1615)
> 	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
> 	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)

After:

> groovyx.net.http.HTTPBuilder@9cebc79

2016-05-26 09:30 UTC, jtnord commented
Does this have the possibility of breaking plugins like the [ivy plugin](https://wiki.jenkins-ci.org/display/JENKINS/Ivy+Plugin) when the versions skew?
Could this not be implemented as a plugin?  (does the same exception occur if the ivy plugin is installed for instance?)

2016-05-26 10:14 UTC, KrestenKjaer commented
I don't think this can be implemented as a plugin. As the Jenkins Script console uses the Jenkins classloader. (I am not 100% on this.)

There are potential conflicts with the Ivy plugin, if that project upgrades their Ivy version. The plugin classloader will still be able to see the Ivy artifact in Jenkins Core.

To avoid this, the ivy-plugin should set their dependency on apache Ivy as a provided dependency in build.gradle .

2016-05-26 13:09 UTC, olivergondza commented
Can we be sure it is not going to affect anything outside the shell itself? I have no idea how grapes are implemented but leaked context classloader comes to mind at least.

I vote for the plugin approach (I can use plugin annotations in `/script` just fine).

2016-05-26 14:17 UTC, KrestenKjaer commented
@olivergondza It _should_ affect stuff outside of the shell. Grapes is part of groovy, so this will add support wherever groovy is used for scripting. 

The groovy support as of right now is broken, and there are a lot of issues relating to grapes. Try searching for @grab in the issue tracker:
https://issues.jenkins-ci.org/browse/JENKINS-26192?jql=text%20~%20%22grape%22

All of the tests were successful.

2016-05-27 08:50 UTC, oleg-nenashev commented
IIRC Grab support was under consideration for Jenkins 2, but was rejected. 
I think it makes sense to discuss the approach with @arothian. Release of the new major release of Ivy plugin should be an option. It may also require some bits from the non-existing API Deprecation engine to provide smooth migration to users.

2016-05-27 13:04 UTC, KrestenKjaer commented
@oleg-nenashev Could you provide a link to the discussions?

2016-06-10 22:48 UTC, oleg-nenashev commented
@KrestenKjaer 
Sorry, missed the comment. Links:
* https://groups.google.com/forum/#!msg/jenkinsci-users/28P-9l9eJk4/bJwdu8DpCwAJ
* https://groups.google.com/forum/#!msg/jenkinsci-users/zumJlQ27GBU/jT_zdHnaBAAJ

2016-08-19 17:34 UTC, jglick commented
Seems dangerous to do prior to JENKINS-29068.

2016-08-19 19:06 UTC, jglick commented
https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/9 seems to offer a workaround for users of existing Jenkins releases.

2016-09-03 12:16 UTC, oleg-nenashev commented
@jglick Do you feel this PR should be integrated?

2016-09-04 13:33 UTC, batmat commented
I guess @jglick doesn't according to "Seems dangerous to do prior to JENKINS-29068"

2017-03-19 18:17 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers any additional votes?

2017-03-19 18:19 UTC, oleg-nenashev commented
Maybe the functionality should be kept in the `Ivy` Jenkins Module then. Or in the pluggable core plugin once @kohsuke finishes https://github.com/jenkinsci/jenkins/pull/2754 . I am not comfortable about picking such dep after the review of transient dependencies

2017-03-20 01:07 UTC, daniel-beck commented
We probably need sane classloader isolation first before doing something like this.

2018-03-04 01:48 UTC, oleg-nenashev requested changes
The correct way in 2018 would be to introduce an API plugin for that. In such case it will be possible to use it in Script Console even if the plugin is not installed. Probably it is also not needed since core plugins like Pipeline Shared Libraries bundle the library. This plugin has more than 100,000 installations by now... and other plugins have CVS Plugin I'd guess.

2018-03-04 02:19 UTC, oleg-nenashev commented
@KrestenKjaer feel free to reopen it if you disagree with my justification above

2018-03-04 02:19 UTC, closed without merging

2020-02-06 22:20 UTC, darxriggs commented
It would also be useful in https://github.com/jenkinsci/groovy-events-listener-plugin which currently packages Groovy + Ivy to be able to support `@Grab`.

2020-02-11 19:06 UTC, jglick commented
If `workflow-cps-global-lib` is installed, you can use Grape. Perhaps it should be split to a common plugin.