[JENKINS-34670] Add support for a new full screen layout
jenkinsci/jenkins pull request #2445
Opened 2016-07-10 19:16 UTC by recena

[JENKINS-34670](https://issues.jenkins-ci.org/browse/JENKINS-34670)

2016-07-10 19:31 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-07-15 07:20 UTC, oleg-nenashev commented
Looks good to me. 👍 and 🐝 
By the way, it may a bit affect users, who bundle custom Javascripts to headers and footers. Maybe makes sense to keep empty header and footer tags then

2016-07-15 08:05 UTC, recena commented
@oleg-nenashev This kind of things should not do. This layout is thought specially for:

- Dashboard
- To replace the page when Jenkins is restarting, and avoid the side-effect of resource not loaded
- Maybe the InstallWizard (@kzantow)
- etc...

2016-07-16 19:18 UTC, oleg-nenashev commented
@reviewbybees done BTW
@jenkinsci/code-reviewers I would appreciate additional feedback

2016-07-17 00:31 UTC, daniel-beck commented
:-1: until the following questions are answered:

* Isn't that what `/lib/layout/html` does? Why not just use that?
* There's no rationale for this change. Why no headers/footers? I get that we may not want a side panel, but nothing?
* How is one supposed to navigate away from such pages? The example *About* page shows it's a dead end with no way to return, seems like a messy, unusable approach.

2016-07-17 09:57 UTC, oleg-nenashev commented
Back to needs-review after the comment from @daniel-beck

2016-07-17 20:40 UTC, kzantow commented
@daniel-beck `/lib/layout/html` should (and will) be removed in favor of this approach. the about page would use the one-column view, the no header/footer is for illustrative purposes only, which would replace the `/lib/layout/html`

:bee: from me on this change

2016-07-17 21:13 UTC, daniel-beck commented
@kzantow 

> should … be removed in favor of this approach.

There's still no rationale for this change besides asserting it's the right thing to do. As I wrote,

> piling on options in lib/layout for exceptional pages like those without headers/footers [may] result in maintenance problems later

2016-07-22 14:25 UTC, recena commented
@reviewbybees done

2016-07-22 14:33 UTC, reviewbybees commented
This pull request has completed our internal processes and we now respectfully request the maintainers of this repository to consider our proposal contained within this pull request for merging.

2016-07-22 16:16 UTC, recena commented
@daniel-beck It seems there are 3 persons, included the person who added the `html.jelly`, agree with this is the right way to implement several layouts (included the full screen).

2016-07-22 16:19 UTC, recena commented
If I provided a way to include support for several layout types, was precisely to avoid hacks that we can see in Jenkins core and plugins.

2016-07-22 21:17 UTC, daniel-beck commented
@recena 

> there are 3 persons [who agree] this is the right way to implement several layouts

And yet none of them managed to explain _why_ it's a better approach, or even just addressed my specific concern above. There's only repeated assertions (another one from you just now) that this is the correct approach.

2016-07-22 21:52 UTC, kzantow commented
@daniel-beck it's a better approach because it consolidates the style/script includes and resource references to a single file, instead of having to update 2 any time we might change them. And plugins could use this instead of defining local style overrides to hide the stuff, there's a common method of doing so.

2016-07-22 22:15 UTC, daniel-beck commented
@kzantow 

Thank you! I feel we're getting closer to a result.

> it consolidates the style/script includes and resource references to a single file

This PR does not remove `html.jelly`, so there are no such benefits.

> plugins could use this instead of defining local style overrides to hide the stuff

They can use `html.jelly` -- they may even already do so, because nowhere does it state that it's not fit for use from plugins.

So, to recap:

* All the benefits of this change only apply if `html.jelly` gets removed.
* `html.jelly` doesn't get removed.
* In fact, it may be not possible to remove it, as it's effectively part of Jenkins' public plugin API now.

2016-07-22 22:19 UTC, kzantow commented
@daniel-beck so, we could modify `html.jelly` to include the `layout.jelly` with the appropriate parameter to make it equivalent, probably remove the `html.jelly` usage in the setup wizard, and then figure out a way to deprecate it later.

2016-07-22 22:49 UTC, recena commented
@daniel-beck 

This is a step to remove `html.helly` and provide a right way to provide full-screen layout. This step belongs to a more general solution that started few months ago.

2016-07-22 22:50 UTC, recena commented
@kzantow Thanks for your assistance. My internet connection is very limited on these days.

2016-07-22 23:08 UTC, daniel-beck commented
@kzantow Good idea. I think this should be fine if it included that change so there's actually a benefit to merging this.

2016-08-08 08:12 UTC, oleg-nenashev commented
So it's ready to merge from what I see

2016-08-08 08:27 UTC, recena commented
@oleg-nenashev From my side it is ready to merge but I understand @daniel-beck wants to see a real usage of that. My recommendation is to prepare a new PR.

2016-08-08 10:05 UTC, daniel-beck commented
@oleg-nenashev @recena  I'd like to see actual applications of this code included in this same PR. Too much unused infrastructure in Jenkins as-is.

2016-08-08 10:25 UTC, recena commented
@daniel-beck If I do it, this PR will be more difficult to review. The use cases are clear and were explained in this PR.

> Too much unused infrastructure in Jenkins as-is.

What do you mean? Examples?

In the UI, any cleanup or attempt to unify ways to do the things, should be considered. I don't know how this could be considered an `unused infrastructure`, especially when one of its goals it is precisely to remove code (I'd say _hacks_) that is not usable.

2016-08-13 11:23 UTC, daniel-beck commented
@recena

> What do you mean? Examples?

How about #1788 which was implemented for basically the same purpose that is now served by #2323 and has no known applications? Once we add something, we cannot easily remove it anymore, so we should make sure we're adding the right thing, in the right way. 

There are no views actually making use of this change. Make it a new commit, or a separate PR, or a PR to a plugin if you're worried about reviewability, but do _something_ with the new layout you're adding here.

> any cleanup or attempt to unify ways to do the things, should be considered.

There's no cleanup here. That's the problem. You're just getting a mop and bucket but don't do anything with them, so they just clutter up the room.

2016-10-02 18:40 UTC, recena commented
@daniel-beck 

> There's no cleanup here. That's the problem. You're just getting a mop and bucket but don't do anything with them, so they just clutter up the room.

Not everyone sees the same dirt 😄

2016-10-02 18:42 UTC, recena commented
I think this PR is ready to be merge.

2016-11-14 16:35 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-11-19 22:19 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers Seems some voting is required

2016-11-19 22:25 UTC, daniel-beck commented
:-1: while there's no application for this. We carry around too much crap that's not used by anyone already

2016-11-21 22:46 UTC, recena commented
@daniel-beck Ok.

more feedback is welcome @jenkinsci/code-reviewers

2016-11-21 22:47 UTC, recena commented
@oleg-nenashev IMO, the label `needs-fix` is not correct. Nothing is needed to fix.

2016-11-21 22:48 UTC, recena commented
@daniel-beck How it works in this OSS project? I need to get votes?

2016-11-21 22:53 UTC, recena commented
@daniel-beck I'll send a new PR where you could see the usage. I'm trying to avoid a *big* PR.

2016-11-21 23:17 UTC, daniel-beck commented
@recena 

> I'm trying to avoid a *big* PR

Me, months ago:

> Make it a new commit, or a separate PR, or a PR to a plugin if you're worried about reviewability, but do *something* with the new layout you're adding here.

2016-11-22 00:02 UTC, recena commented
> if you're worried about reviewability

I'm worry about improving the UI of this project 😄

2016-12-15 22:52 UTC, oleg-nenashev commented
I have a use-case for it: adding a blank layout (one-column, no header and footer). I used it a couple of times for IFraming of particular Jenkins pages. Maybe it could be a valid case

2016-12-15 23:02 UTC, daniel-beck commented
I don't know why this appears to be stalled. To clarify, I just pointed out that

> I'll send a new PR where you will be able to see the usage.

is exactly what I was asking for the entire time.

2016-12-15 23:07 UTC, oleg-nenashev commented
Maybe I will provide the usage in the core later. Reassigning to myself

2017-02-12 10:40 UTC, oleg-nenashev commented
@recena Should I go forward with the reference impl? During the private chat on Dec you said you will do it on your own, but it has not happened yet

2017-02-12 13:20 UTC, recena commented
@oleg-nenashev You are totally right. From now on, I believe I will have more spare time for my personal contribution. Please, give me an one chance more. Ok?

2017-02-26 13:51 UTC, recena commented
@daniel-beck As part of this PR I've re-visited how the Setup Wizard implements the full-screen concept. Now, it uses what this PR propones.

2017-02-26 13:53 UTC, recena commented on core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
> +  <l:layout norefresh="true" type="full-screen" title="${it.displayName}">
How this step of the Setup Wizard is managed (by using a `iframe`) needs to be changed.

2017-02-26 13:56 UTC, recena commented on core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
> +     <div id="create-admin-user">
More robust while removing the usage of `iframe`

2017-02-26 13:58 UTC, recena commented on core/src/main/resources/lib/layout/html.jelly
> -<!--
This file only had sense for the Setup Wizard and was a copy of `layout.jelly`. It was created for implementing the full screen layout. Now, different layouts can be managed through `layout.jelly`.

2017-02-26 13:59 UTC, recena commented
@oleg-nenashev @daniel-beck Waiting for your final thoughts.

2017-02-26 15:58 UTC, kzantow requested changes

2017-02-26 15:58 UTC, kzantow commented on core/src/main/resources/jenkins/install/SetupWizard/proxy-configuration.jelly
> +<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:d="jelly:define" xmlns:l="/lib/layout" xmlns:t="/lib/hudson" xmlns:s="/lib/form">
Need `xmlns:f="/lib/form"`

2017-02-26 16:08 UTC, recena commented on core/src/main/resources/jenkins/install/SetupWizard/proxy-configuration.jelly
> +<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:d="jelly:define" xmlns:l="/lib/layout" xmlns:t="/lib/hudson" xmlns:s="/lib/form">
Great catch. Is this jelly used currently?

2017-02-26 20:08 UTC, recena commented
Unit tests have passed.

2017-02-26 20:09 UTC, recena commented
@kzantow Are the changes fine for you?

2017-02-27 04:53 UTC, kzantow commented on core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
> +  <l:layout norefresh="true" type="full-screen" title="${it.displayName}">
why, exactly?

2017-02-27 04:54 UTC, kzantow approved these changes
👍  LGTM

2017-02-27 09:16 UTC, recena commented on core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
> +  <l:layout norefresh="true" type="full-screen" title="${it.displayName}">
@kzantow I think we should not use `iframes`. I would like to work on a proposal based on a wizard (flow) with _real_ steps / states, where we can have a URL per state.

2017-02-28 23:08 UTC, daniel-beck commented
Tons of unnecessary whitespace/line break changes even in `?w=1` diff.

2017-02-28 23:14 UTC, daniel-beck commented
Regression in the layout of the *Configure Proxy* dialog (no margin), possibly others. I don't like that (based on previous comments) this apparently wasn't tested?

> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23438824/f4cd7492-fe13-11e6-8ca6-ae2a1a7c705d.png)

> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23438825/f949ea00-fe13-11e6-9164-1fdd57ccdde8.png)

2017-03-01 12:28 UTC, recena commented
@daniel-beck Good catch.

Precisely this step needs also to be revisited:

1. Different space (margin) configuration in comparison with other steps
1. Different font configuration

2017-03-04 22:45 UTC, daniel-beck commented on core/src/main/resources/lib/layout/layout.jelly
> +      Available values: two-column (by default), one-column (full-width size) or full-screen.
Should mention which versions introduced these options, with the new one being `(since TODO)`

2017-03-04 23:22 UTC, recena commented on core/src/main/resources/lib/layout/layout.jelly
> +      Available values: two-column (by default), one-column (full-width size) or full-screen.
@daniel-beck I can do it but I never saw this annotation of jelly tag.

2017-03-04 23:25 UTC, recena commented on core/src/main/resources/lib/layout/layout.jelly
> +      Available values: two-column (by default), one-column (full-width size) or full-screen (since TODO).
`since TODO` was asked by @daniel-beck

2017-03-13 09:52 UTC, recena commented
@daniel-beck ping?

2017-03-13 12:50 UTC, daniel-beck commented
I think this is the wrong approach (couldn't `/lib/layout` just inherit from from `/lib/html` for headers etc?), but now there's nothing obviously broken anymore AFAICT.

2017-03-14 14:43 UTC, daniel-beck commented
To clarify my previous comment, I'm not blocking this. My concerns were addressed. I should have written…

> I'm not convinced this is the right approach.

My review position is therefore ±0.

2017-03-14 14:56 UTC, recena commented
@daniel-beck thanks.

2017-03-15 12:33 UTC, oleg-nenashev requested changes
I disagree with removal of `lib/layout/html.jelly ` in such way. Even if it does not make sense for other usages (proof?), it was a part of the Jenkins API for Jelly, which is documented in Jenkins TagLib documentation. This TagLib site is not being hosted on jenkins.io now (hope it changes at some point), but IMHO it is not safe to just remove it.

I would propose to keepthis Jelly tag somehow. It is fine to mark it as deprecated in the documentation if you do not want to inherit from it like @daniel-beck proposed.

2017-03-15 20:22 UTC, recena commented
THIS IS INCREDIBLE!

2017-03-15 20:24 UTC, recena commented
@oleg-nenashev `html.jelly` was introduced by @kzantow for providing a full screen layout. This tag is being used only in the setup wizard.

2017-03-15 20:25 UTC, recena commented
@oleg-nenashev Curiously, the author of this tag agrees with the changes proposed here.

2017-03-15 20:43 UTC, recena commented
I'm remembering this one https://github.com/jenkinsci/jenkins/pull/1717, with more than **122** comments.

2017-03-16 10:00 UTC, oleg-nenashev commented
I and @recena discussed this issue internally. I still disagree with such ranting and I still feel strong about my feedback.

I propose the following ways to proceed...

1) Get more votes for @jenkinsci/code-reviewers . I do not veto this PR (nobody can)
2) Decouple the `html.jelly` deletion to a separate PR an continue the discussion there

2017-03-16 10:09 UTC, recena commented
If _ranting_ means sharing / expressing my frustration, yes. Each change related with the UI involves a BIG challenge. We should think / reflect why the UI and UX has been one of the most negative part of this project.

2017-03-31 16:51 UTC, recena commented
@oleg-nenashev Given the two options, I've choose the second one.

2017-04-01 15:38 UTC, recena commented
@oleg-nenashev 

> I would propose to keepthis Jelly tag somehow. It is fine to mark it as deprecated in the documentation if you do not want to inherit from it like @daniel-beck proposed.

This was what I did.

2017-04-01 17:33 UTC, oleg-nenashev approved these changes
👍 for the code itself. Ready to merge assuming it was manually tested

2017-04-01 17:34 UTC, oleg-nenashev commented
@daniel-beck wdyt?

2017-04-01 18:24 UTC, recena commented
@oleg-nenashev I'm goint to prepare the PR for removing `html.jelly`, as you suggested.

2017-04-01 19:44 UTC, recena commented
@oleg-nenashev this was tested many times.

Today, I did smoke tests against: `2.32.3`, `2.41.1` and `master`.

2017-04-01 19:45 UTC, recena commented
By the way, I did a rebase with `master, this was my last commit.

2017-04-01 19:47 UTC, oleg-nenashev commented
@recena OK, ty. Will sync-up on the release of this fix with Daniel

2017-04-02 18:22 UTC, oleg-nenashev commented
According to the feedback from @daniel-beck , he is neutral regarding this change.
Merging according to the feedback from others

2017-04-02 18:22 UTC, merged

2017-04-02 18:45 UTC, oleg-nenashev commented
My bad, merged it without squash. But it is not a backporting candidate anyway

2017-04-02 18:54 UTC, recena commented
@oleg-nenashev In general, I prefer to merge this kind of changes by using squash mode. But as you mentioned, this is not a candidate for backporting.

2017-04-02 18:55 UTC, recena commented
@kzantow @oleg-nenashev @daniel-beck I appreciate a lot your time and reviews.