fix UpdateCenter download error
jenkinsci/jenkins pull request #2552
Opened 2016-09-19 16:26 UTC by wikimore

fix UpdateCenter download from http url error when response http status code is 301 or 302

Jira issue is [#JENKINS-38340](https://issues.jenkins-ci.org/browse/JENKINS-38340)

2016-09-19 20:08 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/UpdateCenter.java
> +                    IOUtils.closeQuietly(httpConn.getInputStream());
It won't be closed on exceptional paths.
Please also use Util.closeAndLogFailures() instead, because we want to report the issue in logs at least

2016-09-19 20:09 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/UpdateCenter.java
> +                    // 302, 301
Maybe this comment is an overkill

2016-09-19 20:10 UTC, oleg-nenashev requested changes
The idea looks good to me, but the closeable resources issue needs to be addressed. We're on Java7, hence try with resources is the most straightforward way

2016-09-20 11:00 UTC, wikimore commented on core/src/main/java/hudson/model/UpdateCenter.java
> +                    IOUtils.closeQuietly(httpConn.getInputStream());
Hi, @oleg-nenashev I add try-finally.

2016-09-20 16:18 UTC, daniel-beck commented
:-1:  This PR misses an explanation why 

* this only occurs on the Chinese mirror based on all known reports (JENKINS-8028 and JENKINS-32796 have both been used, as well as mailing lists)
* why the initial redirect from updates.j.o to mirrors.j.o works
* why [the code to automatically handle redirects in HttpUrlConnection doesn't apply](http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/4645fadf8352/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#l2308)

I appreciate the desire to get this fixed, but it looks like nobody currently understands the problem, and that's a bad starting point for code changes.

2016-09-20 16:30 UTC, daniel-beck commented
> why the code to automatically handle redirects in HttpUrlConnection doesn't apply 

The explanation could be that the Chinese mirror is the only one serving HTTPS, which is a different protocol from HTTP, and [that code rejects those](http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/4645fadf8352/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#l2329).

Still unclear why the redirect from https://updates.j.o to http://mirrors.j.o works.

2016-09-20 16:31 UTC, daniel-beck commented on core/src/main/java/hudson/model/UpdateCenter.java
> +                    // TODO maybe need to resolve recursive redirect
Unclear what's TODO here, as the recursion happens three lines below.

2016-09-20 17:58 UTC, daniel-beck commented
> Still unclear why the redirect from https://updates.j.o to http://mirrors.j.o works.

Ugh. There's no such redirect, as the URLs in update-center.json are all HTTP. So to recap, we only had http -> http redirects so far, and now we have http -> https, which isn't handled by HttpURLConnection.

@rtyler disabled the mirror for now, we may need to make it HTTP due to this issue for at least the foreseeable future, as a fix in Jenkins will take forever to be distributed among all users.

So any change here needs to be considered an improvement independent of the current problem.

2016-09-20 18:08 UTC, daniel-beck commented on core/src/main/java/hudson/model/UpdateCenter.java
> +            URLConnection conn = ProxyConfiguration.open(src);
never closed?

2016-09-21 01:48 UTC, wikimore commented on core/src/main/java/hudson/model/UpdateCenter.java
> +            URLConnection conn = ProxyConfiguration.open(src);
closed outside where invoke the `connect` method?

2016-09-21 02:28 UTC, wikimore commented
Hi, @daniel-beck I just wanted to update plugins.

I think this problem happened when use mirror, not only chinese.

OK, I know this is because the chinese mirror use https.

thank you @daniel-beck , I will close this PR

2016-09-21 02:28 UTC, closed without merging

2016-09-21 02:30 UTC, daniel-beck commented on core/src/main/java/hudson/model/UpdateCenter.java
> +            URLConnection conn = ProxyConfiguration.open(src);
@wikimore Not if there's a redirect.

2016-09-21 13:18 UTC, canatac commented
Coming from [this jenkins issue : Can't update plugins: incorrect checksum](https://issues.jenkins-ci.org/browse/JENKINS-32796). Is this related ? If so, @wikimore you're right, not only chinese mirror, we're in Paris,

2016-09-22 02:29 UTC, daniel-beck commented
@canatac Past experience indicates most checksum issues are due to networking issues (broken proxy, broken other network equipment, MITM attack). Check the tmp file created in JENKINS_HOME/plugins, if it's the HTML part of an HTTP 302 response, it's this problem. Otherwise, it's something else.

Please note that GitHub pull request threads are not a discussion/support forum. To get help, ask on the jenkinsci-users mailing list, or on IRC.