[FIXED JENKINS-38473] Set a short timeout on the socket when using it to wake the acceptor thread.
jenkinsci/jenkins pull request #2564
Opened 2016-09-23 16:32 UTC by stephenc

[JENKINS-38473](https://issues.jenkins-ci.org/browse/JENKINS-38473)

@jenkinsci/code-reviewers @reviewbybees

2016-09-23 16:40 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-09-23 20:52 UTC, oleg-nenashev commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> +                s.
WAT?

2016-09-23 20:53 UTC, oleg-nenashev requested changes
PR is incomplete. Would be also great to make the timeout configurable via system properties since 1000 MAY be too small in edge cases

2016-09-23 20:54 UTC, oleg-nenashev commented
🐛  for now. I think bot code leftover and timeout magic number should be addressed

2016-09-23 21:10 UTC, stephenc commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> +                s.
Oh dear... how did that end up there... I'll fix on monday

2016-09-29 18:16 UTC, stephenc commented
@oleg-nenashev if it takes longer than a second to wake the acceptor thread that doesn't matter as the event for wake will be in the works and we are just waiting for the acceptor thread to wake... could run a shorter timeout too but that risks more log statements about a socket being closed before any data was read.

In any case what advice would we give users about tuning this? Reality is none.

2016-09-29 18:24 UTC, jtnord commented
I'm kind of :bee: here - but at the same time with the later JNLPv4 protocol we do not do blocking in the slecector thread - so this whole shutdown - send something to the JNLPPort to wake the selector should be uneeded...   Perhaps I'm missing something :-(

2016-09-29 20:33 UTC, oleg-nenashev commented
> In any case what advice would we give users about tuning this? Reality is none.

Well, some users like thinking they manage something :)
Anyway, I'm more or less fine with this interval. 🐝

2016-09-29 20:34 UTC, oleg-nenashev commented
@reviewbybees done

2016-09-29 22:03 UTC, stephenc commented
@jtnord the thread that accepts incoming connections is blocking IO not NIO, even for JNLP4 if we switched to NIO we'd have to use a separate selector to ensure it works on windows.

The point of the ping is to wake the blocking IO thread by establishing an incoming connection.

2016-09-30 11:37 UTC, jtnord commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> +                client.setSoTimeout(1000); // waking the acceptor loop should be quick
Why not just set the SO_TIMEOUT on the server socket and remove whole section?

2016-09-30 11:40 UTC, jtnord commented
maybe there is a reason I am not aware of - but the code looks overly complex.
There is no need to wake the selector thread if you use a socket timeout on the server socket.. and then there is no need to send a ping and then there is no need to check if any exception was because we where shutting down, and then the code that handles the accept can also control the shutting down of the socket - and then you have much cleaner code with less hacks...

2016-10-01 10:19 UTC, oleg-nenashev commented
So, somebody can follow-up with a better fix later.
@jtnord Could you create a follow-up task?

2016-10-01 10:19 UTC, oleg-nenashev approved these changes

2016-10-01 10:19 UTC, merged