Cleaning up @since TODO / @since XXX
jenkinsci/jenkins pull request #2578
Opened 2016-10-04 09:04 UTC by daniel-beck

I've left out most LTS releases and only noted the weeklies, since new API shouldn't be particularly relevant for those (and are likely to be harmful).

@jenkinsci/code-reviewers

2016-10-04 09:14 UTC, oleg-nenashev commented
#2571 addresses Console Commands. I'd rather exclude them from this PR in order to avoid conflicts

2016-10-04 09:15 UTC, oleg-nenashev commented
But thanks for doing it in any case. Was somewhere in my TODO list, but I've never addressed it completely

2016-10-04 20:18 UTC, oleg-nenashev commented
PWNED by #2576. @batmat

2016-10-04 20:25 UTC, daniel-beck commented
@oleg-nenashev Why would that be a close reason?

2016-10-04 22:18 UTC, oleg-nenashev commented
@daniel-beck Sorry, just assigned wrong label

2016-10-11 01:44 UTC, KostyaSha approved these changes

2016-10-12 21:48 UTC, oleg-nenashev commented
Still a merge conflict

2016-10-15 20:53 UTC, daniel-beck commented
Fixed the merge conflicts, one line endings file, two where #2571 got it wrong.

2016-10-15 21:06 UTC, oleg-nenashev requested changes
Line ending got replaced by a wrong one, but other changes LGTM

2016-10-15 21:06 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessKillingVeto.java
> +}
ORLY?

2016-10-15 21:08 UTC, KostyaSha commented on core/src/main/java/hudson/util/ProcessKillingVeto.java
> +}
but who cares... other prs reformatting code also

2016-10-15 21:13 UTC, oleg-nenashev commented
OK, I agree with @KostyaSha it is not that important

2016-10-15 21:13 UTC, oleg-nenashev approved these changes

2016-10-15 21:25 UTC, daniel-beck commented
@oleg-nenashev Fixed the missing line ending in the last line.

Fixing merge conflicts when all line endings are changed is a PITA :frowning_face:

2016-10-15 22:27 UTC, oleg-nenashev commented
re-:+1:

On Oct 15, 2016 14:25, "Daniel Beck" <notifications@github.com> wrote:

> @oleg-nenashev <https://github.com/oleg-nenashev> Fixed the missing line
> ending in the last line.
>
> Fixing merge conflicts when all line endings are changed is a PITA ☹️
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/2578#issuecomment-254012109>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC3IoMGJSHBKDYEDmG78q3V1WnOKHesUks5q0UTTgaJpZM4KNckU>
> .
>

2016-10-16 11:39 UTC, batmat approved these changes
:+1: 
Yeah, sorry, was a necessary evil. The good news is it was a one-time to now make mixing newline formats impossible.

2016-10-16 13:34 UTC, merged