Jenkins 35845 Internationalisation for Blue Ocean and JDL
jenkinsci/jenkins pull request #2586
Opened 2016-10-11 09:23 UTC by scherler

Allow plugins to export i18n resources.

Alternative to jenkinsci/jenkins#2400 related to JENKINS-35270.

Created the PR because of [JENKINS-35845] Internationalisation for Blue Ocean and JDL

2016-10-11 09:39 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-10-11 14:01 UTC, scherler commented
@tfennelly can you have a look on the above since you appear the original author.

2016-10-12 13:29 UTC, tfennelly commented on core/src/main/java/jenkins/I18n.java
> +            return HttpResponses.errorJSON(e.getMessage(), HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
I see what you are doing here and it makes sense, but strictly speaking is not needed for fixing the issue wrt loading bundles from plugins, or am I missing something?

2016-10-12 13:29 UTC, tfennelly commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +        }
I wonder should we be specifying the actual plugin name as a parameter on the rest endpoint?

2016-10-12 13:29 UTC, tfennelly commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +        }
I suppose this is ok ... keeps the code more simple and is only executed once (if the bundle is not in the cache).

2016-10-12 13:29 UTC, tfennelly commented on test/src/test/java/jenkins/I18nTest.java
> +        }
Hmmm .... maybe check for something more specific?

2016-10-12 13:34 UTC, tfennelly commented on test/src/test/java/jenkins/I18nTest.java
> +        }
I just looked and I think you should get a HtmlUnit exception (`FailingHttpStatusCodeException` I think) that you can check i.e. check for an expected exception Vs just any exception. If it is `FailingHttpStatusCodeException`, you should still be able to get the actual response and perform the same checks that were removed, I think.

2016-10-12 15:55 UTC, oleg-nenashev requested changes
Several 🐜s in the implementation and definitely not enough tests. IIMHO 🐛

2016-10-12 15:55 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/HttpResponses.java
> +    public static HttpResponse errorJSON(@Nonnull String message, int errorCode) {
Maybe YAGNI, but OK

2016-10-12 15:55 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/HttpResponses.java
> +        public JSONObjectResponse setStatusCode(Integer statusCode) {
Maybe <code>withStatusCode()</code>?

2016-10-12 15:55 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/HttpResponses.java
> +        private Integer statusCode;
🐜 Add <code>@CheckForNull</code>.

2016-10-12 15:55 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            if (jenkins != null) {
This check is not required

2016-10-12 15:55 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +                for (PluginWrapper plugin : jenkins.getPluginManager().getPlugins()) {
Ideally needs to be optimized. IIRC baseName usually contains /plugin/myPlugin, which may tweak the performance

2016-10-12 15:55 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static ResourceBundle getBundle(String baseName, Locale locale, ClassLoader classLoader) {
🐜 Add <code>@ChewckForNull</code> to return value and parameters if they are nullable

2016-10-12 15:55 UTC, oleg-nenashev commented on test/src/test/java/jenkins/I18nTest.java
> +        }
I do not feel this test is enough for the change

2016-10-13 12:49 UTC, scherler reviewed
@oleg-nenashev I have created another test and fixed your comments.

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/HttpResponses.java
> +import java.io.File;
Please never use IDE's autoformat :(

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/HttpResponses.java
> +        public JSONObjectResponse withStatusCode(Integer statusCode) {
Also <code>@CheckForNull</code> for parameter? NIT

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/jenkins/I18n.java
> +            return HttpResponses.errorJSON(e.getMessage(), HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
+1

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @Nullable
Strange formatting

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            // fall through and return null.
🐜 Must go to system log

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @Nullable
Should be CheckForNull since it may happen on a common path

2016-10-13 22:56 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +     * @throws MissingResourceException Missing resource bundle.
🐛 It's not being thrown from the method

2016-10-14 19:28 UTC, scherler commented on core/src/main/java/jenkins/I18n.java
> +            return HttpResponses.errorJSON(e.getMessage(), HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
@tfennelly you are right strictly this is not needed.

2016-10-14 20:06 UTC, scherler commented
@oleg-nenashev fixed your feedback

2016-10-15 15:38 UTC, oleg-nenashev commented
Still 🐜 for unrelated formatting changes, but the changes itself LGTM. 🐝

2016-10-17 10:12 UTC, scherler commented
@oleg-nenashev fixed all not releated formating changes

2016-10-18 15:10 UTC, oleg-nenashev commented
Test failure seems to be related. The logic causes NPE: https://ci.jenkins.io/job/Core/job/jenkins/job/PR-2586/9/testReport/jenkins.util/ResourceBundleUtilTest/test_unknown_bundle/

2016-10-18 15:11 UTC, oleg-nenashev commented on core/src/main/java/jenkins/I18n.java
> +            return HttpResponses.errorJSON(e.getMessage(), HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
Better to submit as a separate PR then

2016-10-18 15:12 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @CheckForNull ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader) {
Well, @jglick-style violates the recommended code style

2016-10-18 15:13 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.info(e.getMessage());
Add error to the logged message. Likely INFO is a bad logging level since it's an expected behavior sometimes. Will pollute logs

2016-10-18 15:26 UTC, scherler commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @CheckForNull ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader) {
@oleg-nenashev not sure what you mean

2016-10-18 15:27 UTC, scherler commented on core/src/main/java/jenkins/I18n.java
> +            return HttpResponses.errorJSON(e.getMessage(), HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
I will refactor to drop the part on SC_INTERNAL_SERVER_ERROR

2016-10-18 16:12 UTC, scherler commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            if (jenkins != null) {
Actually it is @oleg-nenashev the failure you have linked is provoked by that test not being in place anymore.

2016-10-18 16:28 UTC, scherler commented
@oleg-nenashev your feedback is in this PR now.

2016-10-20 14:54 UTC, scherler commented
@oleg-nenashev ping

2016-10-20 14:58 UTC, oleg-nenashev commented on test/src/test/java/jenkins/I18nTest.java
> +    public void test_baseName_plugin() throws IOException, SAXException {
Nice2have: Add <code>@Issue()</code> reference

2016-10-20 14:58 UTC, oleg-nenashev approved these changes
Looks good to me 🐝

2016-10-20 15:00 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @CheckForNull ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader) {
Well...

Style defined in  https://wiki.jenkins-ci.org/display/JENKINS/Beginners+Guide+to+Contributing#BeginnersGuidetoContributing-CodeStyle

```
@CheckForNull 
private static ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader)
```

jglick-style:

```
private static @CheckForNull ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader)
```

2016-10-20 16:45 UTC, scherler commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @CheckForNull ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader) {
@oleg-nenashev ok got ya, so should I fix the other occurrence of that in the file?

2016-10-20 16:56 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +    private static @CheckForNull ResourceBundle getBundle(@Nonnull String baseName, @Nonnull Locale locale, @Nonnull ClassLoader classLoader) {
Yep, the file contains only one annotation style. 

Then I'd just keep it as is and then perform a bulk refactoring when Jesse goes to a vacation without internet access :)

2016-10-20 17:09 UTC, oleg-nenashev commented
re-:bee:

2016-10-20 17:22 UTC, aheritier commented
🐝

2016-10-20 17:27 UTC, oleg-nenashev commented
@reviewbybees done
@jenkinsci/code-reviewers your turn

2016-10-22 10:21 UTC, merged

2016-11-08 20:29 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.warning(e.getMessage());
I think we just need to reduce the message severity to the FINE or FINEST level

2016-11-08 20:56 UTC, i386 commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.warning(e.getMessage());
@oleg-nenashev is this the only update that is blocking this from a backport?

2016-11-08 22:34 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.warning(e.getMessage());
"Blocking" - maybe. But we still need to agree regarding the feasibility of the backporting

2016-11-08 23:11 UTC, daniel-beck commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.warning(e.getMessage());
Wait, will this print an average of dozens of messages every time a non-core resource is searched? It iterates over all plugins… If so, this should be changed in master as well.

2016-11-08 23:14 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.warning(e.getMessage());
Yes, it should

2016-11-08 23:22 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/ResourceBundleUtil.java
> +            logger.warning(e.getMessage());
https://issues.jenkins-ci.org/browse/JENKINS-39604

2016-11-09 06:44 UTC, olivergondza commented
@i386, this is the only thing that made me hesitate with backporting this. It will go in with oleg's tuning.