[FIXED JENKINS-37590] Better handling of null parameter definitions.
jenkinsci/jenkins pull request #2589
Opened 2016-10-12 11:05 UTC by abayer

[JENKINS-37590](https://issues.jenkins-ci.org/browse/JENKINS-37590)

Rejecting null parameter definitions lists results in an error if you
try to save a job config with "This build is parameterized" checked
but no actual parameters specified. We should handle null better by
populating an empty list if needed instead.

cc @jenkinsci/code-reviewers @reviewbybees

2016-10-12 11:14 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-10-12 11:24 UTC, imod commented
👍

2016-10-12 15:44 UTC, oleg-nenashev approved these changes
I would rather like to see one constructor invoking another one && Annotations && Javadoc. But 🐝

2016-10-12 15:44 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/ParametersDefinitionProperty.java
> +    public ParametersDefinitionProperty(List<ParameterDefinition> parameterDefinitions) {
Add CheckForNull instead

2016-10-12 15:44 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/ParametersDefinitionProperty.java
> +    public ParametersDefinitionProperty(ParameterDefinition... parameterDefinitions) {
Also CheckForNull

2016-10-12 15:45 UTC, jglick commented
IIUC corrects some regression in #2296?

2016-10-12 15:48 UTC, jglick requested changes
:-1:, would rather just fix [JENKINS-33991](https://issues.jenkins-ci.org/browse/JENKINS-33991) so that there is no property at all in this case.

2016-10-13 23:00 UTC, oleg-nenashev commented
Maybe needs-fix since @jglick blocks it. But fine for me

2016-10-15 21:41 UTC, daniel-beck commented
Depends which behavior makes more sense on the UI. "Build With Parameters" with an empty page or something similar that would appear broken?

2016-10-18 06:00 UTC, oleg-nenashev commented
> Depends which behavior makes more sense on the UI. "Build With Parameters" with an empty page or something similar that would appear broken?

Well, it's rather a Unix way. If one feel brave, he can do it (e.g. if one injects Javascript magic into this Build With Parameters page). Empty screen by default is not that bad.

2016-10-18 06:01 UTC, oleg-nenashev commented
Of course a fallback text like "No parameters defined" would be even better

2016-10-18 17:29 UTC, daniel-beck commented
> If one feel brave, he can do it (e.g. if one injects Javascript magic into this Build With Parameters page). Empty screen by default is not that bad.

We shouldn't elevate injection of JS/CSS into a supported use case. There's just pain down that road. So this isn't an argument for me.

2016-10-22 10:24 UTC, oleg-nenashev commented
@daniel-beck So would you be happy if there is a "No parameters defined" in the "buildParameterized" page?

2016-10-24 10:29 UTC, daniel-beck commented
@oleg-nenashev 

>  So would you be happy if there is a "No parameters defined" in the "buildParameterized" page?

No, I think the job should not be considered to be parameterized if there are no parameters.

2016-10-24 10:42 UTC, oleg-nenashev commented
OK, then needs fix

2016-11-14 16:32 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-12-19 19:12 UTC, abayer commented
So I don't get how [JENKINS-33991](https://issues.jenkins-ci.org/browse/JENKINS-33991) should be addressed. With https://github.com/jenkinsci/jenkins/commit/0b517705f5de454f2896d5c345ac8ec4fa8f6651 in from 2.14 onward, it's no longer possible to save a job with empty parameters and the parameterized button checked, though the fix here was still needed to deal with some edge cases. Anyway, I've updated responding to review comments and added a round-tripping test that gets the right result.

2017-01-18 19:35 UTC, jglick commented
IMO better to revert #2444, and adopt my suggestion from JENKINS-33991 to restore the historical behavior in Jenkins: override `ParametersDefinitionProperty.DescriptorImpl.newInstance` to return `null` in case the `super` return value had `parameterDefinitions.isEmpty()`. Easy, no UI hassle.

2017-01-18 19:36 UTC, jglick requested changes
As above.

2017-01-20 00:30 UTC, abayer commented
@jglick #2444 was already reverted in https://github.com/jenkinsci/jenkins/commit/e43222dde84be0ea7d05647790fedc12d70f8052#diff-49180eb94a7d79905023758a89bb88eb after I opened this...so I'm just junking this PR completely and starting over. Yay?

2017-01-20 00:30 UTC, closed without merging