record system metrics during boot
jenkinsci/jenkins pull request #2592
Opened 2016-10-14 09:13 UTC by ndeloof

to help diagnose loooong jenkins launch on some installations, by collecting system metrics every second as well as init milestones.
Only supports Linux - other systems could be added later if this makes sense

2016-10-14 12:04 UTC, jtnord commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +            e.printStackTrace();
output is likely to be lost - please use a Logger.

2016-10-17 17:49 UTC, daniel-beck commented on changelog.html
> +  <li class="rfe">
Please don't include changelog entries on PRs. Only leads to merge conflicts.

2016-10-17 18:31 UTC, ndeloof commented on changelog.html
> +  <li class="rfe">
ok, no worries, isolated commit anyway

2016-10-21 11:39 UTC, ndeloof commented
@ reviewbybees

2016-10-21 11:53 UTC, ndeloof commented
also see https://github.com/jenkinsci/support-core-plugin/pull/77

2016-10-21 11:57 UTC, daniel-beck requested changes

2016-10-21 11:57 UTC, daniel-beck commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> + */
`@since TODO`

2016-10-21 11:57 UTC, daniel-beck commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +public class BootMetrics implements InitReactorListener {
`@Restricted(NoExternalUse.class)`?

2016-10-21 11:57 UTC, daniel-beck commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +        if (!System.getProperty("os.name").toLowerCase().startsWith("linux")) {
Don't we have OS detection somewhere already?

2016-10-21 11:57 UTC, daniel-beck commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +            timer.cancel();
Would an NPE here (if e.g. creation of the `logs` directory fails) fail the Jenkins startup?

2016-10-21 11:59 UTC, daniel-beck commented
Is it reasonably possible to test this change?

How does this behave when running e.g. inside Tomcat?

2016-10-21 12:02 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-10-31 01:11 UTC, KostyaSha commented
> Only supports Linux - other systems could be added later if this makes sense

So why not place in support plugin?

2016-11-02 10:41 UTC, daniel-beck commented
@KostyaSha 

> So why not place in support plugin?

How would you do this given that this needs to run before plugins and extension points have been loaded? AFAIK this could be a module at best, but definitely needs to be part of `jenkins.war`.

2016-11-07 00:47 UTC, KostyaSha commented
> How would you do this given that this needs to run before plugins and extension points have been loaded?

I guess javaagent loads on early boot?

2016-11-07 07:01 UTC, ndeloof commented
Using a javaagent would require some significant changes to jenkins launch script, and most users won't enable this feature, so we wouldn't be able to help diagnose live issue.

2016-11-07 09:45 UTC, daniel-beck commented
Not to mention all the fun people might then have thanks to over-eager antivirus tools.

Is there a reason you're asking for a different approach @KostyaSha ? It's not clear to me what's wrong with this one.

2016-11-19 21:24 UTC, oleg-nenashev commented on core/src/main/java/hudson/Platform.java
> +    public static boolean isLinux() {
Maybe should be restricted. NIT

2016-11-19 21:26 UTC, oleg-nenashev commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +        log.getParentFile().mkdirs();
🐜 Unchecked mkdirs. Use `Files` instead

2016-11-19 21:29 UTC, oleg-nenashev commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +            m.iowait = Long.parseLong(s[5]) / Hertz;
🐛 unhandled NumberFormatException

2016-11-19 21:29 UTC, oleg-nenashev commented on core/src/main/java/jenkins/diagnosis/BootMetrics.java
> +                        m.read_bytes = Long.parseLong(line.substring(12));
same

2016-11-19 21:29 UTC, oleg-nenashev requested changes
Needs fix IMHO

2016-11-19 21:31 UTC, daniel-beck commented on core/src/main/java/hudson/Platform.java
> +    public static boolean isLinux() {
Given the methods before and after this one, doesn't make sense.

2016-11-20 14:45 UTC, KostyaSha commented
> Is there a reason you're asking for a different approach @KostyaSha ? It's not clear to me what's wrong with this one.

The same as bundled plugins, in case of changes for diagnostics algorithms it will be impossible to change it without changing core. It also missing non-linux archs. In mac i guess it will be also bit different. Maybe core can scan and load via classpath or directly additional jar diagnostics classes?
PS i have no notifications.

2016-11-20 14:50 UTC, KostyaSha commented
Btw, wouldn't universal way http://techblog.netflix.com/2015/07/java-in-flames.html work for such case? CC @svanoort

2016-11-20 15:02 UTC, daniel-beck commented
@KostyaSha 

> in case of changes for diagnostics algorithms it will be impossible to change it without changing core

Well, plugins would load too late to be useful, and modules etc. would still need to be delivered as part of core. So there's no real alternative here.

> Maybe core can scan and load via classpath or directly additional jar diagnostics classes?

Looks a lot like YAGNI to me. Also, I think we've generally told people not to mess with the extracted war, so I'd rather not introduce that bit of insanity. If you want better diagnostics, you'll just need to upgrade Jenkins (or lobby for a backport).

FWIW as long we keep this diagnostic stuff separate from core, i.e. no code reuse, it should be trivial enough to extract later to a module or something like that later. So this concern shouldn't hold up getting _some_ diagnostics going. _That_ definitely helps nobody.

> PS i have no notifications. 

Not sure what that means. If you want to get notified again, just subscribe to this thread again?

2016-11-29 19:09 UTC, svanoort commented
I have very mixed feelings about this diagnostic approach and directly integrating into core -- it feels rather brittle obtaining and parsing system stats this way.  Since it's part of core, not easy to rip out if something breaks in a critical way that blocks startup -- and everything from formatting issues in expected content to logic errors to permissions or security settings could potentially block it (would need deep inspection).

For these reasons I would strongly prefer this to be part of a plugin, and at the very least, controlled by a system property that is off by default.


Agree with @KostyaSha also that core is not the best place to put this, because putting it in a plugin lets us easily extend and enhance it (or offer patched versions to users needing far more detail).  As far as platform support goes though: I think this is an 80/20 case.  The stats I've seen suggest ~80-90% of masters are running on Linux, and generally that covers most of the big or critical installs (with a handful on Windows).  

BTW that article Kostya linked on flame graphs has been a favorite of mine for a while.  Once I finish addressing the key bottlenecks I know of in pipeline, I want to give that profiling technique a whirl.   So far it's a bit overkill for our needs, because most of the bottlenecks I've seen so far can be traced by either a good JVM profiler (YourKit) or GC logs.   I think we will have good results using an approach like that for startup with a reasonable benchmark case (perhaps coupled to vmstat to see if I/O time is an issue). 

Side comment that I have some ideas on adding a flame chart view of pipeline executions so you can see which blocks and steps take most of the time (the Pipeline Steps view offers a less elegant form of this, after integrating basic timing into it).

2016-11-29 19:41 UTC, ndeloof commented
@svanoort this _can't_ be part of a plugin, as jenkins boot takes place _before_ plugins are enabled.

2016-11-29 19:47 UTC, ndeloof commented
I agree flame graph or any other system monitoring approach would perfectly feet this need, but this only can take place AFTER user complains about long boot time, in circumstances he wouldn't agree to reboot just to run some tests, and in many cases with limited technical skills to run such a diagnostic. If you think getting jenkins allow slef-diagnostic isn't a good think, then just close this PR.

2016-11-29 20:31 UTC, svanoort commented
@ndeloof You have a point about normal plugin loading -- I was under the impression we could do this with a class using an `@Initializer` though and we'd be able to get everything after PLUGINS_PREPARED or at least PLUGINS_STARTED?   Is that wrong, or is there reason to think the early parts are significant problems vs. extension augmentation, job loading and overall completion?

I don't disagree with the idea of instrumenting startup, just this particular way of implementing it (and how tightly it is integrated).

I hear your point about trying to proactively solve user pain with long restarts where restarting at all is an issue, but I'm just not convinced this is going to fix it for them because we only get aggregate statistics about the resources used (I/O wait time vs. CPU time).  While that's interesting, it's not going to point at the culprit methods / operations.  Would it not make sense to include (optional) very granular logging of substeps (i.e. each plugin/extension loaded/augmented, each job loaded)?  Perhaps even include internal counters/timers for XMLFile loading, etc?

2016-11-29 20:37 UTC, rtyler commented
I wonder if this could be implemented instead as a Java Agent instead? That certainly doesn't solve the distribution aspect, but would allow instrumenting the full boot process without needing to wait for the plugin system to load _or_ needing to hack core.

2016-11-30 08:17 UTC, ndeloof commented
seems this approach doesn't get general agreement. closing

2016-11-30 08:17 UTC, closed without merging

2016-11-30 14:52 UTC, KostyaSha commented
> in circumstances he wouldn't agree to reboot just to run some tests, and in many cases with limited technical skills to run such a diagnostic.

The same point i raise for every new system property in jenkins without configurable UI.  But new and new are coming, plugin updates requires restarts. So unfortunately it's jenkins architecture to do restarts...