[JENKINS-26940] Print message when installer isn't applicable
jenkinsci/jenkins pull request #2598
Opened 2016-10-20 15:23 UTC by daniel-beck

Example:

	[Gradle] - Launching build.
	Installer "Extract *.zip/*.tar.gz" cannot be used to install "Gradle 2" on the node "Jenkins"
	[Gradle] - [ERROR] Can't retrieve the Gradle executable.

It seems that users occasionally wonder why their installers "don't work". I'd also print the label expression to be extra helpful, but this may be misleading as `isApplicable(…)` can be overridden.

2016-10-20 15:42 UTC, oleg-nenashev commented
Weak 👎 . I had many installers defined for Tool Installations (up to 16 IIRC for label combinations) + multiple tool definitions. Such per-installer logging would pollute my builds much by expected behavior.

My proposal:
* Log info for each installer to system logs on FINE level
* Write only one message to build logs if we're about returning null from the method ("None of installers can be applied")

2016-10-20 15:44 UTC, oleg-nenashev requested changes
needs change imho

2016-10-20 15:49 UTC, oleg-nenashev commented
I'd vote for creating a new low-priority bug/improvement

2016-10-20 15:57 UTC, daniel-beck commented
@ndeloof 

> Log info for each installer to system logs on FINE level

Uh, you mean log it in such a way that nobody will ever see it? What's the use of that? Since it's typically something trivial like labels, if you know how to look for the log you know enough to figure out the problem anyway.

---

> Such per-installer logging would pollute my builds much by expected behavior.

How about this -- only print anything when no applicable installer was found, but then, print all of them? Then you'll only have log output in the failure case, i.e. when you need it.

2016-10-20 16:36 UTC, oleg-nenashev commented
@daniel-beck 

> How about this -- only print anything when no applicable installer was found, but then, print all of them? Then you'll only have log output in the failure case, i.e. when you need it.

Fine for me. FINE-level logging is not required in such case, of course

2016-10-20 20:34 UTC, daniel-beck commented
@oleg-nenashev Please re-review.

2016-10-20 22:48 UTC, oleg-nenashev commented on core/src/main/java/hudson/tools/InstallerTranslator.java
> +            log.getLogger().println(message);
Ideally it should be a single message for a correct logging. Especially once we have the External task logging support. Should be fine for now

2016-10-20 22:48 UTC, oleg-nenashev approved these changes

2016-10-25 09:10 UTC, evieluvsrainbows approved these changes

2016-10-25 09:13 UTC, oleg-nenashev commented on core/src/main/java/hudson/tools/InstallerTranslator.java
> +            log.getLogger().println(message);
We agreed to postpone it for now

2016-10-25 09:13 UTC, merged