[FIXED JENKINS-39167] Make JobColumn smart
jenkinsci/jenkins pull request #2599
Opened 2016-10-21 10:51 UTC by stephenc

See [JENKINS-39167](https://issues.jenkins-ci.org/browse/JENKINS-39167)

@reviewbybees @jenkinsci/code-reviewers 

*NOTE:* Personally I have no strong opinion on merging this, it is more a question of UX, but as I am removing a poorly implemented hack version of this in https://github.com/jenkinsci/github-organization-folder-plugin/pull/34 I created this to enabling restoration of equivalent functionality.

If the enhanced UX is considered useful, we can merge this PR... if the considered opinion is that this is all tweaking something that is not important in the grand scheme of things... well then let's just close this as won't fix!

2016-10-21 10:58 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-10-21 11:16 UTC, oleg-nenashev requested changes
I agree with @stephenc that the need in this change is very debatable. Small UX impact, but it makes the code to iterate through all jobs in the view when rendering the column. It may be a heavy operation in the case of security checks.

I would rather vote for just allowing specifying a display name of the column in view settings.

Putting 🐛 since I expect some performance tweaks in the algorithm. Regarding the feasibility, we need more feedback from reviewers IMHO

2016-10-21 11:16 UTC, oleg-nenashev commented on core/src/main/java/hudson/views/JobColumn.java
> +        if (metaName == null) {
I would use StringUtils.isBlank(). Just to avoid blank column headers in the case of misbehaving <code>AlternativeUiTextProvider</code>s

2016-10-21 11:16 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +     */
since?

2016-10-21 11:16 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +    public static final Message<AbstractItem> META_NAME = new Message<AbstractItem>();
What is the need to keep it as a non-restricted public field?

2016-10-21 11:16 UTC, oleg-nenashev commented on core/src/main/java/hudson/views/JobColumn.java
> +        String metaName = null;
I recommend to immediately return from the entry if there is no applicable <code>AlternativeUiTextProvider</code> implementations. Just a performance tweak

2016-10-21 11:16 UTC, oleg-nenashev commented on core/src/main/java/hudson/views/JobColumn.java
> +                    : Messages.JobColumn_DisplayName();
return immediately? If there are only non-<code>AbstractItem</code> items, the logic will iterate through all jobs without any chance to change the result

2016-10-21 12:04 UTC, stephenc commented
FTR I am not inclined to work further on this unless there is active responses from the community that this is a Good Thing™

If the consensus is that it is a Good Thing™ then I am prepared to move it forward. Personally, my view is this should be won't fix... but given that @kohsuke felt the need to customise the column header in the first place, I didn't want to revert his hack without at least addressing the use case driving that hack

2016-10-24 20:30 UTC, jglick requested changes
:bug: the implementation doubles work.

My suggestion elsewhere was to have the header cell render just _Name_ as far as Jelly is concerned, but then have each table cell put in the appropriate pronoun as an invisible HTML attribute, and have an onload hook on the header cell to swap in a single unique pronoun if there is one.

2016-10-24 20:30 UTC, jglick commented on core/src/main/java/hudson/model/AbstractItem.java
> +    public static final Message<AbstractItem> META_NAME = new Message<AbstractItem>();
In case someone wishes to replace the name in some contexts.

2016-10-24 20:32 UTC, jglick commented
I do not see the need for `META_NAME`. All concrete item types that I know of override `getPronoun()`.

2016-10-30 14:21 UTC, oleg-nenashev commented
So we have 2 -1s. I think it's a subject for closing since @stephenc does not feel strongly as well

2016-11-03 21:58 UTC, stephenc commented
4 days and nobody chimed in to the contrary... closing

2016-11-03 21:58 UTC, closed without merging