JENKINS-37282 ignore exceptions when including summaries
jenkinsci/jenkins pull request #2600
Opened 2016-10-25 13:22 UTC by pjfanning

2016-10-25 13:56 UTC, oleg-nenashev commented
IMHO it is not the best fix approach, because summary.jelly is not supposed to throw exceptions at all. In general, I feel that suppressing exception propagation rather makes the issue more severe since nobody knows about it.

A good fix of [JENKINS-37282](https://issues.jenkins-ci.org/browse/JENKINS-37282) would be to...
1) Consider suppression of particular actions here: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/AbstractBuild/index.jelly#L110 (e.g. catch exception and write warning)
2) Investigate what happens with causes in `InterruptedBuildAction` ([code](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/model/InterruptedBuildAction/summary.groovy))
3) Ensure that causes in MultiJob plugin (esp [here](https://github.com/jenkinsci/tikal-multijob-plugin/blob/ae30e9b5b5f80854d252f563603131153e3955cb/src/main/java/com/tikal/jenkins/plugins/multijob/SubTask.java#L47) )are not being created with null run pointer (seems so)

It worth adding hardening the Jenkins core, but the root cause of the failure is poor handling of edge cases in MultiJob plugin. The plugin needs to get a better null handling

2016-10-25 13:57 UTC, oleg-nenashev requested changes
Needs fix according to the previous comment

2016-10-25 13:57 UTC, oleg-nenashev commented
CC @hagzag

2016-10-25 14:23 UTC, pjfanning commented
The issue I am seeing in Jenkins 2.27 is easy to reproduce. I created a multiphase job with a subjob that has an 'Execute Shell' build step with 'sleep 180'. I set the 'Abort the build if it's stuck' option on the parent job to 1 minute. Run the parent job and after it aborts, try to look at the status of the subjob.

2016-10-25 15:11 UTC, pjfanning commented
Exception for jenkins.model.InterruptedBuildAction@2a5e76d5: org.apache.commons.jelly.JellyTagException: jar:file:/Users/Shared/Jenkins/Home/war/WEB-INF/lib/jenkins-core-2.28-SNAPSHOT.jar!/hudson/model/AbstractBuild/index.jelly:111:86: <st:include> org.apache.commons.jelly.JellyTagException: jar:file:/Users/Shared/Jenkins/Home/war/WEB-INF/lib/jenkins-core-2.28-SNAPSHOT.jar!/lib/hudson/summary.jelly:105:31: <d:invokeBody> Cannot get property 'fullName' on null object

2016-10-25 15:17 UTC, oleg-nenashev commented
@pjfanning Did you actually read my comment?

2016-10-25 15:25 UTC, pjfanning commented
@oleg-nenashev one option you mentioned was printing a warning about the exception that is caught (point 1 in your list of 3) - but I do agree that the ultimate fix is to look into the issues in the MultiJob plugin - I still think that having some exception handling in AbstractBuild/index.jelly is useful.

2016-10-26 23:14 UTC, pjfanning commented
@oleg-nenashev With InterruptedBuildAction, I logged the causes and found that UserInterruption has user=anonymous but that User.get(user, false, Collections.emptyMap()) returned null. 
https://github.com/jenkinsci/jenkins/blob/5537b3170844649b6836445eb28caabf492f8492/core/src/main/java/jenkins/model/CauseOfInterruption.java#L89
This seems to the cause of the "Cannot get property 'fullName' on null object" error.

2016-10-27 13:30 UTC, daniel-beck commented
What's the point of this change? Exceptions are already logged, right?

2016-10-27 16:19 UTC, pjfanning commented
@daniel-beck the exception stack trace is all you see, while with this patch, you get the page but with a small message saying there is an exception displaying one summary. Reworking UserInterruption to handle anonymous user with throwing a NullPointerException is ultimate fix. This patch just makes the exception not block the display of the job summaries.

2016-11-11 16:05 UTC, pjfanning commented
Probably will be fixed by https://github.com/jenkinsci/jenkins/pull/2630

2016-11-11 16:35 UTC, closed without merging

2016-11-11 17:15 UTC, oleg-nenashev commented
@pjfanning Yes, #2630 should address this particular case.