[JENKINS-39232] Walk the DelegatingComputerLauncher instances when checking if JNLPComputerLauncher
jenkinsci/jenkins pull request #2602
Opened 2016-10-26 09:49 UTC by stephenc

See [JENKINS-39232](https://issues.jenkins-ci.org/browse/JENKINS-39232)

@jenkinsci/code-reviewers @reviewbybees

Replaces #2601

2016-10-26 09:57 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-10-26 11:03 UTC, oleg-nenashev commented
I do not believe it's a perfect fix since anybody can implement his own launcher using `ComputerLauncher` API. And there are many examples: https://github.com/search?q=org%3Ajenkinsci+%22extends+computerlauncher%22&type=Code

I agree it worths adding support of Delegating launchers, but it does not fix the issue

2016-10-26 12:00 UTC, daniel-beck commented on core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
> +     */
`@Extension(NoExternalUse.class)`

2016-10-26 12:26 UTC, oleg-nenashev commented on core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
> +        } catch (NoSuchMethodException | InvocationTargetException | IllegalAccessException e) {
ReflectiveOperationException?

2016-10-26 12:29 UTC, oleg-nenashev commented on core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
> +            } else if (null != (l = getDelegate(launcher))) {  // TODO remove when all plugins are fixed
Does not guarantee a success for old plugins from what I see

2016-10-26 12:29 UTC, oleg-nenashev commented on core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
> +                            + "correctly as being a JNLP agent", clientName);
Please explicitly provide a class of the launcher

2016-10-26 12:32 UTC, oleg-nenashev requested changes
If we want to go in such way, we need better diagnostic messages. :bug: for it.

I still have concerns about such approach due to impact on plugins, but it's a subject for voting by @jenkinsci/core

2016-10-26 13:19 UTC, oleg-nenashev approved these changes

2016-10-26 13:23 UTC, oleg-nenashev commented
I approve the code change itself since it makes the situation better that it is in 2.27. So 🐝 and 👍 as a partial fix.

But I still do not feel it's a right approach to nuke so many instances. Hence as a community member I keep 👎 regarding the change as a **complete** fix of JENKINS-39232

2016-10-27 16:31 UTC, oleg-nenashev commented
@reviewbybees done
@jenkinsci/code-reviewers We really really really want to get it in the next weekly

2016-10-27 16:32 UTC, oleg-nenashev commented
P.S: I will follow-up on the default behavior

2016-10-28 12:36 UTC, oleg-nenashev commented
I will merge it into the next weekly if nobody shouts

2016-10-29 11:25 UTC, merged

2016-11-20 22:12 UTC, KostyaSha commented on core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
> +    private static ComputerLauncher getDelegate(ComputerLauncher launcher) {
comment wasn't addressed?

2016-11-20 22:13 UTC, KostyaSha commented on core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
> +            // ignore
you can name `ignore` instead `e` to disable warnings static analysing tools.