[JENKINS-23271] - Prevent the prelimimary deallocation of the Proc instance by GC
jenkinsci/jenkins pull request #2635
Opened 2016-11-15 00:55 UTC by oleg-nenashev

Just realized I have not proposed a hackish fix for [JENKINS-23271](https://issues.jenkins-ci.org/browse/JENKINS-23271) yet. It was implemented a while ago, but seems to be still actual. Have not tested it with the latest core BTW.

It is a hackish way, which likely prevents a preliminary deallocation of the spawned `RemoteProc` instance, which we see in JENKINS-23271. Proc instance was not actually required in the original code since we were creating and using `RemoteInvocationHandler` wrapper only, and the theory discussed with @stephenc was that object gets removed by Java8 garbage collector before we get into join().

This fix enforces the persistency of `ProcStarter#start()` result by adding logging and the enforced volatile field (maybe the last one is not really required, but JIT compiler in Java implementations may be smart enough to skip unused loggers)

This is a pretty old fix from August, which has been soak tested on my instance for several weeks (mid-August => Jenkins World). On the reference instance (just a small Jenkins 2.7.1 instance with 4 agents and very frequent builds with `CommandInterpreter steps`) I saw 2 failures over the period. On the fixed instance - 0. It does not proof anything, but at least the fix was soak tested a bit.

@reviewbybees @stephenc

2016-11-15 01:03 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-11-15 10:15 UTC, stephenc reviewed
I think the fix you have suggested is the wrong fix, but given that you have soak tested, if you want to take the pragmatic route and push your change with a follow-up to apply my suggestion after further soak testing (assuming my suggestion works) and you add the TODO comments to indicate such a plan... then I am fine

2016-11-15 10:15 UTC, stephenc commented on core/src/main/java/hudson/Launcher.java
> +        private volatile Proc procHolderForJoin;
I think this is unnecessary for the fix

2016-11-15 10:15 UTC, stephenc commented on core/src/main/java/hudson/Launcher.java
> +        public synchronized int join() throws IOException, InterruptedException {
I think what we really want to do is:

```
Proc proc = start();
try {
  return proc.join();
} finally {
  if (proc.isAlive()) { // will never happen but this forces Proc to not be removed and early GC by escape analysis
    LOGGER.log(Level.WARNING, "Process not finished after call to join() completed");
  }
}
```

Which has the advantage of reducing the memory footprint and localizing the hack to just a single method

2016-11-15 10:15 UTC, stephenc commented on core/src/main/java/hudson/Launcher.java
> +         * This method stores internal context and hence it is synchronized
Adding a use case for the objects public monitor is never a good plan IMHO

2016-11-15 12:53 UTC, oleg-nenashev commented
@stephenc I agree with the comments. As you may have seen in the summary, I also do not see much need in the volatile field. It was just a hack I had in soak testing. I will remove the field

2016-11-15 16:39 UTC, oleg-nenashev commented
CC @aheritier, who was pinging me about this issue for months :(

2016-11-15 17:27 UTC, aheritier commented
Yeah @oleg-nenashev !!!
LGTM 🐝

2016-11-15 21:10 UTC, daniel-beck commented
Preliminary? 

> denoting an action or event preceding or done in preparation for something fuller or more important

2016-11-15 22:37 UTC, oleg-nenashev commented
Fixed my Inglesh

2016-11-17 09:07 UTC, stephenc requested changes
The `assert` is dodgy IMHO. I'd prefer the `finally` pattern

2016-11-18 17:10 UTC, oleg-nenashev commented on core/src/main/java/hudson/Launcher.java
> +                assert false : "Process not finished after call to join() completed";
Finally block is also not a silver bullet, right?

2016-11-18 19:22 UTC, stephenc commented on core/src/main/java/hudson/Launcher.java
> +                assert false : "Process not finished after call to join() completed";
So the contract of finally means that the JVM cannot evaluate it out of order, and then by not bothering with an assert, rather running to warning log level then escape analysis cannot remove the if... plus while it should never happen, we want to know if it does... an assertion error is not a good way to have that happen...

2016-11-18 19:41 UTC, oleg-nenashev commented on core/src/main/java/hudson/Launcher.java
> +                assert false : "Process not finished after call to join() completed";
OK. Let's do finally with assert :)

2016-11-18 20:21 UTC, stephenc requested changes

2016-11-18 20:21 UTC, stephenc commented on core/src/main/java/hudson/Launcher.java
> +                    assert false : "Process not finished after call to join() completed";
And still you leave the exploding bomb of an `assert false`

2016-11-19 21:20 UTC, oleg-nenashev commented on core/src/main/java/hudson/Launcher.java
> +                    assert false : "Process not finished after call to join() completed";
it is bad? I will remove it just to unblock anyway

2016-11-19 21:32 UTC, daniel-beck approved these changes

2016-11-19 21:33 UTC, oleg-nenashev commented
I assume the last comment from @stephenc is addressed. I will merge it tomorrow if the tests pass

2016-11-19 21:40 UTC, stephenc approved these changes
:bee:

2016-11-19 23:53 UTC, oleg-nenashev commented
CI passed, merging

2016-11-19 23:53 UTC, merged