Allow override setUser(User)
jenkinsci/jenkins pull request #2655
Opened 2016-11-30 15:06 UTC by KostyaSha

UserProperty may contain nested objects that depend on User. 
On User reconfiguration setUser(User) is called so it should be non-final to have ability override it and update references in nested objects.

I want store some configs in nested classes without messing all logic in UserProperty class.

2016-11-30 16:01 UTC, jglick requested changes
Impossible to review meaningfully without a concrete example (downstream linked PR which accomplishes some clear goal which would be impossible without this change).

Anyway this change as written makes no API change, since `setUser` is package access.

2016-11-30 16:04 UTC, KostyaSha commented
> Anyway this change as written makes no API change, since setUser is package access.

Sorry, will update PR from IDE instead GH UI. I have some private stuff that will be opensourced later. I will create the test case with similar behaviour.

2016-12-05 20:49 UTC, KostyaSha commented
@jglick added test, can create jira issue if needed

2016-12-06 12:18 UTC, oleg-nenashev approved these changes
LGTM

2016-12-06 23:22 UTC, jglick approved these changes

2016-12-06 23:42 UTC, daniel-beck approved these changes

2016-12-06 23:49 UTC, KostyaSha commented
squash merge with reference to issue please.

2016-12-06 23:52 UTC, merged