updated Russian translations
jenkinsci/jenkins pull request #2657
Opened 2016-12-08 14:21 UTC by bigscoop

added missing translations

2016-12-09 10:03 UTC, oleg-nenashev commented
Well, I'm supposed to review it

2016-12-09 18:53 UTC, oleg-nenashev commented
@bigscoop Is it "in progress"?

2016-12-10 22:10 UTC, bigscoop commented
@oleg-nenashev yep, still translating

2016-12-11 08:42 UTC, oleg-nenashev commented
OK, just ping me when you are ready

2016-12-23 20:23 UTC, daniel-beck commented
@oleg-nenashev Please squash when merging.

2016-12-23 23:24 UTC, bigscoop commented
@oleg-nenashev I'm done

2016-12-25 20:30 UTC, oleg-nenashev commented
@bigscoop Great, thanks! I will review the changes within 1-2 weeks

2017-01-08 12:41 UTC, oleg-nenashev requested changes
Thanks a lot for the translations! Added several review comments. Some changes are definitely required: license headers and a couple of typos. Other comments are rather improvement proposals

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/Job/configure_ru.properties
> +name={0}
Seems to be wrong. I would expect it to include "имя"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/Job/requirePOST_ru.properties
> +# Copyright (c) 2004-, Kohsuke Kawaguchi, Sun Microsystems, Inc., and a number of other of contributors
Wrong license header.
Please use your own name if you want to have this header in the property file

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/ListView/newJobButtonBar_ru.properties
> +Add\ to\ current\ view=\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a \u0442\u0435\u043a\u0443\u0449\u0435\u043c\u0443 \u0432\u0438\u0434\u0443
The terminology is a bit messed up here. From what I see, the translations use "вид" and "представление" terms. Maybe worth aligning at list within the scope of this PR

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/MyView/noJob_ru.properties
> +blurb=\u0414\u0430\u043d\u043d\u043e\u0435 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043d\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0437\u0430\u0
Now it's "представление"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/ProxyView/configure-entries_ru.properties
> +The\ name\ of\ a\ global\ view\ that\ will\ be\ shown.=\u0418\u043c\u044f \u0433\u043b\u043e\u0431\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0432\u0438\u0434, \u043a\u043e\u0442\u043e\u0440\u043e\u
I really like "представление" more...

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/UpdateCenter/index_ru.properties
> +Update\ Center=\u0426\u0435\u043d\u0442\u0440 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0439
I would use the capital "О" in the second word

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/View/newJob_ru.properties
> +CopyOption.description=\u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u044d\u0442\u0443 \u043e\u043f\u0446\u0438\u044e, \u0435\u0441\u043b\u0438 \u0432\u044b \u0445\u043e\u0442\u0438\u0442\u0435 \
Should start from the capital letter

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/model/View/newJob_ru.properties
> +ItemName.label=\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0438\u043c\u044f Item''\u0430
Change "Item'a" to "элемента"?

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +SCMTrigger.BuildAction.DisplayName=\u0416\u0443\u0440\u043d\u0430\u043b \u043e\u043f\u0440\u043e\u0441\u0430
Maybe "Лог" is better than "Журнал" for IT guys. BTW the current version is more correct

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +SCMTrigger.getDisplayName={0} \u0416\u0443\u0440\u043d\u0430\u043b \u043e\u043f\u0440\u043e\u0441\u0430
Maybe "Журнал опроса {0}" is better

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +TimerTrigger.DisplayName=\u0421\u043e\u0431\u0438\u0440\u0430\u0442\u044c \u043f\u0435\u0440\u0438\u043e\u0434\u0438\u0447\u0435\u0441\u043a\u0438
s/Собирать/Запускать/ . Just to reflect the real meaning of this setting

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +TimerTrigger.MissingWhitespace=\u041f\u043e\u0445\u043e\u0436\u0435 \u043d\u0435 \u0445\u0432\u0430\u0442\u0430\u0435\u0442 \u043f\u0440\u043e\u0431\u0435\u043b\u0430 \u043c\u0435\u0436\u0434\u0443 *
No comma after "Похоже"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/_safeRestart_ru.properties
> +Jenkins\ cannot\ restart\ itself\ as\ currently\ configured.=\u0421\u043e\u0433\u043b\u0430\u0441\u043d\u043e \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430\u043c, Jenkins \u043d\u0435 \u043c
"В текущей конфигурации Jenkins не может перезапуститься сам". It's not only about user settings, but rather about system configuration (OS, web container)

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/configure_ru.properties
>  System\ Message=\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u0441\u0438\u0441\u0442\u0435\u043c\u044b
Better translation: "Системное сообщение"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/configure_ru.properties
> +Build\ Record\ Root\ Directory=\u041a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u0438\u044f \u0437\u0430\u043f\u0438\u0441\u0438 \u0441\u0431\u043e\u0
"Корневая директория для сборок"?

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/load-statistics_ru.properties
> +Load\ Statistics=\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438
I,d say that "Статистика использования" would be better here

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/loginError_ru.properties
>  Invalid\ login\ information.\ Please\ try\ again.=\u041d\u0435\u0432\u0435\u0440\u043d\u043e \u0443\u043a\u0430\u0437\u0430\u043d \u043b\u043e\u0433\u0438\u043d/\u043f\u0430\u0440\u043e\u043b\u044c.
s/е/ё/ in both lines

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/newView_ru.properties
> +View\ name=\u0418\u043c\u044f \u0432\u0438\u0434\u0430
вид/представление

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +stackTracePlease=\u041f\u0440\u0438 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u043e\u0448\u0438\u0431\u043a\u0438, \u043f\u043e\u0436\u0430\u0
"s" on the end of this string

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +Twitter\:\ @jenkinsci=\u0422\u0432\u0438\u0442\u0442\u0435\u0440: jenkinsci
"@" symbol is missing in the translation

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +checkJIRA=\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435 <a href="https://issues.jenkins-ci.org/">\u043d\u0430\u0448 \u0431\u0430\u0433-\u0442\u0440\u0435\u043a\u0435\u0440</a> \u0447\u0442\u043e\u
no comma after the hyperlink

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +pleaseReport=\u0415\u0441\u043b\u0438 \u0432\u044b \u0434\u0443\u043c\u0430\u0435\u0442\u0435, \u0447\u0442\u043e \u044d\u0442\u043e \u043d\u043e\u0432\u0430\u044f \u043e\u0448\u0438\u0431\u043a\u043
"пожалуйста, создайте новый баг в JIRA"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +vote=\u0415\u0441\u043b\u0438 \u044d\u0442\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u0443\u0436\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0430, \u043f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u
s/чтобы мы поняли её охват/чтобы мы могли оценить влияние ошибки

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/lib/hudson/artifactList_ru.properties
> +view=\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c
should start from the lower-case letter, I'd guess

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/lib/hudson/project/config-assignedLabel_ru.properties
> +Restrict\ where\ this\ project\ can\ be\ run=\u041e\u0433\u0440\u0430\u043d\u0438\u0447\u0438\u0442\u044c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0437\u043b\u043e\u0432,
It's not about number of agents. It's aboult labels
Maybe "Ограничить лейблы сборщиков, которые могут исполнять данную задачу"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/lib/hudson/project/config-scm_ru.properties
> +SCM\ Checkout\ Strategy=\u0421\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u044f \u0432\u044b\u0433\u0440\u0443\u0437\u043a\u0438 \u0438\u0441\u0445\u043e\u0434\u043d\u043e\u0433\u043e \u043a\u043e\u04
"выгрузки" does not seem to be the best word,  but I cannot offer something better and generic. Maybe just "чекаута"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/lib/hudson/scriptConsole_ru.properties
> +It\ is\ not\ possible\ to\ run\ scripts\ when\ agent\ is\ offline.=\u041d\u0435\u0432\u043e\u0437\u043c\u043e\u0436\u043d\u043e \u0437\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u0441\u043a\u04
"когда агент не подключен"

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/lib/hudson/scriptConsole_ru.properties
> +description=\u0412\u0432\u0435\u0434\u0438\u0442\u0435 <a href="http://www.groovy-lang.org">Groovy \u0441\u043a\u0440\u0438\u043f\u0442</a> \u0438 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u04
I'm not sure double quotes will be processed correctly here

2017-01-08 12:41 UTC, oleg-nenashev commented on core/src/main/resources/lib/layout/layout_ru.properties
> +searchBox.url=http://wiki.jenkins-ci.org/display/JENKINS/Search+Box
I doubt it needs to be localizaed

2017-01-16 13:05 UTC, bigscoop commented
@oleg-nenashev  cool! thanks a lot! will review that in 1-2 weeks

2017-01-19 12:36 UTC, bigscoop commented on core/src/main/resources/hudson/model/Job/requirePOST_ru.properties
> +# Copyright (c) 2004-, Kohsuke Kawaguchi, Sun Microsystems, Inc., and a number of other of contributors
can I leave the header empty in that case? or just leave '# This file is under the MIT License by authors'?

2017-01-19 14:01 UTC, oleg-nenashev commented
Yes, empty header is fine for translation files. MIT license is global in
Jenkins project anyway

On Jan 19, 2017 06:37, "Dmitri Karpovich" <notifications@github.com> wrote:

> *@bigscoop* commented on this pull request.
> ------------------------------
>
> In core/src/main/resources/hudson/model/Job/requirePOST_ru.properties
> <https://github.com/jenkinsci/jenkins/pull/2657>:
>
> > @@ -0,0 +1,23 @@
> +# The MIT License
> +#
> +# Copyright (c) 2004-, Kohsuke Kawaguchi, Sun Microsystems, Inc., and a number of other of contributors
>
> can I leave the header empty in that case? or just leave '# This file is
> under the MIT License by authors'?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/2657>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC3IoG8LFdMa9LJmfj3KBo2IPwFnIH-nks5rT1jwgaJpZM4LH3nI>
> .
>

2017-01-30 13:22 UTC, bigscoop commented on core/src/main/resources/hudson/model/AllView/noJob_de.properties
> +Welcome\ to\ Jenkins!=Willkommen bei Jenkins!
that was proposed by translation-tool. also the neighbor files have the same key

2017-01-30 13:25 UTC, bigscoop commented on core/src/main/resources/hudson/model/Job/requirePOST_ru.properties
> +# Copyright (c) 2004-, Kohsuke Kawaguchi, Sun Microsystems, Inc., and a number of other of contributors
ok

2017-01-30 13:27 UTC, bigscoop commented on core/src/main/resources/hudson/model/Job/configure_ru.properties
> +name={0}
ok

2017-01-30 13:31 UTC, bigscoop commented on core/src/main/resources/hudson/model/ListView/newJobButtonBar_ru.properties
> +Add\ to\ current\ view=\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a \u0442\u0435\u043a\u0443\u0449\u0435\u043c\u0443 \u0432\u0438\u0434\u0443
ok, changed to "представление"

2017-01-30 13:34 UTC, bigscoop commented on core/src/main/resources/hudson/model/MyView/noJob_ru.properties
> +blurb=\u0414\u0430\u043d\u043d\u043e\u0435 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043d\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0438\u0442 \u0437\u0430\u0
ok

2017-01-30 13:35 UTC, bigscoop commented on core/src/main/resources/hudson/model/ProxyView/configure-entries_ru.properties
> +The\ name\ of\ a\ global\ view\ that\ will\ be\ shown.=\u0418\u043c\u044f \u0433\u043b\u043e\u0431\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0432\u0438\u0434, \u043a\u043e\u0442\u043e\u0440\u043e\u
ok

2017-01-30 13:39 UTC, bigscoop commented on core/src/main/resources/hudson/model/View/newJob_ru.properties
> +CopyOption.description=\u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u044d\u0442\u0443 \u043e\u043f\u0446\u0438\u044e, \u0435\u0441\u043b\u0438 \u0432\u044b \u0445\u043e\u0442\u0438\u0442\u0435 \
ok

2017-01-30 13:40 UTC, bigscoop commented on core/src/main/resources/hudson/model/View/newJob_ru.properties
> +ItemName.label=\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0438\u043c\u044f Item''\u0430
ok

2017-01-30 13:42 UTC, bigscoop commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +SCMTrigger.BuildAction.DisplayName=\u0416\u0443\u0440\u043d\u0430\u043b \u043e\u043f\u0440\u043e\u0441\u0430
ok

2017-01-30 13:43 UTC, bigscoop commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +SCMTrigger.getDisplayName={0} \u0416\u0443\u0440\u043d\u0430\u043b \u043e\u043f\u0440\u043e\u0441\u0430
ok

2017-01-30 13:45 UTC, bigscoop commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +TimerTrigger.DisplayName=\u0421\u043e\u0431\u0438\u0440\u0430\u0442\u044c \u043f\u0435\u0440\u0438\u043e\u0434\u0438\u0447\u0435\u0441\u043a\u0438
ok

2017-01-30 13:46 UTC, bigscoop commented on core/src/main/resources/hudson/triggers/Messages_ru.properties
> +TimerTrigger.MissingWhitespace=\u041f\u043e\u0445\u043e\u0436\u0435 \u043d\u0435 \u0445\u0432\u0430\u0442\u0430\u0435\u0442 \u043f\u0440\u043e\u0431\u0435\u043b\u0430 \u043c\u0435\u0436\u0434\u0443 *
ok

2017-01-30 14:31 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/_safeRestart_ru.properties
> +Jenkins\ cannot\ restart\ itself\ as\ currently\ configured.=\u0421\u043e\u0433\u043b\u0430\u0441\u043d\u043e \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430\u043c, Jenkins \u043d\u0435 \u043c
ok

2017-01-30 15:29 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/configure_ru.properties
>  System\ Message=\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u0441\u0438\u0441\u0442\u0435\u043c\u044b
ok

2017-01-30 15:56 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/configure_ru.properties
> +Build\ Record\ Root\ Directory=\u041a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u0438\u044f \u0437\u0430\u043f\u0438\u0441\u0438 \u0441\u0431\u043e\u0
ok, agree, much better

2017-01-30 15:57 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/load-statistics_ru.properties
> +Load\ Statistics=\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438
ok

2017-01-30 16:00 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/newView_ru.properties
> +View\ name=\u0418\u043c\u044f \u0432\u0438\u0434\u0430
ok

2017-01-30 16:20 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +stackTracePlease=\u041f\u0440\u0438 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u043e\u0448\u0438\u0431\u043a\u0438, \u043f\u043e\u0436\u0430\u0
ok

2017-01-30 17:23 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +Twitter\:\ @jenkinsci=\u0422\u0432\u0438\u0442\u0442\u0435\u0440: jenkinsci
ok

2017-01-30 17:24 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +checkJIRA=\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435 <a href="https://issues.jenkins-ci.org/">\u043d\u0430\u0448 \u0431\u0430\u0433-\u0442\u0440\u0435\u043a\u0435\u0440</a> \u0447\u0442\u043e\u
ok

2017-01-30 17:25 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +pleaseReport=\u0415\u0441\u043b\u0438 \u0432\u044b \u0434\u0443\u043c\u0430\u0435\u0442\u0435, \u0447\u0442\u043e \u044d\u0442\u043e \u043d\u043e\u0432\u0430\u044f \u043e\u0448\u0438\u0431\u043a\u043
ok

2017-01-30 17:25 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/oops_ru.properties
> +vote=\u0415\u0441\u043b\u0438 \u044d\u0442\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u0443\u0436\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0430, \u043f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u
ok

2017-01-30 17:27 UTC, bigscoop commented on core/src/main/resources/lib/hudson/artifactList_ru.properties
> +view=\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c
ok

2017-01-30 17:28 UTC, bigscoop commented on core/src/main/resources/lib/hudson/project/config-assignedLabel_ru.properties
> +Restrict\ where\ this\ project\ can\ be\ run=\u041e\u0433\u0440\u0430\u043d\u0438\u0447\u0438\u0442\u044c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0437\u043b\u043e\u0432,
ok

2017-01-30 17:30 UTC, bigscoop commented on core/src/main/resources/lib/hudson/project/config-scm_ru.properties
> +SCM\ Checkout\ Strategy=\u0421\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u044f \u0432\u044b\u0433\u0440\u0443\u0437\u043a\u0438 \u0438\u0441\u0445\u043e\u0434\u043d\u043e\u0433\u043e \u043a\u043e\u04
ok, typed "checkout'а"

2017-01-30 17:31 UTC, bigscoop commented on core/src/main/resources/lib/hudson/scriptConsole_ru.properties
> +It\ is\ not\ possible\ to\ run\ scripts\ when\ agent\ is\ offline.=\u041d\u0435\u0432\u043e\u0437\u043c\u043e\u0436\u043d\u043e \u0437\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u0441\u043a\u04
ok

2017-01-30 17:33 UTC, bigscoop commented on core/src/main/resources/lib/hudson/scriptConsole_ru.properties
> +description=\u0412\u0432\u0435\u0434\u0438\u0442\u0435 <a href="http://www.groovy-lang.org">Groovy \u0441\u043a\u0440\u0438\u043f\u0442</a> \u0438 \u0432\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u04
ok, replaced with ''''

2017-01-30 17:35 UTC, bigscoop commented on core/src/main/resources/lib/layout/layout_ru.properties
> +searchBox.url=http://wiki.jenkins-ci.org/display/JENKINS/Search+Box
well, in other languages these strings are localized

2017-01-30 17:36 UTC, bigscoop commented on core/src/main/resources/hudson/PluginManager/check_ru.properties
> +lastUpdated=\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e: {0} \u043d\u0430\u0437\u0430\u0434
ok, done

2017-01-30 17:37 UTC, bigscoop commented on core/src/main/resources/hudson/model/UpdateCenter/index_ru.properties
> +Update\ Center=\u0426\u0435\u043d\u0442\u0440 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0439
ok

2017-01-30 17:38 UTC, bigscoop commented on core/src/main/resources/jenkins/model/Jenkins/loginError_ru.properties
>  Invalid\ login\ information.\ Please\ try\ again.=\u041d\u0435\u0432\u0435\u0440\u043d\u043e \u0443\u043a\u0430\u0437\u0430\u043d \u043b\u043e\u0433\u0438\u043d/\u043f\u0430\u0440\u043e\u043b\u044c.
where exactly?

2017-01-30 17:42 UTC, bigscoop commented
@oleg-nenashev I've fixed files, pls review

2017-02-12 10:39 UTC, oleg-nenashev commented
The ball is on my side

2017-02-16 07:01 UTC, oleg-nenashev commented
@bigscoop Sorry for the long delay. FOSDEM, etc. I will review and integrate changes on this weekend

2017-02-25 19:09 UTC, oleg-nenashev approved these changes
👍 after the manual review of changes

2017-03-14 09:02 UTC, oleg-nenashev commented
It has been merged via #2798. Thanks @bigscoop !

2017-03-14 09:02 UTC, closed without merging