Fix JENKINS-40286: SlaveComputer should be the only place that JnlpMac is computed
jenkinsci/jenkins pull request #2658
Opened 2016-12-08 14:24 UTC by kbrowder

This change centralizes the jnlpMac generation and makes it simpler for plugin developers extending SlaveComputer to change how the encryption key is generated.

2016-12-09 10:17 UTC, oleg-nenashev requested changes
Binary incompatibility issue. IMHO you could just start from something like...

```java
final byte[] jnlpMac;
if (it instanceof SlaveComputer) {
  jnlpMac = Util.fromHexString(it.getJnlpMac());
nlpMac = Util.fromHexString(it.getJnlpMac());
} else {
   jnlpMac = JnlpSlaveAgentProtocol.SLAVE_SECRET.mac(slaveName.getBytes("UTF-8"));
}
```

I'm not 100% sure it can fly in the proposed way (need a deep dive if it changes the behavior of our internal plugins)

2016-12-09 10:17 UTC, oleg-nenashev commented on core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
> +    public EncryptedSlaveAgentJnlpFile(SlaveComputer it, String viewName, Permission connectPermission) {
This is a binary incompatible change. It does not impact open-source plugins (the only use-case in Jenkins org is Mesos plugin), but I have confirmed it impacts a couple of private-source plugins.

2016-12-09 10:53 UTC, jtnord requested changes
Please keep backwards compatability

2016-12-09 10:53 UTC, jtnord commented on core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
> +     * some type of {@link SlaveComputer}.
This is unfortunately an incorrect assumption.  The only reason you need to have changed this is to get the MAC of the JNLP slave, but you can achieve this by keeping binary compatibility.

2016-12-09 10:53 UTC, jtnord commented on core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
> +    public EncryptedSlaveAgentJnlpFile(SlaveComputer it, String viewName, Permission connectPermission) {
It is possible to keep backwards compatibility here if you keep the existing constructor and compute the MAC for the slave there.

In your new constructor get the mac and store it, and then use this stored mac in `generateResponse()`

2016-12-09 14:54 UTC, kbrowder commented
OK I've made it backwards compatible in basically the way @oleg-nenashev suggested.  I didn't pre-compute the mac like @jtnord since it looked like I'd have to change the constructors throws.
Sorry it took two commits for this latest change (it's 0a08a81 that really contains the change), PEBKAC on my part, I can rebase if you'd like.

@oleg-nenashev
> I'm not 100% sure it can fly in the proposed way (need a deep dive if it changes the behavior of our internal plugins).
That's a good question.  Although in those cases the UI is busted currently (because the jelly files use getJnlpMac) to give you the Jnlp connection string.

2016-12-09 15:00 UTC, oleg-nenashev commented
No need in rebasing, we can just squash commits during the merge

2016-12-11 10:07 UTC, oleg-nenashev approved these changes
The proposed change looks good to me. 👍

2016-12-11 10:10 UTC, oleg-nenashev commented
Just for the future, I would rather introduce a new interface like `JNLPMacProvider` with `getJnlpMac()`. In such case other `AccessControlled` items will be also able to tweak the logic by implementing this interface. Maybe deserves a follow-up JIRA ticket

2016-12-13 14:22 UTC, kbrowder commented
@oleg-nenashev I created [JENKINS-40413](https://issues.jenkins-ci.org/browse/JENKINS-40413) to that effect

2016-12-14 09:35 UTC, oleg-nenashev commented
@jtnord WDYT? about the new version?

2016-12-15 10:30 UTC, jtnord approved these changes

2016-12-15 10:31 UTC, merged