Enhance CLI HTTP proxy support
jenkinsci/jenkins pull request #2711
Opened 2017-01-10 19:25 UTC by ydubreuil

Fix few issues around proxy support in CLI:

* make proxy support work with recent Squid version which reply with HTTP/1.1 even if request is HTTP 1.0
* close the socket connected to the proxy if the connection failed
* output an error message when proxy connection failed
* don't do a reverse DNS lookup, instead use the host string provided in X-Jenkins-CLI-Host headers. It can be a IP address passed with `hudson.TcpSlaveAgentListener.hostName` (we don't know if the DNS resolver on the proxy will be able to resolve the name correctly, or like us).

@reviewbybees

2017-01-10 21:39 UTC, KostyaSha commented on cli/src/main/java/hudson/cli/CLI.java
> +                System.err.println("Failed to tunnel the CLI port through the HTTP proxy. Falling back to HTTP.");
Don't print directly to stderr, i'm using CLI programmatically and don't need to have stderr on jvm.

2017-01-10 21:40 UTC, KostyaSha requested changes
it shouldn't print to stderr directly

2017-01-11 08:02 UTC, oleg-nenashev requested changes
I agree with @KostyaSha

2017-01-11 10:13 UTC, ydubreuil commented on cli/src/main/java/hudson/cli/CLI.java
> +                System.err.println("Failed to tunnel the CLI port through the HTTP proxy. Falling back to HTTP.");
I did this to be consistent with other part of the code, like https://github.com/jenkinsci/jenkins/blob/master/cli/src/main/java/hudson/cli/CLI.java#L418 or https://github.com/jenkinsci/jenkins/blob/master/cli/src/main/java/hudson/cli/CLI.java#L482 . I don't mind outputting to stdout if you prefer

2017-01-11 10:15 UTC, KostyaSha commented on cli/src/main/java/hudson/cli/CLI.java
> +                System.err.println("Failed to tunnel the CLI port through the HTTP proxy. Falling back to HTTP.");
Because main is used for console execution and other methods are programmatically useable.

2017-01-11 10:58 UTC, ydubreuil commented on cli/src/main/java/hudson/cli/CLI.java
> +                System.err.println("Failed to tunnel the CLI port through the HTTP proxy. Falling back to HTTP.");
Ok, got it!

2017-01-11 18:39 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-01-11 19:57 UTC, daniel-beck commented
@ydubreuil I think the idea was to use a logger. CC @oleg-nenashev @KostyaSha

2017-01-12 00:06 UTC, KostyaSha commented
> @ydubreuil I think the idea was to use a logger. CC @oleg-nenashev @KostyaSha

Even logger not needed because exception is thrown. Printing to console instead of loggers is bad pattern. main is exclusion because it used from cli.

2017-01-12 09:21 UTC, ydubreuil commented
I wanted to make it explicit there was an error. The thrown exception is logged with FINE level and is not printed unless you pass a custom logger configuration. I'll use the ERROR to print the additional message.

2017-01-12 09:37 UTC, ydubreuil commented
I just tried to change `System.out` with

```
LOGGER.log(Level.SEVERE, "Failed to tunnel the CLI port through the HTTP proxy. Falling back to HTTP.");
```

Unfortunately, it seems there's no logger configured on the CLI process, so it doesn't go anywhere. Any thought?

2017-01-16 00:18 UTC, KostyaSha commented
@ydubreuil maybe it printed from main? Afair main calls it and main will have your Exception with message.

2017-01-16 13:54 UTC, ydubreuil commented
The exception is silenced in `CLI` constructor, when it falls back to HTTP. It never reach `_main`. I'll turn it into a log write for now, and see if I can configure the logging system in `_main` to at least print out SEVERE messages.

2017-01-16 15:15 UTC, KostyaSha commented on cli/src/main/java/hudson/cli/CLI.java
> +            if(head.equals("-v")) {
you may expose numeric value of logging level and note in docs what level is for what value

2017-01-16 17:18 UTC, ydubreuil commented on cli/src/main/java/hudson/cli/CLI.java
> +            if(head.equals("-v")) {
I was not feeling it was worth it, there's only few messages which could be outputted and it's easier to have just a single parameter to turn logs on IMO.

2017-02-17 22:23 UTC, oleg-nenashev requested changes
🐛 since the `-v` option may reduce the effective logging level is some cases. I doubt it is an expected behavior

2017-02-17 22:23 UTC, oleg-nenashev commented on cli/src/main/java/hudson/cli/CLI.java
> +            if(head.equals("-v")) {
I agree it is not that important since it can be done via the j.u.l property file anyway

2017-02-17 22:23 UTC, oleg-nenashev commented on cli/src/main/java/hudson/cli/CLI.java
> +                    h.setLevel(FINE);
I feel it is a 🐛 , because this setting may *reduce* the logging level, e.g. if it is configured as DEBUG by the j.u.l. property file

2017-02-17 22:23 UTC, oleg-nenashev commented on cli/src/main/resources/hudson/cli/client/Messages.properties
> +   -v           : verbose output. Display logs on the console\n\
I think it should briefly explain the behavior and the j.u.l logging levels to be set

2017-02-17 22:24 UTC, oleg-nenashev commented
Please also create a JIRA issue for the fixes. It may be a backportable change

2017-02-20 09:16 UTC, ydubreuil commented on cli/src/main/java/hudson/cli/CLI.java
> +                    h.setLevel(FINE);
Changing to `FINEST` so there will be no surprise.

2017-02-20 09:16 UTC, ydubreuil commented on cli/src/main/resources/hudson/cli/client/Messages.properties
> +   -v           : verbose output. Display logs on the console\n\
ok, will do

2017-02-20 09:27 UTC, ydubreuil commented
I filed [JENKINS-42191](https://issues.jenkins-ci.org/browse/JENKINS-42191)

2017-03-08 10:22 UTC, oleg-nenashev approved these changes
I am not sure that `FINEST` is a good idea (https://github.com/jenkinsci/jenkins/pull/2711/commits/c36b5c53f7d8221073fa44a4e0fdb7a07e5623ee), but formally it solves my concern.

Maybe `-v`, `-vv` and `-vvv` would be better.

2017-03-13 12:37 UTC, oleg-nenashev commented
🐝  and @reviewbybees done (5 days under review)

2017-03-13 12:38 UTC, oleg-nenashev commented
@KostyaSha WDYT about the new version?

2017-03-13 12:46 UTC, jtnord commented on cli/src/main/java/hudson/cli/CLI.java
> +            if (!(head.startsWith("HTTP/1.0 200 ") || head.startsWith("HTTP/1.1 200 "))) {
NB: this should match HTTP/1.* 200  as per rfc2145

2017-03-13 13:39 UTC, jglick commented on cli/src/main/java/hudson/cli/CLI.java
> +        l.addHandler(h);
Note: will conflict with #2795.

2017-03-14 14:29 UTC, ydubreuil commented on cli/src/main/java/hudson/cli/CLI.java
> +            if (!(head.startsWith("HTTP/1.0 200 ") || head.startsWith("HTTP/1.1 200 "))) {
Given HTTP 2.0 is a brand new protocol and that only HTTP 1.0 and HTTP 1.1 exist, I would prefer to keep the test as it is.

2017-03-15 12:17 UTC, oleg-nenashev commented on cli/src/main/java/hudson/cli/CLI.java
> +        l.addHandler(h);
I suppose we should merge this fix first anyway even if it is a soon-to-be-dead PR

2017-03-15 12:18 UTC, oleg-nenashev approved these changes
Ready to merge if @jtnord agrees with the response from @ydubreuil

2017-03-17 12:19 UTC, jtnord commented
@oleg-nenashev it was not a bug from me, happy to merge regardless of the comment response   :-)

2017-03-17 13:09 UTC, merged