[JENKINS-39402] Cap the number of group headers printed by AccessDeniedException2
jenkinsci/jenkins pull request #2727
Opened 2017-01-27 21:19 UTC by jglick

[JENKINS-39402](https://issues.jenkins-ci.org/browse/JENKINS-39402)

@reviewbybees

2017-01-27 21:20 UTC, jglick commented on test/src/test/java/hudson/security/AccessDeniedException2Test.java
> +            assertEquals(HttpURLConnection.HTTP_FORBIDDEN, x.getStatusCode());
Without fix, fails here with a 500 from Jetty as reported in the field.

2017-01-27 21:20 UTC, jglick commented on test/src/test/java/hudson/security/AccessDeniedException2Test.java
> +                Matchers.<String>hasItem("<991 more>"))); // 1000 + SecurityRealm.AUTHENTICATED_AUTHORITY.getAuthority() - 10
order may be arbitrary

2017-01-28 22:13 UTC, daniel-beck approved these changes
Looks good, although I'm not convinced that with the low limit any useful behavior in nontrivial security realms (where this is actually needed) will remain.

2017-01-28 22:13 UTC, daniel-beck commented on core/src/main/java/hudson/security/AccessDeniedException2.java
> +    private static final int MAX_REPORTED_AUTHORITIES = 10;
Seems to be too low to be useful, especially given crazy behaviors such as https://github.com/jenkinsci/ldap-plugin/blob/4ced65b080ff3eb81ad23916ccb6133077b80185/src/main/java/hudson/security/LDAPSecurityRealm.java#L1039

2017-01-30 11:15 UTC, rsandell commented
:bee:

2017-01-30 14:31 UTC, jglick commented
> any useful behavior in nontrivial security realms

I think this is more a place to start diagnosis. You can always go to `/whoAmI` etc. to see the gory details. I do not want to print many headers for fear of pushing against limits in haproxy and the like.

2017-01-30 14:31 UTC, jglick commented
@reviewbybees done

2017-01-30 15:01 UTC, daniel-beck commented
Should this not rather count both headers and individual authority name length as well? I.e. cap individual names at ~50 chars long or something?

2017-01-30 16:10 UTC, oleg-nenashev requested changes
I agree with @daniel-beck that the limit seems to be too small. In order to avoid negative, the limit should be modifiable via `SystemProperties` at least

2017-01-30 16:47 UTC, jglick commented
These suggestions are more effort than they are worth. I would rather just delete the functionality altogether.

2017-01-30 22:43 UTC, jtnord commented on core/src/main/java/hudson/security/AccessDeniedException2.java
> +        GrantedAuthority[] authorities = authentication.getAuthorities();
do we even need to report this given there is a `whoAmI` which reports this in a much nicer way (and most users won't check the headers, and most scripts can't take any action)

2017-01-30 22:44 UTC, jtnord commented on core/src/main/java/hudson/security/AccessDeniedException2.java
> +    private static final int MAX_REPORTED_AUTHORITIES = 10;
tbh I'm not sure reporting this is ever useful, given the `whoAmI` url

2017-01-30 22:45 UTC, jtnord commented
> These suggestions are more effort than they are worth. I would rather just delete the functionality altogether.

I do not see a use for this funcationality given there is a `whoAmI` so +1 to that.  but :bee: as it stands as it fixes the issue

2017-01-30 22:47 UTC, jtnord approved these changes
Fixes the issue - but not sure it makes sense to leave something capped in the code that you can get from `whoAmI` with a full list.

2017-01-31 18:37 UTC, oleg-nenashev commented
I would rather like to see a test demonstrating the correct behavior in both modes than just removal of the test logic for the disabled logic

2017-01-31 18:58 UTC, jglick commented
> a test demonstrating the correct behavior in both modes

If it is disabled by default, who cares? There was no test before and patch merely conditionally runs the original code. The test logic in the initial version of the patch was to verify that the more complicated capping logic worked.

2017-02-02 19:31 UTC, oleg-nenashev commented on core/src/main/java/hudson/security/AccessDeniedException2.java
> +        if (REPORT_GROUP_HEADERS) {
If false, I would rather return a message like "Disabled due to JENKINS-39402; use /whoAmI to diagnose groups. Or set the XXX system property to true" within the Header value

2017-02-02 19:56 UTC, jtnord approved these changes
:bee:

2017-02-10 15:13 UTC, merged