[JENKINS-41684] Ensure that PluginManager.dynamicLoad runs as SYSTEM
jenkinsci/jenkins pull request #2732
Opened 2017-02-02 22:55 UTC by jglick

[JENKINS-41684](https://issues.jenkins-ci.org/browse/JENKINS-41684)

@reviewbybees

2017-02-03 17:17 UTC, jglick commented
Test failures look unrelated.

2017-02-04 06:58 UTC, daniel-beck commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
Do we really want to not indent this entire block?

2017-02-06 18:27 UTC, jglick commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
I wanted to create a minimal diff, since the intervening block is quite long.

2017-02-06 20:25 UTC, oleg-nenashev approved these changes

2017-02-06 20:25 UTC, oleg-nenashev commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
Maybe it is reasonable to keep the entire method within the clause anyway. There are extension points like `PluginStrategy#updateDependency()`, which may also blow up in the case of the non-System user

2017-02-07 16:23 UTC, jglick commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
Unlikely but conceivable.

2017-02-09 16:25 UTC, jglick commented
@reviewbybees done

2017-02-09 19:54 UTC, KostyaSha commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
> I wanted to create a minimal diff, since the intervening block is quite long.

and max efforts to read logic later

2017-02-09 19:56 UTC, KostyaSha commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
Extract to private method should also provide short diff.

2017-02-09 22:28 UTC, daniel-beck commented on core/src/main/java/hudson/PluginManager.java
> +        try (ACLContext context = ACL.as(ACL.SYSTEM)) {
Would really prefer if something would be done here for readability.

2017-02-09 22:53 UTC, KostyaSha requested changes
intend, i.e. private method

2017-02-10 15:54 UTC, jglick commented on core/src/main/java/hudson/PluginManager.java
> -        LOGGER.info("Attempting to dynamic load "+arc);
Now you are going to have use [this](https://github.com/jenkinsci/jenkins/pull/2732/files?w=1) to understand what is going on.

2017-02-10 15:56 UTC, KostyaSha commented
> I am sick of trying to explain to people how important minimal diffs are.

You can make private method and you will have small diff. Making code messed will definitely make you alone to such parts of code.

2017-02-10 16:01 UTC, daniel-beck commented
:+1:

2017-02-10 16:19 UTC, jglick commented
> You can make private method and you will have small diff.

Yes, but at a cost of added complexity worse than either the diff size or nonstandard indentation.

2017-02-12 10:36 UTC, merged