[FIX JENKINS-9104] Add support for the slaves to access the veto list from the master
jenkinsci/jenkins pull request #2741
Opened 2017-02-09 05:55 UTC by Andne

This is based on my comments in [JENKINS-9104](https://issues.jenkins-ci.org/browse/JENKINS-9104).  I was able to add a test where the process got killed by a slave node and then add my other changes in to make the `ProcessKillingVeto` list get accessed in the same fashion as the `ProcessKillers` list.  Without this change, we have had to disable the process tree killer on any slaves that run Visual C++ so we avoid the issue where `mspdbsrv.exe` gets stopped by one build while a second build is still using it and ends up failing the second build.

I am hoping that this can get this included before the next LTS branch is created, I need it in an LTS branch in order to get our IT group to update the server to it.  The only other solution I could come up with is to somehow get the msbuild plugin to copy its `ProcessKillingVeto` child class to the slaves so that the ExtensionList is properly populated in that system.

2017-02-09 08:45 UTC, oleg-nenashev requested changes
IMHO there are some compatibility issues. I also think serialization of extension points themselves to agents is not something we want to do (CC @stephenc , who was working on the `OnMaster` annotation)

2017-02-09 08:45 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessKillingVeto.java
> +public abstract class ProcessKillingVeto implements ExtensionPoint, Serializable {
I am afraid it cannot work in such way. There may be already non-serializable extension point implementations. I would also vote against propagating new extension points to agents. I will likely have to write a wrapper class like `OnNodeProcessKillingVetoHandler` and return it from a method if the extension point supports vetoing there.

2017-02-09 08:45 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessTree.java
> +    final List<ProcessKillingVeto> getVetoers() throws InterruptedException {
This method does not contain invalidation logic for the cache. If somebody installs a new plugin for vetoing, it won't work till the class instance gets recreated

2017-02-09 08:45 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessTree.java
> +                vetoers = Collections.emptyList();
It would be a fatal error since Jenkins won't retry to collect the list within the same class instance

2017-02-09 08:45 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessTree.java
> +        protected @CheckForNull VetoCause getVeto() throws InterruptedException {
It breaks the compatibility if any child class invokes this method

2017-02-09 10:15 UTC, stephenc commented
`ExtensionList.lookup` was not designed to work on a remote agent JVM.

I think we need to find a better way to allow this kind of extensibility on agents.

My belief is that we should just deprecate this specific extension point and replace with a better implementation that can work.

As to breaking compatibility, given that the existing implementations cannot work on remote agents anyway, I think worrying about compatibility is irrelevant!

2017-02-09 13:17 UTC, Andne commented on core/src/main/java/hudson/util/ProcessTree.java
> +    final List<ProcessKillingVeto> getVetoers() throws InterruptedException {
If I understand correctly, the class is recreated every time ProcessTree.get() is called, which appears to be at the end of any call to Launcher.  Does it matter if the new plugin isn't invoked for a currently running job? I think that's the worst case that would happen here (if even that much).

2017-02-09 13:26 UTC, Andne commented on core/src/main/java/hudson/util/ProcessTree.java
> +        protected @CheckForNull VetoCause getVeto() throws InterruptedException {
According to GitHub, the only current usage appears to be within Jenkins itself.  Granted, someone could have used it in a private version, but I think that's unlikely.

2017-02-09 13:59 UTC, Andne commented
I understand keeping compatibility, but that does seem somewhat pointless when the existing implementation doesn't fully work anyways. The only known usage of this extension I can find is in the MSBuild plugin. I think that as long as the system doesn't crash, it should be ok to change it. If MSBuild has to be updated for it to be used, that seems ok.

Some additional reading from October indicates that ExtensionPoints aren't supposed to be on slaves, though I'm a little unsure what the final conclusion from that conversation is.

I copied the functionality from ProcessKillers, so that should also be revisited if this is not the right way to handle the logic.

2017-02-09 14:01 UTC, Andne commented on core/src/main/java/hudson/util/ProcessKillingVeto.java
> +public abstract class ProcessKillingVeto implements ExtensionPoint, Serializable {
Wouldn't that approach require going back to the master for every process? Is that really needed or a good idea?

Well, I think you'd probably only go back for those that have the cookie/env. variable set, so maybe not so bad.

2017-02-09 15:07 UTC, Andne commented on core/src/main/java/hudson/util/ProcessKillingVeto.java
> +public abstract class ProcessKillingVeto implements ExtensionPoint, Serializable {
FWIW, I was able to test this out this morning on an instance that has the current released version of the MSBuild plugin and it worked properly.  To my knowledge, MSBuild plugin is the only known implementation of this ExtensionPoint so far (or at least the only one in Jenkins GitHub).

I ran a job both on the slave and on master and each time the mspdbsrv process survives the job completion and I see a message in the log recorder that killing that process id has been veto'd.

2017-02-24 22:47 UTC, Andne commented
What should be done with this?  As long as the ExtensionPoint doesn't work on agents, it is causing issues in production environments.  Is this an acceptable fix until the used API's can be improved to better handle ExtensionPoints on agents or does this need to be redone to avoid the serialization and perform the checks on the master instead?

Somewhat related is ProcessKillers.  It already has this defined behavior of passing the list of ExtensionPoints to the agent so it can process them.  It seems to me that ProcessKillers and ProcessKillingVeto ought to be made to work in the same fashion given how close they are to each other.

2017-02-25 18:52 UTC, daniel-beck commented
@stephenc @oleg-nenashev Please see comments above. How can we proceed here?

2017-02-25 19:07 UTC, oleg-nenashev commented
Ideally somebody needs to rewrite this extension point implementation.
Instead of the extension point itself, let's do the following:

* Create a new entity, e.g. "class RemoteVetoInfo implements Serializable", which will provide the vetoing functionality and carry the serializable data over the channel
* Add a method to the extension point, e.g. `@CheckforNull RemoteVetoInfo produceRemoteVetoInfo()  { return null; }"
* Make the agent to request the collection of `RemoteVetoInfo` instead of the extension points

In such case we will be able to avoid sending the extension point implementation over the channel && also avoid the compatibility issues. But the desired functionality will be implemented.

2017-02-27 06:37 UTC, Andne commented
I'm starting to work on this, think I have a good idea where to start, but I have a couple questions:
1. Can I safely use `ProcessKillingVeto.VetoCause` on the agent, or do I need to duplicate that class?  If it is safe to use, then should the new class be a similar child-class of `ProcessKillingVeto` instead of a sibling class?
2. How should agent vs. master be handled?  Does the master using the existing logic and the agent use the new logic?  Maybe it makes sense that the master should use both the existing logic and any 'remote' objects that are provided?  I think I can set up `getVeto()` to try and loop through both lists pretty easily, the end result would be that on an agent the ExtensionPoint list would do nothing and then the remote list would provide the veto instead.

Out of curiosity, what is the reason that the ExtensionPoint shouldn't/can't be Serializable and passed to the agent?  I have nearly no understanding of java remoting, so don't understand any potential issues.

2017-03-10 09:31 UTC, oleg-nenashev commented
Sorry for the response delay @Andne 

1) VetoCause is not serializable, so you cannot easily propagate it over the channel. And you cannot make it serializable without formal comatibility breakage. Maybe @jenkinsci/code-reviewers agree that this case is acceptable, but maybe creating a clone class like `RemotableVetoCause` is better. If you do that, maybe it also worth to put the exception into the class along with the string message
2) "Maybe it makes sense that the master should use both the existing logic and any 'remote' objects that are provided? ". It would be prefeerable

> Out of curiosity, what is the reason that the ExtensionPoint shouldn't/can't be Serializable and passed to the agent? 

* Extension points are being managed within Jenkins master, and generally access to them requires a `Jenkins` instance, which is not being serialized to agents
* We have sees many cases in the plugin code, when presumptions about `Jenkins` instance existence are being made in extension point implementations, and such plugins were not working reliably on agents
* We would like to improve static analysis of the Jenkins codebase in order to simplify contribution, and such `Serializable` extension points are actually one of the problems on this front

So right now extension point implementations can be serialized to agents and may behave probably, but we are planning to deprecate this approach at some point

2017-03-11 17:18 UTC, Andne commented
Am I allowed to change the return type of `getVeto()`?  It executes on the agent machine, but returns a `VetoCause`, so I'm struggling with what a clone class would accomplish since I still have to convert it to or otherwise create a `VetoCause` in order to return from `getVeto()`.  I don't think it's a good idea to duplicate `getVeto()` with a `getRemoteVeto()` function, that just makes it too easy to forget to check both lists.  Does `VetoCause` need to be `Serializable` if it's both created and destroyed on the agent?

2017-03-11 18:54 UTC, oleg-nenashev commented
Currently getVeto() is already a breaking change (InterruptedException), so probably it's fine

2017-03-11 18:55 UTC, oleg-nenashev commented
> Does VetoCause need to be Serializable if it's both created and destroyed on the agent?

If you do not serialize it over the channel, no need to make it serializable

2018-03-11 18:20 UTC, daniel-beck commented
@Andne Do you plan to finish this?

2018-03-12 12:55 UTC, Andne commented
It’s been a while, but I was having trouble getting a new class to work properly.  I suspect I need to rethink what I was doing and try to keep the extension point on the master. While I would like to get this working, I suppose I can close this PR and open a new one when I come up with a better solution.

2018-03-12 12:55 UTC, closed without merging