[WIP] Fix tests on Windows
jenkinsci/jenkins pull request #2745
Opened 2017-02-10 20:36 UTC by slide

Initial low hanging fruit for testing on Windows.

2017-02-10 22:22 UTC, daniel-beck commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
>      @Test public void consoleShouldSuccessWithFollow() throws Exception {
Add a TODO to fix this test. sleep 10. I can't even.

2017-02-10 22:23 UTC, daniel-beck commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                    + "ping 1.1.1.1 -n 1 -w 10000 >NUL\r\nver >NUL\r\necho after sleep - %BUILD_NUMBER%"));
`timeout /t 10`?

2017-02-11 01:14 UTC, slide commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                    + "ping 1.1.1.1 -n 1 -w 10000 >NUL\r\nver >NUL\r\necho after sleep - %BUILD_NUMBER%"));
timeout isn't available on all versions of Windows. I am not sure what versions we need to support.

2017-02-12 11:35 UTC, oleg-nenashev commented on test/src/test/java/hudson/cli/AbstractBuildRangeCommandTest.java
> +        assertThat(result.stdout(), containsString("Builds: 10"+System.lineSeparator()));
Why not just `%n` ?

2017-02-12 11:36 UTC, oleg-nenashev reviewed
Looks good so far (excepting line separators, but maybe the macro does not work in this case)

2017-02-12 14:40 UTC, slide commented on test/src/test/java/hudson/cli/AbstractBuildRangeCommandTest.java
> +        assertThat(result.stdout(), containsString("Builds: 10"+System.lineSeparator()));
I didn't know it existed

2017-02-12 19:40 UTC, daniel-beck commented
CC @jtnord FYI. Close to merging already.

2017-02-13 09:46 UTC, daniel-beck commented
Why did 3d778c1 pass when all of these other tests still needed to be ignored?

2017-02-13 11:43 UTC, jtnord commented
> Why did 3d778c1 pass when all of these other tests still needed to be ignored?

@daniel-beck because the windows tests are not run on the CI.

I guess this needs to also revert [this change](https://github.com/jenkinsci/jenkins/commit/d46fc53ca4215bf84ecacadbe03e7789c9c019ec#diff-58231b16fdee45a03a4ee3cf94a9f2c3) to the Jenkinsfile

2017-02-13 11:50 UTC, daniel-beck commented
@jtnord Check the target branch's Jenkinsfile.

2017-02-13 11:52 UTC, jtnord commented on test/src/test/java/hudson/cli/AbstractBuildRangeCommandTest.java
> +        assertThat(result.stdout(), containsString("Builds: 10"+System.lineSeparator()));
containsString doesn;t take a string format according to the docs?  Are you proposing to use `contasintString(String.format("Builds: 10%n"))`  - in which case this looks ugly - so a matcher `containsFormattedString(String, Object...)` would be cleaner, or even a `containsLine(String)` that adds the line end...

2017-02-13 11:56 UTC, jtnord commented
@daniel-beck then it is because of [this bug](https://issues.jenkins-ci.org/browse/JENKINS-41134), the junit plugin is awaiting release by someone...

Check the unit test reports directly :-)
https://ci.jenkins.io/job/Core/job/jenkins/job/windows-ci/lastCompletedBuild/testReport/

2017-02-13 13:04 UTC, daniel-beck commented
@jtnord Thanks, I thought that release has already happened :disappointed:

2017-02-13 14:41 UTC, slide commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                    + "ping 1.1.1.1 -n 1 -w 10000 >NUL\r\nver >NUL\r\necho after sleep - %BUILD_NUMBER%"));
I switched to timeout, but it doesn't work with jenkins because it tries to redirect stdin and throws an error.

2017-02-16 07:03 UTC, oleg-nenashev approved these changes
The current version looks good to me. @slide Is it ready to merge from your PoV?

2017-02-17 22:12 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers ?

2017-02-17 23:00 UTC, MarkEWaite requested changes
Minor change in the IP address of one of the sleep replacements, otherwise looks good to me

2017-02-17 23:00 UTC, MarkEWaite commented on test/src/test/java/hudson/cli/AbstractBuildRangeCommand2Test.java
> +        project.getBuildersList().add(Functions.isWindows() ? new BatchFile("echo 1\r\nping -n 10 127.0.01 >nul") : new Shell("echo 1\nsleep 10s"));
That doesn't look like an IP address to me.  Didn't you mean `127.0.0.1` instead of `127.0.01`?

2017-02-17 23:00 UTC, MarkEWaite commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                .invokeWithArgs("aProject", "1", "-n", Functions.isWindows() ? "5" : "4");
Why the difference between Windows and Linux on this test case?

2017-02-17 23:00 UTC, MarkEWaite commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                .invokeWithArgs("aProject", "1", "-f", "-n", Functions.isWindows() ? "5" : "4");
Why is Windows count different than Linux?

2017-02-17 23:00 UTC, MarkEWaite commented on test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java
> +    //TODO: determine if this should be pulled out into JenkinsRule or something
The XShell plugin provides something like this.  It takes a command line and attempts to map it to Windows or Linux as appropriate.

2017-02-17 23:00 UTC, MarkEWaite commented on test/src/test/java/hudson/model/ProjectTest.java
> +        p.getBuildersList().add(Functions.isWindows() ? new BatchFile(cmd) : new Shell(cmd));
This is an example that XShell handles, output redirection.

2017-02-23 13:15 UTC, slide commented on test/src/test/java/hudson/model/ProjectTest.java
> +        p.getBuildersList().add(Functions.isWindows() ? new BatchFile(cmd) : new Shell(cmd));
The command itself works fine on both batch and shell, so I agree, XShell might help, but it seems a little overkill to pull in that plugin for a few tests.

2017-02-23 13:16 UTC, slide commented on test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java
> +    //TODO: determine if this should be pulled out into JenkinsRule or something
It doesn't translate things between Batch and Shell, it says right on the wiki that it doesn't do that. It won't translate variable accesses or commands.

2017-02-23 13:16 UTC, slide commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                .invokeWithArgs("aProject", "1", "-f", "-n", Functions.isWindows() ? "5" : "4");
Batch scripts output things different than shell scripts.

2017-02-23 13:16 UTC, slide commented on test/src/test/java/hudson/cli/ConsoleCommandTest.java
> +                .invokeWithArgs("aProject", "1", "-n", Functions.isWindows() ? "5" : "4");
Because batch files output things differently than a shell script, so the information needed was in another line up.

2017-02-23 13:16 UTC, slide commented on test/src/test/java/hudson/cli/AbstractBuildRangeCommand2Test.java
> +        project.getBuildersList().add(Functions.isWindows() ? new BatchFile("echo 1\r\nping -n 10 127.0.01 >nul") : new Shell("echo 1\nsleep 10s"));
You're right, I fat fingered it. I pushed an update.

2017-02-23 16:00 UTC, slide commented
I think this is ready to be merged. Any other items I need to look at?

2017-02-23 16:21 UTC, daniel-beck commented
Seems fine. Anyone else?

I propose we change the target branch of the PR to master, wait for stable build (should be easy), then merge. Then, separate PR adding PR build for Windows on master, wait for stable build, then merge.

2017-02-23 16:52 UTC, slide commented
So, do you want me to push an update to remove "Windows" from Jenkinsfile, or am I misunderstanding what you want to do?

2017-02-24 00:15 UTC, daniel-beck commented
@slide 

Step 1: Change this PR to target master without changing contents (no Windows build, just fixes for Windows tests)
Step 2: Merge if stable
Step 3: New PR (by me so it's trusted) adding back the Windows build
Step 4: Merge if stable.

This will ensure master is always stable.

2017-02-25 18:25 UTC, oleg-nenashev approved these changes
LGTM

2017-02-25 18:27 UTC, oleg-nenashev commented
@daniel-beck @slide So I can integrate the changes via the temporary branch in jenkinsci. Are you fine with that?

2017-02-25 18:36 UTC, slide commented
I'm fine with that, except I think @danielbeck  doesn't want the change to Jenkinsfile initially

2017-02-25 19:21 UTC, daniel-beck commented
Waiting for PR build to master to pass now. Then merging, and opening a new PR to master to add Windows builds. If that passes as well, merging it, and we're done (except for all the open PRs that will never have been built on Windows, but one step at a time…).

2017-02-26 12:06 UTC, daniel-beck commented
Didn't expect my Windows CI build commit to be part of the PR as well, so trying to close this PR, open one of my own with the same source, to see whether Windows tests get executed there…

2017-02-26 12:06 UTC, closed without merging