Update HudsonAuthenticationEntryPoint.java
jenkinsci/jenkins pull request #2748
Opened 2017-02-13 11:38 UTC by tkisme

Login page is missing charset.

2017-02-13 11:49 UTC, daniel-beck commented
What's the issue this fixes?

2017-02-13 12:10 UTC, tkisme commented
see [this](https://issues.jenkins-ci.org/browse/JENKINS-41977)

2017-02-13 12:15 UTC, oleg-nenashev approved these changes
The fix looks reasonable to me. 👍

2017-02-13 14:24 UTC, daniel-beck requested changes
I have questions.

2017-02-13 14:24 UTC, daniel-beck commented on core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
>                  "<meta http-equiv='refresh' content='1;url=%1$s'/>" +
This does not seem to do what it claims to in the issue, as it sets the encoding for the HTTP redirect page, not the `/login` URL. Has this change been tested at all? What am I missing?

2017-02-13 14:35 UTC, tkisme commented on core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
>                  "<meta http-equiv='refresh' content='1;url=%1$s'/>" +
This error always come with https ,without https everything just fine,I will change all charset to see what happens.

2017-02-13 14:35 UTC, tkisme commented on core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
>                  "<meta http-equiv='refresh' content='1;url=%1$s'/>" +
This error always come with https without https everything just fine,I will change all charset to see what happens.

2017-02-13 14:37 UTC, tkisme commented on core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
>                  "<meta http-equiv='refresh' content='1;url=%1$s'/>" +
This error always come with https without https everything just fine,I will change all charset to see what happens.

2017-02-15 13:01 UTC, tkisme commented on core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
>                  "<meta http-equiv='refresh' content='1;url=%1$s'/>" +
now I found this error only occurs when define gzip compression.I close it.

2017-02-15 13:02 UTC, closed without merging

2017-02-15 13:06 UTC, tkisme commented on core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
>                  "<meta http-equiv='refresh' content='1;url=%1$s'/>" +
If someone came with same error,you can see here
https://github.com/containous/traefik/issues/1060