[FIXED JENKINS-42443] Make f:select display spinner during AJAX requests
jenkinsci/jenkins pull request #2771
Opened 2017-03-02 17:31 UTC by stephenc

See [JENKINS-42443](https://issues.jenkins-ci.org/browse/JENKINS-42443)

Based on https://github.com/jenkinsci/github-branch-source-plugin/pull/125

@reviewbybees

2017-03-02 17:33 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-03-02 20:57 UTC, daniel-beck reviewed
This looks like something that could profit from tests, and maybe a ui-samples addition.

2017-03-02 20:57 UTC, daniel-beck commented on core/src/main/java/hudson/util/FormFillFailure.java
> + * Copyright (c) 2004-2009, Sun Microsystems, Inc.
?

2017-03-02 20:57 UTC, daniel-beck commented on core/src/main/resources/lib/form/select/select.js
> +        if (header && "clear".toUpperCase() === header.toUpperCase()) {
i18n issues possible?

2017-03-02 20:57 UTC, daniel-beck commented on core/src/main/resources/lib/form/select/select.js
> +        var header = rsp.getResponseHeader('X-Jenkins-Select-Error');
Is this HTTP2 compatible?

2017-03-02 20:57 UTC, daniel-beck commented on core/src/main/java/hudson/util/FormFillFailure.java
> + * Represents the result of the form field fill failure.
To clarify, `FormFillFailure` is to `doFillWhatever` as `FormValidation` is to `doCheckWhatever`? This didn't exist before?

2017-03-02 21:28 UTC, stephenc commented on core/src/main/resources/lib/form/select/select.js
> +        var header = rsp.getResponseHeader('X-Jenkins-Select-Error');
XMLHttpRequest.getResponseHeader() is supposed to be case insensitive

2017-03-02 21:30 UTC, stephenc commented on core/src/main/resources/lib/form/select/select.js
> +        if (header && "clear".toUpperCase() === header.toUpperCase()) {
[toLocale___Case](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase) is the variants that would have i18n issues.

But looking at this again, I can remove one call by just changing the header value to lowercase

2017-03-02 23:25 UTC, jglick requested changes
I think you forgot to add `select-ajax-pending` to CSS.

I would encourage you to actually prototype rewriting https://github.com/jenkinsci/github-branch-source-plugin/pull/125 using a snapshot baseline to verify that this works.

2017-03-02 23:25 UTC, jglick commented on core/src/main/java/hudson/util/FormFillFailure.java
> +     * to everyone or just those who have higher access to job/hudson/etc.
Is this copied-and-pasted by any chance?

2017-03-02 23:25 UTC, jglick commented on core/src/main/java/hudson/util/FormFillFailure.java
> +        if (e==null)    return _errorWithMarkup(Util.escape(message),kind);
Clearly it is…

2017-03-02 23:25 UTC, jglick commented on core/src/main/java/hudson/util/FormFillFailure.java
> +                        req.getContextPath()+ Jenkins.RESOURCE_PATH+"/images/none.gif' height=16 width=1>"+
Share code with `FormValidation` please.

2017-03-02 23:25 UTC, jglick commented on core/src/main/java/hudson/util/FormFillFailure.java
> +    public FormFillFailure withSelectionCleared() {
missing Javadoc

2017-03-02 23:26 UTC, jglick commented
`spinner.gif` seems to be missing too.

2017-03-03 00:02 UTC, stephenc commented
> spinner.gif seems to be missing too. 

Nope it is present already (which is why the css was added to the main css and not an adjunct)

2017-03-03 10:29 UTC, stephenc commented
@jenkinsci/code-reviewers

2017-03-03 14:33 UTC, oleg-nenashev reviewed
The error retrieval code dies not seem to be related to the PR title. Maybe you want to create a separate issue for Fill error handling.

I am also not sure we want to follow the single-message design. We already had this issue with `FormValidation`, where we had to rework the implementation to support multiple validation messages.

I think the best approach would be to reuse the existing FormValidation approach and maybe classes.

2017-03-03 14:33 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/FormFillFailure.java
> + * @since FIXME
Please use `@since TODO` for the consistency. Otherwise awe may miss it during the bulkupdate

2017-03-03 14:33 UTC, oleg-nenashev commented on core/src/main/resources/lib/form/select/select.js
> +        var header = rsp.getResponseHeader('X-Jenkins-Select-Error');
I'm fine with that. Once we start following HTTP2 rules, we will need to either make Stapler to do it for us OR to perform a bulk update in the core and plugins. I prefer the first option

2017-03-03 20:45 UTC, jglick approved these changes

2017-03-03 20:46 UTC, jglick commented on core/src/main/resources/lib/form/select/select.js
> +        var header = rsp.getResponseHeader('X-Jenkins-Select-Error');
I am probably being dumb here but what is the issue exactly?

2017-03-09 14:43 UTC, stephenc commented
No objections in 6 days... merging

2017-03-09 14:43 UTC, merged