Jenkins 42627
jenkinsci/jenkins pull request #2787
Opened 2017-03-09 15:44 UTC by TristanFAURE

a suggestion to have jenkins CLI in french, 
i think the translation is relevant but it can obviously be discussed with other french native people (maybe french developer would also prefer to keep english messages ?)

2017-03-09 21:30 UTC, batmat requested changes
apostrophes missing

2017-03-09 21:30 UTC, batmat commented on cli/src/main/resources/hudson/cli/client/Messages_fr.properties
> +   -i KEY       : fichier de la cl� priv�e SSH � utiliser pour l authentification\n\
missing _apostrophe_

2017-03-09 21:30 UTC, batmat commented on cli/src/main/resources/hudson/cli/client/Messages_fr.properties
> +   -noKeyAuth   : ne charge pas la cl� priv�e d authentification SSH. En conflit avec -i\n\
missing _apostrophe_

2017-03-09 21:30 UTC, batmat commented on cli/src/main/resources/hudson/cli/client/Messages_fr.properties
> +CLI.NoSuchFileExists=Ce fichier n existe pas: {0}
apostrophe

2017-03-09 21:42 UTC, TristanFAURE commented
I first inserted apostrophe but at execution they were dropped. For instance the result was : 
LURL instead of L'URL that's why I dropped them.

2017-03-10 08:49 UTC, batmat commented
@TristanFAURE as it is `.properties` you have to double the single quotes (apostrophe) to escape them.

2017-03-10 08:55 UTC, TristanFAURE commented
Ok I will change that

2017-03-19 20:32 UTC, batmat commented on cli/src/main/resources/hudson/cli/client/Messages_fr.properties
> +CLI.NoSuchFileExists=Ce fichier n''existe pas: {0}
NIT: en français, ya une espace avant deux points (:), mais je ne vais pas/plus bloquer juste pour ça.

Thanks!

2017-03-19 20:33 UTC, merged