[FIXED JENKINS-35160] Wait up to 15 seconds for interrupted builds to complete
jenkinsci/jenkins pull request #2789
Opened 2017-03-09 17:21 UTC by stephenc

- Also now aware of concurrent builds

See [JENKINS-35160](https://issues.jenkins-ci.org/browse/JENKINS-35160)

@reviewbybees

2017-03-09 17:24 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-03-09 17:45 UTC, stephenc commented on core/src/main/java/hudson/model/Job.java
> -    protected void performDelete() throws IOException, InterruptedException {
need to not hold the lock while interrupting or the interrupted threads may be unable to complete

2017-03-09 17:46 UTC, oleg-nenashev requested changes
🐛 for the concurrency flaws. Ideally the job should be marked for deletion (e.g. boolean flag), and after setting this flag the job should prevent any attempts to schedule it to the queue. And maybe the flag should be released if the deletion fails (or not?).

Another 🐛  for using `isAlive()` for the executor

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +            Queue.getInstance().cancel((Queue.Task) this);
It won't work for the Promoted Builds and other such... exotic implementations

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +                        building.put(e.getCurrentExecutable(), e);
Lacks logging

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +                        e.interrupt();
Lacks logging

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +                    throw new AbortException(Messages.Job_FailureToStopBuilds(building.size(), getFullDisplayName()));
Should it also go to the system log?

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +                        if (!entry.getValue().isAlive() || entry.getKey() != entry.getValue().getCurrentExecutable()) {
It should be `isActive()`. E.g. if the executor is starting up/shutting down, we should not ignore the task check 🐛

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +            if (!building.isEmpty()) {
🐛 this method uses cached list of builds. If the new build gets started due to whatever reason, during the deletion cycle, these builds won't be noticed.

2017-03-09 17:46 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Job.java
> +                if (!building.isEmpty()) {
Risk of false negatives since this is a value from the past

2017-03-09 18:01 UTC, jglick submitted a review, later dismissed

2017-03-09 18:01 UTC, jglick commented on core/src/main/java/hudson/model/Job.java
> +                        e.interrupt(Result.ABORTED);
Better to factor into a helper method. Better yet, introduce `Computer.getAllExecutors()`, since that is a common problem. (See `Executor.of` etc.)

2017-03-09 18:01 UTC, jglick commented on core/src/main/java/hudson/model/Job.java
> +                        building.put(e, e.getCurrentExecutable());
Maybe easier to just check for

```
Queue.Executable exec = e.getCurrentExecutable();
if (exec instanceof Run && ((Run) exec).getParent() == this) {
```

2017-03-09 18:01 UTC, jglick commented on core/src/main/java/hudson/model/Job.java
> +                        if (!entry.getKey().isAlive() || entry.getValue() != entry.getKey().getCurrentExecutable()) {
And then we could use simply `Run.isLogUpdated()`.

2017-03-09 18:01 UTC, jglick commented on core/src/main/java/hudson/model/Job.java
> +            Queue.getInstance().cancel((Queue.Task) this);
Better consider that architecturally deprecated.

2017-03-09 18:02 UTC, jglick commented on core/src/main/java/hudson/model/Job.java
> +                    throw new AbortException(Messages.Job_FailureToStopBuilds(building.size(), getFullDisplayName()));
I do not see why. The user has gotten a failure message (I hope—test it?); the job has not been deleted; there is nothing for the admin to do.

2017-03-10 15:15 UTC, stephenc commented
@oleg-nenashev if the executor is interrupted the thread will die: https://github.com/jenkinsci/jenkins/commit/111a8d364c4a7a1afb8c8a88a7ab6809bb2a19dc#diff-4da8c72b731d029f61f01ed41568d209R248 so the only way to know that the executor has completed is to observe  `isAlive()`

Other issues addressed

2017-03-14 00:56 UTC, oleg-nenashev commented
@stephenc maybe it also addresses https://issues.jenkins-ci.org/browse/JENKINS-32783

2017-03-15 11:08 UTC, oleg-nenashev submitted a review, later dismissed
I have a minor :ant: regarding the missing Interruption cause, but the most of the code looks good to me. IMHO some testing like ATH and PCT would not hurt in such case due to the fix complexity and potential risk of severe regressions.

Also dismissing the review from @jglick since the code has changed significantly

2017-03-15 11:08 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +            throw new Failure(Messages.AbstractItem_BeingDeleted(getPronoun()));
Maybe it worth putting this warning into UI as well (e.g. in the summary page near the "disabled" status)

2017-03-15 11:08 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +                // interrupt any builds in progress (and this should be a recursive test so that folders do not pay
Maybe they should, but not sure. It makes FolderDelition a separate long background task. Which is probably fine, but out of the scope of this PR imho

2017-03-15 11:08 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +                                        e.interrupt(Result.ABORTED);
🐛  No `CauseOfInterruption`, which would be really useful in this code. The default behavior will be an emty cause in such case: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Executor.java#L190

2017-03-15 11:08 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +                            entry.getKey().interrupt(Result.ABORTED);
Same, missing cause

2017-03-15 16:35 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +                                        e.interrupt(Result.ABORTED);
1. The job is going to be deleted
2. As the this is the user who will be triggering the interrupt the `UserInterruption` cause will be injected

2017-03-15 16:36 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +                            entry.getKey().interrupt(Result.ABORTED);
Nope: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Executor.java#L183-L196

2017-03-15 16:37 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +                // interrupt any builds in progress (and this should be a recursive test so that folders do not pay
We are recursively interrupting all jobs in one go here, any deletion will be at most 15 seconds

2017-03-15 16:37 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +            throw new Failure(Messages.AbstractItem_BeingDeleted(getPronoun()));
For all of 15 seconds!!!

2017-03-15 16:38 UTC, stephenc commented
@oleg-nenashev I argue that your bug was incorrect, the interruption is a user triggered action and will have a cause reflecting that

2017-03-15 16:40 UTC, stephenc commented on core/src/main/java/hudson/model/Executor.java
> +            for (Executor executor : computer.getAllExecutors()) {
I think you are arguing for more complex code on the grounds of performance in the absence of a proven performance degradation. That smells like premature optimization

2017-03-15 16:55 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +            throw new Failure(Messages.AbstractItem_BeingDeleted(getPronoun()));
okay

2017-03-15 16:55 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +            throw new Failure(Messages.AbstractItem_BeingDeleted(getPronoun()));
Still may be a case if the timeout gets configurable

2017-03-15 17:14 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +            throw new Failure(Messages.AbstractItem_BeingDeleted(getPronoun()));
Then whoever adds that feature can add the UI indicator. Solved

2017-03-15 17:16 UTC, stephenc commented on core/src/main/java/hudson/model/Executor.java
> +            for (Executor executor : computer.getAllExecutors()) {
if you have lots of one-off executors then the majority of cases will be checking the one-off executors, so we save two ArrayList and two Iterator allocations, plus escape analysis can reveal that the one list is only ever used for iteration and the method can be inlined as it is small... the JVM is smarter than you think. (maybe not that smart, but there is hope!)

2017-03-22 21:34 UTC, stephenc commented
@oleg-nenashev @jglick ping also @jenkinsci/code-reviewers

2017-03-23 08:17 UTC, oleg-nenashev commented
@stephenc removed the bug according to explanation

2017-03-29 09:48 UTC, oleg-nenashev commented
@reviewbybees any feedback?

2017-03-29 13:06 UTC, stephenc commented
@oleg-nenashev per policy, 7 days so @reviewbybees done

2017-03-30 11:19 UTC, stephenc commented on core/src/main/java/hudson/model/Computer.java
> +        return result;
Why do you want to add another layer of indirection, plus we have given you a copy so you can do what you want with it

2017-03-30 11:20 UTC, stephenc commented on core/src/main/java/jenkins/model/queue/ItemDeletion.java
> +@Extension
No because plugins may need access to perform additional checks and prevent work on items that are registered

2017-03-30 16:49 UTC, daniel-beck commented on core/src/main/java/hudson/model/Computer.java
> +        return result;
Because that's how I interpret the "read-only" part of the Javadoc.

2017-04-01 20:42 UTC, oleg-nenashev commented on core/src/main/java/jenkins/model/queue/ItemDeletion.java
> +@Extension
Will be likely non-backportable then

2017-04-01 20:46 UTC, oleg-nenashev approved these changes
I agree with the fix since it definitely does not make the behavior worse than it was before. I am concerned about adding another non-configurable magic number for timeout, but I accept delaying it.

I will be likely against backporting the fix into .2 due to the potential impact of the changes. Also non-Restricted API

2017-04-10 11:05 UTC, rsandell commented on core/src/main/java/hudson/model/Computer.java
> +        return result;
Yea, `read-only` should be removed from the javadoc, `snapshot view` should be enough, since it actually isn't read-only :)

2017-04-10 11:14 UTC, rsandell commented on core/src/main/java/jenkins/model/queue/ItemDeletion.java
> +@Extension
It could be backported, but restricted in the backport

2017-04-10 11:17 UTC, oleg-nenashev commented
On hold for now since we are waiting for the 2.54 release. Will merge afterwards

2017-04-10 11:18 UTC, rsandell commented on test/src/test/java/hudson/model/JobTest.java
> +        assertThat(end - start, Matchers.lessThan(TimeUnit.SECONDS.toNanos(1)));
Might result in flaky builds on slower build agents.

2017-04-10 14:03 UTC, rsandell commented
:bee:

2017-04-10 14:05 UTC, oleg-nenashev commented
@reviewbybees done
No merge right now pls

2017-04-11 10:42 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers we would appreciate some additional feedback. It **may** potentially break some use-cases with deletion of projects with pending builds, though these use-cases were not working reliably anyway. If you are fine, my plan is to merge it towards the next weekly on Friday.

2017-04-13 22:35 UTC, jglick approved these changes
Did not follow all of the code here but overall looks right.

2017-04-13 22:35 UTC, jglick commented on core/src/main/java/hudson/model/Computer.java
> +        return result;
Would prefer to just use `unmodifiableList`.

2017-04-13 22:35 UTC, jglick commented on core/src/main/java/hudson/model/queue/Tasks.java
> +        // TODO move to default method on SubTask once code level is Java 8
Can do that now.

2017-04-13 22:35 UTC, jglick commented on core/src/main/java/jenkins/model/queue/ItemDeletion.java
> +@Extension
Should be `@Restricted` unless there is a tested & documented use case for accessing it from a plugin (which I doubt—a real API would be designed differently).

2017-04-13 22:35 UTC, jglick commented on core/src/main/java/jenkins/model/queue/ItemDeletion.java
> +                lock.readLock().unlock();
Pity that `Lock` is not `AutoCloseable`.

2017-04-14 07:33 UTC, merged

2017-04-22 12:29 UTC, daniel-beck commented
> Should be `@Restricted` unless there is a tested & documented use case for accessing it from a plugin (which I doubt—a real API would be designed differently).

:frowning_face:

2017-04-22 13:14 UTC, oleg-nenashev commented
@jglick @daniel-beck 

> Should be @Restricted unless there is a tested & documented use case for accessing it from a plugin (which I doubt—a real API would be designed differently).

Makes sense to Restrict in a follow-up PR.

2017-10-10 19:00 UTC, jglick commented on core/src/main/java/hudson/model/AbstractItem.java
> +            synchronized (this) { // could just make performDelete synchronized but overriders might not honor that
Unusable API; see https://github.com/jenkinsci/cloudbees-folder-plugin/pull/112.