Fixed incorrect string concatenation
jenkinsci/jenkins pull request #2800
Opened 2017-03-12 12:54 UTC by epidemia

2017-03-12 14:18 UTC, oleg-nenashev approved these changes
All changes look good to me though the original approach is not incorrect. It is "just" ineffective

2017-03-12 17:45 UTC, daniel-beck commented on test/src/test/java/hudson/ProcTest.java
> +            stringBuilder.append("oxox");
Is the Java compiler really not smart enough to optimize this away?

2017-03-12 18:03 UTC, oleg-nenashev commented on test/src/test/java/hudson/ProcTest.java
> +            stringBuilder.append("oxox");
JVM may be smart enough, but at least OpenJDK does not optimize it IIRC

2017-03-17 08:43 UTC, oleg-nenashev commented
Retriggering the PR builder

2017-03-17 13:08 UTC, oleg-nenashev requested changes
1 errorneous change in the tests

2017-03-17 13:08 UTC, oleg-nenashev commented on test/src/test/java/hudson/ProcTest.java
> +            assertEquals(stringBuilder, baos.toString().trim());
It causes a test failure:

<img width="1013" alt="screen shot 2017-03-17 at 14 07 31" src="https://cloud.githubusercontent.com/assets/3000480/24044338/279694ee-0b1b-11e7-8d65-e08f77d91b29.png">

2017-04-15 19:48 UTC, oleg-nenashev commented
@epidemia gentle ping

2017-04-26 06:56 UTC, mc1arke commented on test/src/test/java/hudson/ProcTest.java
> +            assertEquals(stringBuilder, baos.toString().trim());
Failure is caused by comparing a String to a StringBuilder. Need to call `toString()` on the String builder to make this pass.

2017-08-29 11:58 UTC, closed without merging