Updating view with CLI using input of a different view type should fail
jenkinsci/jenkins pull request #2804
Opened 2017-03-13 21:12 UTC by scoheb

[FIXES JENKINS-42728]

# Description

See [JENKINS-42728](https://issues.jenkins-ci.org/browse/JENKINS-42728).

2017-03-14 11:15 UTC, scoheb commented
@jenkinsci/code-reviewers

2017-03-14 11:54 UTC, olivergondza commented on core/src/main/java/hudson/model/View.java
> +            if (o!=this) {
Not `!o.getClass().equals(getClass())`?

2017-03-14 12:02 UTC, scoheb commented on core/src/main/java/hudson/model/View.java
> +            if (o!=this) {
I was basing myself on the "tried, tested and true":

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/AbstractItem.java#L673

2017-03-14 18:03 UTC, oleg-nenashev requested changes
I would rather prefer to have explicit class type checks, because I do not understand how the  current implementation may work reliably

2017-03-14 18:03 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/View.java
> +            if (o!=this) {
+1 to @olivergondza 's proposal. Though I am not sure if it is going to be safe for the data migration logic like [class renaming](https://wiki.jenkins-ci.org/display/JENKINS/Hint+on+retaining+backward+compatibility). Maybe it worth doing some direct tests for this use-case.

`o != this` seems to be pretty nangerous

2017-04-06 21:33 UTC, scoheb commented
@oleg-nenashev  @olivergondza 

I was not sure where to put 

> TestView.java

Let me know if you think we need more tests.

2017-04-11 08:26 UTC, olivergondza requested changes

2017-04-11 08:26 UTC, olivergondza commented on test/src/test/java/hudson/cli/UpdateViewCommandTest.java
> +        assertThat(result, failedWith(0));
`succeeded()` or `succeededSilently()`.

2017-04-13 13:52 UTC, oleg-nenashev commented
Will try to take another look ASAP

2017-04-15 18:43 UTC, oleg-nenashev approved these changes
Looks good to me

2017-04-15 18:43 UTC, oleg-nenashev commented on test/src/test/java/hudson/cli/UpdateViewCommandTest.java
> +     * @throws Exception
Better to have a description defined. Otherwise Javadoc engine may grumble about that

2017-04-15 18:43 UTC, oleg-nenashev commented
@olivergondza WDYT?

2017-04-25 08:11 UTC, olivergondza commented on test/src/test/java/hudson/cli/UpdateViewCommandTest.java
> +     * @throws Exception
Or avoid javadoc (`/*`) for tests, it is not generated anyway. `@throws Exception` on tests is quite pointless.

2017-04-25 08:17 UTC, olivergondza approved these changes

2017-04-25 08:43 UTC, oleg-nenashev commented
Ready to merge. Just to be safe, let's re-run CI after the security release on Wednesday before merging

2017-05-04 15:21 UTC, merged