Cache Parser configurers when running on a slave
jenkinsci/jenkins pull request #2806
Opened 2017-03-15 18:19 UTC by jerrinot

# Description
This changeset caches Parser Configurer(s) when running on a slave.

Details:
applyConfiguration() invokes RPC when running on slave.
-> parsing 1000s XML files results in 1000s of RPCs.

### Changelog entries

Proposed changelog entries:

* Slaves cache returned cache configurers

2017-03-15 18:20 UTC, jerrinot commented
There is no JIRA issue because I don't have an account yet. I created the account today but I have not received a password yet.

2017-03-15 18:21 UTC, jerrinot commented
I am not sure if eternal caching is desired. I will be happy to introduce some TTL is needed. 

I believe the Parser Configurers abstraction used for TestNG tests only.

2017-03-15 22:57 UTC, kuisathaverat commented
this PR could resolve https://issues.jenkins-ci.org/browse/JENKINS-10234

2017-03-16 12:29 UTC, daniel-beck commented
@kuisathaverat Seems unrelated, the problem there is more likely a too permissive ant pattern/too large workspace. Notably `applyConfiguration` isn't in the thread dump. Why do you think this is related?

2017-03-16 14:01 UTC, jerrinot commented
@daniel-beck: I agree the JENKINS-10175 looks somewhat differently. This is the stacktrace I am observing during the lengthy result processing:
```
"pool-1-thread-40 for CLI connection to https://hazelcast-l337.ci.cloudbees.com / waiting for hudson.remoting.Channel@6dc17b83:CLI connection to https://hazelcast-l337.ci.cloudbees.com" #182 prio=5 os_prio=0 tid=0x00007f82a8010000 nid=0x9dd05 in Object.wait() [0x00007f8362200000] 
java.lang.Thread.State: TIMED_WAITING (on object monitor) 
at java.lang.Object.wait(Native Method) 
at hudson.remoting.Request.call(Request.java:147) 
- locked <0x00000005963e5128> (a hudson.remoting.UserRequest) 
at hudson.remoting.Channel.call(Channel.java:780) 
at hudson.util.io.ParserConfigurator.applyConfiguration(ParserConfigurator.java:81) 
at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:124) 
at hudson.tasks.junit.TestResult.parse(TestResult.java:301) 
at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:244) 
at hudson.tasks.junit.TestResult.parse(TestResult.java:175) 
at hudson.tasks.junit.TestResult.parse(TestResult.java:154) 
at hudson.tasks.junit.TestResult.<init>(TestResult.java:126) 
at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132) 
at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107) 
at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731) 
at hudson.remoting.UserRequest.perform(UserRequest.java:120) 
at hudson.remoting.UserRequest.perform(UserRequest.java:48) 
at hudson.remoting.Request$2.run(Request.java:332) 
at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
```

2017-03-16 17:17 UTC, oleg-nenashev reviewed
I would like to discuss the plugin Dynamic loading case before we go forward with such approach.

P.S: This also an example of a serializable extension point, which would generally prefer to avoid. Not related to this change

2017-03-16 17:17 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/io/ParserConfigurator.java
>              all = all();
brackets for else would be also useful

2017-03-16 17:17 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/io/ParserConfigurator.java
> +            return cache;
Such approach won't work reliably, e,g, if a new plugin with `ParserConfigurator` gets dynamically loaded. Without cache invalidation logic in may become error-prone

2017-03-16 17:56 UTC, jerrinot commented on core/src/main/java/hudson/util/io/ParserConfigurator.java
> +            return cache;
what would you recommend to do? can slave subscribe to receive informations about plugins loaded on a master? or is a simple time-to-live enough?

2017-03-16 18:00 UTC, jglick requested changes
I would suggest deprecating this whole extension point as misconceived from the start, and make the `junit` plugin apply `XMLEntityResolver` on its own rather than registering it globally—it is pointless for anyone else doing parsing.

2017-03-16 18:00 UTC, jglick commented on core/src/main/java/hudson/util/io/ParserConfigurator.java
> +    private static volatile Collection<ParserConfigurator> cache;
`@Extension`s should generally not be cached in a `static` field, lest the wrong objects carry over from one `Jenkins` session to the next. If I understand correctly, this field is only used when this class is loaded in an agent JVM, which would be specific to one session, so it is not a problem.

2017-03-16 18:00 UTC, jglick commented on core/src/main/java/hudson/util/io/ParserConfigurator.java
> +            return cache;
You can use `ExtensionListListener` on the master side, but then how would you notify the agent to expire its cache? Could become quite tricky.

2017-03-16 18:02 UTC, jglick commented
The reported stack traces in JENKINS-10175 are unrelated to this optimization.

2017-03-16 18:38 UTC, jerrinot commented
@oleg-nenashev, @jglick: thanks a lot for review. What something like [this](https://github.com/jenkinsci/junit-plugin/pull/65/) work better for you?

2017-03-16 18:43 UTC, jerrinot commented on core/src/main/java/hudson/util/io/ParserConfigurator.java
> +            return cache;
@jglick: I don't really know Jenkins codebase so I thought there could be a subscribe mechanism. 

If there is no such thing then I guess proper invalidation is difficult. So I can either use a static TTL or completely [avoid using the extension mechanism](https://github.com/jenkinsci/junit-plugin/pull/65)

2017-03-16 19:36 UTC, kuisathaverat commented
@daniel-beck I have supposed that the next step of ParserConfigurator should be the parsing process and depends on of when you take the thread dump you could find the stack trace that @jerrinot has posted, also the behavior it is pretty similar.

2017-03-17 13:52 UTC, kuisathaverat commented
@jglick @oleg-nenashev on this https://github.com/jenkinsci/junit-plugin/pull/65/files makes the change to XMLEntityResolver for the JUnit Plugin, it is for sure better than a change on code

2019-01-17 16:00 UTC, batmat commented
Closing, as per my last comment.

@jerrinot please feel free to comment here anytime once/if you feel like getting back to this, and thanks again for the work. We're all happy to reopen anytime it's needed. 

Thanks!

2019-01-17 16:00 UTC, closed without merging

2019-01-17 16:07 UTC, jerrinot commented
@batmat: this PR was actually superseded by https://github.com/jenkinsci/junit-plugin/pull/65/, I just forgot to close it. sorry, for that!

2019-01-17 16:19 UTC, batmat commented
No worries, thanks again for your involvement!