[JENKINS-42861] - Properly deprecate the HudsonExceptionNote implementation
jenkinsci/jenkins pull request #2811
Opened 2017-03-19 10:30 UTC by oleg-nenashev

It is a replacement of the original fix in https://github.com/jenkinsci/jenkins/pull/2808 by @daniel-beck, which I've unintentionally derailed.

The implementation provides deprecates the annotation of the new stacktraces, but it retains the binary and the persisted data compatibility, which were missing in the original PR.
In the longer-term the hyperlinks should be replaced by the best possible equivalent (JIRA search, grepcode or whatever).

See [JENKINS-42861](https://issues.jenkins-ci.org/browse/JENKINS-42861).

### Changelog entries

Proposed changelog entries:

* Entry 1: JENKINS-42861, Remove links in stack traces to the `stacktrace.jenkins-ci.org` service that has been shut down.
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@daniel-beck

2017-03-19 18:53 UTC, daniel-beck commented on core/src/main/java/hudson/console/HudsonExceptionNote.java
> +@Deprecated
`@Restricted(DoNotUse.class)`?

2017-03-19 18:53 UTC, daniel-beck commented on core/src/main/java/hudson/console/HudsonExceptionNote.java
> +                /*
Should just be deleted, we have Git history.

2017-03-19 18:54 UTC, daniel-beck reviewed
Seems overly careful to me, given no known consumers, but okay,

2017-03-19 21:47 UTC, oleg-nenashev commented on core/src/main/java/hudson/console/HudsonExceptionNote.java
> +@Deprecated
Yep

2017-03-19 21:48 UTC, oleg-nenashev commented
> Seems overly careful to me, given no known consumers, but okay,

Do not forget that Console Annotations may be persisted to the disk in some cases. Not sure about this one, but better safe than sorry

2017-03-20 00:02 UTC, daniel-beck approved these changes

2017-03-23 08:13 UTC, oleg-nenashev commented
@reviewbybees?

2017-03-23 09:17 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-03-23 20:48 UTC, jglick requested changes
AFAICT `annotateClassName` and `annotateMethodName` should both be deleted, and the whole `annotate` method should just `return null`.

I guess you want `StreamTaskListener` to still call it for the benefit of retroactively hyperlinking existing build logs if we ever get around to providing an implementation—though I feel this feature has always been pretty useless and would better be done by a `ConsoleLogFilter` in a plugin if someone wants to resurrect it.

2017-03-23 20:48 UTC, jglick commented on core/src/main/java/hudson/console/ConsoleAnnotator.java
> +     *      The callee should put markup into this object. Never {@code null}.
or just omit this clause—documented better by annotation

2017-03-23 20:48 UTC, jglick commented on core/src/main/java/hudson/console/HudsonExceptionNote.java
> +                /*
Seconded.

2017-03-23 20:48 UTC, jglick commented on core/src/main/java/hudson/console/HudsonExceptionNote.java
>          text.addHyperlinkLowKey(charPos,end,annotateClassName(line.substring(charPos,end)));
Why are you leaving this there? That will still link to the dead service.

2017-04-15 19:59 UTC, oleg-nenashev commented
@jglick @daniel-beck Cleaned up the implementation

2017-04-17 13:47 UTC, oleg-nenashev commented
@reviewbybees

2017-04-18 22:40 UTC, jglick approved these changes

2017-04-20 08:29 UTC, stephenc approved these changes
Though the `@Restricted` would be the 🍒 on top

2017-04-21 14:07 UTC, oleg-nenashev commented
Will add Restricted later is a bulk mode for Deprecated classes, which are not supposed to be used (we have plenty of them)

2017-04-21 14:07 UTC, oleg-nenashev commented
@reviewbybees  done

2017-04-22 12:28 UTC, daniel-beck approved these changes

2017-04-22 13:06 UTC, merged