[FIXED JENKINS-38005] Properly log failure due to empty archive in Pipeline
jenkinsci/jenkins pull request #2823
Opened 2017-03-28 22:17 UTC by abayer

# Description

See [JENKINS-38005](https://issues.jenkins-ci.org/browse/JENKINS-38005).

Details: Since the job result is probably still null at the time that archiving
occurs, we weren't actually logging anything in Pipeline jobs in that
case. That was not ideal. So instead, let's log things, and also let's
update the error message to include a tip to use the allowEmptyArchive
option.

Note that there is no test for this added - I couldn't figure out a way to reproduce the Pipeline use case here, i.e., a still-null `result` when we get to `ArtifactArchiver`.

### Changelog entries

Proposed changelog entries:

* Entry 1: Properly log failure due to empty archive in Pipeline

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees

2017-03-28 22:21 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-03-28 22:45 UTC, daniel-beck requested changes

2017-03-28 22:45 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
This will be shown in Freestyle jobs, where the new message makes no sense.

2017-03-28 22:46 UTC, daniel-beck commented
> I couldn't figure out a way to reproduce the Pipeline use case here, i.e., a still-null `result` when we get to `ArtifactArchiver`.

Does it not work with no build steps before this?

2017-03-28 22:54 UTC, abayer commented
@daniel-beck Aaaaaaah - why did I not think of that? Checking - thanks.

2017-03-28 22:55 UTC, abayer commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
Hrm. Good point. Maybe use a different error message depending on whether we're being called in an `AbstractBuild` or not?

2017-03-28 23:10 UTC, abayer commented
@daniel-beck No, wait, still won't work - `result` is getting set before we ever get to post-build actions.

2017-03-29 21:44 UTC, jglick approved these changes
Not easily tested without a Pipeline dep. Could write a test in a downstream plugin repository I suppose.

2017-03-29 21:44 UTC, jglick commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
Why does this not make sense in freestyle builds? Even if the problem is not the consequence of an earlier failure, you might simply have wanted to allow zero artifacts in some cases.

2017-03-30 11:07 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
@jglick I mean the specific label used. It's not called `allowEmptyArchive` on the UI.

2017-04-01 19:22 UTC, sanjaydhawangale commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
exactly #2602

2017-04-01 19:49 UTC, oleg-nenashev commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
@sanjaydhawangale WDYM?

2017-04-03 12:01 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
@oleg-nenashev Just look at the profile. Random spam.

2017-04-07 08:57 UTC, oleg-nenashev requested changes
Looks good to me, it will also help other plugins like AnyBuildStep plugin. Hence 🐝 

But the merge conflict needs to be solved

2017-04-25 19:45 UTC, oleg-nenashev approved these changes
:bee:

2017-04-26 13:22 UTC, daniel-beck requested changes
Change to localized message still doesn't make sense.

2017-04-26 13:38 UTC, abayer commented on core/src/main/resources/hudson/tasks/Messages.properties
> +ArtifactArchiver.NoMatchFound=No artifacts found that match the file pattern "{0}". Did you mean to use the "allowEmptyArchive" option?
@daniel-beck Do you have suggestions for alternatives?

2017-04-28 17:03 UTC, abayer commented
@daniel-beck What would you recommend?

2017-05-04 14:01 UTC, daniel-beck commented
@abayer Not changing it. The existing message is sufficient, and independent of *how* the step is used.

2017-05-04 15:40 UTC, abayer commented
@daniel-beck Gotcha - will do.

2017-05-04 15:48 UTC, jglick approved these changes

2017-05-04 15:51 UTC, oleg-nenashev approved these changes
:bee: and @reviewbybees done

2017-05-04 15:57 UTC, daniel-beck approved these changes
Should probably be squashed given how trivial this ended up being.

2017-05-04 22:19 UTC, oleg-nenashev commented
Will merge it tomorrow if nobody votes again.
P.S: I am a professional squash-merger anyway

2017-05-05 15:36 UTC, merged

2017-05-05 20:17 UTC, jglick commented
BTW in [JENKINS-31931](https://issues.jenkins-ci.org/browse/JENKINS-31931) I suggested this fix, plus some additional cleanup.