Created weblogic.xml
jenkinsci/jenkins pull request #2839
Opened 2017-04-11 16:08 UTC by ajshastri

This is to enable jenkins to work with weblogic.

# Description

Details: Added weblogic.xml with context jenkins for application weblogic support

### Changelog entries

Proposed changelog entries:

* Entry 1: Added weblogic.xml with context jenkins for application weblogic support

2017-04-14 07:35 UTC, oleg-nenashev commented on war/src/main/webapp/WEB-INF/weblogic.xml
> +     <wls:weblogic-version>12.1.3</wls:weblogic-version>
Should this version be hardcoded?

2017-04-19 01:28 UTC, ajshastri commented on war/src/main/webapp/WEB-INF/weblogic.xml
> +     <wls:weblogic-version>12.1.3</wls:weblogic-version>
Unfortunately yes. There is no harm from what I have experienced with it being a different version.

2017-04-20 20:29 UTC, goughy000 commented on war/src/main/webapp/WEB-INF/weblogic.xml
> +     <wls:weblogic-version>12.1.3</wls:weblogic-version>
According to [this page](https://docs.oracle.com/cd/E24329_01/web.1211/e21049/weblogic_xml.htm#WBAPP574)

> The weblogic-version element indicates the version of WebLogic Server on which this Web application (as defined in the root element weblogic-web-app) is intended to be deployed. This element is informational only and is not used by WebLogic Server.

Is this entire element actually required?

2017-04-27 11:49 UTC, oleg-nenashev requested changes
Needs fix according to the comment from 
@goughy000

2018-03-04 01:16 UTC, oleg-nenashev commented
@ajshastri any plans to address comments? If no, I propose to close the PR

2018-03-07 14:23 UTC, closed without merging