[FIXED JENKINS-34226] No pressed style for OK button on Create Item.
jenkinsci/jenkins pull request #2844
Opened 2017-04-14 19:55 UTC by Andrei94

# Description

See [JENKINS-34226](https://issues.jenkins-ci.org/browse/JENKINS-34226).

The button was using a different style from the one that was used for example in save/apply for in the job config section. I changed it so that it uses the same style as the others.

### Submitter checklist

- [*] JIRA issue is well described
- [*] Link to JIRA ticket in description, if appropriate

2017-04-15 19:46 UTC, oleg-nenashev commented
CC random @jenkinsci/code-reviewers with UI background: @kzantow , @recena, @tfennelly

2017-04-17 13:21 UTC, recena commented on core/src/main/resources/hudson/model/View/newJob.jelly
> +              <div class="yui-button">
No more YUI dependency.

2017-04-17 13:21 UTC, recena commented on war/src/main/js/add-item.js
> +      return (itemName === '');
What is the relation with the event behavior that you want to change?

2017-04-17 15:19 UTC, Andrei94 commented on war/src/main/js/add-item.js
> +      return (itemName === '');
I haven't found one. It was just a small improvement that could be made.

2017-04-17 15:20 UTC, Andrei94 commented on core/src/main/resources/hudson/model/View/newJob.jelly
> +              <div class="yui-button">
I'm sorry, should I remove the yui dependency?

2017-04-20 19:13 UTC, recena commented on core/src/main/resources/hudson/model/View/newJob.jelly
> +              <div class="yui-button">
@Andrei94 I added a new CSS class in order to stop using YUI.

2017-04-20 19:14 UTC, recena commented on war/src/main/js/add-item.js
> +      return (itemName === '');
Unrelated with the JIRA issue. IMHO, the previous one is more readable.

2017-04-29 08:53 UTC, oleg-nenashev commented
@Andrei94 @recena so how do we proceed here?

2017-05-14 05:45 UTC, oleg-nenashev commented
@Andrei94 @recena ping

2017-05-15 19:42 UTC, Andrei94 commented on core/src/main/resources/hudson/model/View/newJob.jelly
> +              <div class="yui-button">
@recena the button is in a `footer` class and hence it doesn't get the YUI style, like the buttons from the other views i.e. the job config step. Here the buttons are part of the table and in the `additem.less` there is reference to the YUI styles.

2017-05-25 09:07 UTC, Andrei94 commented on core/src/main/resources/hudson/model/View/newJob.jelly
> +              <div class="yui-button">
@recena ping

2017-05-25 14:23 UTC, recena commented
My apologies, I lost this PR...

2017-06-17 23:54 UTC, oleg-nenashev commented
@recena you have lost it again, I'd guess

2019-04-04 19:37 UTC, daniel-beck commented
It is unclear to me why this is labeled _work in progress_, it seems a good code review or two and a test drive away from being merged. Or am I missing something?

2019-04-06 14:23 UTC, daniel-beck commented
Okay, I updated the PR branch and tried this. Here are screen shots.

# Before

> ![OK-old-disabled](https://user-images.githubusercontent.com/1831569/55670684-d93d1900-5887-11e9-9450-32daa9cffebc.png)

> ![OK-old-enabled](https://user-images.githubusercontent.com/1831569/55670686-db06dc80-5887-11e9-81fe-7e48bb2d6f00.png)

> ![OK-old-focused](https://user-images.githubusercontent.com/1831569/55670687-dcd0a000-5887-11e9-973f-a128d7adb799.png)

# After (with this PR)

> ![OK-new-disabled](https://user-images.githubusercontent.com/1831569/55670690-e2c68100-5887-11e9-8586-2fa1fd08fd75.png)

> ![OK-new-focused](https://user-images.githubusercontent.com/1831569/55670693-e4904480-5887-11e9-8fcc-a2cf943737c5.png)

![OK-new-pressed](https://user-images.githubusercontent.com/1831569/55670718-2b7e3a00-5888-11e9-9915-6392ab4b1dfc.png)

I would like to note that "old style" buttons with a pressed style exist in job configuration forms, so I'm confused as to the need to restyle these so thoroughly.

> ![Save-pressed](https://user-images.githubusercontent.com/1831569/55670705-0689c700-5888-11e9-88df-b2101cd99860.png)

Not to mention the alignment/margin seems a bit weird as well.

2019-04-06 14:25 UTC, daniel-beck commented
> The button was using a different style from the one that was used for example in save/apply for in the job config section. I changed it so that it uses the same style as the others.

Perhaps something changed since this PR was filed (despite there not having been a merge conflict), but it doesn't look like it's just like the others.

2019-04-06 14:40 UTC, daniel-beck commented
I noticed a few more problems with the current state:

The button does not stick to the bottom of the screen (which might be deliberate, not sure) when the content is higher than the viewport. Screenshot from before:

> ![old-fixed](https://user-images.githubusercontent.com/1831569/55670950-916bc100-588a-11e9-8ed9-4d4f7bf5b63a.png)

Since there's no area around the button, the grey area below the list is much larger than it would need to be, see previous screen shots.

And finally, there is a pressed, disabled state:

> ![new-disabled-pressed](https://user-images.githubusercontent.com/1831569/55670960-b3654380-588a-11e9-8585-ff44a3286530.png)

2019-04-06 14:42 UTC, daniel-beck commented
@Andrei94 I would love to see this PR updated to address review feedback (above), but in the current state it's not something I'd want to merge.

I completely understand if you're no longer interested, and I apologize for our failure to provide timely feedback.

2019-04-09 12:35 UTC, daniel-beck requested changes
As above

2019-04-18 13:17 UTC, batmat commented
I think this PR will be closed on next pass if we don't hear back in the meantime.

Again, we are **very** sorry we weren't responsive enough initially so this could move forward after it was filed. The reason we are closing this is also because we're trying to fix this mistake by having a better vision on the current PRs and **actually** review them.

Obviously: even after we possibly have closed this, please feel free to just comment here if you'd like to get back to it. We will be happy to reopen anytime.

Thanks for your understanding.

2019-04-18 13:37 UTC, batmat commented
Closing already, as latest comment from Daniel saying the same thing was 9 days old. Please refer to my previous anytime if you'd like to see it reopened. Thanks!

2019-04-18 13:37 UTC, closed without merging