[JENKINS-43733] Pick up the latest release of version-number library
jenkinsci/jenkins pull request #2851
Opened 2017-04-20 19:01 UTC by recena

# Description

See [JENKINS-43733](https://issues.jenkins-ci.org/browse/JENKINS-43733).

Details: TODO

### Changelog entries

Proposed changelog entries:

* Entry 1: Issue, Human-readable Text

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@mention

2017-04-20 19:36 UTC, oleg-nenashev commented
No need in the placeholder JIRA if it is an improvement without backporting need. 🐝 anyway

2017-04-20 19:51 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-04-20 21:32 UTC, jglick requested changes
You should fix `OldDataMonitor.VersionRange.isOld` now that there is a replacement, as mentioned in https://github.com/jenkinsci/lib-version-number/pull/3.

2017-04-21 18:23 UTC, recena commented
@jglick Addressed.

2017-04-22 10:27 UTC, recena commented
The PR builder is failing due to something unrelated with these changes:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project test: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\Downloads\0\tools\hudson.model.JDK\jdk8\jre\bin\java -Dfile.encoding=UTF-8 -Xmx1g -jar C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\Downloads\0\workspace\Core_jenkins_PR-2851-7NNP5F22RZD2R5X4EAH2CSUY2YJI56S3FC4YDZ2LVB3IL262SFSA\test\target\surefire\surefirebooter156011780002022759.jar C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\Downloads\0\workspace\Core_jenkins_PR-2851-7NNP5F22RZD2R5X4EAH2CSUY2YJI56S3FC4YDZ2LVB3IL262SFSA\test\target\surefire\surefire3610675378673748306tmp C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.8\Downloads\0\workspace\Core_jenkins_PR-2851-7NNP5F22RZD2R5X4EAH2CSUY2YJI56S3FC4YDZ2LVB3IL262SFSA\test\target\surefire\surefire_58895678356336142184tmp"
[ERROR] -> [Help 1]
```

The tests were:

```
Tests run: 7877, Failures: 0, Errors: 0, Skipped: 5, Flakes: 1
```

2017-04-22 10:32 UTC, oleg-nenashev commented
may be related if version-number bundles JNI stuff somehow, but I doubt about that

2017-04-22 12:24 UTC, recena commented
@oleg-nenashev I don't think so. I linked the changes between `1.3` and `1.4`.

2017-04-24 00:02 UTC, daniel-beck reviewed
Would prefer if this were held off a bit until https://github.com/jenkinsci/lib-version-number/pull/4 has been considered.

2017-04-24 09:38 UTC, recena commented
@daniel-beck What do you mean with _has been considered_? Tested? Verified? Checked?

2017-04-24 09:48 UTC, oleg-nenashev commented
@recena I suppose @daniel-beck wants to avoid API deprecation by just updating to `1.5` with his proposal. Since this PR has missed 2.56, it seems reasonable to me to do that in 2.58 on next Sunday

2017-04-24 09:51 UTC, recena commented
@oleg-nenashev ah ok. Thanks for your explanation.

2017-04-24 10:04 UTC, daniel-beck commented
@recena AFAIUI, the change to `OldDataMonitor` would be unnecessary if my PR is considered useful and merged into `version-number`. If it's not, we can just go ahead here.

2017-04-24 20:34 UTC, jglick requested changes

2017-04-24 20:34 UTC, jglick commented on test/.gitignore
> +/0/
Huh? Please revert.

2017-04-25 20:48 UTC, recena commented on test/.gitignore
> +/0/
@jglick When you run the tests this folder is created. I though it would be interesting to ignore it.

2017-04-25 20:53 UTC, jglick commented on test/.gitignore
> +/0/
Created by what? I have never seen such a file. I think something may be broken on your machine.

2017-04-26 13:24 UTC, daniel-beck commented on test/.gitignore
> +/0/
I've seen these directories as well.

2017-04-26 14:31 UTC, jglick commented on test/.gitignore
> +/0/
Containing what?

2017-04-26 16:33 UTC, recena commented on test/.gitignore
> +/0/
`mvn test -Dtest=OldDataMonitorTest`

output:

```
ip-192-168-1-111:test recena$ cd 0/
ip-192-168-1-111:0 recena$ ls -la
total 8
drwxr-xr-x  3 recena  staff  102 26 abr 18:31 .
drwxr-xr-x  8 recena  staff  272 26 abr 18:31 ..
-rw-r--r--  1 recena  staff  197 26 abr 18:31 build.xml
ip-192-168-1-111:0 recena$ 
```

This is being generated and hence, it should be ignored.

2017-04-26 16:51 UTC, olivergondza commented on test/.gitignore
> +/0/
I would say it should be generated somewhere where it gets cleaned ...

2017-04-26 16:59 UTC, jglick commented on test/.gitignore
> +/0/
Nope, fixing in #2860, so please revert.

2017-04-26 19:11 UTC, recena commented on test/.gitignore
> +/0/
@jglick thanks.

2017-04-26 21:24 UTC, jglick approved these changes

2017-04-27 07:44 UTC, oleg-nenashev approved these changes
lgtm

2017-04-27 07:44 UTC, oleg-nenashev commented
@reviewbybees done

2017-04-28 10:29 UTC, oleg-nenashev commented
Will merge tomorrow if there is no feedback

2017-04-29 15:44 UTC, merged