[JENKINS-43653] - Ensure AbstractItem#delete() NPE and RTE safety when checking executors
jenkinsci/jenkins pull request #2854
Opened 2017-04-22 10:16 UTC by oleg-nenashev

This is a regression introduced by https://github.com/jenkinsci/jenkins/pull/2789 in 2.55. See See [JENKINS-43653](https://issues.jenkins-ci.org/browse/JENKINS-43653).

This change adds missing NPE checks and also improves handling of Executables#getParentOf(), which may throw undocumented Runtime exceptions if Executable uses core API below 1.377 and does not implement getParent(). Executor#stop() has been also modified to explicitly handle the issue though there is still the same issue with estimated execution times.

### Changelog entries

Proposed changelog entries:

* JENKINS-43653: Ensure `NullPointerException` and `RuntimeException` safety when aborting builds during item deletion (regression in 2.55).
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees @stephenc

2017-04-22 10:21 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-04-22 10:22 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> -                            Item item = Tasks.getItemOf(getParentOf(workUnit.getExecutable()));
The reported issue is `getParentOf`

2017-04-22 10:35 UTC, stephenc commented
Bit overly finicky of an impl

2017-04-22 10:35 UTC, stephenc approved these changes

2017-04-22 12:17 UTC, jglick reviewed
I am not fully comfortable with the new API methods in `Executables`; at least they should be `@Restricted(NoExternalUse.class)` for purposes of a hotfix. The `Executor` change also looks gratuitous. The actual issue in `AbstractItem.delete` could have been addressed much more conservatively with a single `try`-`catch`.

2017-04-22 12:17 UTC, jglick commented on core/src/main/java/hudson/model/Executor.java
> +                    return HttpResponses.error(500, ex);
Suffices to just throw this exception (or a wrapper) out of the method.

2017-04-22 12:17 UTC, jglick commented on core/src/main/java/hudson/model/queue/Executables.java
> +            return null;
Please do not introduce API methods accepting null arguments for no particular reason. Should be `@Nonnull`.

2017-04-22 12:17 UTC, jglick commented on core/src/main/java/hudson/model/queue/Executables.java
> +        } catch(RuntimeException | Error ex) {
`AbstractMethodError` you mean?

2017-04-22 12:17 UTC, jglick commented on core/src/main/java/hudson/model/queue/Executables.java
> +     * @throws InvocationTargetException Operation failure due to the usage of incompatible API for old plugin depending on a core older than 1.377
I do not think we need a new method here. Suffices to document the exception in the original, and have `doStop` let it be thrown up as it did before—right?

2017-04-22 13:22 UTC, oleg-nenashev commented
> I am not fully comfortable with the new API methods in Executables; at least they should be @Restricted(NoExternalUse.class) for purposes of a hotfix.

The original issue is in Weekly, backporting of the fixes is not required. I would rather prefer to have a "proper" public API, because plugins are supposed to use this `Executables` utility class to retrieve the tasks instead of directly calling `getParent()` to be compatible with plugins targeting all cores. Do they do it? [Sometimes](https://github.com/search?q=org%3Ajenkinsci+%22queue.Executables%22&type=Code).

Anyway, I doubt it would be sane to introduce such interface changes again

2017-04-22 13:53 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/queue/Executables.java
> +        } catch(RuntimeException | Error ex) {
Nope. It calls the `getParentOf()`method above, which throws these types :(

2017-04-22 13:54 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Executor.java
> +                    return HttpResponses.error(500, ex);
This is a non-Restricted public API (it should be restricted, of course), hence I would prefer to keep the current implementation if you do not feel strongly. The user-visible behavior does not change

2017-04-22 14:21 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/queue/Executables.java
> +     * @throws InvocationTargetException Operation failure due to the usage of incompatible API for old plugin depending on a core older than 1.377
Restricted it for now

2017-04-22 14:22 UTC, stephenc requested changes
I think this needs rework on more considered review

2017-04-22 14:22 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +import java.util.Optional;
Unused afaiks

2017-04-22 14:22 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +import java.util.Optional;
Unused import from what I can see

2017-04-22 14:22 UTC, stephenc commented on core/src/main/java/hudson/model/AbstractItem.java
> +                        final SubTask subtask = executable != null ? getParentOfOrNull(executable) : null;
I'm really not liking the OrNull pattern.

2017-04-22 14:22 UTC, stephenc commented on core/src/main/java/hudson/model/queue/Executables.java
> +    public static @Nonnull SubTask getParentOf(@Nonnull Executable e)
I think the correct thing is to just return `e` in case of those issues and remove all the junk. I'd need to confirm on other than my phone though

2017-04-22 14:35 UTC, stephenc commented
I think this is complete over-kill IMHO

Explain why we need any more than

```
diff --git a/core/src/main/java/hudson/model/AbstractItem.java b/core/src/main/java/hudson/model/AbstractItem.java
index 974a940d54..0f44f79f34 100644
--- a/core/src/main/java/hudson/model/AbstractItem.java
+++ b/core/src/main/java/hudson/model/AbstractItem.java
@@ -622,7 +622,8 @@ public abstract class AbstractItem extends Actionable implements Item, HttpDelet
                     for (Executor e : c.getAllExecutors()) {
                         WorkUnit workUnit = e.getCurrentWorkUnit();
                         if (workUnit != null) {
-                            Item item = Tasks.getItemOf(getParentOf(workUnit.getExecutable()));
+                            Queue.Executable exe = workUnit.getExecutable();
+                            Item item = exe != null ? Tasks.getItemOf(getParentOf(exe)) : null;
                             if (item != null) {
                                 while (item != null) {
                                     if (item == this) {
```

?

2017-04-22 14:36 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +import java.util.Optional;
Yep, my bad

2017-04-22 14:36 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/AbstractItem.java
> +                        final SubTask subtask = executable != null ? getParentOfOrNull(executable) : null;
OK, will just kill that method and use try/catch

2017-04-22 14:39 UTC, oleg-nenashev commented
> Explain why we need any more than

* workUnit.getExecutable() may return null, will cause NPE in getParentOf
* getParentOf() may throw exceptions in a edge case (plugin implementing old Executable API)

2017-04-22 15:17 UTC, stephenc commented
The bug here is that I forgot the race condition where there is a delay between assigning the work unit and assigning the executable. That bug is all we should be fixing here.

GetParentOf will *never* throw exceptions. If you analyse the pre-1.377 signature and the post 1.377 signature you will see that *no* implementation will ever actually throw an exception. javac cannot know what the old signature was and hence does not see that there will never be an exception, hence it requires that we throw something.

Now with Java 9 and modules, we could end up with exceptions... except old code cannot be using modules so will be in the unnamed module so we will be able to setAccessible anyway and in any case we would need to be using modules for the plugin classloader to even have to worry about this.

Just go for the minimalist fix here, the extra API stuff is wholesale unnecessary IMHO (but I will. E pleasantly surprised if you can show my analysis incorrect)

2017-04-22 16:12 UTC, jglick reviewed
From looking at the JIRA issue, all that is required is a simple null check, as in @stephenc’s proposed patch. From mobile I lack the tools to understand the apparently unrelated hypothetical problems you are trying to address in this PR.

2017-04-22 16:12 UTC, jglick commented on core/src/main/java/hudson/model/queue/Executables.java
> +     * @since TODO
If restricting, delete `@since`.

2017-04-22 16:12 UTC, jglick commented on core/src/main/java/hudson/model/Executor.java
> +                    return HttpResponses.error(500, ex);
`Executor.doStop` is actually used from plugins AFAIK, so should not be restricted. Better to leave its original implementation alone unless this is somehow required to fix the reported bug.

2017-04-22 21:28 UTC, oleg-nenashev commented
No time to continue arguing this weekend. Will remove everything excepting the NPE fix & follow-up on other things afterwards

2017-04-23 10:21 UTC, oleg-nenashev commented
@stephenc E.g. there may be a problem with old version of DistFork plugin: https://issues.jenkins-ci.org/browse/JENKINS-8100 . Unrealistic example, of course. Will investigate on the next week, removing the code right now

2017-04-23 10:34 UTC, oleg-nenashev commented
I have left the TODO and Javadoc comment for Executables + Annotations. But there is no code changes left for that exception, only the NPE fix

2017-04-23 10:47 UTC, stephenc approved these changes
Recommend squashing before merge. I don't like adding rumours of JENKINS-8100 without confirmation

2017-04-23 10:52 UTC, stephenc commented
JENKINS-8106 fixed JENKINS-8100 please drop the TODO noise

2017-04-23 10:53 UTC, stephenc requested changes

2017-04-23 10:53 UTC, stephenc commented on core/src/main/java/hudson/model/queue/Executables.java
> +     * @throws Error Executable type does not offer the {@link Executable#getParent()} method or it fails with {@link Error}.
Noise see JENKINS-8106

2017-04-23 10:54 UTC, stephenc commented
https://github.com/jenkinsci/jenkins/commit/14d17c551a9c8229b59ee1cf702a7e30731764fb

2017-04-23 10:58 UTC, stephenc commented
Or https://github.com/jenkinsci/jenkins/commit/dced4d4cd49c02105b789d6ff5367b38497c246c may be the commit and it is https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-7546 (which was fixed in 1.380 rather than 1.388)

2017-04-23 10:59 UTC, stephenc commented
In either case the `getParentOf` method was to ensure correct signature handling and those TODOs are just noise.

I am fine with the two `@CheckForNull` annotations though

2017-04-23 11:43 UTC, jglick approved these changes

2017-04-23 11:43 UTC, jglick commented on core/src/main/java/hudson/model/AbstractItem.java
> +                        if (subtask != null) {
Could be simplified to only check `executable != null`.

2017-04-23 11:48 UTC, oleg-nenashev commented
@stephenc OK, dropped it.  The PR will be squashed of course

2017-04-23 13:58 UTC, stephenc approved these changes
Looks fine, only minor niggles

2017-04-23 13:58 UTC, stephenc commented on core/src/main/java/hudson/model/queue/Executables.java
> +            // TODO: according to the code above, e.getparent() may fail. The method also needs to be reworked
Noise

2017-04-23 13:58 UTC, stephenc commented on core/src/main/java/hudson/model/queue/Executables.java
> +            throws Error, RuntimeException {
Throws are unnecessary

2017-04-23 14:14 UTC, oleg-nenashev commented
@reviewbybees done
@jenkinsci/code-reviewers I would appreciate authorization to merge it (regression in the last weekly). IMHO it is important to get it in this weekly

2017-04-23 15:34 UTC, mc1arke approved these changes

2017-04-23 15:34 UTC, mc1arke commented on core/src/main/java/hudson/model/queue/Executables.java
> +            throws Error, RuntimeException {
No need to declare a method throwing a RuntimeException

2017-04-23 16:12 UTC, daniel-beck approved these changes
LTGM assuming squash.

2017-04-23 16:12 UTC, daniel-beck commented on core/src/main/java/hudson/model/AbstractItem.java
> +import java.lang.reflect.InvocationTargetException;
Unused import?

2017-04-23 16:22 UTC, oleg-nenashev commented
PR builder passed. Merging it, will cleanup the leftover after the weekly

2017-04-23 16:22 UTC, merged

2017-04-24 20:42 UTC, jglick commented on core/src/main/java/hudson/model/queue/Executables.java
> +            throws Error, RuntimeException {
Agreed with other reviewers, these `throws` should be reverted.