Indicate the actual protocol being served by jglick:TcpSlaveAgentListener
jenkinsci/jenkins pull request #2863
Opened 2017-05-01 17:11 UTC by jglick

# Description

Useful for distinguishing, say, deprecated `-remoting` CLI from JNLP agent connections.

### Changelog entries

None required.

### Desired reviewers

@reviewbybees

2017-05-01 17:12 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-05-01 17:12 UTC, jglick commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> -                LOGGER.log(Level.INFO, "Accepted connection #{0} from {1}", new Object[]{id,s.getRemoteSocketAddress()});
Note: will no longer print anything for `GET` diagnostic requests, or for malformed requests or those requesting a nonexistent protocol. But probably that is for the best anyway.

2017-05-01 17:16 UTC, daniel-beck commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> +                            LOGGER.log(Level.INFO, "Accepted {0} connection #{1} from {2}", new Object[] {protocol, id, this.s.getRemoteSocketAddress()});
What sort of value is `protocol`?

2017-05-01 17:18 UTC, jglick commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> +                            LOGGER.log(Level.INFO, "Accepted {0} connection #{1} from {2}", new Object[] {protocol, id, this.s.getRemoteSocketAddress()});
Typically `CLI2-connect` or `JNLP4-connect`.

2017-05-01 22:11 UTC, jglick commented
`InstallerTranslatorTest` failures are being tracked in an INFRA issue.

2017-05-02 06:09 UTC, stephenc commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> -                LOGGER.log(Level.INFO, "Accepted connection #{0} from {1}", new Object[]{id,s.getRemoteSocketAddress()});
Better to lower the log lever to FINE. This can be useful when diagnosing some issues connecting.

2017-05-02 06:33 UTC, oleg-nenashev commented on core/src/main/java/hudson/TcpSlaveAgentListener.java
> +                            LOGGER.log(Level.INFO, "Accepted {0} connection #{1} from {2}", new Object[] {protocol, id, this.s.getRemoteSocketAddress()});
It's fine for JNLP stuff, because it's how protocols are documented in Remoting

2017-05-02 06:34 UTC, oleg-nenashev approved these changes
🐝

2017-05-02 08:05 UTC, batmat approved these changes
:bee:

2017-05-02 08:22 UTC, stephenc requested changes
I'd rather keep the initial accept but at a lower level

2017-05-02 18:28 UTC, oleg-nenashev approved these changes
re-:bee:

2017-05-02 18:38 UTC, stephenc approved these changes

2017-05-02 21:43 UTC, jglick commented
@reviewbybees done

2017-05-04 13:10 UTC, merged