Translate few HTML resources to Mandarin
jenkinsci/jenkins pull request #2865
Opened 2017-05-01 21:20 UTC by lilyJi

2017-05-02 12:08 UTC, daniel-beck approved these changes
Google Translate looks reasonable, and I don't think we have people who speak Mandarin on the team.

2017-05-04 13:08 UTC, daniel-beck commented
@fengxx WDYT?

2017-05-04 15:52 UTC, fengxx commented on war/src/main/webapp/help/project-config/block-downstream-building_zh_CN.html
> +  启用选项后，Jenkins会阻止该项目的建立如果该项目的子项目在队列中或正在构建。
选中此选项后，当该项目的子项目在队列或构建中时，Jenkins将阻止该项目构建

2017-05-04 15:56 UTC, fengxx commented on war/src/main/webapp/help/system-config/master-slave/demand/idleDelay_zh_TW.html
> -</div>
by accident?
change EOF for unrelated files may cause merge issues.

2017-05-04 15:56 UTC, fengxx commented on war/src/main/webapp/help/system-config/master-slave/demand/idleDelay_zh_TW.html
> -</div>
it is traditional chinese, not related to this PR

2017-05-21 17:53 UTC, oleg-nenashev commented
Needs fix according to the feedback from @fengxx

2017-11-04 09:22 UTC, oleg-nenashev requested changes
@lilyJi any plans to address comments from @fengxx ?

2018-01-28 10:37 UTC, oleg-nenashev commented
@lilyJi @fengxx @daniel-beck there is no progress since the last feedback + there are merge conflicts due to the changes made by @linuxSuRen. I propose to close this PR

2018-01-28 11:21 UTC, LinuxSuRen commented
It does been long time ago.

2018-02-23 19:48 UTC, oleg-nenashev commented
@LinuxSuRen are you fine with closing?

2018-02-28 07:31 UTC, LinuxSuRen commented
@oleg-nenashev I can help put these translation into repo, if the orignal author don't focus it.

2018-02-28 16:29 UTC, closed without merging