Implement alphanum sorting in sortable.js
jenkinsci/jenkins pull request #2885
Opened 2017-05-11 22:52 UTC by ssbarnea

JENKINS-44119 alphanum sorting

# Description

See [JENKINS-44119](https://issues.jenkins-ci.org/browse/JENKINS-44119).

Details: TODO

### Changelog entries

Proposed changelog entries:

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@mention

2017-05-14 02:27 UTC, oleg-nenashev commented
I am definitely a wrong guy to review the JS code. Maybe @recena?

2017-05-15 18:55 UTC, daniel-beck commented
IMO needs more manual testing than review.

2017-05-16 23:34 UTC, orrc commented on war/src/main/webapp/scripts/sortable.js
> +    }
This code seems to be copied from elsewhere. Do you know what the license is?

2017-05-19 12:24 UTC, ssbarnea commented on war/src/main/webapp/scripts/sortable.js
> +    }
Yes, that code is mainly based on the http://www.davekoelle.com/files/alphanum.js which is LGPL. Based on https://softwareengineering.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application i would assume that there is no license conflict.

Please let me know if you want to make any changes to the code as we would all benefit from merging this.

The code worked for me well in Firefox, Chrome and Safari. I didn't had any other browsers to test with but based on its nature I doubt we would encounter any browser specific issues.

2017-05-20 19:22 UTC, daniel-beck requested changes
License issues

2017-05-20 19:22 UTC, daniel-beck commented on war/src/main/webapp/scripts/sortable.js
> +    }
> Only if you'd modify the library or directly include parts of the code in your software, then your code would have to be LGPL.

This seems to pretty obviously taint Jenkins.

2017-06-01 16:02 UTC, dmkoelle commented on war/src/main/webapp/scripts/sortable.js
> +    }
I'm the author of the Alphanum algorithm and I have no specific reason to maintain the LGPL license on it. I'd like to change Alphanum's licensing and I might as well select a license that will satisfy the use of the code in Jenkins. I imagine an MIT license would fit nicely with Jenkins. Would an Apache license also be acceptable?

2017-06-01 16:06 UTC, ssbarnea commented
@daniel-beck I contacted the author and today I got a reply as he would be glad to contribute these lines of code to Jenkins. You should hear back from him here for confirmation. His pick of LGPL was a moment decision and not something designed to harden the adoption by other projects.

2017-06-01 16:34 UTC, dmkoelle commented
(I also commented above the the thread started by @orrc)

I'm the author of the Alphanum algorithm I'm interested in licenses other than LGPL that would make this kind of use of Alphanum as easy as possible. You have my permission to proceed.

2017-06-17 23:53 UTC, oleg-nenashev commented
@daniel-beck @orrc So WDYT?

2017-06-18 09:38 UTC, daniel-beck commented
IANAL and all that, but I still see 2-3 problems here:

* @dmkoelle 's statement above does not change the license;
* the JS adaptation was independently developed and appears to be LGPL only (unclear license header);
* And finally, I'd prefer if this were integrated as a separate, as-unmodified-as-possible source file, with attribution/copyright and original license included.

 ideally @dmkoelle publishes his original work with MIT license, gets Brian Husman to re-release `alphanum.js` explicitly as MIT (or @ssbarnea wipes his memory clean of this implementation and creates his own based solely on @dmkoelle 's work, presumably the Java version), and @ssbarnea adapts the PR to integrate a new `alphanum.js`

2017-06-20 08:05 UTC, daniel-beck commented
Relevant part of the governance document (bold highlights mine): https://jenkins.io/project/governance/#copying-code-from-elsewhere

> **When you have a license to do so, and when that license is compatible with the MIT license, you can copy the code from elsewhere into Jenkins.**
> 
> The most typical case of this is that the original code is licensed under a certain subset of the open-source licenses, such as ASL, BSD, and MIT license. **Copyleft licenses, even though they are open-sourced, cannot be copied, such as EPL and GPL.**
> 
> **The code to be copied must be clearly marked with the license it is under, and when copying, you need to maintain the copyright/license attribution in the header.** Please also indicate the origin of the copy as a part of the commit message.

2017-06-22 01:38 UTC, dmkoelle commented
I will be changing alphanum to the MIT License as soon as possible (next day or two), and will update this thread when I complete that work.

2017-07-09 13:08 UTC, johnou commented
@dmkoelle any updates?

2017-07-09 17:12 UTC, daniel-beck commented
I tried using the JS implementation of this for https://github.com/jenkins-infra/infra-statistics/pull/32 before choosing a much simpler approach, and noticed that it sorts  `2.10`, `2.2`, `2.7`. Does this also apply to this implementation?

2017-07-12 03:46 UTC, dmkoelle commented
Great news - the Alphanum algorithm now officially uses the MIT License! 

Please see http://davekoelle.com/alphanum.html

Additionally, I have updated the license text in each of the source files linked from http://davekoelle.com/alphanum.html

2017-07-12 04:06 UTC, dmkoelle commented
@daniel-beck I have verified that the implementation as I had written it would sort those values as 2.2, 2.7, 2.10.

2017-07-12 08:14 UTC, ssbarnea commented
Please let me know if further changes are expected from me on this PR. If so please tell me so I can make them, merge and move on to more pressing tasks ;)

2017-07-12 08:26 UTC, johnou commented
@ssbarnea I would think taking a fresh copy of the re-licensed code, keeping the licence headers in place and updating the pull request would be a good start :)

2017-07-12 10:41 UTC, daniel-beck commented
@ssbarnea See https://github.com/jenkinsci/jenkins/pull/2885#issuecomment-309266874

2017-07-12 10:44 UTC, daniel-beck commented
@dmkoelle Did you get permission from Brian Huisman, author of the JS implementation, to do so, or otherwise have an indication that it would be licensed under whatever license the original is? All we have is the header to go on, and while it states "same as original", it also includes (included) the LGPL.

2017-07-12 10:52 UTC, daniel-beck commented
@ssbarnea What is this PR supposed to do again? Or is my observation above, with the sort implementation being broken, correct? I tried a PR build, and got this on the "All" view for projects (no display name, these are their actual names):

> ![screen shot](https://user-images.githubusercontent.com/1831569/28114333-ae9d08e2-6700-11e7-838c-cc52c5742b1c.png)

I clicked the column header a few times, but it never showed up in the expected order, either ascending or descending.

2017-07-12 13:59 UTC, dmkoelle commented
@daniel-beck Brian Huisman gives his permission. In an email to me on July 12, 2017, he wrote: "I have no problem with changing the license."

2017-07-12 14:10 UTC, daniel-beck commented
@dmkoelle Great, thank you. So from a license POV I have no concerns anymore.

2017-07-12 14:16 UTC, johnou commented
@daniel-beck wouldn't it still require updating this pull request with the updated code and license headers in tact? I have seen other projects revert / downgrade libraries because the license changed and it was no longer compatible / tainted the project.

2017-07-12 14:24 UTC, daniel-beck commented
@johnou Right, to clarify what I mean:

* [x] License is compatible now and no longer an obstacle to inclusion.
* [ ] Needs updating the implementation (separate file, license header, etc.) as previously mentioned
* [ ] Needs a response to my concerns about possible buggy implementation

2017-07-15 05:16 UTC, dmkoelle commented
I suspect, but have not confirmed, that the issue is with the line "var m = (i == 46 || (i >=48 && i <= 57));" in the code - specifically, the check for "i == 46", where ASCII 46 is a period. That is not something that my original implementation checks for (I check for whether the character is purely a digit), and I think this is causing 2.10 to come before 2.3 because, mathematically, "2 point 1 0" does indeed come before "2 point 3". If the period is interpreted like a string as I intended, the 2's would be compared, then the periods, then the value "10" vs. the value "3", leading to the correct ordering of 2.3 followed by 2.10.

2017-07-15 09:53 UTC, daniel-beck commented
@dmkoelle Interesting find; it could be considered to make sense to give decimal numbers special behavior (sorting by value). But then it stops being locale independent -- Germany has `1.234,56`; Switzerland uses both `1'234.56` and `1'234,56` -- and just generally becomes a mess. Especially when version numbers are mistaken as numbers…

2017-07-15 11:36 UTC, ssbarnea commented
@dmkoelle You are right, current proposal is bugged due to the line you mentioned before. That's because my proposal used the "official" JS implementation from www.davekoelle.com/files/alphanum.js which contains this bug.

If you could create an alphanum repository on github where you keep all implementations it would be much easier to raise bugs or make pull requests for fixing them (or even better, to write some unittests).

I will update my change with the fix, which worked well in my tests. Also I should mention that there is already a published npm package that implements that. There are multiple npm packages published but that the only one that I tried, and it worked.

As I hate duplicating code across projects I would prefer finding a way to use external one but I am not aware of Jenkins being able to do this with npm dependencies. Also the licensing may be another issue preventing this. I would let others with more knowledge about the subject to decide on that matter.

2017-07-15 11:53 UTC, johnou commented
@ssbarnea instead of modifying an existing javascript file and adding in custom code I think it would be less maintenance burden to simply update the entire sortable.js file which now supports alphanum sorting.. https://www.kryogenix.org/code/browser/sorttable/sorttable.js

2017-07-15 17:19 UTC, ssbarnea commented
@johnou I totally agree with you and I realised that Jenkins is already using npm packages, so I made my first npm package an hour ago. The code is still buggy but at least it has CI https://github.com/jsContribs/alphanum 

Once I have the module working (regarding of using @dmkoelle implementation or another one), I will update this PR use a npm package.

2017-07-15 18:40 UTC, ssbarnea commented
I could use some hints here. I managed to publish `sorttable` to npm and add it to `war/package.json` but I don't know how to replace the current loading of the embedded `sortable.js` from `core/src/main/resources/lib/layout/html.jelly` and `core/src/main/resources/lib/layout/layout.jelly` with the npm module.

2017-09-03 01:55 UTC, daniel-beck commented
@kzantow Could you help out here? (Previous comment) Thanks!

2018-03-04 00:18 UTC, oleg-nenashev commented
@kzantow @recena help with reviews will be appreciated.

So far there is a merge conflict after #3125 .

2019-02-07 22:29 UTC, oleg-nenashev commented
I have resolved the merge conflict, but I suspect it is maximum what my Javascript skills allow here.
Is anybody interested in getting it over the line?

2019-04-04 12:26 UTC, daniel-beck commented
The last notable activity here was almost two years ago, so I'm closing this PR as stalled. I'm sorry we were unable to support you with your NPM change.

FWIW I still think this would be viable and useful.

2019-04-04 12:26 UTC, closed without merging