[FIXED JENKINS-44204] Provide essential views for clouds
jenkinsci/jenkins pull request #2887
Opened 2017-05-16 10:15 UTC by olivergondza

# Description

Provide essential views for clouds
    
Cloud pages can now be customized by actions and sidepanel, that can be further customized by widgets.

- Clouds now have default `index` view so they can be linked.
- `Cloud` is actionable now.
- Clouds can present relevant info via `main` or `top` view instead of overriding the `index` page as a whole.
- Cloud is now actionable and actions can contribute snippets for main portion of `index` view, sidepanel's task list or list of boxes underneath.

cloud-stats plugin integration in downstream PR: TBD
![cloud-stats](https://cloud.githubusercontent.com/assets/206841/26101353/2c16a35c-3a31-11e7-9b0f-0cca213a0ef3.png)

See [JENKINS-44204](https://issues.jenkins-ci.org/browse/JENKINS-44204).

### Changelog entries

Views for Jenkins clouds.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@jenkinsci/code-reviewers, this is a new view API for cloud plugins.

2017-05-16 10:29 UTC, oleg-nenashev requested changes
Looks good to me 👍 All comments are rather improvement proposal excepting the missing documentation to `Cloud` Javadoc. I would follow the approach in other such API classes when new pages are documented

2017-05-16 10:29 UTC, oleg-nenashev commented on core/src/main/java/hudson/slaves/Cloud.java
> +    public @Nonnull String getUrl() { return "cloud/" + name; }
I would not inline the code here. IIRC Oracle codestyle does not advertise it

2017-05-16 10:29 UTC, oleg-nenashev commented on core/src/main/java/hudson/slaves/Cloud.java
> +    public @Nonnull String getSearchUrl() {
Add Javadoc as well? Just to explain difference. Maybe it is also a subject for default implementation like @jglick did for job APIs

2017-05-16 10:29 UTC, oleg-nenashev commented on core/src/main/resources/hudson/slaves/Cloud/index.jelly
> +            <h1>Cloud ${it.name}</h1>
"Cloud" should be localizable IMHO

2017-05-16 10:29 UTC, oleg-nenashev commented on core/src/main/resources/hudson/slaves/Cloud/index.jelly
> +            <st:include page="main.jelly" optional="true"/>
Maybe makes sense to print something if there is no such main page. NIT

2017-05-16 10:29 UTC, oleg-nenashev commented on core/src/main/java/hudson/slaves/Cloud.java
> +public abstract class Cloud extends Actionable implements ExtensionPoint, Describable<Cloud>, AccessControlled {
Cloud Javadoc needs to describe the new UI components

2017-05-16 10:59 UTC, olivergondza commented on core/src/main/java/hudson/slaves/Cloud.java
> +public abstract class Cloud extends Actionable implements ExtensionPoint, Describable<Cloud>, AccessControlled {
You mean the ones I introduced, no those that `Actionable` brought in, right?

2017-05-16 11:02 UTC, oleg-nenashev commented on core/src/main/java/hudson/slaves/Cloud.java
> +public abstract class Cloud extends Actionable implements ExtensionPoint, Describable<Cloud>, AccessControlled {
yep. The ones introduced by Actionable are not mandatory though it would not hurt

2017-05-16 11:07 UTC, olivergondza commented on core/src/main/resources/hudson/slaves/Cloud/index.jelly
> +            <st:include page="main.jelly" optional="true"/>
The thing is Jenkins knows very little about the clouds itself.

2017-05-16 14:28 UTC, oleg-nenashev approved these changes
👍

2017-05-20 22:26 UTC, oleg-nenashev commented
As @olivergondza said in IRC, he prefers to wait for a while for feedback from @jenkinsci/code-reviewers . So I will put this PR on-hold & let Oliver to decide when to merge

2017-05-28 20:36 UTC, daniel-beck commented
@olivergondza Ping?

2017-05-29 07:31 UTC, olivergondza commented
No more feedback so I will go on and merge.

2017-05-29 07:32 UTC, merged