Deprecate TimeUnit2
jenkinsci/jenkins pull request #2892
Opened 2017-05-19 10:11 UTC by batmat

`java.util.concurrent.TimeUnit` is preferrable now.

Quoting Stephen:
> Java 5 did not have all the units required. So TU2 was one that had better conversion. Can be deprecated 
once we upgrade to Java 6 ;-)

# Description

* I didn't file a JENKINS issue since this is a pretty internal/dev oriented change. But if this is judged necessary, please tell me so and I'll do it.

Details: see title, very small change. And 0 risk from a runtime perspective. 

### Changelog entries

Proposed changelog entries:

_N/A_ I don't even think this should have an entry in the changelog, should it?

### Submitter checklist

- ~~[ ] JIRA issue is well described~~
- ~~[ ] Link to JIRA ticket in description, if appropriate~~
- [X] Appropriate autotests or explanation to why this change has no tests
- ~~[ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)~~

### Desired reviewers

@reviewbybees

2017-05-19 10:12 UTC, stephenc approved these changes

2017-05-19 10:18 UTC, oleg-nenashev approved these changes
:bee:

2017-05-19 10:18 UTC, oleg-nenashev commented
Maybe `@Restricted(DoNotUse.class)` will be a good addition

2017-05-19 10:22 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-05-19 12:26 UTC, batmat commented
@stephenc @oleg-nenashev `@Restricted(DoNotUse.class)` also added as requested/proposed.

2017-05-19 12:28 UTC, stephenc approved these changes

2017-05-19 12:32 UTC, oleg-nenashev approved these changes

2017-05-19 12:39 UTC, batmat commented
@reviewbybees done

2017-05-19 13:20 UTC, jglick requested changes
There are dozens of usages of `TimeUnit2` in this repository. You should clean them up. (I know they are harmless, but as a matter of policy we should not be deprecating things with a claim that a full replacement is available, without proof that this is actually so in some representative code base.)

2017-05-19 13:43 UTC, batmat commented
Agreed @jglick I actually have that change locally, but it fails for now because accmod either is limited or, more probably IIUC, has a bug wrt to enums.

```
[INFO] --- access-modifier-checker:1.11:enforce (default) @ jenkins-core ---
[ERROR] hudson/util/TimeUnit2$1:0 hudson/util/TimeUnit2 must not be used
[ERROR] hudson/util/TimeUnit2$2:0 hudson/util/TimeUnit2 must not be used
[ERROR] hudson/util/TimeUnit2$7:0 hudson/util/TimeUnit2 must not be used
[ERROR] hudson/util/TimeUnit2$4:0 hudson/util/TimeUnit2 must not be used
[ERROR] hudson/util/TimeUnit2$3:0 hudson/util/TimeUnit2 must not be used
[ERROR] hudson/util/TimeUnit2$6:0 hudson/util/TimeUnit2 must not be used
[ERROR] hudson/util/TimeUnit2$5:0 hudson/util/TimeUnit2 must not be used
```

2017-05-19 13:59 UTC, jglick commented
Arguably a bug in `access-modifier-checker`. You could fix that and `deploy` a snapshot for use in this PR, or just relax to `NoExternalUse` for now.

2017-05-20 13:57 UTC, batmat commented
@jglick fixed, build is passing on my machine. 
It's for now using a SNAPSHOT of https://github.com/kohsuke/access-modifier/issues/6 while it's not merged/released.

2017-05-22 20:10 UTC, jglick commented on core/src/main/java/hudson/util/TimeUnit2.java
> +@Restricted(DoNotUse.class)
Do we actually need this to be `@Restricted`? Why? `@Deprecated` accomplishes everything we need, I think.

2017-05-22 20:10 UTC, jglick commented on pom.xml
> +    <access-modifier.version>1.12-PR6-SNAPSHOT</access-modifier.version>
You need to change the two properties below instead of this one.

2017-05-22 21:05 UTC, batmat commented on core/src/main/java/hudson/util/TimeUnit2.java
> +@Restricted(DoNotUse.class)
It was recommended by @oleg-nenashev and encouraged by @stephenc I guess this avoids we possibly reintroduce some usages as we go @jglick ?

2017-05-23 12:16 UTC, jglick commented on core/src/main/java/hudson/util/TimeUnit2.java
> +@Restricted(DoNotUse.class)
I generally reserve restriction for newly introduced (or modified) APIs, or cases where ongoing use is clearly going to break, so this seems like overkill. I am not objecting, just FYI.

2017-09-15 15:20 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-09-17 13:32 UTC, batmat commented
[Finally followed the recommendation of @jglick above](https://github.com/jenkinsci/jenkins/pull/2892#issuecomment-302710465):

> [...] just relax to NoExternalUse for now.

In the end, the goal of actually deprecating `TimeUnit2` and that people/code start adapting and replace their usage would be moving forward, which was the gist of the PR...

Sorry for the long-lived PRs :-(

2017-09-18 18:51 UTC, jglick approved these changes

2017-09-18 18:51 UTC, jglick commented on core/src/main/java/hudson/util/TimeUnit2.java
> +@Restricted(NoExternalUse.class)
A restriction is inappropriate here. `@Deprecated` is appropriate and suffices. The reason for the existence of `@Restricted(NoExternalUse.class)` is to allow access from another package within the same source root, similar to `public` in a nonexported package in Java 9.

2017-09-18 18:51 UTC, jglick commented on core/src/main/java/hudson/util/TimeUnit2.java
> + * @deprecated use {@link TimeUnit}. (Java 5 did not have all the units required, so TimeUnit2 was introduced because it
`@code` or `@link`

2017-09-18 19:47 UTC, batmat commented
@reviewbybees done

2017-09-18 19:49 UTC, merged

2017-09-18 19:49 UTC, batmat commented
Thanks for the reviews!

2017-09-24 16:44 UTC, daniel-beck commented
Since `TimeUnit2` is used in plenty of plugins, and newly restricted core API, a changelog entry is definitely needed.

2017-09-24 19:16 UTC, batmat commented
@daniel-beck 

* `hudson.util.TimeUnit2` deprecated, use `java.util.concurrent.TimeUnit` instead. 

?