[JENKINS-34464] Switch ReverseBuildTrigger.threshold to DataBoundSetter
jenkinsci/jenkins pull request #2895
Opened 2017-05-22 16:28 UTC by abayer

# Description

See [JENKINS-34464](https://issues.jenkins-ci.org/browse/JENKINS-34464).

Details: Adding `ReverseBuildTrigger.setThreshold(Result)` as a `@DataBoundSetter`, defaulting `threshold` to `Result.SUCCESS`.

### Changelog entries

Proposed changelog entries:

* Entry 1: Switch ReverseBuildTrigger.threshold to DataBoundSetter

### Submitter checklist

- [x] JIRA issue is well described
- [x] Link to JIRA ticket in description, if appropriate
- [x] Appropriate autotests or explanation to why this change has no tests (no new tests needed - existing behavior continues to work)
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees

2017-05-22 16:29 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-05-22 16:43 UTC, oleg-nenashev requested changes
🐛 It breaks binary compatibility of a public constructor with external usages: https://github.com/search?utf8=%E2%9C%93&q=org%3Ajenkinsci+%22new+ReverseBuildTrigger%22&type=Code

2017-05-22 16:43 UTC, oleg-nenashev commented on core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
> +    public ReverseBuildTrigger(String upstreamProjects) {
🐛 Binary-incompatible change

2017-05-22 19:52 UTC, jglick commented on core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
> +    public ReverseBuildTrigger(String upstreamProjects) {
Right, need to keep original with `@Deprecated`.

2017-05-24 16:18 UTC, abayer commented on core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
> +    public ReverseBuildTrigger(String upstreamProjects) {
Whoopsie, fixing.

2017-05-24 16:58 UTC, jglick approved these changes

2017-05-24 17:04 UTC, oleg-nenashev approved these changes
🐝 . Would be nice to have clarification of why ReverseBuildTrigger is deprecated in Javadoc

2017-05-25 20:56 UTC, jglick approved these changes

2017-05-25 21:02 UTC, oleg-nenashev approved these changes
🐝 and @reviewbybees done

2017-05-29 11:27 UTC, oleg-nenashev commented
Ready for merge. @abayer please propose a user-readable changelog, the current one is rather for developers

2017-05-31 04:34 UTC, oleg-nenashev commented
It also fixes [JENKINS-44559](https://issues.jenkins-ci.org/browse/JENKINS-44559), but probably this bug requires readResolve() for the migrated triggers. @abayer WDYT?

2017-06-03 07:38 UTC, daniel-beck commented
> user-readable changelog

Looks reasonable after *Internal* prefix, as that's what this is. Unless this enables a user-visible change, in that case, that should be mentioned.

2017-06-09 21:53 UTC, daniel-beck commented
@abayer Ping

2017-06-16 10:43 UTC, oleg-nenashev commented
I pinged @abayer yesterday in PM. He was going to fix that

2017-06-16 12:11 UTC, abayer commented
I added the "Internal"

2017-06-17 00:39 UTC, daniel-beck commented
@abayer So there's no user-visible effect of this PR?

2017-06-17 15:14 UTC, jglick approved these changes
There is: cleaner **Pipeline Syntax** for `properties`.

2017-06-17 15:54 UTC, daniel-beck commented
Then we should phrase it like that. Good to go then IMO.

2017-06-24 19:59 UTC, merged