[JENKINS-44663] Authorization header should be case insensitive
jenkinsci/jenkins pull request #2913
Opened 2017-06-10 06:19 UTC by daurnimator

2017-06-10 08:48 UTC, daniel-beck commented on core/src/main/java/jenkins/security/BasicHeaderProcessor.java
> +        if (authorization!=null && authorization.regionMatches(true, 0, "Basic ", 0, 6)) {
`StringUtils.startsWithIgnoreCase` for readability?

2017-06-10 08:50 UTC, daniel-beck commented on test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
> +    private void makeRequestAndVerify(String headerName, String headerValue, String username) {
Still needs to declare `IOException, MalformedURLException` (PR build failure)

2017-06-10 22:23 UTC, oleg-nenashev requested changes
Yes, needs a fix

2017-06-11 08:41 UTC, daurnimator commented on core/src/main/java/jenkins/security/BasicHeaderProcessor.java
> +        if (authorization!=null && authorization.regionMatches(true, 0, "Basic ", 0, 6)) {
Is that a standard function? I didn't find much when I searched for it.

2017-06-11 09:01 UTC, daniel-beck commented on core/src/main/java/jenkins/security/BasicHeaderProcessor.java
> +        if (authorization!=null && authorization.regionMatches(true, 0, "Basic ", 0, 6)) {
@daurnimator It's from commons-lang and included with Jenkins.

2017-06-11 18:04 UTC, daniel-beck commented
> `BasicHeaderProcessorTest.java:[99,46] error: incompatible types: String cannot be converted to boolean`

@daurnimator 

Could you please at least compile the tests locally? Otherwise this becomes a waste of time for us.

2017-06-26 07:09 UTC, daurnimator commented
I didn't manage to get tests to run locally. I'll let someone else fix the issue.

2017-06-26 07:09 UTC, closed without merging

2017-06-26 07:41 UTC, oleg-nenashev commented
@daurnimator would be great to know what was the issue with running tests