[JENKINS-43496] - Add handling of the null Node#createComputer() result.
jenkinsci/jenkins pull request #2922
Opened 2017-06-18 19:47 UTC by oleg-nenashev

it is a follow-up to https://github.com/jenkinsci/jenkins/pull/2836#discussion_r110604865

De-facto many Cloud plugins return `null` in `Node#createLauncher()`, but it has never been documented.
In order to prevent possible API misusages in the future, I have added annotations and fixed handling of the extension point in `AbstractCIBase#updateComputer()` which may fail in the case of `null` or `RuntimeException` in the Node implementation.

See [JENKINS-43496](https://issues.jenkins-ci.org/browse/JENKINS-43496).

### Changelog entries

Proposed changelog entries:

* Entry 1: Prevent failure of the computer update logic if the `Node` implementation in a plugin does not support creation of ad-hoc computers or throws a runtime exception.
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees

2017-06-18 19:49 UTC, oleg-nenashev commented
CC @abayer  and @jtnord who were working on this codebase recently

2017-06-18 20:17 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-06-19 16:13 UTC, stephenc reviewed
One question to answer

2017-06-19 16:13 UTC, stephenc commented on core/src/main/java/hudson/model/Node.java
> +    @Restricted(NoExternalUse.class)
Won't this cause compilation failures for sub-classes? (and if it doesn't then won't the subclass method be invocable anyway, in which case the annotation is useless

2017-06-19 16:25 UTC, jglick requested changes
Apparently gratuitous restriction on `createComputer`. I do not know offhand of `Node`s which are neither `Jenkins` nor `Slave`s, but the API seems designed to make it possible.

2017-06-19 16:55 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Node.java
> +    @Restricted(NoExternalUse.class)
Agreed

2017-06-19 17:08 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Node.java
> +    @Restricted(NoExternalUse.class)
@stephenc @jglick My intention was to reflect the `Nobody but {@link Jenkins#updateComputerList()} should call this method.` comment in Javadoc. If you know a better annotation for it, just let me know. Not sure if I can dedicate time to writing another restriction if it is missing, so I will just remove it in such case

2017-06-19 17:09 UTC, jglick commented on core/src/main/java/hudson/model/Node.java
> +    @Restricted(NoExternalUse.class)
@oleg-nenashev ah, were you looking for `ProtectedExternally` then?

2017-06-19 17:11 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Node.java
> +    @Restricted(NoExternalUse.class)
@jglick Yep, it should work better in this case

2017-06-19 17:37 UTC, jglick requested changes
The annotation on `Slave` does not appear to match reality. I do not know what it would mean to return null, but apparently some plugins do so for some reason.

2017-06-19 17:37 UTC, jglick commented on core/src/main/java/hudson/model/Node.java
> +     *         Can be {@code null} if the {@link Node} implementation does not support it (e.g. {@link Cloud} agent).
Is this actually true? A `Cloud` agent would ultimately be a `Slave`, and that is now documented to return non-null—which seems to contradict your statement that some implementations do return non-null.

2017-06-19 17:37 UTC, jglick commented on core/src/main/java/hudson/model/Slave.java
> +    @Nonnull
This is not true in the case of [`GoogleSlave`](https://github.com/jenkinsci/gcloud-plugin/blob/4b84dbdd2532dc65feb5bef11f82f713360622b2/src/main/java/com/cloudbees/jenkins/plugins/gcloud/GoogleSlave.java#L19-L21), from a quick search.

2017-06-20 08:18 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Slave.java
> +    @Nonnull
I agree. Better to just remove since the parent Javadoc describes the `null` case in a portable way

2017-06-20 08:19 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Node.java
> +     *         Can be {@code null} if the {@link Node} implementation does not support it (e.g. {@link Cloud} agent).
Fixed. `Slave#createLauncher()` now can create nulls

2017-06-20 15:04 UTC, oleg-nenashev commented
Needs another review

2017-06-20 15:38 UTC, jglick approved these changes

2017-06-21 08:38 UTC, oleg-nenashev commented
@reviewbybees done, passing to @jenkinsci/code-reviewers

2017-06-24 20:01 UTC, daniel-beck commented on core/src/main/java/hudson/model/AbstractCIBase.java
> +                LOGGER.log(Level.WARNING, "Node {0} has not executors. Cannot udate the Computer instance for it", n.getNodeName());
… has no … update its …

2017-06-26 22:06 UTC, oleg-nenashev commented
@daniel-beck fine for you?

2017-07-01 06:11 UTC, oleg-nenashev commented
In IRC @daniel-beck said he sees no obvious issues, hence merging

2017-07-01 06:11 UTC, merged