[JENKINS-38527] - Prevent NullPointerException in Slave#createLauncher() and add cause diagnostics
jenkinsci/jenkins pull request #2923
Opened 2017-06-20 09:22 UTC by oleg-nenashev

The original issue comes from the isUnix() unboxing, but we can also get into an issue later if we pass a null Channel instance to the logic.
This change adds some diagnostics which discovers potential root causes of such potential NPEs due to the race conditions with Computer reconnection

See [JENKINS-38527](https://issues.jenkins-ci.org/browse/JENKINS-38527) raised by @ndeloof (isUnix()).

No tests, because I am not sure how to reliably reproduce such issue in JTH. `this != computer.getNode()` also may happen only due to the race condition

### Changelog entries

Proposed changelog entries:

* Entry 1: revent NullPointerException in Slave#createLauncher() when creating command launchers for disconnected or reconnected agents.
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Link to JIRA ticket in description, if appropriate
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For new API and extension points: Link to the reference implementation in open-source (or example in Javadoc)

### Desired reviewers

@reviewbybees

2017-06-20 09:27 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-06-21 09:01 UTC, stephenc requested changes
I think you need to guard against a closing or closed channel in the check... (though if this is a `VirtualChannel` you cannot IIRC in which case this code is fine)

2017-06-21 09:01 UTC, stephenc commented on core/src/main/java/hudson/model/Slave.java
> +            final Boolean isUnix = channel != null ? c.isUnix() : null; // No sense to check it if the channel is down
`channel != null && !channel.isClosingOrClosed()`

2017-06-21 09:24 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Slave.java
> +            final Boolean isUnix = channel != null ? c.isUnix() : null; // No sense to check it if the channel is down
It should have failed later in such case, but I agree it worth having an explicit check

2017-06-21 09:52 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Slave.java
> +            final Boolean isUnix = channel != null ? c.isUnix() : null; // No sense to check it if the channel is down
I expected `channel.call()` to handle it, but it does not...
The only handler is https://github.com/jenkinsci/remoting/blob/a762e0703a04ae41fbd413b2379d57f80fc282b2/src/main/java/hudson/remoting/Channel.java#L604-L605 , which effectively checks for the closed channel after a bunch of operations.

IMHO `Channel` should provide a new API for user-space calls which should not be performed in parallel with close. Making it a default behavior seems to be a breaking change though, needs much testing

2017-06-21 09:56 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Slave.java
> +            final Boolean isUnix = channel != null ? c.isUnix() : null; // No sense to check it if the channel is down
Created https://issues.jenkins-ci.org/browse/JENKINS-45023

2017-06-21 10:13 UTC, stephenc approved these changes

2017-06-21 10:40 UTC, oleg-nenashev commented
@reviewbybees done, passing to @jenkinsci/code-reviewers

2017-06-26 09:02 UTC, merged

2017-06-29 21:34 UTC, jglick reviewed
Seems to be updated in part by https://github.com/jenkinsci/remoting/pull/175.

2017-06-29 21:34 UTC, jglick commented on core/src/main/java/hudson/model/Slave.java
> +    private void reportLauncerCreateError(@Nonnull String humanReadableMsg, @CheckForNull String exceptionDetails, @Nonnull TaskListener listener) {
Typo.

2017-09-08 21:24 UTC, daniel-beck commented on core/src/main/java/hudson/model/Slave.java
> +    private void reportLauncerCreateError(@Nonnull String humanReadableMsg, @CheckForNull String exceptionDetails, @Nonnull TaskListener listener) {
Luckily `private` :-)