[JENKINS-43581] - Create new custom tool button should be on top
jenkinsci/jenkins pull request #2926
Opened 2017-06-25 22:08 UTC by Ykus

See [JENKINS-43581](https://issues.jenkins-ci.org/browse/JENKINS-43581).

### Proposed changelog entries

* Adds button, for adding new entries, on top of a repeatable form (issue 43581)

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @oleg-nenashev

2017-06-25 22:56 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-06-26 07:34 UTC, oleg-nenashev commented
@Ykus Please do not use `@reviewbybees` if you not a CloudBees employee. Use @jenkinsci/code-reviewers  instead

2017-06-26 07:39 UTC, oleg-nenashev requested changes
The change impacts all `repeatable.jelly` usages, and IMHO it may cause some UX issues in cases when the list is short.  

I would advice to add a new `attrs` parameter, which enables the button on the top. And then apply it to the long layouts like tools.

The code itself looks good to me, but I am not a Javascript developer. Extra feedback would be useful

2017-07-09 11:24 UTC, Ykus commented
@oleg-nenashev I have changed repeatable forms behavior regarding your suggestion.

2017-07-09 11:39 UTC, oleg-nenashev approved these changes
I have reviewed it yesterday. The most of the change looks good, and thanks for adding tests for it. 👍 

I have only minor comments regarding the license headers and the CSS file

2017-07-09 11:39 UTC, oleg-nenashev commented on test/src/test/resources/lib/form/RepeatableTest/testNestedRadioTopButton.jelly
> +Copyright (c) 2004-2010, Sun Microsystems, Inc., Alan Harder
I am not sure about this and other headers. Was it full copy-paste of the file? If no, makes sense to update dates and to add your names

2017-07-09 11:39 UTC, oleg-nenashev commented on war/src/main/webapp/css/style.css
> +.row-set-end, .hide { display: none; }
Hm, is it related? I see no usages

2017-07-09 16:35 UTC, Ykus commented on war/src/main/webapp/css/style.css
> +.row-set-end, .hide { display: none; }
Good catch, Thanks.

2017-07-09 16:48 UTC, oleg-nenashev commented on test/src/test/resources/lib/form/RepeatableTest/testNestedTopButtonInner.jelly
> +Copyright (c) 2004-2017 by Zdenek Soukup
2017- then

2017-07-09 17:03 UTC, daniel-beck commented on core/src/main/resources/lib/form/repeatable.jelly
> +      Display of top button depends also on number of items.
Too vague.

2017-07-09 17:05 UTC, daniel-beck commented
Does this just move the button, or add a second button?

What sorts of lists in Jenkins does this affect? Could this also be applied to lists of build steps in freestyle projects? IIRC there is a request to add new steps on top.

2017-07-09 22:13 UTC, Ykus commented
It adds new (second) button above the repeatable form.

It affects only repeatable (repeatable.js) lists. Freestyle projects are made by hetero-list. I think I can make similar changes for hetero-list as I made for repeatable.

2017-07-22 18:09 UTC, oleg-nenashev commented
I think @daniel-beck should just create a follow-up ticket for the Hetero List. I have modified the changelog entries in order to reflect which control and page are updated.

2017-07-22 22:43 UTC, daniel-beck commented
@oleg-nenashev Alike things should behave alike. It's insane that Jenkins records who created an agent, but not any other object in Jenkins.

I'd like to take another look at this before this goes in to understand it better.

2017-07-22 22:57 UTC, oleg-nenashev commented
ack, on hold then

2017-08-03 20:55 UTC, oleg-nenashev commented
@daniel-beck gentle reminder. It would be nice to land it into the next LTS baseline, because it is a real problem for big tool configs

2017-08-04 12:13 UTC, daniel-beck commented
I suppose it fixes the issue as reported by introducing yet more buttons. I feel sorry for the person who wants their stuff to appear in the middle of the list.

Besides that obvious limitation, I'm really not sure about this. As I wrote above,

> Alike things should behave alike.

And all other lists don't get this. I'm pretty sure the corresponding request for build steps is even older than this. In the case of build steps, we might be saying that it's not a good idea to have so many different ones to begin with. But personally, I'd say the same for lists of tool installations.

Not strongly opposed, but I don't think this is a good solution either.

2017-08-04 18:55 UTC, oleg-nenashev commented
> And all other lists don't get this. I'm pretty sure the corresponding request for build steps is even older than this. In the case of build steps, we might be saying that it's not a good idea to have so many different ones to begin with

I agree though I rather see it as a follow-up ticket. Testing UX on a single control LGTM. More feedback from @jenkinsci/code-reviewers would be definitely useful

2017-08-12 23:06 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers ping, the vacation period is almost over ;)

2017-08-12 23:07 UTC, oleg-nenashev commented
Unassigned @daniel-beck according to his feedback in IRC, we need more votes

2017-09-15 15:32 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-11-04 09:08 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers ping. Custom Tools plugin is generally broken now due to the dependency on insecure Extended Choice version, but maybe somebody is up to reviewing it

2017-11-04 10:01 UTC, recena commented
IMHO, screenshots before/after are very helpful for this PR.

2017-11-06 14:46 UTC, daniel-beck commented
> I agree though I rather see it as a follow-up ticket. Testing UX on a single control LGTM.

Then we need specific commitment of someone to follow up on this no later than N months from now and either revert, or implement everywhere.

2018-01-22 18:23 UTC, daniel-beck commented
@oleg-nenashev 

I do not think the minor usability improvement here outweighs the resulting inconsistency between similar UI controls, making this a (slightly) net negative change. Hence my previous comment.

The road forward is clear IMO: Not do this, or apply it consistently.

Again, I'm not specifically _blocking_ this if you feel strongly, but it doesn't look to me that many others are interested in seeing this land based on limited feedback here.

2018-03-04 01:35 UTC, oleg-nenashev commented
I am merging it on my own responsibility since nobody else blocks the pull request. Although it is a "minor improvement" for API users, it is a significant UX improvement for Jenkins admins who have to define many tool installations. The change is well covered by tests. Since we have much bigger barely-justified changes like XML 1.1 merged, I consider it is as a judgment call. And in this case I decide to merge this contribution from a community member instead of blocking it indefinitely.

I have created [JENKINS-49900](https://issues.jenkins-ci.org/browse/JENKINS-49900) as a follow-up to @daniel-beck's requirement. It's a newbie-friendly ticket, I will be offering it to GSoC students who are interested in UI-related project ideas.

2018-03-04 01:35 UTC, merged

2018-03-04 01:36 UTC, oleg-nenashev commented
Thanks for your contribution @Ykus! My apologies for it taking so long

2018-03-04 18:41 UTC, recena commented
@jglick 

> We are not generally investing time in “classic UI”; contributions should go toward Blue Ocean.

Long life to the classic UI.