[FIXED JENKINS-43199] Defensively ensure the root stream is always closed even when plugins misbehave
jenkinsci/jenkins pull request #2953
Opened 2017-07-31 11:51 UTC by stephenc

See [JENKINS-43199](https://issues.jenkins-ci.org/browse/JENKINS-43199) and [JENKIN-45057](https://issues.jenkins-ci.org/browse/JENKINS-45057)

@reviewbybees

2017-07-31 11:56 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-07-31 14:19 UTC, oleg-nenashev reviewed
Mostly LGTM, minor comments

2017-07-31 14:19 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/Run.java
> +            IOUtils.closeQuietly(listener);
Logging would be useful here. IIRC there is a method in hudson.Util or other util class

2017-07-31 14:19 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/StreamBuildListener.java
> +    public StreamBuildListener(OutputStream out, Charset charset, Closeable... additionalClosables) {
Add some javadoc?

2017-07-31 14:19 UTC, oleg-nenashev commented on core/src/main/java/hudson/model/StreamBuildListener.java
> +    public void close() throws IOException {
It implies that all classes are tolerant against douple close() call. They should according to the Closeable speck, so fine for me

2017-07-31 17:57 UTC, jglick reviewed
Should work, though #2954 would accomplish the same with no new API and less fuss.

2017-07-31 17:57 UTC, jglick commented on core/src/main/java/hudson/model/Run.java
> +            IOUtils.closeQuietly(listener);
This is already called at line 1788, so what is the effect of calling it again?

2017-07-31 17:57 UTC, jglick commented on core/src/main/java/hudson/model/StreamBuildListener.java
> +    private final Closeable[] additionalClosables;
This new API seems unnecessary complicated. Would suffice for `RunExecution.execute` to retain the `OutputStream logger` as a separate local variable, and close _that_ in its `finally` block.

2017-08-02 19:37 UTC, jglick commented on core/src/main/java/hudson/model/StreamBuildListener.java
> +                        e.addSuppressed(e1);
If we are to do something this fancy, I think it should be a more general-purpose utility, as proposed here: https://github.com/jenkinsci/remoting/pull/104#r75861893

2017-08-02 19:47 UTC, jglick requested changes

2017-08-02 19:47 UTC, jglick commented on core/src/main/java/hudson/model/StreamBuildListener.java
> +    private final Closeable[] additionalClosables;
Making this field be non`transient` seems to cause [many legitimate-looking test failures](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-2953/1/testReport/).

2017-08-02 20:08 UTC, stephenc commented
Closing in favour of #2954

2017-08-02 20:08 UTC, closed without merging