JENKINS-13153 Use directory from env:BASE when writing jenkins.copies
jenkinsci/jenkins pull request #2992
Opened 2017-08-21 21:07 UTC by hplatou

… and when rewriting jenkins.exe

See [JENKINS-13153](https://issues.jenkins-ci.org/browse/JENKINS-13153).

"jenkins.copies" should be written to the folder containing the service wrapper executable(jenkins.exe). Currently, JENKINS_HOME is used. Using a custom JENKINS_HOME will cause the file to be written to a wrong directory. The service wrapper is setting the environment variable BASE which is the correct directory to use. 

### Proposed changelog entries

* Entry 1: JENKINS-13153, Fixing problem with Auto Upgrade when using custom JENKINS_HOME on Windows

2017-08-21 22:20 UTC, oleg-nenashev requested changes
+1 for making `BASE` a default source of the path, but I suggest to use the current behavior as a fallback instead of throwing exceptions. In such case a warning in the System log should be enough.

Later it makes sense to make a better WinSW discovery logic, which would check process tree and locate executables.

2017-08-21 22:20 UTC, oleg-nenashev commented on core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java
> +            throw new FileNotFoundException("Unable to locate Jenkins base directory. Environment variable 'BASE' not found.");
I would still try Jenkins root dir as a fallback. Otherwise there is a risk of breaking some cases.

2017-08-22 13:31 UTC, hplatou commented
Updated based on your request. Sorry for the wrong formatting commits.

2017-08-25 20:57 UTC, oleg-nenashev approved these changes
LGTM 👍 
@jenkinsci/code-reviewers , WDYT?

2017-09-02 19:07 UTC, oleg-nenashev commented
No negative feedback, merging

2017-09-02 19:08 UTC, merged