[Fix JENKINS-44663] Make authorization header to be case in-sensitive
jenkinsci/jenkins pull request #3002
Opened 2017-09-05 12:36 UTC by liketic

See [JENKINS-44663](https://issues.jenkins-ci.org/browse/JENKINS-44663).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

2017-09-05 17:38 UTC, daniel-beck approved these changes

2017-09-05 22:11 UTC, oleg-nenashev approved these changes
👍

2017-09-05 22:11 UTC, oleg-nenashev commented on test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
> +    private void doMakeRequestWithAuthAndVerify(String authCode, String expected) throws IOException, SAXException {
doMake... sounds like a Stapler endpoint prefix, but it's does not matter much for a private method

2017-09-05 22:12 UTC, oleg-nenashev requested changes
Hmm, test failure is definitely related...

2017-09-06 08:06 UTC, liketic commented
@oleg-nenashev Thank you. I didn't figure out how to run a single test yet, any help is appreciated. :) .

2017-09-06 09:27 UTC, oleg-nenashev commented
@liketic Thanks for the fix. In the case of Java/Groovy tests in the repo, see this page: http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html

2017-09-09 14:42 UTC, oleg-nenashev approved these changes

2017-09-09 14:44 UTC, merged