[JENKINS-45245] Start deploying war-for-test again
jenkinsci/jenkins pull request #3029
Opened 2017-09-19 18:17 UTC by abayer

See [JENKINS-45245](https://issues.jenkins-ci.org/browse/JENKINS-45245).

This is just the first part, but at the very least it'll mean that
when the rest of JENKINS-24064 gets reverted, core versions from when
this is merged onward will work with newer plugin parents/test
harness/maven-hpi-plugin/etc.

### Proposed changelog entries

* Entry 1: JENKINS-45245, start building and deploying `war-for-test` artifact again.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees

2017-09-19 18:20 UTC, jglick commented
I do not think we have finished exploring all avenues here.

2017-09-19 18:21 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-09-19 18:23 UTC, abayer commented
@jglick I respectfully disagree. If/when a solution is found that doesn't require `war-for-test`, this can always be reverted again, but I see absolutely no reason why we should keep making it a pain in the ass for people using Intellij to run unit tests in the meantime.

2017-09-19 18:24 UTC, abayer commented
Also worth mentioning that `war-for-test` is used by `gradle-jpi-plugin` too: https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy#L174

2017-09-19 18:42 UTC, svanoort approved these changes
PLEASE.

2017-09-19 18:43 UTC, svanoort commented
@jglick There's nothing stopping us from exploring avenues  at leisure once we need a working solution for developers.   Can turn this back off once that's sorted.

2017-09-19 18:51 UTC, recena commented
I understand @svanoort and @abayer, but if we want to move forward we need to adapt and change things. We had to do it https://github.com/jenkinsci/plugin-compat-tester/pull/42

2017-09-19 18:55 UTC, daniel-beck commented
@recena We cannot just fix https://youtrack.jetbrains.com/issue/IDEA-175538 ourselves.

2017-09-19 19:10 UTC, svanoort commented
What @daniel-beck said... and IntelliJ is currently the most popular Java IDE, so breaking the ability to use it with unit tests really makes it hard for new contributors to Jenkins.

Hacky workarounds and all are OK but at a minimum it needs to work.

2017-09-19 19:13 UTC, daniel-beck commented
This discussion should be continued in https://issues.jenkins-ci.org/browse/JENKINS-45245 – multiple separate PRs just fragments it.

2017-09-19 19:47 UTC, jglick requested changes
Most likely unnecessary. Should be possible to work around for IDEA, for example via https://github.com/jenkinsci/jenkins-test-harness/pull/73.

2017-09-19 19:50 UTC, jglick commented
> `war-for-test` is used by `gradle-jpi-plugin` too

Up to devs of that tool to keep up. Presumably needs some analogue of https://github.com/jenkinsci/plugin-pom/pull/65, but I do not know enough Gradle to be sure.

2017-09-19 21:07 UTC, ChrisJBurns approved these changes

2017-09-19 21:52 UTC, abayer commented
Not needed any more thanks to https://github.com/jenkinsci/jenkins-test-harness/pull/73

2017-09-19 21:52 UTC, closed without merging

2017-09-21 09:33 UTC, recena commented
@jglick AWESOME!