Avoid having "authenticated" twice in the group membership of a user (LastGrantedAuthorities)
jenkinsci/jenkins pull request #3123
Opened 2017-11-01 11:00 UTC by Wadeck

- this occur when the SecurityRealm potentially already grants that role (like in github-oauth-plugin)

See [JENKINS-47768](https://issues.jenkins-ci.org/browse/JENKINS-47768).

### Submitter checklist

- [x] JIRA issue is well described
- [x] Appropriate autotests or explanation to why this change has no tests

### Desired reviewers

@reviewbybees

2017-11-01 11:02 UTC, Wadeck commented
Instead of checking that on each "update" I think it's better to do on the information retrieval. The main advantage is that we do not bother performance for user that do not use the "cache" that is provided by LastGrantedAuthorities. I think it's the majority of cases.

2017-11-01 11:03 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-11-01 11:35 UTC, oleg-nenashev reviewed
Would it be possible to use Set or Map instead? Just to avoid N^2 complexity on this method. 

Maybe it's just better to modify the internal data structure and to use Maps in new API

2017-11-01 13:21 UTC, oleg-nenashev approved these changes

2017-11-01 13:21 UTC, oleg-nenashev commented on core/src/main/java/jenkins/security/LastGrantedAuthoritiesProperty.java
> +        List<GrantedAuthority> grantedAuthorities = new ArrayList<>();
Initialize with `roles.length`

2017-11-01 13:25 UTC, Wadeck commented on core/src/main/java/jenkins/security/LastGrantedAuthoritiesProperty.java
> +        List<GrantedAuthority> grantedAuthorities = new ArrayList<>();
changed

2017-11-01 17:38 UTC, dwnusbaum commented on core/src/main/java/jenkins/security/LastGrantedAuthoritiesProperty.java
> +                grantedAuthorities.add(new GrantedAuthorityImpl(roles[i]));
If `this.roles` is not null, but doesn't contain `SecurityRealm.AUTHENTICATED_AUTHORITY`, then `SecurityRealm.AUTHENTICATED_AUTHORITY` won't be added to the result. Unless I'm missing something I think you want to add `AUTHENTICATED_AUTHORITY` to the the list before the loop to make sure it's included, right? (And initialize the list to `roles.length + 1`).

2017-11-04 09:10 UTC, oleg-nenashev requested changes
Agreed with @dwnusbaum, the test failures are related

2017-11-06 14:17 UTC, dwnusbaum approved these changes
🐝

2017-11-10 18:16 UTC, oleg-nenashev approved these changes
🐝 and 👍 for reworking just another Groovy test

2017-11-10 18:41 UTC, oleg-nenashev commented
@reviewbybees done

2017-11-12 14:48 UTC, merged