Cache permission id to avoid allocating of new strings
jenkinsci/jenkins pull request #3155
Opened 2017-11-21 14:26 UTC by Jimilian

Every request that comes from Jelly is checked against Permissions.
As result it leads to a call of `getId` method that produces the new string.
Usually it's not a problem, but in case of stop-the-world pause user requests are accumulated.
So, once pause is finished, we forcibly allocated tons of strings for
every request. That leads to new stop-the-world pause. (And this cycle
can repeat multiple times)

Now to help Jenkins to recover we need to turn off nginx for 1 minute :(

### Proposed changelog entries

* Performance: Jenkins can recover faster after FullGC/stop-the-world pause

### Desired reviewers

@svanoort, @oleg-nenashev, @jglick, @daniel-beck 

Screenshots that show memory allocations in 1.5 seconds just after stop-the-world pause:
![screen shot 2017-11-21 at 15 12 05](https://user-images.githubusercontent.com/4785672/33077455-2e9afb76-ced0-11e7-92bb-ec62f6c8dd0c.png)
![screen shot 2017-11-21 at 15 09 33](https://user-images.githubusercontent.com/4785672/33077457-2ec52d92-ced0-11e7-9900-b9e2708c5049.png)

2017-11-21 19:32 UTC, oleg-nenashev approved these changes

2017-11-21 20:43 UTC, svanoort commented on core/src/main/java/hudson/security/Permission.java
> +        return id;
Are Permission objects ever serialized in configuration?  Generally they're statically created AFAIK but if a plugin lets you select the permission type to apply to some property (none I know of off the top of my head) then we could have cases where this is null. 

If so, we should probably check if field is non-null and fall back to old logic when null.

2017-11-21 20:46 UTC, svanoort requested changes
Great catch here @Jimilian  -- I think we do a lot of needless object allocation in Jenkins in general and removing some of that will help with performance.  Especially when the method is called frequently -- this will help with more efficient CPU cache use potentially. 

I do think we probably should include the null-check on the field though, to protect against some obscure usage that serializes a permission (maybe picking the Permission to apply for some feature from a list).  

Maybe being overly cautious here, but for pure optimizations, best to limit potential negative impact.

2017-11-21 22:51 UTC, KostyaSha approved these changes

2017-11-22 09:47 UTC, Jimilian commented
@svanoort, addressed.

2017-11-22 14:15 UTC, svanoort approved these changes
@Jimilian I LIKE IT.  Now that my one concern is addressed, let's merge this! 😄

2017-11-23 13:52 UTC, daniel-beck approved these changes

2017-11-26 09:32 UTC, merged

2017-12-03 10:38 UTC, oleg-nenashev commented
@Jimilian has created a placeholder issue for it: https://issues.jenkins-ci.org/browse/JENKINS-48349.