Add setBuildResult to ArtifactArchiver
jenkinsci/jenkins pull request #3171
Opened 2017-12-03 12:22 UTC by KieranPringle

This change is a continuation in the spirit of https://github.com/jenkinsci/jenkins/pull/732 and allows the end user to choose whether or not ArtifactArchiver is allowed to change the build status at all, putting the decision about what makes a build successful or not back under their control. This defaults to `true`, maintaining the old behaviour. 

The primary reason for this PR is that on complex pipeline builds that may have multiple places where they archive large numbers of artifacts (i.e. logs and test framework reports), the change for a rogue IOException increases. In these situations, ArtifactArchiver sets the build result to Failed without throwing an exception.  The run continues but prevents a deployment or other step in a CICD process that depends on reading the result of the previous job. In these jobs, the lack of a single log file can be annoying, but is not reason enough to mark the job as unsuccessful.

2017-12-03 20:34 UTC, oleg-nenashev requested changes
It retains the default behavior for newly created archivers, bit not for ones loaded from the disk. `setBuildResult` will be `false` in this case.

My suggestion would be to use `false` value for the old behavior

2017-12-05 07:59 UTC, daniel-beck commented
I'm 👎 on this. I don't think it is useful to work around robustness issues (that could well be caused by infra/configuration problems) by adding more options.

Artifact management in Jenkins is fairly basic, so if you're using it in a way that regularly results in IOExceptions, you should probably look into getting a dedicated tool for that, like Artifactory.

2017-12-05 10:50 UTC, KieranPringle commented
@oleg-nenashev I think it is less invasive to maintain the old behaviour, otherwise users that depend on the "old" behaviour would be in for a nasty surprise. There are definitely going to be users who depend on this plugin failing their build for them and I don't think we'd want this PR breaking that behaviour for them on an upgrade.

@daniel-beck I agree this is a workaround for a robustness issue, but should it not ultimately be the end-user's choice about what makes a job successful? I don't think it should be up to a plugin to dictate to the user what counts as their build having been successful or not. The person implementing the build process knows what they consider to be a successful job, and so they should be in control of choosing the fail the build on whether or not it meets their requirements. At least, this is my opinion on the case. I am not a long-term contributor to Jenkins so I can't comment on whether or not this goes against some higher-level Jenkins design philosophy.

I'd also argue Artifactory is not for logs or test output, it is for binaries, as are most artifact repositories. Our workflow tends to prefer our Jenkins pipeline job as a "one stop shop" for figuring out why a build was unsuccessful since this puts those output files alongside the test results published by another Jenkins plugin. Putting the log files and test reports in our binaries repository would be very much against this approach -- again, this might be against some higher-level Jenkins design approach and we could be unaware of that fact.

2017-12-05 11:04 UTC, daniel-beck commented
> should it not ultimately be the end-user's choice about what makes a job successful? I don't think it should be up to a plugin to dictate to the user what counts as their build having been successful or not. The person implementing the build process knows what they consider to be a successful job, and so they should be in control of choosing the fail the build on whether or not it meets their requirements.

This seems to argue for a general per-publisher/per-buildstep setting for how to handle failure in that step -- because why limit it to archiving artifacts? That could be useful to add some consistency for all steps, but is going to be a lot more work than this.

Going with a solution specific to archiving is how we get difficult to learn inconsistencies between different but similar features, or inexplicably limited behaviors (like recording the user who created an agent -- the only administrative action in all of Jenkins that does this).

---

I would expect Any Build Step + Conditional Build Step Plugins to help accomplish your goal in freestyle jobs.

In Pipeline, I'd hope there's an exception getting thrown you can catch to prevent build failures. If that's not the case, it should probably be filed as an issue.

2017-12-05 11:21 UTC, KieranPringle commented
@daniel-beck there is no exception thrown, so there is no control over whether the build is set as failed or not (hence this PR). If that is an issue, then should I just open another PR that instead rethrows the exception?

2017-12-05 14:29 UTC, daniel-beck commented
@KieranPringle I'm not 100% sure what the best idiom for pipeline would be, doing that via exception catching should be more natural. Invoking @jglick and @abayer.

2017-12-22 09:27 UTC, closed without merging