Add default impl. to RootAction
jenkinsci/jenkins pull request #3172
Opened 2017-12-04 10:36 UTC by Wadeck

- to ease the inner implementation that often return null

Proposed after discussion in JTH.

If this one is accepted, we can close the [#85 JTH](https://github.com/jenkinsci/jenkins-test-harness/pull/85)

@reviewbybees

2017-12-05 10:33 UTC, daniel-beck commented
Why aren't we doing that with `Action` to begin with? Perhaps we want to make the overriding explicit, but then, why is this proposing to do that with `RootAction`?

2017-12-05 12:18 UTC, Wadeck commented
@daniel-beck I changed accordingly to your comment. I am not sure if I need to push the getDisplayName default method even to the `ModelObject` (parent of `Action`) since that interface does not provide `@CheckForNull` signature.

2017-12-05 15:28 UTC, dwnusbaum submitted a review, later dismissed
🐝 I think this is preferable to the JTH PR. I'm not sure if pushing the default implementation of `getDisplayName` to `ModelObject` makes sense. The default is useful  for `Action`s since they are often invisible to the user, but I'm guessing (maybe incorrectly) that generally someone extending `ModelObject` wants to use a non-null display name.

2017-12-05 16:03 UTC, daniel-beck commented
@jenkinsci/code-reviewers I need to know the exact shade of red for this bike shed 😉 

Is there value in continuing to force people to override the two (three?) methods of Action so they're not overlooked?

2017-12-05 23:20 UTC, oleg-nenashev reviewed
No strong opinion. It simplifies the test code, but there is unlikely a case for the production one. 

* In production we do expect people to implement these methods or to use https://github.com/jenkinsci/jenkins/blob/08def67a18eee51de9f3f99bc2a792fee1c160e0/core/src/main/java/hudson/model/InvisibleAction.java.
* In tests: There is InvisibleAction.java for this case, so the tests can be simplified just by using this class.

Weak -1 regarding the change.

2017-12-06 03:45 UTC, jglick commented
> There is `InvisibleAction` for this case, so the tests can be simplified just by using this class.

Ah but all methods in `InvisibleAction` are `final`, so you cannot use it as a base class if you do actually need to implement `getUrlName`, which is fairly common.

As I wrote in https://github.com/jenkinsci/jenkins-test-harness/pull/85 and @daniel-beck echoes, I am wary of people forgetting to override methods they actually need.

Making `InvisibleAction.getUrlName` non`final` would I think be the least controversial change, and satisfy most of the use cases. For that matter, doing nothing is OK too.

2017-12-06 12:35 UTC, daniel-beck commented
> least controversial

I disagree. A visible action inheriting from `InvisibleAction` makes no sense.

2017-12-06 12:39 UTC, stephenc commented
>  A visible action inheriting from `InvisibleAction` makes no sense.

But it would be invisible as it does not have an icon or display name so there would be no *visible* link.

Now if it was called `NonNavigableAction` you would have a point, but invisible != non-navigable, just we have chosen to make `InvisibleAction` really a `InvisibleNonNavigableAction`

2017-12-06 12:40 UTC, stephenc commented
>  I am wary of people forgetting to override methods they actually need.

I am also wary... hence 👎  from my PoV to current change

2017-12-06 12:44 UTC, daniel-beck commented
@stephenc 

> But it would be invisible as it does not have an icon or display name so there would be no *visible* link.

Good point, I missed @jglick specifically referring to `getUrlName`, and this PR implements the other two. So for purposes of `getDisplayName`, `getIconFileName` this still seems unsuitable.

2017-12-07 07:11 UTC, oleg-nenashev commented
Yes, forgetting implementations was also my concern in the comment above. I'd guess there is an agreement that the change should be done in another ways. I second @stephenc and agree that a couple of new classes is feasible.

2017-12-07 07:12 UTC, oleg-nenashev requested changes
Requesting changes to follow the process

2018-01-09 10:51 UTC, oleg-nenashev commented
@Wadeck ping, there is a pending feedback. Do you plan to work on this change?

2018-02-15 14:36 UTC, Wadeck commented
@stephenc @oleg-nenashev I proposed a new approach based on a new class to not confuse user as discussed. I am not totally satisfied with the name `DefaultRootAction`, since the default comes from the default methods in the interface and not to be meant as "default rootAction". So if you have a good idea, I will take it.

(AbstractRootAction seems not really consistent with the use of an interface)

2018-02-20 18:44 UTC, dwnusbaum reviewed
I think rather than a new interface it would be preferable to make `InvisibleAction#getUrlName` non-final and have the test classes extend `InvisibleAction` and implement `RootAction` as discussed previously.

It seems like there aren't a ton of implementations that could be cleaned up by this change, so it might not be worth the work necessary to get everyone to agree. 😄

2018-02-22 21:11 UTC, jglick commented
Urgh, [looks](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-3172/3/testReport/junit/org.jvnet.hudson.test/BuildTriggerTest/Windows___Windows_Publishing___testSomething/) like #3168 did not work.

2018-02-22 21:18 UTC, jglick reviewed
I still feel like this is more noise than signal and it would be more intuitive to make `InvisibleAction.getUrlName` non`final` (and also useful for other kinds of `Action`s), but I do not have a strong opinion.

2018-02-22 21:18 UTC, jglick commented on core/src/main/java/hudson/model/DefaultRootAction.java
> + *
maybe `@see` from `InvisibleAction`

2018-02-22 21:29 UTC, jglick commented
> did not work

Never mind, you just need to `git merge master` to bring this up to date.

2018-02-23 10:14 UTC, Wadeck commented
Following advice from Devin + Jesse, `InvisibleAction#getUrlName` made final

2018-03-04 00:03 UTC, oleg-nenashev requested changes
IMHO it violates the `InvisibleAction` documentation: "Partial {@link Action} implementation that doesn't have any UI presence.". Apparently the refactored methods have such UI presence since you have to override the method

2018-03-07 23:04 UTC, oleg-nenashev approved these changes
weak 🐝

2018-04-28 19:00 UTC, daniel-beck approved these changes
:shipit:

2018-04-28 19:00 UTC, daniel-beck commented on core/src/main/java/hudson/model/InvisibleAction.java
> + * Partial {@link Action} implementation that doesn't have any UI presence (unless the {@link #getUrlName()} is overrided).
This seems slightly confusing as just having a URL does not make for a UI presence, at least not in the most direct sense of having a presence on a side panel.

2018-04-28 19:07 UTC, daniel-beck commented on core/src/main/java/hudson/model/InvisibleAction.java
> + * Partial {@link Action} implementation that doesn't have any UI presence (unless the {@link #getUrlName()} is overrided).
In a way I'm contradicting what @oleg-nenashev wrote in his older comment. It really depends on what "UI presence" means. Perhaps just clarify that there can be a URL space with views etc., but there cannot be a presence in a sidepanel?

I guess unless you override `action.jelly` or what it's called. Well…

Let's just merge as is, any second spent on this is wasted.

2019-01-27 16:21 UTC, oleg-nenashev commented
It was stalled for almost 6 months without new reviews. Taking the positive feedback in the latest comments, merging it

2019-01-27 16:21 UTC, merged