Correction of quote for French + space before colon
jenkinsci/jenkins pull request #3179
Opened 2017-12-08 09:27 UTC by Wadeck

- correction of a `\'` in french
- add a space before `:`, in english only one space after, in french one before and one after

As the colon moved from HTML to translation, I let original translator validates the addition of colon in their language.
@alshopov for bulgarian translation (according to [Microsoft Bulgarian Style Guide](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwih5NrfivrXAhWFPxoKHcMlDkkQFggnMAA&url=http%3A%2F%2Fdownload.microsoft.com%2Fdownload%2Fa%2F2%2F9%2Fa29902cc-41c0-4ceb-a6ed-ba16bc511e15%2Fbul-bgr-styleguide.pdf&usg=AOvVaw2TnsdLGRd8mrTc3waBIlJj) it's like in english)
@tomas for lithuanian translation (nothing special mentioned in [Microsoft Lithunian Style Guide](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjM-IrEi_rXAhWKfxoKHZKwALYQFggvMAE&url=http%3A%2F%2Fdownload.microsoft.com%2Fdownload%2Fd%2F9%2Fb%2Fd9b3b746-78ec-4049-bc43-c0f744199f71%2Flit-ltu-StyleGuide.pdf&usg=AOvVaw1kRbldbyOy83vobZySPtYX), so like english ?)
@damianszczepanik for polish translation (according to [Microsoft Polish Style Guide](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwi4uIX_i_rXAhXGMBoKHSzZAC0QFggtMAE&url=http%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F3%2Fe%2F6%2F3e688569-1e3f-48a4-a33c-07e6daaa57b4%2Fpol-pol-StyleGuide.pdf&usg=AOvVaw30jwInULP3yzHI7BtbgpMb) it's like in english)

@reviewbybees

2017-12-08 17:39 UTC, alecharp requested changes

2017-12-08 17:39 UTC, alecharp commented on core/src/main/resources/hudson/model/View/newJob_fr.properties
> +ItemType.validation.required=Veuillez choisir un type d\u2019Item
maybe we can translate "Item" as well

2018-01-02 08:33 UTC, alecharp approved these changes
LGTM :bee:

2018-01-02 08:35 UTC, Wadeck commented
@reviewbybees done

2018-01-02 13:35 UTC, oleg-nenashev commented
Hmm, it impacts other translations as well. 
Let's wait for responses from CCed translation contributors

2018-01-03 12:59 UTC, damianszczepanik commented
As I see the colon has been moved from template to translations so it should not have impact for translations that were updated (hopefully all). So for Polish translation - fix is fine.

2018-01-03 13:02 UTC, Wadeck commented
@damianszczepanik yeah all the translations where I can read the characters that have a colon were updated (and CC in the description)
Thank you for the review 👍

2018-01-03 13:35 UTC, damianszczepanik approved these changes

2018-01-06 16:30 UTC, merged