[JENKINS-48831] New/fixed version of js-lib core-asset modules
jenkinsci/jenkins pull request #3215
Opened 2018-01-06 08:11 UTC by tfennelly

See [JENKINS-48831](https://issues.jenkins-ci.org/browse/JENKINS-48831).

Depends on https://github.com/jenkinsci/js-libs/pull/4

@jenkinsci/code-reviewers @reviewbybees

2018-01-08 16:47 UTC, jglick commented
Not a werk-in-progress merely because it might need snapshot dependency updates; that is something that can be done by a merger.

2018-01-08 17:28 UTC, jglick commented on war/pom.xml
> +    <js.libs.version>2.0.0-SNAPSHOT</js.libs.version>
Suggest `js-libs.version` to match repo name.

2018-01-08 17:50 UTC, daniel-beck commented
On-holding until upstream release.

2018-01-11 18:47 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2018-12-10 23:52 UTC, daniel-beck commented
@tfennelly Do you plan to finish this? I think there's no release of the dependency yet?

2019-01-28 20:20 UTC, oleg-nenashev requested changes

2019-01-28 20:20 UTC, oleg-nenashev commented on war/pom.xml
> +    <js-libs.version>2.0.0-SNAPSHOT</js-libs.version>
It has not been released so far

2019-02-20 12:41 UTC, closed without merging