[FIXED JENKINS-45235] When multiple update sites publish different versions, allow those versions to be seen
jenkinsci/jenkins pull request #3269
Opened 2018-01-26 11:40 UTC by stephenc

- When automatically installing dependent plugins, the first update center with a version meeting the minimum required will win
- Also enhances the CLI command to allow specification of a minimum version

See [JENKINS-45235](https://issues.jenkins-ci.org/browse/JENKINS-45235).

### Proposed changelog entries

* When Jenkins has multiple update sites, the plugins listed were de-duplicated, however this could hide updated versions being published by the second or subsequent update sites, now multiple versions of plugins will be shown when the update sites are publishing different versions.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
    * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
    * Very tricky to write a test for this, requires multiple update sites with different plugin versions. Manually verified the functionality. Existing test cases should cover the single update site case for the 90%+ of users
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@daniel-beck this should fix the issue I described and help testing of plugin security releases

2018-06-15 02:08 UTC, dongsik2026 commented on core/src/main/java/hudson/model/UpdateCenter.java
> +        for (UpdateSite s : sites) {
Good use of foreach statement!

2018-06-15 02:10 UTC, dongsik2026 requested changes

2018-06-15 02:10 UTC, dongsik2026 commented on core/src/main/resources/hudson/PluginManager/_table.js
> +                    console.log(name);
why do not use the logger?

2018-11-16 19:21 UTC, daniel-beck commented
Tests report NPEs in `UpdateCenter.getPlugin`

2018-11-17 20:36 UTC, stephenc commented
@daniel-beck so remaining test failure seems unrelated: a job rename ath only on firefox

2018-11-19 13:35 UTC, merged