Improve dutch translation
jenkinsci/jenkins pull request #3323
Opened 2018-03-04 17:15 UTC by Ka-Wing

See [JENKINS-49901](https://issues.jenkins-ci.org/browse/JENKINS-49901).

Issue should say enough. As these are text translations, I don't think tests are needed.
I am a native speaker by the way.

### Proposed changelog entries

* Improved Dutch translation.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

Dutch natives.

2018-03-04 17:25 UTC, oleg-nenashev commented
CC @vStone who may be interested (https://github.com/jenkinsci/jenkins/pull/3286)

2018-03-07 01:34 UTC, oleg-nenashev commented
@lange88 are you fine with the changes?

2018-03-07 08:39 UTC, vStone requested changes
I've went through it, finally. some remarks added.

2018-03-07 08:39 UTC, vStone commented on core/src/main/resources/hudson/util/IncompatibleServletVersionDetected/index_nl.properties
> +  Blijkbaar ondersteunt uw servletcontainer de servlet versie 2.4 niet!\
`Blijkbaar` bugs me here. `We merken dat` ?

2018-03-07 08:39 UTC, vStone commented on core/src/main/resources/hudson/util/NoTempDir/index_nl.properties
> +Bestaat deze map?  Is deze map beschrijfbaar door de gebruiker\
`beschrijfbaar` -> `wijzigbaar`

2018-03-07 08:39 UTC, vStone commented on core/src/main/resources/jenkins/model/Jenkins/projectRelationship-help_nl.properties
> +For\ this\ feature\ to\ work,\ the\ following\ conditions\ need\ to\ be\ met\:=De volgende voorwaarden dient voldaan te worden om met deze functionaliteit te werken:
`De volgende voorwaarden dienen voldaan...`

2018-03-07 08:39 UTC, vStone commented on core/src/main/resources/lib/hudson/project/config-publishers_nl.properties
> +Post-build\ Actions=Acties voor na de bouwpoging
`Acties uit te voeren na de bouwpoging`

2018-03-07 08:39 UTC, vStone commented on core/src/main/resources/lib/hudson/project/config-publishers2_nl.properties
> +Post-build\ Actions=Acties voor na de bouwpoging
`Acties uit te voeren` na / voor `de bouwpoging`

2018-03-07 08:39 UTC, vStone commented on core/src/main/resources/lib/layout/breadcrumbBar_nl.properties
> +ENABLE\ AUTO\ REFRESH=Automatisch vernieuwen inschakelen
Capitalization should match original string

2018-03-07 13:37 UTC, Ka-Wing commented on core/src/main/resources/hudson/model/Fingerprint/index_nl.properties
> +This\ file\ has\ been\ used\ in\ the\ following\ places=Dit bestand is volgende plaatsen gebruikt.
Yeah, should be "Dit bestand is op de volgende plaatsen gebruikt.".

2018-03-07 22:23 UTC, Ka-Wing commented on core/src/main/resources/hudson/model/Run/logKeep_nl.properties
> +Keep\ this\ build\ forever=Bewaar deze Build voor altijd.
Indeed, I have overlooked it. I have changed it to "bouwpoging"

2018-03-07 22:30 UTC, Ka-Wing commented
@vStone I have made changes according to your suggestions. Can you check them again please?

2018-03-08 09:21 UTC, lange88 commented
Changes look good @Ka-Wing @oleg-nenashev

2018-03-09 15:31 UTC, vStone approved these changes
👍

2018-03-10 15:56 UTC, merged

2018-03-10 15:56 UTC, oleg-nenashev commented
Thanks a lot @Ka-Wing @lange88 @vStone !

2018-03-10 23:34 UTC, Ka-Wing commented
@oleg-nenashev You are welcome. I am happy to be able to help.