Update triggerRemotely documentation
jenkinsci/jenkins pull request #3331
Opened 2018-03-07 10:47 UTC by shanx

It took me quite a while to find out that the trigger endpoint doesn't work when anonymous users don't have read access, even though you use a special authentication token. With this update to the docs I hope to prevent others from falling into this trap.

2018-03-07 10:56 UTC, oleg-nenashev submitted a review, later dismissed
Looks reasonable, just a minor URL change is needed

2018-03-07 10:56 UTC, oleg-nenashev commented on war/src/main/webapp/help/project-config/triggerRemotely.html
> +  <a href="https://wiki.jenkins.io/display/JENKINS/Build+Token+Root+Plugin" target="_blank">
Please link the plugin page on https://plugins.jenkins.io/ instead of Wiki

2018-03-07 14:09 UTC, shanx commented
Good point just updated the link! Thanks for picking up on this so quickly!

2018-03-07 14:16 UTC, daniel-beck requested changes
Not strictly true, as scripts can just run with an authentication (HTTP Basic) that has Read permission, then use the remote trigger token.

Of course, then the question is why not just grant build permission, so continuing to mention Build Token Root Plugin makes sense.

2018-03-07 19:07 UTC, shanx commented
@daniel-beck what do you want me to do? I don't really see an actionable item in your review?

2018-03-08 16:28 UTC, daniel-beck commented
@shanx How about phrasing it something like this?

> This is most useful when your Jenkins instance grants read access to this job to anonymous users.
> When that's not the case, Jenkins will reject requests sent to the trigger URL even when the correct token is specified.
>
> To solve this, the HTTP requests needs to be authenticated as a user with the necessary read permission for the job -- but then you could probably just grant this user the permission to build this anyway.
> 
> Another option is to use the Build Token Root Plugin, that provides additional URL endpoints to trigger builds using this token, and doesn't require the otherwise necessary Overall/Read and Job/Read permissions to do so.

Basically, there are two options, given them roughly equal space.

2018-04-14 21:14 UTC, oleg-nenashev commented
@shanx Do you plan to address @daniel-beck's comment? It's almost there from what I see

2018-12-10 23:50 UTC, daniel-beck commented
Superseded by https://github.com/jenkinsci/jenkins/pull/3801

2018-12-10 23:50 UTC, closed without merging