WIP: Moves XmlFile into hierarchy XmlFileStorage -> FileStorage -> Storage.
jenkinsci/jenkins pull request #3393
Opened 2018-04-14 12:36 UTC by deepy

### Proposed changelog entries

* Moves some XmlFile methods to into the interfaces FileStorage and Storage.
This is to provide a foundation to start adding an extension point for storage.

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

2018-04-14 17:22 UTC, oleg-nenashev requested changes
In the current state it breaks binary compatibility. Although I understand the idea, it needs to be well described and justified if you really need to break the compatibility.

P.S: According to my experience in the Pluggable Storage area, binary compatibility could be retained by deprecating old methods and creating new ones.

2018-06-15 10:33 UTC, oleg-nenashev commented
I have a similar use-case, and I will probably provide an alternate implementation

2018-06-15 10:38 UTC, oleg-nenashev commented
https://issues.jenkins-ci.org/browse/JENKINS-51966

2018-08-08 10:19 UTC, oleg-nenashev commented
I have submitted a JEP proposal to unblock it: https://github.com/jenkinsci/jep/pull/172

2019-01-28 17:36 UTC, oleg-nenashev commented
@deepy Hi. Are you still interested to finalize it?

2019-04-04 14:13 UTC, batmat commented
Hello @deepy, in agreement with @daniel-beck we are closing this PR given the previous comments, and the current conflicted state.

If you are willing to look into this again, please feel 100% free to comment here anytime, and we will be able to reopen for you as needed.

Thank you again for your work!

2019-04-04 14:13 UTC, closed without merging