Add new permission for REST API
jenkinsci/jenkins pull request #3469
Opened 2018-05-31 21:58 UTC by daniel-beck

Make it easier to provide Jenkins REST API access to those who legitimately need it, while disabling it for others.

Basically, implement https://github.com/jenkins-infra/jenkins-infra/pull/1006 in core.

There's a potential scope definition problem that I tried to address in the description: `/createItem` is still accessible, and only covered by Item/Create. In fact, some endpoints, such as `/job/name/description` are pure API, and not governed by separate permissions (beyond Item/Read).

Still, I think it makes sense to add a REST API permission for the `…/api/…` URLs specifically.

WDYT?

Untested.

2018-06-01 07:49 UTC, oleg-nenashev commented on core/src/main/java/jenkins/model/Jenkins.java
> +    public static final Permission REST_API = new Permission(PERMISSIONS, "RestApi", Messages._Jenkins_RestApiPermission_Description(), ADMINISTER, PermissionScope.JENKINS);
`READONLY_REST_API` ?

2018-06-01 07:50 UTC, oleg-nenashev commented
Looks good as idea. Maybe we need to review all APIs and set these permission checks in other places

2018-06-01 11:15 UTC, Wadeck approved these changes
:bee: seems promising, nice idea!

2018-06-01 13:03 UTC, daniel-beck commented
> Maybe we need to review all APIs and set these permission checks in other places

The permission would only be effective on specific APIs that opt in to it. I have no idea, for example, how to get plugins on board for their various API like endpoints.

To increase consistency I opted for this rather narrow scope, and let other APIs be governed by appropriate Configure/Delete/… permissions.

2018-06-01 14:14 UTC, daniel-beck commented
Notably, `/api` does something unique, while other endpoints would just be replaced by bad browser imitation, like people already do for features lacking from the `/buildWithParameters` API.

2018-06-04 11:07 UTC, amuniz commented
How is this different from `Jenkins.READ`? I see it only applies to the WS API, but still, if an administrator wants a user to access Jenkins in read-only mode it does not matter if it's to the WS API only or also to the UI.

2018-06-04 17:04 UTC, jglick requested changes
I think this is a bad idea. Implies that there is something about REST access which in intrinsically less safe than UI access, which is not true. We should be working to simplify the Jenkins permissions model to its essential features, not make it more complex.

The PR you refer to was a compromise—better than that having no REST access whatsoever, which were the only options offered by the admin. If you want to simulate that somehow, which I would be merely -0 on if it were implemented as a plugin with a `ServletFilter`, then make it so that Stapler responses which are neither HTML nor resources (CSS, JS, images) require BASIC authentication to be defined.

2018-06-05 16:09 UTC, rtyler commented
@jglick From my perspective, the REST APIs _are_ intrinsically less safe, largely due to the `?depth=∞` parameter. The param makes it very easy to exhaust resources on a Jenkins instance (either maliciously or through incompetence), in a way which requires much less effort on the attacker's side than if they were to only hit the web UI.

(as an aside, my understanding of some of the work recently for the incrementals publisher was that it is possible for Jenkins to provide information via the APIs that is not presented through a rendered web UI)

I applaud @daniel-beck's effort at trying to introduce something that addresses this problem. I can imagine an extra permission would give administrators a bit more flexibility even if they're not considering abusive scenarios like those we have experienced on [ci.jenkins.io](https://ci.jenkins.io).

2018-11-27 21:11 UTC, rtyler commented
As far as I can tell, this pull request is totally stalled. I'm going to close this, it can be re-opened in the future if there is any change here.

2018-11-27 21:11 UTC, closed without merging