Tie alt to manage object icon object class
jenkinsci/jenkins pull request #3498
Opened 2018-06-15 21:23 UTC by jsoref

The jelly is designed to give reasonable alt text. What's present now is actually worse than nothing.

```
<a href="configure" title="Configure System"><img src="/static/f12bd9f6/images/48x48/gear2.png" alt="manage-option" class="icon" /><dl><dt>Configure System</dt><dd>Configure global settings and paths.</dd><dd></dd></dl></a></div><div class="manage-option">
  |  
  | <a href="configureSecurity" title="Configure Global Security"><img src="/static/f12bd9f6/images/48x48/secure.png" alt="manage-option" class="icon" /><dl><dt>Configure Global Security</dt><dd>Secure Jenkins; define who is allowed to access/use the system.</dd><dd></dd></dl></a></div><div class="manage-option">
```

A screen reader will offer `manage-option Configure System` and `manage-option Configure Global Security`. A human will see `gear Configure System` and `lock Configure Global Security`. Having the screen reader read `manage-option` repeatedly is actually worse than not having it read anything at all. And since the links are reasonably described...

That said, it seemed worth trying to express the spirit of the icons.

2018-06-19 09:46 UTC, daniel-beck commented
Since the file names are frequently useless I wonder whether we could just empty the `alt` and done.

2018-06-19 12:01 UTC, jsoref commented
I'm happy to do that.

2018-06-23 21:31 UTC, oleg-nenashev approved these changes
I am fine with the current approach. Leaving text empty is fine as well IMHO.

CC @recena who is the author of the new design

2018-06-23 23:06 UTC, daniel-beck approved these changes

2018-06-23 23:07 UTC, daniel-beck commented
Would prefer empty since it doesn't add anything, but either works.

2018-06-29 12:32 UTC, daniel-beck requested changes

2018-06-29 12:32 UTC, daniel-beck commented on core/src/main/resources/jenkins/model/Jenkins/manage.jelly
>          <j:set var="icon" value="${m.iconClassName != null ? m.iconClassName : m.iconFileName}" />
`getIconFileName` is `@CheckForNull`, so the line below could through NPEs I think.

2018-06-29 12:33 UTC, daniel-beck commented on core/src/main/resources/jenkins/model/Jenkins/manage.jelly
>          <j:if test="${icon!=null}">
Null test right here, so just needs to be in this block.

2018-07-05 19:55 UTC, jsoref commented on core/src/main/resources/jenkins/model/Jenkins/manage.jelly
> +          <j:set var="alt" value="${icon.replaceAll('\\d*\\.[^.]+$', '')} />
@daniel-beck : sorry, code updated by moving within the null check...

2018-07-06 09:35 UTC, recena approved these changes

2018-07-06 09:40 UTC, recena commented on core/src/main/resources/jenkins/model/Jenkins/manage.jelly
> +                <img class="icon" src="${iconUrl}" alt="[${%alt}]"/>
Given to the size of the images is known, I would add the attributes `width` and `height`.  [Ref](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML)

2018-07-06 10:52 UTC, daniel-beck approved these changes

2018-07-07 10:06 UTC, oleg-nenashev commented
@daniel-beck @jsoref Closing quote was missing. I have added it and retriggered CI. Please do not merge it until it passes

2018-07-10 20:33 UTC, jsoref commented
@oleg-nenashev: thanks

2018-07-12 20:11 UTC, daniel-beck commented
Un-onholding this due to build passing.

2018-07-14 14:55 UTC, merged