Fix JENKINS-52181 about permission issue when using cli to get console
jenkinsci/jenkins pull request #3527
Opened 2018-06-27 09:27 UTC by ericyu2018

Fixed https://issues.jenkins-ci.org/browse/JENKINS-52181 about issue when using jenkins-cli to get console of a project requires user has Job/Build permission as per guidance from Oleg Nenashev.

2018-06-27 13:02 UTC, ericyu2018 commented
I see test case https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-3527/1/tests failed.

Could you please help to advise if the following test case in  test\src\test\java\hudson\cli\ConsoleCommandTest.java should be removed?

@Test public void consoleShouldFailWithoutItemBuildPermission() throws Exception

{ j.createFreeStyleProject("aProject"); final CLICommandInvoker.Result result = command .authorizedTo(Jenkins.READ, Job.READ) .invokeWithArgs("aProject"); assertThat(result, failedWith(6)); assertThat(result, hasNoStandardOutput()); assertThat(result.stderr(), containsString("ERROR: user is missing the Job/Build permission")); }

2018-06-27 13:15 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers It would be great to get feedback regarding the patch feasibility. Changing permission looks good to me (see JIRA), but maybe I am missing something

2018-07-07 09:55 UTC, oleg-nenashev requested changes
Since there is no other feedback from @jenkinsci/code-reviewers , I +1 this change. Please adjust the tests so that the build is passing

2018-07-07 12:45 UTC, ericyu2018 commented
Removed invalid test case consoleShouldFailWithoutItemBuildPermission() and now the build can pass.

2018-07-07 12:59 UTC, oleg-nenashev approved these changes
It would be preferable to invert the test and to ensure it passes, but fine with me

2018-07-07 18:06 UTC, daniel-beck requested changes
Test should be retained with fixed assertion.

2018-07-14 14:58 UTC, oleg-nenashev commented
@ericyu2018 Would it be possible to address feedback from @daniel-beck ?

2018-07-28 21:22 UTC, oleg-nenashev commented
Ping @ericyu2018

2018-07-31 07:48 UTC, oleg-nenashev commented
@daniel-beck I have added a test here

2018-08-18 08:55 UTC, oleg-nenashev commented
Hmmm

```
Expected: Exited with 0 return code
but: CLI command exited with 4
STDERR:
ERROR: Permalink lastBuild produced no build
```

2018-08-18 18:14 UTC, oleg-nenashev commented
@daniel-beck I propose to merge it, test was fixed

2018-08-18 21:39 UTC, daniel-beck commented
@oleg-nenashev Would resolution of CLI args make it cumbersome to have a test confirming the log isn't accessible without Job/Read (but perhaps Job/Discover)? If not, that would be really nice to have.

2018-08-19 11:34 UTC, oleg-nenashev commented
@daniel-beck `consoleShouldFailWithoutJobReadPermission()` already checks the case when there is no permissions. `Job/Discover` will definitely fail in the current code, I will check whether it worth adding a test for it

2018-08-19 13:32 UTC, daniel-beck approved these changes

2018-08-19 13:32 UTC, daniel-beck commented
@oleg-nenashev Thanks, had just looked at the diff and missed that.

2018-08-19 13:37 UTC, merged