If copy of artifact with attributes throws error, retry without attributes
jenkinsci/jenkins pull request #3537
Opened 2018-07-04 00:22 UTC by zbynek

See [JENKINS-52325](https://issues.jenkins-ci.org/browse/JENKINS-52325).
Catch error when copying files. After first file fails, retry this file without COPY_ATTRIBUTES flag and copy further files also without this flag (to avoid copy - fail - rollback - retry cycles)

### Proposed changelog entries

* Entry 1: Internal: when archiving artifacts, handle the case when Jenkins can copy files but cannot change attributes like modification time.

### Desired reviewers

@jvz

2018-07-04 09:29 UTC, daniel-beck commented on core/src/main/java/hudson/FilePath.java
> +                                exceptionEncountered = true;
Great opportunity for a log message telling users that their terrible setup prevents this (or perhaps only if the alternative operation is successful for the first time).

Also, would prefer the exception not be discarded. If in doubt, log `FINE`.

2018-07-04 10:46 UTC, zbynek commented on core/src/main/java/hudson/FilePath.java
> +                        if(exceptionEncountered) {
we need to reach this branch when exception is thrown for the first time, so `else` won't work

2018-07-04 17:36 UTC, jvz requested changes
It might be cleaner to refactor this copy-retry for a single file into another method. Something like `static Optional<IOException> tryCopyWithAttributes(...)` maybe? And I agree with @daniel-beck about logging the bad configuration, especially if there's a link to docs or something. :)

2018-07-05 09:32 UTC, daniel-beck commented
> It might be cleaner to refactor this copy-retry for a single file into another method.

AFAIUI this deliberately implements the optimization to only try once to copy attributes per call. Taking this into consideration I doubt it'd be much nicer that way.

2018-07-05 14:57 UTC, jvz commented
Oh right, good point. No need to refactor that. Would just like the exception logged.

2018-07-07 17:17 UTC, zbynek commented
I've added some log messages. Are any other changes needed?

2018-07-07 18:21 UTC, jvz approved these changes
Looks good to me!

2018-07-07 21:45 UTC, daniel-beck commented on core/src/main/java/hudson/FilePath.java
> +                                    "Attributes removed when copying to {0}, please make sure Jenkins process owns the directory.",
I don't know. It's certainly fairly spammy output in configurations that are affected. OTOH there's somewhat broken behavior as a result. Let's see what others think.

2018-07-12 21:17 UTC, daniel-beck approved these changes
This looks reasonable. We can always adjust log level based on user feedback.

2018-07-12 21:47 UTC, oleg-nenashev approved these changes
The solution looks good though having private methods in anonymous classes is quite exotic IMHO

2018-07-13 10:53 UTC, merged

2018-07-13 10:54 UTC, oleg-nenashev commented
Thanks @zbynek ! It should land in the next weekly release