Add content doc for split plugins resource file
jenkinsci/jenkins pull request #3538
Opened 2018-07-05 17:28 UTC by daniel-beck

Written based on https://jenkins.io/changelog/#v2.112 and https://jenkins.io/changelog/#v2.86

Weirdly enough, https://github.com/jenkinsci/jenkins/blob/d041df95f9e6844e530192c12e626506d514e3b8/core/src/main/java/hudson/ClassicPluginStrategy.java#L387 seems to contradict that. AFAIUI, those plugins were split off when core was 2.86-SNAPSHOT and 2.112-SNAPSHOT, respectively, so seem to be one off in the resource file (as the linked comment seems to say these should be 2.85 and 2.111 per https://github.com/jenkinsci/jenkins/blob/d041df95f9e6844e530192c12e626506d514e3b8/core/src/main/java/hudson/ClassicPluginStrategy.java#L440)?

Hoping to get some clarity from reviewers here.

2018-07-09 21:07 UTC, jglick reviewed
I really cannot remember now. Seems that @dwnusbaum dug into it.

2018-07-09 22:40 UTC, daniel-beck commented
@dwnusbaum 

> I tried looking through the old changelog entries (as a proxy for lack of git tags for old versions, although maybe there is a better way)

Not sure what you mean. We have tags back to 1.312, which covers all but two detachments. The format changed multiple times though before settling to the current one in `jenkins-1.416`, consult any really old commit to see the tags listed at the top, e.g. d4c6a4b06cb5aa6823ed0b5fb3a6e11abb1d2029

2018-07-11 04:20 UTC, dwnusbaum commented
@daniel-beck Sorry, I think it was just user error since it looks like the GitHub tag dropdown only includes some of the tags (maybe the 100 most recent tags?). I should be able to look into this next week to figure out exactly which detached plugins are off-by-one if we want to fix them retroactively, although I'd need to spend some time thinking about the implications of doing that.

2018-07-21 00:02 UTC, dwnusbaum commented
I found the commit that removes each plugin, and listed them in the table below. It looks like Kohsuke and Oliver listed the last core version containing the split plugin's code in split-plugins.txt (except for the very first split plugin), and everyone else listed the first core version no longer containing the split plugin's code.

In the table, plugins should have the second column be the version before the last column. Off-by-one plugins have the same version in both columns.

Based on this all split plugins after and including matrix-auth are off by one. My vote would be to document that all of those plugins are off-by-one, and say that they should list the immediately prior version, but not bother changing the versions in the file since there is no serious issue with being off-by-one AIUI.

Plugin | Core version in split-plugins.txt | First core version with code removed
-- | -- | --
maven-plugin | 1.296 | tags don't go back far enough
 subversion | 1.310 | tags don't go back far enough
cvs | 1.340 | [1.340](https://github.com/jenkinsci/jenkins/commit/2960fea44bfda9a2bd2a8d23b99cfdbd33f55aaf) (but the history is a little confusing, would be great for someone to double-check)
ant | 1.430 | [1.431](https://github.com/jenkinsci/jenkins/commit/ce2be81243aa2044cda16e2b2020c0c947eb8dc8) 
javadoc | 1.430 |  [1.431](https://github.com/jenkinsci/jenkins/commit/778fff9cd1e8ea1f8416e2afc95bdea5a1bbc195) 
external-monitor-job | 1.467 | [1.468](https://github.com/jenkinsci/jenkins/commit/903bf089b7cc7eb45492344532df76676b3f9bdf)
ldap | 1.467 | [1.468](https://github.com/jenkinsci/jenkins/commit/9b4cd99620ae0eb6af8c98df4356734889ba7844) 
pam-auth | 1.467 | [1.468](https://github.com/jenkinsci/jenkins/commit/f98c9fb41370e3460367c96d698217bf4f9f86de)
mailer | 1.493 | [1.494](https://github.com/jenkinsci/jenkins/commit/fd3ee4a4d80945bff189e50bd09626aab36741da)
**subsequent plugins are off-by-one** | | 
matrix-auth | 1.535 | [1.535](https://github.com/jenkinsci/jenkins/commit/b0ac41c3b1e62b526365a1c7325abd2771316064)
windows-slaves | 1.547 | [1.547](https://github.com/jenkinsci/jenkins/commit/2669e4a86d72f2d8b67417812db8f52aa487f3de)
antisamy-markup-formatter | 1.553 | [1.553](https://github.com/jenkinsci/jenkins/commit/b2c69b4a355b47f6da400a21173680daea4f6a4c)
matrix-project | 1.561 | [1.561](https://github.com/jenkinsci/jenkins/commit/6883b915239b7a8e46b5376f65353c85d3e482c7)
junit | 1.577 | [1.577](https://github.com/jenkinsci/jenkins/commit/16197ea502bc2f370f70b65242b9ccb2f0583372)
bouncycastle-api | 2.16 | [2.16](https://github.com/jenkinsci/jenkins/commit/3e72adafeb006ee4f557365291a15d309a68d801)
command-launcher | 2.86 | [2.86](https://github.com/jenkinsci/jenkins/commit/d292929502f88c9839c8d7ffaa337586052312df)
jdk-tool | 2.112 | [2.112](https://github.com/jenkinsci/jenkins/commit/f0819d2585bdf212ca1928146d1fa8e50cc3025c)

2018-07-21 00:09 UTC, dwnusbaum requested changes

2018-07-21 00:09 UTC, dwnusbaum commented on core/src/main/resources/jenkins/split-plugins.txt
> +# Columns are: plugin ID, first core release without the plugins' functionality, plugin version that's implied
Based on my investigation I think this should be changed to something like: 

> \# Columns are: plugin ID, last core release still containing the plugin's functionality, plugin version that's implied. 
> \# Note that all listed plugins between and including matrix-auth and jdk-tool incorrectly use the first core release without the plugin's functionality when they should use the immediately prior release.

2018-07-23 14:41 UTC, dwnusbaum approved these changes
Looks good to me, thanks for adding the documentation!

2018-07-28 21:03 UTC, oleg-nenashev approved these changes

2018-07-28 21:03 UTC, merged