Add java.time.Ser to security whitelisted classes
jenkinsci/jenkins pull request #3542
Opened 2018-07-09 15:49 UTC by ValHaris

When transmitting objects of the new time api (introduced with Java 8) between slave and master, java.time.Ser is used in the serialization process.

2018-07-10 11:16 UTC, oleg-nenashev requested changes
Hi, thanks for the pull request!

In order to get this request reviewed, there should be a Jenkins JIRA ticket documenting the issue and the use-case. Without that such whitelist addition is not justified

See https://jenkins.io/blog/2018/03/15/jep-200-lts/#reporting-jep-200-issues

2018-07-13 10:52 UTC, oleg-nenashev approved these changes
The class is specifically designed for serialization according to http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/time/Ser.java

Permitting it looks good to me. Note that the class contains an "Object" field, so it will be a responsibility of the API user and implementation to use it correctly

CC @jglick

2018-07-13 10:52 UTC, oleg-nenashev commented
https://issues.jenkins-ci.org/browse/JENKINS-52534

2018-07-13 10:57 UTC, daniel-beck commented
Does this actually fix the observed problem? Given the object field, we need to add all of `Duration` etc. also to the permitted types, right?

2018-07-14 14:53 UTC, merged

2018-07-14 14:53 UTC, oleg-nenashev commented
Thanks @ValHaris !