Customly updated data is not retrieved anymore.
jenkinsci/jenkins pull request #3560
Opened 2018-07-24 15:54 UTC by varyvol

Automated test that proves a functionality that was lost with [7bd6d1e80c40fc2117ab713bd9e3d9e7707dd394](https://github.com/jenkinsci/jenkins/commit/7bd6d1e80c40fc2117ab713bd9e3d9e7707dd394).

How to fix the issue is unclear.

2018-07-24 16:20 UTC, oleg-nenashev approved these changes

2018-07-25 17:52 UTC, jglick reviewed
Seems like the clean fix would be for `UpdateSite.updateData` to become `protected`. IIUC the current `UpdateSite` subclass motivating this issue uses Java reflection, which is obviously not something we can support across refactorings.

As a workaround with current core versions, it seems like it would suffice to call `doInvalidateData()`.

2018-07-25 17:52 UTC, jglick commented on test/src/test/java/hudson/model/UpdateSiteTest.java
> +    public void updateSiteWithCustomUpdateNowUpdatesData() throws IOException {
Currently fails with

```
org.junit.ComparisonFailure: expected:<1.[2]> but was:<1.[1]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at hudson.model.UpdateSiteTest.updateSiteWithCustomUpdateNowUpdatesData(UpdateSiteTest.java:147)
```

so it should be `@Ignore`d with a note to that effect.

2018-07-25 17:52 UTC, jglick commented on test/src/test/resources/hudson/model/custom-update-center-0.json
> +{"connectionCheckUrl":"http://www.google.com/","core":{"buildDate":"Feb 24, 2014","name":"core","sha1":"EE4zpzxQOIpvdBU9DsHc32E342g=","url":"http://updates.jenkins-ci.org/download/war/1.552/jenkins.w
Maybe write a minimal JSON just mentioning `beer`.

2018-07-28 21:11 UTC, oleg-nenashev requested changes
retracting my approval. Tests need to be fixed before merging

2018-07-30 08:44 UTC, varyvol commented
@oleg this didn't pretend to be a fix, but a proof of the failure I had seen.

2018-07-30 10:17 UTC, daniel-beck commented
@varyvol Are you planning to address the issue in this PR? Or did you just want to contribute a test?

If the latter, the test should be ignored by default, so it doesn't introduce failures.

2018-08-03 13:30 UTC, varyvol commented
@daniel-beck I've ignored the test.

2018-10-11 07:21 UTC, closed without merging