[FIXED JENKINS-34172] Add null safety checks to FilePath
jenkinsci/jenkins pull request #3615
Opened 2018-09-08 15:47 UTC by slgriff

See [JENKINS-34172](https://issues.jenkins-ci.org/browse/JENKINS-34172).

2018-09-08 15:58 UTC, oleg-nenashev requested changes
Not sure it is a right idea for all methods.
AFAICT it some cases it makes the operations noop when `null` is passed. Instead of that I would suggest throwing checked IOException so that the error does not get suppressed.

But maybe a better way is to add `@Nonnull` annotations and track down incorrect usages (at least within the core)

2018-09-08 16:56 UTC, daniel-beck commented
Agree with Oleg, this significantly changes the semantics in case of misuse.

2018-09-09 17:15 UTC, slgriff commented
Thanks for the feedback. I will make the requested changes and update the PR.

2018-09-10 01:26 UTC, slgriff commented
FIXED JENKINS-34172] Update FilePath with static analysis annotations for null safety checks and to propogate runtime NPEs

2018-09-13 09:31 UTC, oleg-nenashev reviewed
will try to review after DevOps World | Jenkins World. Sorry for the delay, and thanks for your patience!

2018-09-13 09:31 UTC, oleg-nenashev commented on core/src/main/java/hudson/FilePath.java
> +    private void unzip(@Nonnull File dir, File zipFile) throws IOException {
second arg should be nonnull as well

2018-09-13 09:31 UTC, oleg-nenashev commented on core/src/main/java/hudson/FilePath.java
> +    	assert base != null;
something is wrong with indenting here and below

2018-09-13 09:31 UTC, oleg-nenashev commented on core/src/main/java/hudson/FilePath.java
> +        assert dst != null;
I do not think asserts are really required, static analysis should start producing issues even before the tests run (we also need to configure surefire to do the same if possible, like IDEA does)

2019-01-31 00:05 UTC, oleg-nenashev commented
I believe that all asserts should be removed. Although I fixed the merge conflict, I do not think this PR can be cleaned up easily. Might be better to start from scratch

@slgriff Are you still interested in it?

2019-01-31 00:06 UTC, oleg-nenashev requested changes
requesting changes as per comments above

2019-03-28 14:45 UTC, daniel-beck commented
No response to comments in two months, so closing as inactive.

@slgriff If you want to resume working on this, just open a new PR with conflicts resolved. Thanks!

2019-03-28 14:45 UTC, closed without merging