[JENKINS-53505] Remove the restriction on DownloadSettings
jenkinsci/jenkins pull request #3617
Opened 2018-09-11 08:50 UTC by amuniz

See [JENKINS-53505](https://issues.jenkins-ci.org/browse/JENKINS-53505).

### Proposed changelog entries

* JENKINS-53505: `DownloadSettings` is not restricted now.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/code-reviewers

2018-09-11 09:33 UTC, daniel-beck commented
`useBrowser` is an implementation detail (and one we should probably remove altogether), so that does not seem relevant enough.

`@Symbol` makes sense for config-as-code situations that can handle backwards incompatible changes; elevating this to supported API is different.

2018-09-11 09:36 UTC, amuniz commented
Justification is in the JIRA ticket: I need to read this property to be able replicate it in another Jenkins instance. Code is not public though.

2018-09-11 09:39 UTC, daniel-beck commented
@amuniz I saw, which is why I specifically address the description of the issue.

This change elevates `useBrowser` to public API despite it being effectively deprecated since early 2015. I expect the next one to touch this class will just remove it.

Except, with this change, they can't.

2018-09-11 09:42 UTC, amuniz commented
>  despite it being effectively deprecated since early 2015

The it should have been properly `@Deprecated` IMO, not just `@Restricted`.

2018-09-11 09:48 UTC, amuniz commented
So, what if I just remove it now @daniel-beck?

2018-09-11 10:10 UTC, oswaldohp commented
I agree with @amuniz that this element should have been `@Deprecated` to be consistent.

What would you like to do here then @daniel-beck ? Should we remove this altogether now and remove our usage from operations-center? 

Or should we just deprecate the element, if so what sort of timeline are we looking at here for jenkins to remove this altogether?

FYI @cyrille-leclerc ^^

2018-09-11 11:53 UTC, daniel-beck commented
> I agree with @amuniz that this element should have been `@Deprecated` to be consistent.

Not disagreeing, but beyond the semantics, would it have accomplished anything? Historically we have a difficult time removing deprecated elements, especially if they're user features. See e.g. `BuildAuthorizationToken`, which was deprecated more than a decade ago.

Beyond the specific annotations, https://github.com/jenkinsci/jenkins/blob/4620aed77bcd354a48988cae7fa80a38beb4c1be/core/src/main/java/jenkins/model/DownloadSettings.java#L137 should be indication enough that this feature has no future.

`@Restricted` was around for this API from the start, and has stronger "do not use this" semantics than `@Deprecated`. I would be _very_ surprised if a similar PR existed if this were `@Deprecated` instead of `@Restricted`.

> Should we remove this altogether now and remove our usage from operations-center?

Ideally we'll piggyback on https://github.com/jenkinsci/jenkins/pull/3604 which will hopefully start providing information in a week or two to inform any decision here. This feature needs to die, but if a significant subset of users still use it, we might not get away with simply removing it.

I don't know how it is used elsewhere. If it is, its use is bypassing the `@Restricted` check somehow (one of the bugs in the maven plugin?), and never should have been introduced.

2018-09-11 12:31 UTC, amuniz commented
> I don't know how it is used elsewhere. If it is, its use is bypassing the @Restricted check somehow (one of the bugs in the maven plugin?), and never should have been introduced.

Correct, it was used because of the bug on the maven plugin checking it.

So, IIUC you are proposing to wait for #3604 to see how much this property is used and than take a decision, right?

2018-09-24 07:51 UTC, amuniz commented
#3604 is merged, do we have the information to take a decision here @daniel-beck?

2018-09-24 07:53 UTC, amuniz commented
Well, it will need to be released, ok.

2018-09-30 11:49 UTC, oleg-nenashev approved these changes
Personally I am fine with that. `@Restricted` would also cause JCasC to fail for this global configuration (CC @ndeloof  just in case). Still needs review from @daniel-beck

2018-09-30 11:55 UTC, oleg-nenashev commented
I was unable to find usages of `downloadSettings` in JCasC config files in GitHub, so my comment is probably not relevant

2019-01-31 02:17 UTC, oleg-nenashev commented
@amuniz @oswaldohp Are you interested to proceed with this PR? I can request wider reviews if you are interested to get it landed

2019-04-09 09:33 UTC, daniel-beck commented
FYI https://github.com/jenkinsci/jenkins/pull/3970

2019-04-21 23:05 UTC, daniel-beck commented
Given the recent lack of responses and the fact that #3970 looks like it'll make it into a release fairly soon, I'm closing this one. It can always be revived (or redone, 1 line change) if #3970 ends up rejected or reverted.

2019-07-18 11:08 UTC, amuniz commented
Reopening this as #3970 does not seem to progress.

2019-07-18 11:09 UTC, amuniz commented
@oleg-nenashev yes, I am still interested on this.

2019-08-01 10:16 UTC, rsandell approved these changes

2019-08-01 10:17 UTC, alecharp approved these changes

2019-08-29 09:15 UTC, varyvol approved these changes
It does not hurt in my opinion given I think this could actually be used previously (even if not recommended).

@daniel-beck you were reluctant to the change, do you keep thinking the same?

2019-10-03 09:58 UTC, varyvol commented
@daniel-beck could you please provide your opinion so that we can maybe move this forward?

2019-10-03 09:58 UTC, fcojfernandez approved these changes

2019-10-04 15:21 UTC, daniel-beck requested changes
Still prefer #3970 and will finish it up today.

2019-10-11 07:30 UTC, daniel-beck commented
#3970 was merged, so this is obsolete.

2019-10-11 07:30 UTC, closed without merging