Add languages plugin category for setupWizard
jenkinsci/jenkins pull request #3626
Opened 2018-09-15 10:14 UTC by LinuxSuRen

2018-09-15 23:29 UTC, oleg-nenashev requested changes
With the current setting it will install the plugin by-default on each instance, I believe that the "suggested" flag should be removed.

BTW, the request does seem to comply with https://github.com/jenkinsci/jep/blob/master/jep/2/README.adoc , so I am fine with adding the category.

Translation assistance could be added here as well once it is cleaned up

2018-09-16 01:29 UTC, LinuxSuRen commented
I think it's compatible because the Chinese translation was in the core Jenkins, once we remove them from the core Jenkins than users will get a non-Chinese version.
At least, I could try to decide this from the browser language settings.

2018-09-16 01:53 UTC, oleg-nenashev commented
> At least, I could try to decide this from the browser language settings

That would be an interesting experiment with Installation wizard

2018-09-16 20:05 UTC, oleg-nenashev commented on war/src/main/js/api/pluginManager.js
> +					} else if (pluginCategory.category === "Languages"){
Tabs vs. spaces

2018-09-22 03:25 UTC, oleg-nenashev approved these changes

2018-09-22 03:53 UTC, daniel-beck commented
Have some concerns about this, would like to onhold.

Also, we started with a big process around which plugins are suggested; this seems very different, perhaps too different. Unsure though TBH.

2018-09-22 05:11 UTC, LinuxSuRen commented
If move all Chinese localization resource files into a plugin, I think the plugin should be suggested. So I could get your point about this. And the suggestion is dynamic according user-agent.

2018-10-01 13:23 UTC, jglick approved these changes
Seems reasonable to me.

2018-10-01 14:02 UTC, LinuxSuRen commented on core/src/main/resources/jenkins/install/platform-plugins.json
> +            { "name": "localization-zh-cn"}
Just because of all other plugins' name use `-` instead of `_`.

2018-10-06 10:52 UTC, oleg-nenashev commented
@daniel-beck Is it still on hold? I believe this is a good thing to experiment with, no negative feedback so far.
A;so https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jenkinsci-dev/4WlxJUXnNE4

2018-10-13 17:07 UTC, daniel-beck commented
Seems reasonable; interactive testing also seemed to show this works nicely, even when accepting the default set.

2018-10-25 13:40 UTC, LinuxSuRen commented
I wonder if we could continue this?

2018-11-10 05:40 UTC, oleg-nenashev commented
Nobody voted against so 🚢 🇮🇹

2018-11-10 05:40 UTC, merged

2018-11-10 05:43 UTC, oleg-nenashev commented
Added the changelog.

@LinuxSuRen I believe https://github.com/jenkinsci/jep/blob/master/jep/216/README.adoc needs to be updated in order to document this feature and the plugin naming standard.

2018-11-10 09:45 UTC, LinuxSuRen commented
@oleg-nenashev Got it. I am going to do this as soon as possible.