Try to use a known working ath docker image
jenkinsci/jenkins pull request #3628
Opened 2018-09-15 14:43 UTC by raul-arabaolaza

I have found several builds failing due to selenium errors since yesterday, including the ATH itself and several internal builds.
I suspect something has happened with the docker image, maybe the firefox ECR version has changed in the local repo or something similar

If I am right this version of the docker image should still work.

With the builds working again we can center in fixing the docker image

2018-09-15 15:18 UTC, raul-arabaolaza commented
This seems to fix the ATH issues, build is still failing due to an unrelated findbugs problem, which I suspect is related to the last commit in core (see https://github.com/jenkinsci/jenkins/commit/0a12ba85a98111d456fc640374f904f753d293ea) and build [1062](https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/master/1062/pipeline/8):
No idea why BO is showing a green stage when the last command failed ... 

```
[INFO] --- findbugs-maven-plugin:3.0.5:check (findbugs) @ jenkins-core ---

[INFO] BugInstance size is 1

[INFO] Error size is 0

[INFO] Total bugs: 1

[INFO] The method jenkins.security.apitoken.ApiTokenStore$HashedToken.readResolve() must be declared with a return type of Object rather than ApiTokenStore$HashedToken [jenkins.security.apitoken.ApiTokenStore$HashedToken] At ApiTokenStore.java:[lines 360-361] SE_READ_RESOLVE_MUST_RETURN_OBJECT
```


cc @oleg-nenashev @olamy @olivergondza @jtnord

2018-09-15 16:11 UTC, raul-arabaolaza commented
I have disabled the findbugs check using the proper annotation to have a green build, but it should be reviewed by @jtnord as soon as possible.

2018-09-15 19:03 UTC, oleg-nenashev approved these changes
At least it improves the situation. @jtnord can review and fix it in the follow-up, bogus code is in the master branch anyway

2018-09-15 23:22 UTC, oleg-nenashev requested changes
IIUC the warning means that @jtnord 's patch just won't work. the methods are private, will just fix them

2018-09-16 19:33 UTC, oleg-nenashev commented
The PR does not make it worse at least, merging

2018-09-16 19:33 UTC, merged