[FIX JENKINS-54325] Add support for multiple SimplePageDecorators in …
jenkinsci/jenkins pull request #3710
Opened 2018-10-29 21:06 UTC by jvz

…login.jelly

Signed-off-by: Matt Sicker <boards@gmail.com>

See [JENKINS-54325](https://issues.jenkins-ci.org/browse/JENKINS-54325).

### Proposed changelog entries

* `Internal:` `login.jelly` now supports displaying all registered `SimplePageDecorator` extensions rather than just the top priority one.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @scherler

2018-10-30 20:59 UTC, Wadeck requested changes
nit: you can `@Deprecated` the `getSimplePageDecorator()`

RC: The `hudson/security/HudsonPrivateSecurityRealm/signup.jelly` also requires a modification otherwise the login page will work but not the signup one ;)

2018-10-30 21:13 UTC, jvz commented
@Wadeck Deprecated the old function, and updated signup.jelly

2018-10-30 21:56 UTC, Wadeck approved these changes
:bee:

2018-11-05 12:14 UTC, scherler requested changes
> Internal: login.jelly and signup.jelly now support displaying all registered SimplePageDecorator extensions rather than just the top priority one.

Actually there is a point behind to return only one. Your changes will provoke that all existing login pages would display 2 logos when a custom one is provided.

Did you test this? 

If you are not provide a way to actually limit e.g. the logo to only one implementations I am not seeing the point to break the only one implementation approach.

2018-11-05 16:58 UTC, jvz commented
I tested this mainly with a new plugin called Paranoia. The problem being that I can't provide any footer without losing the header, and I didn't want to copy the default headers and styles.

Perhaps the logo should only display the first one while the other includes can overlap?

2018-11-05 19:49 UTC, scherler commented
Did you see https://jenkins.io/blog/2018/06/27/new-login-page/ ? There is no need to copy and paste but you can include the default ones.

Regarding the footer could the paranoia plugin not expose another extension point which aggregates all footers and then inject it as only one 

The reason of only one is to have a clean design and prevent surprises in design when plugins are extending.

2018-11-05 20:18 UTC, jvz commented
Are you suggesting an extension point in core? If so, I could redo this change as such to add some sort of footer decorator. Otherwise, I'm not sure what you mean. I'd like to have this plugin be able to work with other custom page decorators or still use the default one otherwise.

2018-11-05 20:19 UTC, scherler commented
Not in core in your plugin, people using it can extend it.

2018-11-05 20:30 UTC, scherler commented
Hmm, do you want to have a quick hangouts/meet/... about it?

In the blog post I wrote: 

```
<?jelly escape-by-default='true'?>
<j:jelly xmlns:j="jelly:core">
  <link rel="stylesheet" href="${resURL}/css/simple-page.css" type="text/css" />
  <link rel="stylesheet" href="${resURL}/css/simple-page.theme.css" type="text/css" />
  <style>
    .simple-page .logo {
        background-image: url('${resURL}/plugin/YOUR_PLUGIN/icons/my.svg');
        background-repeat: no-repeat;
        background-position: 50% 0;
        height: 130px;
    }
  </style>
  <link rel="stylesheet" href="${resURL}/css/simple-page-forms.css" type="text/css" />
</j:jelly>
```

That is using the core/default styles and adding to it,  would that not cover your case?

2018-11-05 20:38 UTC, jvz commented
I mean I can do that, but this plugin isn't overriding the styles there. I'm injecting scripts into pages.

2018-11-07 12:42 UTC, scherler reviewed
As I see it you need simply provide `src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-footer.jelly` and inject your stuff there

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/jenkins/model/Jenkins/login.jelly
> +                <j:forEach var="simpleDecorator" items="${simpleDecorators}">
This is actually the only change you need besides creating the methods to get all decorators.

2018-11-07 12:42 UTC, scherler commented on core/src/main/java/hudson/Functions.java
> +    @Deprecated
Nupp

2018-11-07 12:42 UTC, scherler commented on core/src/main/java/hudson/Functions.java
> +    public static List<SimplePageDecorator> getSimplePageDecorators() {
:+1:

2018-11-07 12:42 UTC, scherler commented on core/src/main/java/jenkins/model/SimplePageDecorator.java
> +    public static List<SimplePageDecorator> all() {
:+1:

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
> +    <j:set var="simpleDecorators" value="${h.simplePageDecorators}"/>
You need both

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
> -            <st:include it="${simpleDecorator}" page="simple-head.jelly" optional="true"/>
Nupp

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
> +                        <div class="footer">
I am fine with that

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/jenkins/model/Jenkins/login.jelly
> +  <j:set var="simpleDecorators" value="${h.simplePageDecorators}"/>
see above, you need both

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/jenkins/model/Jenkins/login.jelly
> -      <st:include it="${simpleDecorator}" page="simple-head.jelly" optional="true"/>
:-1:

2018-11-07 12:42 UTC, scherler commented on core/src/main/resources/jenkins/model/Jenkins/login.jelly
> -              <st:include it="${simpleDecorator}" page="simple-header.jelly" optional="true"/>
:-1:

2018-11-07 18:06 UTC, jvz commented
Ah, I see what you mean. I'll update this to only add support for multiple footers. Then I can set a low priority on my decorator.

2018-11-07 20:45 UTC, jvz commented
Redone in #3721.

2018-11-07 20:45 UTC, closed without merging