[JEP-216] Support loading localizer resources from any plugin
jenkinsci/jenkins pull request #3729
Opened 2018-11-10 23:12 UTC by daniel-beck

**WIP** This exists mostly to get a PR build and share with @LinuxSuRen for feedback.

This is en _experiment_. `localization-zh-cn` supports overriding any localized resource except `Messages` from the localizer lib. This is an attempt at addressing that limitation.

Essentially no test coverage, and extremely limited interactive testing so far.

Ideally JEP-216 style localization plugins will have some metadata that allows core to limit the search to them, and e.g. invalidate caches when they're newly loaded or something.

Downstream from https://github.com/kohsuke/localizer/pull/16

2018-11-11 09:57 UTC, daniel-beck commented
This might be better off in the `localization` plugin, but the direction is unclear to me for further localizations.

2018-11-21 08:13 UTC, oleg-nenashev commented
CC @jenkinsci/chinese-localization-sig @jonbrohauge

2018-11-21 08:15 UTC, oleg-nenashev reviewed
👍 for the approach. looking forward to get it merged

2018-11-21 08:17 UTC, LinuxSuRen commented
LGTM, but we need to wait for the downstream.

2018-11-21 15:09 UTC, daniel-beck commented
> LGTM, but we need to wait for the downstream.

Well, the proof of concept exists, so we _could_ already include this. That said, I want to get further with `localization-support` before introducing core changes that might be difficult to back out again.

2019-02-06 07:35 UTC, LinuxSuRen commented
I'm just able to maintain the Simplified Chinese localization. AKA the *.zh_CN.* files.

2019-02-06 08:16 UTC, daniel-beck commented
@LinuxSuRen That's fine. I removed `zh_TW` here only temporarily to make it easier to test and develop, that will be reverted.

2019-02-06 09:05 UTC, LinuxSuRen commented
Got it.

2019-02-06 11:27 UTC, oleg-nenashev requested changes
Looks good to me overall. IIUC it will also need updates in the detached plugin list so that a proper version of https://github.com/jenkinsci/localization-zh-cn-plugin is referenced from there

2019-02-06 11:57 UTC, daniel-beck commented
@oleg-nenashev It has never been considered split from core in the first place, I don't see a reason to do this now.

2019-02-25 16:32 UTC, jvz approved these changes

2019-02-25 18:42 UTC, jeffret-b approved these changes
Looks good once the conflict is resolved and we get another good build.

Looks like it's still waiting on an upstream dependency.

2019-02-26 09:26 UTC, Wadeck approved these changes
Have you considered that all the new logic here will be called multiple times per page request and thus, could potentially impact the performance?

IIRC there is no code cache for the resource files / urls, and so, the addition/deletion of a localization plugins will have no impact on that, right?

WDYT about renaming `localization-support-plugin` to `localization-api-plugin` as it's not meant to be used directly?

2019-02-26 09:26 UTC, Wadeck commented on core/src/main/java/jenkins/MetaLocaleDrivenResourceProvider.java
> +public final class MetaLocaleDrivenResourceProvider extends LocaleDrivenResourceProvider {
`@Restricted(DoNotUse.class)` as it seems to be self-sufficient?

2019-02-26 09:26 UTC, Wadeck commented on core/src/main/java/jenkins/MetaLocaleDrivenResourceProvider.java
> +            URL url = provider.lookup(s);
nit: An additional layer of `try{...}catch` could be useful and is free in terms of perf.

2019-02-26 15:13 UTC, daniel-beck commented
@Wadeck 

> Have you considered that all the new logic here will be called multiple times per page request and thus, could potentially impact the performance?

> IIRC there is no code cache for the resource files / urls, and so, the addition/deletion of a localization plugins will have no impact on that, right?

Not considered. Would expect this to not be worse than 2x the file system accesses, and that didn't seem too expensive. Note that Localizer does cache, and `localization-support` clears the cache as needed. Can always add further caching later, I think, if necessary. Notably, nothing here is really 

> WDYT about renaming `localization-support-plugin` to `localization-api-plugin` as it's not meant to be used directly?

No opinion. Both names indicate to me that they're not really immediately useful/standalone end-user features.

2019-02-26 21:11 UTC, daniel-beck commented
Cleaned up the history, and focusing now on the localization-support infra (i.e. not removing localized files, too).

2019-03-08 09:22 UTC, oleg-nenashev approved these changes
Ready to go once Stapler is released and integrated

2019-03-09 03:43 UTC, LinuxSuRen approved these changes

2019-03-20 01:34 UTC, LinuxSuRen commented
localizer 1.26 was released.

2019-03-21 12:18 UTC, daniel-beck commented
@LinuxSuRen This needs a release of Stapler.

2019-04-08 14:28 UTC, jglick commented on core/pom.xml
> +    <stapler.version>1.257-JEP-216-SNAPSHOT</stapler.version>
1.257 (and next time you can use Incrementals!)

2019-04-08 14:44 UTC, daniel-beck commented on core/pom.xml
> +    <stapler.version>1.257-JEP-216-SNAPSHOT</stapler.version>
```suggestion
    <stapler.version>1.257</stapler.version>
```

2019-04-09 13:33 UTC, jglick requested changes

2019-04-09 14:22 UTC, jglick approved these changes
Better, thanks!

2019-04-10 10:09 UTC, merged