Include Build Timestamp in console output page
jenkinsci/jenkins pull request #3810
Opened 2018-12-12 15:49 UTC by dsrink

### Proposed changelog entries
* Include Build Timestamp in console output page

### Justification/Description of the change
When analyzing the console output, one often needs the start time of the build.
Since that start time is shown in the same location from hudson/model/AbstractBuild/index.jelly, I have copied the respective jelly code from there.

Anyway, this spot of the page is basically unused, so it won't hurt to include this information at this location.

### Trying to comply with the applicable parts of submitter checklist
* No Jenkins issue was created since this a very minor change.
* No tests where added due to the same reason, and since this change is in jelly

2018-12-12 16:01 UTC, jvz approved these changes
Sounds reasonable to me.

2018-12-13 10:07 UTC, daniel-beck commented
> When analyzing the console output, one often needs the start time of the build.

Jenkins build output does not include time stamps automatically, so this assumes it's done manually.

In addition to that, the time zone on the build agent might be different from the master's, making this addition actively confusing. For that reason, :-1: for inclusion.

I recommend plugins such as Timestamper, which supports displaying elapsed build time for each log message instead.

2019-01-25 18:23 UTC, oleg-nenashev requested changes
I agree with @daniel-beck . It might be useful to enable Timestamper plugin by default in new Jenkins installations, but there are also questions about BlueOcean installations.

@dsrink would you agree with closing this PR? If no, how would you address the comments?

2019-02-14 17:04 UTC, oleg-nenashev commented
Closing due to the lack of response

2019-02-14 17:04 UTC, closed without merging