[JENKINS-55292] - Remove MailCommand localization from the core
jenkinsci/jenkins pull request #3819
Opened 2018-12-21 07:51 UTC by oleg-nenashev

See [JENKINS-55292](https://issues.jenkins-ci.org/browse/JENKINS-55292). It is a counterpart of https://github.com/jenkinsci/mailer-plugin/pull/48 

### Proposed changelog entries

* Remove MailCommand localization from the core
* ...

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/core

2018-12-21 07:52 UTC, oleg-nenashev commented
On hold until https://github.com/jenkinsci/mailer-plugin/pull/48 is released

2018-12-23 13:36 UTC, olivergondza approved these changes

2019-01-28 15:54 UTC, oleg-nenashev commented
Mailer plugin patch was released in 1.23 (Dec 2018. I believe we can go forward here

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +InstallPluginCommand.NotAValidSourceName={0} no es un fichero/url v�lido, ni existe en el centro de actualizaciones
```suggestion
InstallPluginCommand.NotAValidSourceName={0} no es un fichero/url válido, ni existe en el centro de actualizaciones 
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +InstallPluginCommand.NoUpdateDataRetrieved=No se recogi� todav�a informaci�n de actualizacion desde: {0}
```suggestion
InstallPluginCommand.NoUpdateDataRetrieved=No se recogió todavía información de actualizacion desde: {0}
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +InstallPluginCommand.DidYouMean={0} parece un nombre de plugin corto. �Quieres decir ''{1}''?
```suggestion
InstallPluginCommand.DidYouMean={0} parece un nombre de plugin corto. ¿Quieres decir ''{1}''?
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +GetJobCommand.ShortDescription=Volcar el fichero XML de la definici�n de tarea a la salida est�ndard
```suggestion
GetJobCommand.ShortDescription=Volcar el fichero XML de la definición de tarea a la salida estándard
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +InstallToolCommand.ShortDescription=Autom�ticamente instala componentes e imprime su localizaci�n a la salida est�ndard. S�lo se puede llamar desde un trabajo.
```suggestion
InstallToolCommand.ShortDescription=Automáticamente instala componentes e imprime su localización a la salida estándard. Sólo se puede llamar desde un trabajo.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +VersionCommand.ShortDescription=Muestra la versi�n actual.
```suggestion
VersionCommand.ShortDescription=Muestra la versión actual.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +CreateJobCommand.ShortDescription=Permite crear una nueva tarea leyendo un fichero XML por la entrada est�ndard.
```suggestion
CreateJobCommand.ShortDescription=Permite crear una nueva tarea leyendo un fichero XML por la entrada estándard.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +SetBuildResultCommand.ShortDescription=Establece el resultado del trabajo actual. S�lo se puede ejecutar desde un trabajo.
```suggestion
SetBuildResultCommand.ShortDescription=Establece el resultado del trabajo actual. Sólo se puede ejecutar desde un trabajo.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +UpdateJobCommand.ShortDescription=Actualiza el fichero XML de la definici�n de una tarea desde la entrada est�ndard. Es lo contrario al comando get-job.
```suggestion
UpdateJobCommand.ShortDescription=Actualiza el fichero XML de la definición de una tarea desde la entrada estándard. Es lo contrario al comando get-job.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +SetBuildDescriptionCommand.ShortDescription=Establece la descripci�n de una ejecuci�n.
```suggestion
SetBuildDescriptionCommand.ShortDescription=Establece la descripción de una ejecución.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +WaitNodeOnlineCommand.ShortDescription=Esperando hasta que el nodo est� activado
```suggestion
WaitNodeOnlineCommand.ShortDescription=Esperando hasta que el nodo esté activado
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +WaitNodeOfflineCommand.ShortDescription=Esperando a que el nodo est� desactivado
```suggestion
WaitNodeOfflineCommand.ShortDescription=Esperando a que el nodo esté desactivado
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +Deshabilita uno o m�s plugins instalados.
```suggestion
Deshabilita uno o más plugins instalados.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_es.properties
> +Deshabilita los plugins con los nombre cortos dados. Puede definir c�mo proceder con los plugins dependientes y si se realiza un reinicio posterior.
```suggestion
Deshabilita los plugins con los nombre cortos dados. Puede definir cómo proceder con los plugins dependientes y si se realiza un reinicio posterior.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +InstallPluginCommand.NoUpdateCenterDefined=Si noti che in quest''istanza di Jenkins non � definito alcun Centro aggiornamenti.
```suggestion
InstallPluginCommand.NoUpdateCenterDefined=Si noti che in quest''istanza di Jenkins non è definito alcun Centro aggiornamenti.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +InstallPluginCommand.NotAValidSourceName={0} non � n� un file valido, n� un URL, n� il nome di un artefatto di un plugin nel Centro aggiornamenti
```suggestion
InstallPluginCommand.NotAValidSourceName={0} non è né un file valido, né un URL, né il nome di un artefatto di un plugin nel Centro aggiornamenti
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +DeleteBuildsCommand.ShortDescription=Elimina uno o pi� record relativi alle build.
```suggestion
DeleteBuildsCommand.ShortDescription=Elimina uno o più record relativi alle build.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +DeleteViewCommand.ShortDescription=Elimina una o pi� viste.
```suggestion
DeleteViewCommand.ShortDescription=Elimina una o più viste.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +DeleteJobCommand.ShortDescription=Elimina uno o pi� processi.
```suggestion
DeleteJobCommand.ShortDescription=Elimina uno o più processi.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +LoginCommand.FullDescription=A seconda dell''area di sicurezza sar� necessario fornire argomenti come:\n\
```suggestion
LoginCommand.FullDescription=A seconda dell''area di sicurezza sarà necessario fornire argomenti come:\n\
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +Pu� non essere supportato in alcune aree di sicurezza come il single sign on.\n\
```suggestion
Può non essere supportato in alcune aree di sicurezza come il single sign on.\n\
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +modalit� di autenticazione non consentir� di fare riferimento (ad esempio)\n\
```suggestion
modalità di autenticazione non consentirà di fare riferimento (ad esempio)\n\
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +UpdateJobCommand.ShortDescription=Aggiorna l''XML della definizione del processo dallo standard input. � il comando contrario di get-job.
```suggestion
UpdateJobCommand.ShortDescription=Aggiorna l''XML della definizione del processo dallo standard input. È il comando contrario di get-job.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +UpdateNodeCommand.ShortDescription=Aggiorna l''XML della definizione del nodo dallo standard input. � il comando contrario di get-node.
```suggestion
UpdateNodeCommand.ShortDescription=Aggiorna l''XML della definizione del nodo dallo standard input. È il comando contrario di get-node.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +UpdateViewCommand.ShortDescription=Aggiorna l''XML della definizione della vista dallo standard input. � il comando contrario di get-view.
```suggestion
UpdateViewCommand.ShortDescription=Aggiorna l''XML della definizione della vista dallo standard input. È il comando contrario di get-view.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +BuildCommand.CLICause.CannotBuildDisabled=Impossibile compilare {0} perch� � disabilitato.
```suggestion
BuildCommand.CLICause.CannotBuildDisabled=Impossibile compilare {0} perché è disabilitato.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +BuildCommand.CLICause.CannotBuildConfigNotSaved=Impossibile compilare {0} perch� la sua configurazione non � stata salvata.
```suggestion
BuildCommand.CLICause.CannotBuildConfigNotSaved=Impossibile compilare {0} perché la sua configurazione non è stata salvata.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +QuietDownCommand.ShortDescription=Ferma le attivit� di Jenkins in preparazione a un riavvio. Non avvia alcuna build.
```suggestion
QuietDownCommand.ShortDescription=Ferma le attività di Jenkins in preparazione a un riavvio. Non avvia alcuna build.
```

2019-01-28 16:18 UTC, oleg-nenashev commented on core/src/main/resources/hudson/cli/Messages_it.properties
> +OfflineNodeCommand.ShortDescription=Non utilizza pi� temporaneamente un nodo per eseguire le build fino al successivo comando "online-node".
```suggestion
OfflineNodeCommand.ShortDescription=Non utilizza più temporaneamente un nodo per eseguire le build fino al successivo comando "online-node".
```

2019-01-28 16:20 UTC, oleg-nenashev commented
I fixed broken symbols from the web UI , but it does not loo to be enough apparently

2019-01-29 08:56 UTC, oleg-nenashev commented
```
ERROR] Failed to execute goal org.jvnet.hudson.tools:maven-encoding-plugin:1.1:check-encoding (default) on project jenkins-core: Problems detected -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jvnet.hudson.tools:maven-encoding-plugin:1.1:check-encoding (default) on project jenkins-core: Problems detected

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)

    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:566)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

Caused by: org.apache.maven.plugin.MojoExecutionException: Problems detected

    at org.jvnet.hudson.tools.PropertyFileEncodingCheckerMojo.execute (PropertyFileEncodingCheckerMojo.java:78)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)

    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:566)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

[ERROR] 

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

:(

2019-01-29 14:43 UTC, alecharp requested changes
I see way more changes than it should have.

2019-02-20 12:43 UTC, daniel-beck commented
> I see way more changes than it should have.

I don't -- just way more highlighted lines. Is this a file encoding change?

2019-02-20 12:59 UTC, oleg-nenashev commented
yes, encoding.
I have no quick way to fix it on my laptop, it seems

On Wed, Feb 20, 2019 at 1:43 PM Daniel Beck <notifications@github.com>
wrote:

> I see way more changes than it should have.
>
> I don't -- just way more highlighted lines. Is this a file encoding change?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/3819#issuecomment-465558677>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC3IoL9vOIeX674LLSbxSqH2uK1xh5d3ks5vPUL8gaJpZM4Zdh8_>
> .
>

2019-04-09 13:43 UTC, closed without merging