Fix for issue JENKINS-12699 and JENKINS-32215
jenkinsci/jenkins pull request #3844
Opened 2019-01-14 14:03 UTC by bphinz

See:

[JENKINS-12699](https://issues.jenkins-ci.org/browse/JENKINS-12699)
[JENKINS-32215](https://issues.jenkins-ci.org/browse/JENKINS-32215).

### Proposed changelog entries

* Internal: Jenkins creates temp file object and never deletes it, possibly causing server to run out of disk space

### Submitter checklist

- [ x] JIRA issue is well described
- [x ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ x] Appropriate autotests or explanation to why this change has no tests
      * I don't know how to write a test for this change but we've had this in our production Jenkins instance since November and no negative side effects have been observed.  The temp files are deleted after merging this in.
- [ x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

2019-01-14 15:45 UTC, jvz reviewed
Seems logical. Do you think you can add a test for this?

2019-01-14 16:30 UTC, bphinz commented
I could try, but I've never written a test like this.  Are there examples somewhere that I might be able to leverage?  What should the test consist of, just verifying that the files get deleted?

2019-01-14 17:01 UTC, jvz commented
Yes, just verify the file was deleted. It might be doable with mocks, but I'd assume that you can use `WebClient` in the test to upload a file to a form and things like that.

2019-01-25 17:59 UTC, oleg-nenashev requested changes
Thanks for the pull request @bphinz ! Unfortunately it will not work as expected, because the file will not be consumed until the build is actually executed in https://github.com/jenkinsci/jenkins/blob/881dafe385f42bdd2568c7286e1dfac30bec6daa/core/src/main/java/hudson/model/FileParameterValue.java#L173 . 

It might be possible to have better implementation, which would automatically move temporary files to the build directory when the build starts. In such case the files would be rotated along with build directories. Or it could just remove files, because they are browsed from the workspace anyway in https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/FileParameterValue.java#L228 

Such logic likely requires additional metadata which would indicate that the file is actually a temporary one

2019-01-25 18:18 UTC, bphinz commented
Thanks for responding.  I like the idea of moving them into the build directory at the start of the build.  I'll see if I can work through that this weekend.

2019-01-25 18:19 UTC, oleg-nenashev commented
thanks!

2019-02-03 22:12 UTC, bphinz commented
I verified manually that with this patch the tmp files get deleted, but I'm not really sure how to go about writing an automated test for this...  The problem only presents itself when slaves are present, so the test would need to ensure that.  Also, the test would need to watch java.io.tmpdir on the master to see if a tmp file was created and then deleted.  Any thoughts?

2019-02-26 19:30 UTC, bphinz commented
Hi @oleg-nenashev.  Are you still reviewing this?

2019-02-26 19:51 UTC, oleg-nenashev commented
Sorry, I missed the previous comment. Will add to my queue

On Tue, Feb 26, 2019, 20:31 Brian Hinz <notifications@github.com> wrote:

> Hi @oleg-nenashev <https://github.com/oleg-nenashev>. Are you still
> reviewing this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/3844#issuecomment-467579124>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC3IoHhOiyefn7Bvj0F2vw9rrjlVPnPRks5vRYtzgaJpZM4Z-T3z>
> .
>

2019-03-10 06:42 UTC, jsoref commented
@bphinz: you have ` `  + `x` in your `[]` which breaks the checkbox feature of github, can you make sure you have exactly one of those two characters between `[` and `]`?

2019-04-09 12:45 UTC, batmat commented
@bphinz thank you very much for this work. That's an interesting fix. 

I also feel like this ought to have an automated test, both for checking we do reproduce/see the issue, and we keep it fixed once done.

I would recommend you look at [`hudson.model.FileParameterValueTest`](https://github.com/jenkinsci/jenkins/blob/c3351d2e7c3edfee82b9470e9aa1168982296072/test/src/test/java/hudson/model/FileParameterValueTest.java#L51) and the tests around this. It seems like you would _just_ to find a way to 

1) (by removing your fix first locally) write a test that fails by checking there's no temporary file left
2) add your fix and see if that goes back to success.

If you feel like this is something you could enjoy playing with, then we're happy to help. If you don't feel like it, or have no time anymore, please just tell us and I think we will try to see if we can add that test ourselves.

Thanks again!

2019-04-22 14:52 UTC, bphinz commented
Sorry, didn't mean to let this fall off the radar.  I will attempt to create a testcase based on @batmat's suggestions.

2019-04-30 12:58 UTC, jglick commented
I am not sure it is worth trying to salvage `FileParameter`, which has so many architectural problems to begin with. [Discussion](https://issues.jenkins-ci.org/browse/JENKINS-27413?focusedCommentId=352030&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-352030)

2019-05-13 07:23 UTC, batmat commented
hello @bphinz! Are you still intending to finish this? I still think this is a useful fix, so if you need on how to write a test in/for Jenkins, just ask. Thanks!

2019-08-01 10:41 UTC, alecharp commented
@bphinz do you think you would have time to add a test-case on this? Thanks.

2019-08-02 13:42 UTC, bphinz commented
I'm really sorry for the delay!  Yes, I still want to try to build the
testcase

On Thu, Aug 1, 2019 at 6:42 AM Adrien Lecharpentier <
notifications@github.com> wrote:

> @bphinz <https://github.com/bphinz> do you think you would have time to
> add a test-case on this? Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/3844?email_source=notifications&email_token=AB45M3OTHD7U3N3XMXB2UQ3QCK4W5A5CNFSM4GPZHXZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3KEZAY#issuecomment-517229699>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB45M3KGWUSEK53MKBT4HNDQCK4W5ANCNFSM4GPZHXZQ>
> .
>

2019-08-12 13:06 UTC, bphinz commented
I have a test that I think will work.  I will commit the patch later today

On Fri, Aug 2, 2019 at 9:42 AM Brian Hinz <bphinz@users.sourceforge.net>
wrote:

> I'm really sorry for the delay!  Yes, I still want to try to build the
> testcase
>
> On Thu, Aug 1, 2019 at 6:42 AM Adrien Lecharpentier <
> notifications@github.com> wrote:
>
>> @bphinz <https://github.com/bphinz> do you think you would have time to
>> add a test-case on this? Thanks.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jenkinsci/jenkins/pull/3844?email_source=notifications&email_token=AB45M3OTHD7U3N3XMXB2UQ3QCK4W5A5CNFSM4GPZHXZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3KEZAY#issuecomment-517229699>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AB45M3KGWUSEK53MKBT4HNDQCK4W5ANCNFSM4GPZHXZQ>
>> .
>>
>

2019-08-29 09:36 UTC, alecharp commented
@bpaquet Thanks for the test case but could you please review the merge conflict and try to resolve it?

2019-08-29 10:13 UTC, oleg-nenashev commented
Fixed the merge conflict

2019-08-29 10:17 UTC, oleg-nenashev reviewed
I am in favor of making it a default behavior, but it may cause regressions in some rebuild functionality. I think more comments from @jenkinsci/core team needed before merging.

Also note that `FileItem#delete` does not really propagate deletion issues. Not a big deal for temporary files

2019-09-19 08:57 UTC, alecharp commented on test/src/test/java/hudson/model/FileParameterValueTest.java
> +
```suggestion
    }

```

2019-09-19 08:58 UTC, alecharp requested changes
Requires to close the test function but other than that :+1:

2019-09-19 10:40 UTC, oleg-nenashev commented on test/src/test/java/hudson/model/FileParameterValueTest.java
> +
Fixed it manually

2019-09-19 10:43 UTC, oleg-nenashev approved these changes
To reiterate on my previous feedback, I am +1 for this change
It would be nice to have a system property to allow opting out, but I think we can start from the current behavior in weekly

2019-09-19 12:28 UTC, jglick commented
Anyone happen to know if file parameters worked with the `rebuild` plugin before and, if so, whether this breaks the combination? (An example of the “architectural problems” I mentioned.)

2019-09-19 12:43 UTC, bphinz commented
I will check today but I believe that rebuilds always worked and should
continue to do so.  The file gets copied into the workspace and distributed
to the slaves from there.  What this patch addresses is the tmp file that
only ever gets created on the master but then doesn't get deleted after
being copied to the workspace.

On Thu, Sep 19, 2019 at 8:29 AM Jesse Glick <notifications@github.com>
wrote:

> Anyone happen to know if file parameters worked with the rebuild plugin
> before and, if so, whether this breaks the combination? (An example of the
> “architectural problems” I mentioned.)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/3844?email_source=notifications&email_token=AB45M3NYUSLJQ3MNNPQ4BBDQKNWBNA5CNFSM4GPZHXZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7DJCDA#issuecomment-533106956>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB45M3JB3NK32B427ZGVB33QKNWBNANCNFSM4GPZHXZQ>
> .
>

2019-09-19 12:53 UTC, bphinz commented
Slight correction - I just tested and rebuilds from the web UI require the
file to be uploaded again irregardless of this patch

On Thu, Sep 19, 2019 at 8:42 AM Brian Hinz <bphinz@users.sourceforge.net>
wrote:

> I will check today but I believe that rebuilds always worked and should
> continue to do so.  The file gets copied into the workspace and distributed
> to the slaves from there.  What this patch addresses is the tmp file that
> only ever gets created on the master but then doesn't get deleted after
> being copied to the workspace.
>
> On Thu, Sep 19, 2019 at 8:29 AM Jesse Glick <notifications@github.com>
> wrote:
>
>> Anyone happen to know if file parameters worked with the rebuild plugin
>> before and, if so, whether this breaks the combination? (An example of the
>> “architectural problems” I mentioned.)
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jenkinsci/jenkins/pull/3844?email_source=notifications&email_token=AB45M3NYUSLJQ3MNNPQ4BBDQKNWBNA5CNFSM4GPZHXZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7DJCDA#issuecomment-533106956>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AB45M3JB3NK32B427ZGVB33QKNWBNANCNFSM4GPZHXZQ>
>> .
>>
>

2019-09-25 16:38 UTC, jeffret-b approved these changes
I'm in favor of this change. I haven't tried testing it, but the code looks fine and I'm in favor of the improvement.

2019-09-25 16:48 UTC, jeffret-b requested changes
Hmm ... I got curious about the CI failure and went ahead and downloaded the PR, built it and ran the tests. Unfortunately, the new test is failing on my machine. I'm not sure what's going on.

I'm still in favor of the improvement of the PR but something in the PR still needs a little work.

2019-10-17 10:21 UTC, varyvol commented
@bphinz could you review the test failures that @jeffret-b mentioned? It's actually the test that you introduced and it seems to be failing when checking the file does not exist anymore.

2019-10-17 10:22 UTC, varyvol commented on test/src/test/java/hudson/model/FileParameterValueTest.java
> +    	  assertThat(fpv.getFile(), equalTo(null));
assertNull() probably easier to read (I'm not doing the suggestion directly because it might require the import).

2019-11-28 10:49 UTC, fcojfernandez commented
Since there is no activity, we're proposing this PR for close

2019-11-28 14:51 UTC, bphinz commented
No argument from me, I can't spin my wheels on this anymore.  Note that this issue is probably worthy of a CVE because it allows a remote user to fill up /tmp on the jenkins master, potentially creating a DoS condition (that's actually how I discovered it in the first place).

2019-11-29 13:34 UTC, alecharp commented
If so, it would be way better not discussing it here but on a security ticket.

2019-12-12 10:00 UTC, MRamonLeon commented
Closed as agreed

2019-12-12 10:00 UTC, closed without merging