Improve alignment of settings widgets
jenkinsci/jenkins pull request #3859
Opened 2019-01-22 08:10 UTC by jsoref

At some point, the default layout for various widgets input/textarea/label may have changed a bit. But at least in modern time, the behavior of input-type=checkbox w/ label as rendered w/ the jenkins styles is pretty bad, and the use of td{vertical-align:top} makes for a pretty ugly outcome when a setting interacts with an input.

## Before
![image](https://user-images.githubusercontent.com/2119212/51520839-c7a0b500-1df2-11e9-9375-7f4103a0232f.png)
## After
![image](https://user-images.githubusercontent.com/2119212/51520845-ca9ba580-1df2-11e9-8039-e6704c4d137a.png)

### Proposed changelog entries

* Entry 1: Improve alignment of form widgets with labels

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)

### Desired reviewers

2019-01-22 14:05 UTC, daniel-beck commented
The problem here is that very high fields will have their label centered vertically, way down. What happens in the example once you have 20 API tokens?

2019-01-22 14:40 UTC, jsoref commented
Here's what it looks like today (note: I randomly selected a number of tokens, 11 total by clicking the add button 10 times):
![image](https://user-images.githubusercontent.com/2119212/51542274-dbffa480-1e28-11e9-8b9a-07ab72e01302.png)

Here's what that part would look like with the change:
![image](https://user-images.githubusercontent.com/2119212/51542370-136e5100-1e29-11e9-9eb2-d96ccdd7debc.png)
And that same set from the top of the section:
![image](https://user-images.githubusercontent.com/2119212/51542382-1c5f2280-1e29-11e9-88e2-7117666de072.png)
And from the top of the page:
![image](https://user-images.githubusercontent.com/2119212/51542470-53353880-1e29-11e9-9d81-97471edd5115.png)

In some ways, it would have to be twice as many items as the in this view before middle would actually be worse than top.

This is partially because there aren't too many sections above **API Token**. Admittedly, the rule would apply to other things as well. I'm not sure it's a huge concern, if you're coming from the top, there will probably be a section header, like **API Token**. It's true that eventually it would be offscreen, but, as shown in the first screen, that's actually pretty easy to achieve today.

2019-01-24 09:31 UTC, oleg-nenashev approved these changes
LGTM

2019-01-24 10:17 UTC, Wadeck commented
+) the text area is closer to the sliding stuff at its bottom
-) the middle alignement is bad from my PoV. I don't remember having seen such behavior before and so, as a user, what I am not used to, is bad for my quick / "natural" understanding.

So it's a -1 from me.

2019-01-25 15:59 UTC, oleg-nenashev commented
@Wadeck if you vote -1, could you please request changes next time so that it does not get missed?

2019-01-25 16:05 UTC, Wadeck requested changes
See comments above

2019-01-25 16:17 UTC, jsoref commented
Fwiw, I think the layout used here (labels on the left of another cell) is not commonly used in most of the world.

Most things just use section headings...
(For one, section headings don't eat horizontal real-estate and thus do less harm for mobile displays.)

Would people be open to me redoing all of these things to delete the left column and transition the items to (effectively) `<th>` like things above the corresponding rows?

Here's **Windows 10**  `Settings` > `Wi-Fi` > `Manage known networks`:
![image](https://user-images.githubusercontent.com/2119212/51757494-7f52f280-2091-11e9-9ffb-dd96a36eb39b.png)

Here's **Windows 10** `Feedback Hub` `Add new feedback`: 
![image](https://user-images.githubusercontent.com/2119212/51757708-1cae2680-2092-11e9-8198-46511c15fd0c.png)

Beyond that: how often do you run into a case where this edge matters much?
For the 1-3 item case, it's going to be closer to a natural feel. In the 1 item case, the positioning will be better than what we have today.

And, out of curiosity how many places can you point to where this matters? The token case is afaik a fairly obscure case which I doubt many people use (and certainly expect they wouldn't use for more than a handful of tokens, although I welcome evidence).

2019-01-25 16:38 UTC, Wadeck commented
@jsoref 
> Would people be open to me redoing all of these things to delete the left column and transition the items to (effectively) <th> like things above the corresponding rows?

Please proceed!

I am opposed to the vertical middle alignment when we are using the two columns "design", because it's bad for the reader "flow". As you say, the edge cases are perhaps not numerous, but I just don't understand the goal to do something that is not better for common cases and worse for some corner cases.

If the only purpose is to have the labels on the left aligned with the middle of the one-liner inputs, in that case, I can only propose to add a padding top so that the alignment is good for 95% of the cases and for text-area, there is no issue.

2019-01-25 18:16 UTC, daniel-beck commented
@jsoref 

Regarding your response to,

> The problem here is that very high fields will have their label centered vertically, way down. What happens in the example once you have 20 API tokens?

I'd like to note that you start the page at the top. In a vertically long section as the one with the API tokens, it'd take some additional scrolling to actually see the vertically centered label when you start from the top. That seems like a bigger deal than not seeing it when further down -- you've already seen it.

2019-01-25 18:19 UTC, daniel-beck commented
@jsoref 

> Would people be open to me redoing all of these things to delete the left column and transition the items

Seems like a reasonable idea (a lot of space is wasted due to -- sometimes nested -- label columns), although you should be prepared to encounter massive problems in this endeavor. We can't really overhaul the form structure of nested tables due to https://wiki.jenkins.io/display/JENKINS/Structured+Form+Submission, and plugins sometimes build their own UI elements with the assumption that the structure looks like it currently does.

While it should be relatively possible to change the core UI, Jenkins will need to continue working reasonably well with most plugins, and certainly all popular plugins.

This is easily JEP/SIG levels of difficulty and effort.

2019-08-01 10:47 UTC, alecharp commented
@jsoref would you like to keep this PR open or do you need to have #3895 merged before?

2019-08-01 11:08 UTC, jsoref commented
This is an independent change.

I'm on vacation this week.

2019-09-19 09:06 UTC, alecharp commented
@jsoref would you have time to work on this?

2019-09-19 16:55 UTC, jsoref commented
@alecharp: I'm not sure what people want me to do.

2019-12-12 10:12 UTC, rsandell commented
I'm also -1 on the middle align.

@jsoref I suggest bringing this up in a UX SIG meeting so that this type of work can be coordinated better.

2019-12-12 10:13 UTC, MRamonLeon commented
I'm with @Wadeck here, I see more natural having it at the top, to see it rapidly. I think this change is controversial, maybe not having the left column is better but it's a bigger change. So my proposal is to close this PR.

2019-12-19 10:25 UTC, fcojfernandez commented
> @alecharp: I'm not sure what people want me to do.

I think there is no consensus here, so I would recommend you to open a proposal in the mailing list, @jsoref. If you agree with that I will change the `proposed-for-close` label into a `stalled` label.

Here my opinion as well:
1. For me, it's more natural to have the upper alignment, but not a strong opinion
1. What actually concerns me is that this change in the css might impact other components. Have you checked?

2020-01-03 10:18 UTC, closed without merging