Remove incorrect annotation that overrides return type of AbstractItem#getParentGroup
jenkinsci/jenkins pull request #3949
Opened 2019-03-25 15:46 UTC by TimvdLippe

This annotation overrode the return type of AbstractItem#getParentGroup
to return Jenkins instead of ItemGroup. This would not compile, when a
normal ItemGroup was returned, as that does not extend Jenkins.

We ran into this issue when using Mockito with the new ByteBuddy mockmaker
that would throw a WrongTypeOfReturnValue as it expected a Jenkins
value, but saw an ItemGroup instead.

### Proposed changelog entries

* bug: Remove incorrect annotation that overrides return type of AbstractItem#getParentGroup

### Submitter checklist

- [X] JIRA issue is well described: N/A, minor improvement.
- [X] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [X] Appropriate autotests or explanation to why this change has no tests: N/A, internal code change
- [X] For dependency updates: links to external changelogs and, if possible, full diffs: N/A, no dependency update

2019-03-26 14:28 UTC, TimvdLippe commented
The diff is easier to read with whitespace ignored: https://github.com/jenkinsci/jenkins/pull/3949/files?w=1

2019-03-28 11:16 UTC, daniel-beck commented
This is clearly deliberate: The annotation is required for backwards compatibility. What problem are you trying to solve here?

Also, please configure your IDE to not introduce unnecessary whitespace changes.

2019-03-28 11:29 UTC, daniel-beck commented
Previously added in https://github.com/jenkinsci/jenkins/commit/072556e8c81ba4de2ba3f807f772db41c4ca1fb5 – looks like it might be long enough ago to not matter anymore.

2019-03-28 11:38 UTC, daniel-beck commented
> This annotation overrode the return type of AbstractItem#getParent
> to return Jenkins instead of ItemGroup. This would not compile, when a
> normal ItemGroup was returned, as that does not extend Jenkins.

This should _add_ a new method in the compiled bytecode with the other return type to remain compatible with plugins that have been compiled against older releases of Jenkins. I'm told that's legal (even if impossible to do in Java source code), so looks more like a limitation of your mock framework.

A quick check indicates this change _might_ result in problems in https://plugins.jenkins.io/template-workflows and/or https://plugins.jenkins.io/jenkins-multijob-plugin which call `hudson/model/TopLevelItem#getParent()Lhudson/model/Hudson;`

2019-03-28 12:30 UTC, TimvdLippe commented
> > This annotation overrode the return type of AbstractItem#getParent
> > to return Jenkins instead of ItemGroup. This would not compile, when a
> > normal ItemGroup was returned, as that does not extend Jenkins.
> 
> This should _add_ a new method in the compiled bytecode with the other return type to remain compatible with plugins that have been compiled against older releases of Jenkins. I'm told that's legal (even if impossible to do in Java source code), so looks more like a limitation of your mock framework.

I initially understood the same and that the bytecode would add a new method. However, since this is a getter, there is no possibility to add a new method. Rereading the [JavaDoc of WithBridgeMethods](https://github.com/infradna/bridge-method-injector/blob/f593a9543160a11981619c92ecccb35c65e5b7a4/annotation/src/main/java/com/infradna/tool/bridge_method_injector/WithBridgeMethods.java#L77-L102) leads me to believe that an `adapterMethod` should instead exist to make sure both return types work. In other words, the `adapterMethod` should make sure that those clients who try to retrieve an `Jenkins` rather than a `ItemGroup` would simply work.

Therefore, rather than removing the annotation, I think an extra adapterMethod should be written on this class that can return a `Jenkins` if required. The bytecode would then thus contain both `hudson/model/TopLevelItem#getParent()Ljenkins/model/Jenkins;` and `hudson/model/TopLevelItem#getParent()Lhudson/model/ItemGroup;`

2019-03-28 12:55 UTC, daniel-beck commented
My reading of the doc is that the current code is correct, since `Jenkins instanceof ItemGroup` and that's the straightforward case described in https://github.com/infradna/bridge-method-injector/blob/f593a9543160a11981619c92ecccb35c65e5b7a4/annotation/src/main/java/com/infradna/tool/bridge_method_injector/WithBridgeMethods.java#L57...L76

(Of course there may be a bug in `bridge-method-injector` that results in the behavior you're seeing, I haven't checked the class files.)

2019-04-01 00:38 UTC, daniel-beck commented
https://github.com/infradna/bridge-method-injector/blob/f593a9543160a11981619c92ecccb35c65e5b7a4/injector/src/main/java/com/infradna/tool/bridge_method_injector/MethodInjector.java looks like it only adds methods, never removes them.

2019-04-03 01:29 UTC, jglick requested changes
From the current bytecode:

```
$ javap -c -classpath core/target/classes hudson/model/AbstractItem
…
  public jenkins.model.Jenkins getParent();
    Code:
       0: aload_0
       1: invokevirtual #140                // Method getParent:()Lhudson/model/ItemGroup;
       4: checkcast     #253                // class jenkins/model/Jenkins
       7: areturn
```

which looks right to me. If Mockito cannot handle that, stop using Mockito. Various mock frameworks generally do not work well in Jenkins and should be avoided.

2019-04-03 01:29 UTC, jglick commented on core/src/main/java/hudson/model/AbstractItem.java
> + *
Please configure your editor to not make unrelated whitespace changes.

2019-04-03 10:56 UTC, TimvdLippe commented
> Various mock frameworks generally do not work well in Jenkins and should be avoided.

If various mock frameworks don't work well with Jenkins, I would argue that is a problem in Jenkins and not the mock frameworks.

That said, we internally made this change without any issues. I thought I would upstream it for the benefit of all other Jenkins users. However, that seems to not be happening, thus I am closing this PR.

2019-04-03 10:56 UTC, closed without merging

2019-04-03 15:51 UTC, jglick commented
> If various mock frameworks don't work well with Jenkins, I would argue that is a problem in Jenkins and not the mock frameworks.

Certainly it was not designed with testability in mind, but it is much too late to change that.