Fix getting information on AIX processes not owned by the current user
jenkinsci/jenkins pull request #3964
Opened 2019-04-03 18:07 UTC by robert-shade

See [JENKINS-56868](https://issues.jenkins-ci.org/browse/JENKINS-56868).

### Proposed changelog entries

* Fix getting information on AIX processes not owned by the current user

2019-04-26 14:18 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessTree.java
> +                    // so don't report this as an error.
Would be nice to have some system logging at least, e.g. on the FINE level

2019-04-26 14:18 UTC, oleg-nenashev commented on core/src/main/java/hudson/util/ProcessTree.java
> +            protected boolean is64BitProcess() {
Do you plan to have any API consumers outside? If not, it might be better to just make it private

2019-05-01 09:10 UTC, oleg-nenashev requested changes
Minor changes are needed before landing this PR.
We do not have any kind of test automation for AIX, but such changes are OK since they do not put other platforms at risk

2019-05-08 16:46 UTC, oleg-nenashev commented
@robert-shade Are you still interested in it?

2019-12-12 10:34 UTC, MRamonLeon commented
@robert-shade could you address @oleg-nenashev's request? In another way, we need to close this PR. Thanks!

2019-12-19 10:15 UTC, fcojfernandez commented
Since there hasn't been more activity on this issue I'm closing the PR. Please feel free to re-open if you can work on this again and address the feedback from Oleg.

2019-12-19 10:15 UTC, closed without merging