[JENKINS-16360] @DataBoundConstructor/@DataBoundSetter for FreeStyleProject
jenkinsci/jenkins pull request #3979
Opened 2019-04-11 18:52 UTC by daspilker

See [JENKINS-16360](https://issues.jenkins-ci.org/browse/JENKINS-16360).

The ticket is about generating Job DSL scripts from existing job definitions. It is one of the most requested features for Job DSL.

The approach is (similar to Pipeline) to use structs-plugin to uninstantiate ([UninstantiatedDescribable.java](https://github.com/jenkinsci/structs-plugin/blob/structs-parent-1.17/plugin/src/main/java/org/jenkinsci/plugins/structs/describable/UninstantiatedDescribable.java#L171)) a job and use the information to generate a Job DSL script.

To be able to uninstantiate a job, it must provide valid `@DataBoundConstructor` and `@DataBoundSetter`s with matching getters. As a start this PR adds the relevant annotations and methods to `FreeStyleProject` and it's super classes. Missing getters are also added to the Maven builder to be able to uninstantiate all builders provided by core.

The first milestone for this feature is to be able to generate scripts for all parts (FreeStyleProject, Maven builder, Fingerprint publisher, etc) provided by core.

See https://github.com/jenkinsci/job-dsl-plugin/pull/1171 for the Job DSL part of JENKINS-16360.

### Proposed changelog entries

* Internal: JENKINS-16360, add `@DataBoundConstructor` and `@DataBoundSetter` for `FreeStyleProject`

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jglick

2019-04-11 19:46 UTC, jglick requested changes
Interesting, though I think there are going to be tricky things here. What we really need (IMO) is full-fledged support for `TopLevelItem` definitions in `configuration-as-code` YAML, not via `job-dsl`.

2019-04-11 19:46 UTC, jglick commented on core/src/main/java/hudson/model/FreeStyleProject.java
> +    @DataBoundConstructor
This is not right. It is not intended to be instantiated like a common `Describable`. Calls to `TopLevelItemDescriptor.newInstance(ItemGroup, String)` (which is the official API here, _not_ direct constructor calls) must be made explicitly by `job-dsl`. The situation is similar to a `GlobalConfiguration`, for example, where you may define `@DataBoundSetter`s for modifying properties of an existing object, but a special code path is used to actually get to the initial default instance.

2019-04-11 19:46 UTC, jglick commented on core/src/main/java/hudson/model/Job.java
> +        throw new UnsupportedOperationException();
Huh? (Ditto elsewhere.)

2019-04-11 19:46 UTC, jglick commented on core/src/main/java/hudson/tasks/Maven.java
> +    public String getPom() {
Why? The field is already `public`. That suffices for databinding.

2019-04-11 19:46 UTC, jglick commented on test-pom/pom.xml
> +      <version>1.3</version>
Why not newer?

2019-04-11 19:48 UTC, jglick commented on core/src/main/java/hudson/model/FreeStyleProject.java
> +    @DataBoundConstructor
Or for the reverse case, of introspecting a `TopLevelItem` and enumerating its properties as a `Map<String, Object>` (_not_ an `UninstantiatedDescribable`), we would need a new API in `structs`.

2020-01-09 09:56 UTC, MRamonLeon commented
@daspilker could you please address Jesse's comments and resolve the conflicts? Thank you.

2020-01-16 10:19 UTC, fcojfernandez commented
Taking into account that there's not activity since Apr'19, changes have been requested and there are conflicts to resolve, I'm proposing for close. @daspilker please let me know if you're still interesting in working on this and I will remove the label.

2020-01-23 10:52 UTC, MRamonLeon commented
@daspilker Feel free to reopen if you have enough bandwidth to work on it to address Jesse's comments.

2020-01-23 10:52 UTC, closed without merging