Rejuvenate log levels
jenkinsci/jenkins pull request #4007
Opened 2019-05-01 19:38 UTC by khatchad

## Introduction

We are in the process of evaluating our [research prototype Eclipse plug-in](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin) that "rejuvenates" log statement levels based on how "interesting" the enclosing methods are to the developers. We hypothesize that portions of a system that are worked on more and more recently should have higher log levels (e.g., INFO as compared to FINEST) and vice-versa. This places event logs related to tasks that are currently more important to the forefront while pushing event logs pertaining to tasks worked on in the past to the background. The goal is to reduce information overload, bring more relevant events to developers' attention, and alleviate developers from manually making log level changes.

The transformation decision is made by analyzing the "degree of interest" (DOI) values of enclosing methods for logging invocations. DOI value is a kind of real number for a program element which shows how developers are interested in it. It is computed from the interaction events between developer and program elements, such as edits. In this project, we calculate the DOI using the project's git history.

We are looking for feedback on our tool from developers. If you can, we would appreciate if you can **comment on each of the transformations** in the case that this PR is not accepted. Of course, we would also love to contribute to your project.

## Settings

We have several analysis settings. We can vary these settings and rerun if you desire. The settings we are using in this pull request are:

1. Treat CONFIG, WARNING, and SEVERE levels as a category and not a traditional level, i.e., our tool ignores these log levels.
1. Never lower the logging level of logging statements within catch blocks.
1. Never lower the logging level of logging statements within if statements.
1. Avoid log wrapping by disregarding logging statements contained in if statements mentioning log levels.
1. The greatest number of commits evaluated: 1000.

The head at time of analysis was: 44c4d3989232082c254d27ae360aa810669f44b7

2019-05-01 20:41 UTC, daniel-beck requested changes
Several log messages that exist to inform admins about the state of Jenkins have been demoted from the visible-by-default INFO to FINE or FINER.

I don't think the premise of this change reflects actual use of log statements in Jenkins, which is informing admins or helping troubleshooting by admins, rather than providing assistance to developers. Perhaps this idea does not take into account the distribution model of Jenkins as an installable software?

2019-05-01 20:41 UTC, daniel-beck commented on core/src/main/java/hudson/ExtensionFinder.java
> +                            LOGGER.log(Level.FINEST, "Failed to instantiate optional component {0}; skipping", key.getTypeLiteral());
Important information for admins.

2019-05-01 20:41 UTC, daniel-beck commented on core/src/main/java/hudson/ClassicPluginStrategy.java
> +            LOGGER.log(Level.FINEST, "Updated dependency of {0}", depender.getShortName());
No.

2019-05-01 20:41 UTC, daniel-beck commented on core/src/main/java/hudson/ClassicPluginStrategy.java
> +            LOGGER.finest("Plugin " + archive.getName() + " is disabled");
No.

2019-05-01 20:41 UTC, daniel-beck commented on core/src/main/java/hudson/FilePath.java
> +                                LOGGER.log(Level.FINEST,
No.

2019-05-02 16:37 UTC, khatchad commented
Thank you for your insightful feedback, @daniel-beck. Indeed, there can be long running events (like server monitoring, as you mentioned) that developers may not be interested in long term but users would be. We have thought of perhaps [annotating certain logs to prevent transformations](https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/issues/205) as a way to alleviate this problem.

2019-05-02 17:03 UTC, khatchad commented
I've also noticed that some of the logs you pointed out as being incorrect have keywords like "failed" and "disabled."  Filed https://github.com/ponder-lab/Optimize-Java-8-Streams-Refactoring/issues/204.

2019-05-02 17:08 UTC, khatchad reviewed
Addressed review comments in https://github.com/jenkinsci/jenkins/pull/4007/commits/8f2cfaf9f075cbeb7c742948b392f0bbcfb23d3f.

2019-05-03 01:46 UTC, daniel-beck reviewed
I highlighted a few more changes I consider not appropriate in this review. As above, I think the use case you're targeting is one different from how Jenkins is usually used, so your heuristics don't seem to match well here.

Thank you very much for your contribution, but I will not review this further. The work to do that properly, and iterate what what I would consider bad choices, seems out of proportion for the potential benefit offered by this change. Of course, this is just my evaluation, perhaps another maintainer is interested in working on this with you further.

Thanks again for considering Jenkins for your work, and submitting this!

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/WebAppMain.java
> +                        LOGGER.finest("Jenkins is fully up and running");
Important life cycle event.

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/WebAppMain.java
> +                LOGGER.log(Level.FINEST, "Shutting down a Jenkins instance that was still starting up", new Throwable("reason"));
Would rather go with upgrade over downgrade here, unless this would be a redundant message.

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/AllView.java
> +                        LOGGER.log(Level.FINEST,
This is a data migration

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/Computer.java
> +                    LOGGER.log(Level.FINEST, "Relocated log file {0} to {1}",new Object[] {f.getPath(),newLocation.getPath()});
Data migration

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/DisplayNameListener.java
> +                    LOGGER.finest(String.format("onRenamed():Setting displayname to null for item.name=%s", item.getName()));
This is probably fine, but also an internal data change.

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/DownloadService.java
> +            LOGGER.finest("Obtained the updated data file for "+id);
Pretty sure these are useful to users.

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/FullDuplexHttpChannel.java
> +                LOGGER.log(Level.FINEST, "Duplex-HTTP session " + uuid + " is terminated", diagnosis);
This is a nonfatal error.

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/ResourceList.java
> +                    LOGGER.finest("Collision with " + r + " and " + l);
Seems notable

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/UpdateCenter.java
> +                LOGGER.finest("Scheduling Jenkins reboot");
lifecycle event

2019-05-03 01:46 UTC, daniel-beck commented on core/src/main/java/hudson/model/UpdateCenter.java
> +                        LOGGER.finest("Scheduled Jenkins reboot unscheduled");
corresponds to the over log message

2019-05-03 18:54 UTC, khatchad commented
> I highlighted a few more changes I consider not appropriate in this review.

Thank you again, @daniel-beck. We were able to extract some keywords of the log messages that avoided some of the transformations you pointed out.

> As above, I think the use case you're targeting is one different from how Jenkins is usually used, so your heuristics don't seem to match well here.

Yes, noted. It may be that this kind of approach would work better in different settings.

> Thank you very much for your contribution, but I will not review this further. The work to do that properly, and iterate what what I would consider bad choices, seems out of proportion for the potential benefit offered by this change. Of course, this is just my evaluation, perhaps another maintainer is interested in working on this with you further.

Understood. We really appreciate the work you've done so far. It's very useful!

> Thanks again for considering Jenkins for your work, and submitting this!

Thank you again for the feedback! We will use the ones you've labeled thus far. Your project had many transformations, and we completely understand that it is infeasible to review so many of them.

2019-05-03 19:07 UTC, khatchad commented
BTW @daniel-beck is it safe to say that you stopped reviewing at https://github.com/jenkinsci/jenkins/pull/4007/files/8f2cfaf9f075cbeb7c742948b392f0bbcfb23d3f#r280647490?

2019-05-04 15:52 UTC, daniel-beck commented
@khatchad 

> BTW @daniel-beck is it safe to say that you stopped reviewing at https://github.com/jenkinsci/jenkins/pull/4007/files/8f2cfaf9f075cbeb7c742948b392f0bbcfb23d3f#r280647490?

Yes, scrolled from top to bottom and stopped there. I looked specifically at change involving INFO only though, as the way Jenkins is set up those messages (and up) are shown by default. So those changes would have the greatest impact.

As far as I can tell, only relatively few loggers in Jenkins meaningfully differentiate between fine/finer/finest, so as long as users know what they're looking for in setting up the specific logger to record messages, they are mostly interchangeable.

2019-10-11 22:38 UTC, daniel-beck commented
Looks abandoned and has conflicts, so for now I'm closing this as general housekeeping.

2019-10-11 22:38 UTC, closed without merging

2019-10-14 14:07 UTC, khatchad commented
Hi @daniel-beck. @saledouble is working on a bug fix using your feedback. Thank you again for your help!