Make WindowsUtil available for use
jenkinsci/jenkins pull request #4038
Opened 2019-05-23 15:29 UTC by res0nance

This change is came about as a follow up to jenkinsci/ec2-plugin#352 where this class had to be copied to ensure proper character escaping on Windows and would likely be useful elsewhere.

### Proposed changelog entries

* Internal: Move WindowsUtil out of test

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

2019-05-23 15:30 UTC, jvz commented on core/src/main/java/hudson/os/WindowsUtil.java
> +        if(Functions.isWindows() == false) {
```suggestion
        if (!Functions.isWindows()) {
```

2019-05-23 15:44 UTC, jvz approved these changes
Looks good to me. I leave an open question on whether or not all the methods in this class should be unrestricted as is.

2019-06-04 14:54 UTC, varyvol commented
@res0nance What do you think about checking for a Windows platform in all methods? I know it was not done before but it might be a good moment.

2019-06-05 03:36 UTC, res0nance commented
@varyvol If we are using this util to quote arguments for running on an agent and we checked for windows platforms with linux master it will throw

2019-06-05 07:20 UTC, varyvol commented
@res0nance as I see it, if that method is being used for situations other than Windows....then it shouldn't be in a class called WindowsUtil.

2019-06-05 10:37 UTC, res0nance commented
The current usage was to use it to quote arguments for the EC2 plugin's winrm launcher

2019-06-06 17:00 UTC, jvz commented
The only Windows-specific stuff in this class are the functions to support directory junctions, and that's only used in a unit test so far. This tool could be useful when your master is on Linux but you have a Windows agent.

2019-06-13 20:31 UTC, oleg-nenashev requested changes
The change itself looks good to me, but it lacks Javadoc. Also., it would be better to move the new code somewhere under https://github.com/jenkinsci/jenkins/tree/master/core/src/main/java/jenkins/util instead of the old `hudson` package

2019-06-15 09:26 UTC, oleg-nenashev approved these changes
Just minor suggestions in Javadoc,, LGTM

2019-06-15 09:26 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/WindowsUtil.java
> + * Utilities for the Windows Platform
```suggestion
 * Utilities for the Windows Platform.
```

2019-06-15 09:26 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/WindowsUtil.java
> + * adapted from:
```suggestion
 * Adapted from:
```

2019-06-15 09:26 UTC, oleg-nenashev commented on core/src/main/java/jenkins/util/WindowsUtil.java
> + */
```suggestion
 *
 * @since TODO
 */
```

2019-06-15 18:04 UTC, oleg-nenashev approved these changes
Thanks! Will merge once the build passes

2019-06-24 12:19 UTC, oleg-nenashev commented
I definitely forgot about it :(

2019-06-24 12:19 UTC, merged

2019-06-24 12:20 UTC, oleg-nenashev commented
Thanks @res0nance !

2019-07-02 07:09 UTC, daniel-beck commented
How does https://github.com/jenkinsci/jenkins/blob/4404c6e662befe16e8daa1ea7a412df73b370086/core/src/main/java/jenkins/util/WindowsUtil.java#L25 even compile?

2019-07-02 10:34 UTC, res0nance commented
@daniel-beck Wow now that you mention it I'm kinda amazed this works. Will refactor.

2019-07-02 14:44 UTC, jvz commented
Ha, it works because Java only _recommends_ that the directory structure match the package name. That's not necessary, though it will likely break any code that assumes a one-to-one correspondence between a fully qualified class name and its respective filepath.

2019-07-02 15:16 UTC, daniel-beck commented
@jvz So… we actually made this available as `hudson.os.WindowsUtil` to plugins…?

2019-07-02 16:29 UTC, jvz commented
It appears so.