[JENKINS-27413]  Handle file parameters on pipeline builds
jenkinsci/jenkins pull request #4070
Opened 2019-06-16 14:34 UTC by octavifs

Fixes [JENKINS-27413] and [JENKINS-47333] (duplicate).

Adds file parameter support on pipeline jobs, while maintaining compatibility
with freestyle projects.

[JENKINS-27413]: https://issues.jenkins-ci.org/browse/JENKINS-27413
[JENKINS-47333]: https://issues.jenkins-ci.org/browse/JENKINS-47333

#### Detailed report of the bug
Freestyle Jobs are executed by `hudson.model.Build`. As part of the workflow, `ParameterAction` `BuildWrapper`'s are created and invoked, which in the case of a `FileParameterValue` results in copying the file to the desired location within the workspace.

When working with pipelines (executed by `org.jenkinsci.plugins.workflow.job.WorkflowJob`), there are no calls to the parameters `BuildWrapper`, so the side effect is not triggered and the files not copied, thus the bug.

#### Proposal

`FileParameterValue` is the only `ParameterValue` that requires execution of side effects (via `BuildWrapper`). The rest of `ParameterValue` subclasses are properly set once `ParameterValue.buildEnvironment()` is called. This call to `buildEnvironment()` is performed both by Freestyle jobs and Pipelines alike.

My proposal moves the execution of the side effect of copying the file from the `BuildWrapper` to `buildEnvironment()` itself. I've added an internal variable to keep track of the `FileParameterValue` so the copying is only performed once.

#### Pipeline example
Example pipeline to showcase the fix working

	pipeline {
	    agent any

	    parameters {
	        file(
	            name: 'example.txt',
	            description: 'This is an example to showcase JENKINS-27413'
	        )
	    }

	    stages {
	        stage('showcase JENKINS-27413') {
	            steps {
	                // Install conda environment
	                sh """
	                    cat example.txt
	                """
	            }
	        }
	    }
	}

### Proposed changelog entries

- Fixed file build parameters with pipeline jobs
- Moved `FileParameterValue` side effects from `createBuildWrapper()` to `buildEnvironment()` to add compatibility with workflow jobs
- Fixed `FileParameterValue.doDynamic()` to allow for parameter inspection once the task has been executed (previous cast was dependant on FreeStyleJob)

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change).
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

2019-06-16 14:37 UTC, octavifs commented
To add a bit of extra context, I found out about this issue early this week, when I was writing some pipelines that would really benefit from the file parameter feature and I thought it was a real shame that this functionality was not working, so I decided to give it a go.

I am no expert on Jenkins internals, and this fix, while it resolves the issue, might not be optimal from an architectural point of view. I am aware that forcing a method used to populate environment variables to carry out side effects is not ideal, but it has the benefit of requiring minimal impact on the project architecture, and it brings `FileParameterValue` closer to how the rest of `ParameterValue` classes work.

If you have ideas in how this could be done in a more harmonious way, I'm willing to give it a go. On the other hand, if you think this is an adequate solution, let me know and I'll write tests for the PR before the merge.

2019-06-21 18:31 UTC, jglick requested changes
I do not believe `FileParameterDefinition` is salvageable. Ideally it would be detached to a plugin and deprecated. My [last recommendation](https://issues.jenkins-ci.org/browse/JENKINS-27413?focusedCommentId=352030&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-352030) stands.

2019-06-21 18:31 UTC, jglick commented on core/src/main/java/hudson/model/FileParameterValue.java
> +            ws = Jenkins.get().getWorkspaceFor(project);
Nope, this is the workspace on the “master node”, which in a properly secured system is not used at all. There simply _is_ no equivalent of this concept for Pipeline builds—they can have zero or more workspaces on diverse nodes.

2019-07-03 17:44 UTC, octavifs commented
Hi @jglick, thanks for the feedback. I'll close this PR, and if anything, come back with a new plugin to replicate the functionality, as per your recommendation.
Cheers!

2019-07-03 17:44 UTC, closed without merging

2024-07-24 12:07 UTC, jglick commented
https://plugins.jenkins.io/file-parameters/ FTR