IntelliJ/Java: Duplicate code -- Refactored as ExtensionFinder.getClassFromIndex
jenkinsci/jenkins pull request #4079
Opened 2019-06-18 20:30 UTC by jsoref

This is for discussion.

Notes:
* Commits was probably created by IntelliJ for #4034
* In general, commits should not change program behavior at all

### Proposed changelog entries

* `Internal:` Internal Java code cleanup

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers
@Wadeck

2019-06-19 14:32 UTC, Wadeck approved these changes
Thx for the split, lot easier to review the changes!

nitpick: as you modified the duplicate code, you can ensure consistency by putting `{ ... }` around the last `else` statement (the one for `throw new AssertionError();`) (looking forward to have a better multiline suggestion feature from GH)

2019-06-19 15:07 UTC, jsoref commented
@Wadeck: added as a distinct commit because there are two places where that seems useful.

2019-06-27 15:53 UTC, oleg-nenashev requested changes
It is a protected method in the public class, so formally it is a part of binary API. Please either add Javadoc (with `@since TODO`) or make it private. The rest looks good to me

2019-06-27 18:56 UTC, jsoref commented on core/src/main/java/hudson/ExtensionFinder.java
> +    private static Class<?> getClassFromIndex(IndexItem<Extension, Object> item) throws InstantiationException {
@oleg-nenashev: marked as private

2019-06-27 19:22 UTC, jvz approved these changes

2019-06-27 19:54 UTC, oleg-nenashev approved these changes
Thanks!

2019-06-28 19:59 UTC, merged