[JENKINS-58157] keep fixed length for the delete build button
jenkinsci/jenkins pull request #4088
Opened 2019-06-25 05:27 UTC by mmh891113

@jsoref 
@oleg-nenashev 

donot add build displayName to the "delete build" button

fix "delete build" button too long,https://issues.jenkins-ci.org/browse/JENKINS-58157

this issue come from this commit: [JENKINS-55848] Identify the name of the thing being deleted (#3871)
revert  core/src/main/resources/hudson/model/Run/delete.jelly
revert  core/src/main/resources/hudson/model/Run/delete.properties

Signed-off-by: Mamh-Linux <bright.ma@blackshark.com>

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

2019-06-25 05:29 UTC, oleg-nenashev commented
Other localizations may need an update though it is better to have more feedback from reviewers first

2019-06-25 06:13 UTC, mmh891113 commented
> Other localizations may need an update though it is better to have more feedback from reviewers first

this patch just revert the two files. there is no impact the localizations. the localizations keep the same as before.
I test EN and zh_CN,zh_TW it show OK.

2019-06-25 10:27 UTC, daniel-beck requested changes
This negates the usability improvements of the original change.

I would consider it rather unlikely that display names are very long in general, and the problem isn't a severe one when it occurs, so I'd rather see a proper solution, perhaps involving label trimming, rather than a simple revert.

2019-06-26 01:20 UTC, mmh891113 commented
> This negates the usability improvements of the original change.

This revert just keep "delete build" button  the previous.
I think It's better to keep  the side-panel  short.

2019-06-28 01:59 UTC, LinuxSuRen requested changes
Please keep sync with other localization plugins if you want to make a change about the localization.

2019-06-28 01:59 UTC, LinuxSuRen commented on core/src/main/resources/hudson/model/Run/delete.jelly
> +</j:jelly>
We usually keep the last blank line

2019-06-28 04:32 UTC, closed without merging

2019-06-28 05:09 UTC, mmh891113 commented
i force push to my master close this PR......