[JENKINS-58157] keep fixed length for the delete build button
jenkinsci/jenkins pull request #4090
Opened 2019-06-28 05:31 UTC by mmh891113

donot add build displayName to the "delete build" button

fix "delete build" button too long,https://issues.jenkins-ci.org/browse/JENKINS-58157

this issue come from this commit: [JENKINS-55848] Identify the name of the thing being deleted (#3871)
revert  core/src/main/resources/hudson/model/Run/delete.jelly
revert  core/src/main/resources/hudson/model/Run/delete.properties

Signed-off-by: Mamh-Linux <bright.ma@blackshark.com>

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

2019-06-30 16:31 UTC, daniel-beck requested changes
https://github.com/jenkinsci/jenkins/pull/4088#pullrequestreview-253911503 still applies.

2019-07-10 09:50 UTC, mmh891113 commented
> [#4088 (review)](https://github.com/jenkinsci/jenkins/pull/4088#pullrequestreview-253911503) still applies.

i force push to my master branch,  this PR was closed
can we reopen it ?

2019-07-10 10:04 UTC, oleg-nenashev commented
> can we reopen it ?

We cannot, because there is already another open PR for this branch

2019-08-16 10:39 UTC, oleg-nenashev commented
@mmh891113 are you still interested in this PR?

2019-08-16 21:27 UTC, zbynek commented
@oleg-nenashev maybe this PR can be closed as https://github.com/jenkinsci/jenkins/pull/4121 fixes this problem in a way compatible with @daniel-beck 's suggestion.

2019-08-16 23:03 UTC, oleg-nenashev commented
Agreed

2019-08-16 23:03 UTC, closed without merging

2019-08-16 23:03 UTC, oleg-nenashev commented
Thanks anyway @mmh891113 !