Make disk usage checker period configurable and reduce default period
jenkinsci/jenkins pull request #4105
Opened 2019-07-09 07:45 UTC by bozaro

Disk usage checker also used by `Free Space Threshold` to take nodes without enough free space offline. As a result, this threshold can be triggered with an hour delay.

See [JENKINS-13246](https://issues.jenkins-ci.org/browse/JENKINS-13246)

### Proposed changelog entries

 * Make disk usage checker period configurable by `hudson.diagnosis.HudsonHomeDiskUsageChecker.period` (milliseconds) property;
 * Change default disk usage checker period: 60 min -> 5 min.

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

2019-07-09 07:53 UTC, oleg-nenashev commented
I am perfectly fine with making it configurable, but I am not sure about changing the defaults. ` java.io.File.getUsableSpace()` execution time and overheads are not specified, and they depend on a filesystem. Increasing the frequency may lead to side effects.

2019-07-09 08:06 UTC, bozaro commented
As I understand `java.io.File.getUsableSpace()` make something like `df` and it should be cheap enough operation to run ones in 5 minutes per host.
With current check period option `Free Space Threshold` looks like useless.

2019-07-11 15:00 UTC, oleg-nenashev submitted a review, later dismissed
I am still not 100% fine about changing the interval, but weak +1

2019-07-11 15:15 UTC, oleg-nenashev reviewed
After some consideration, I think more reviews by @jenkinsci/core are needed. It is not just a single monitor, all monitors will change the period

2019-07-11 15:22 UTC, MRamonLeon requested changes
The root ticket of this PR is asking for a low frequency because it could be disruptive, mainly on big installations (a lot of nodes). But his PR is doing the opposite, changing the frequency from 60' to just 5'. It's good to have it configurable, but de default value doesn't seem to be fine. Even more when it's the default value of all monitors. We are adding a lot more load to the instances. I propose:
* Keep the default value the same (60')
* Change the unit of the System Property to minutes, instead of milliseconds

2019-07-12 20:34 UTC, bozaro commented
I change unit and rename system property.
I return old default value to 60 minutes, but I still sure, that this default valut is incredible big.

2019-07-12 21:04 UTC, oleg-nenashev approved these changes

2019-07-13 11:23 UTC, MRamonLeon commented on core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
> +    private static int PERIOD_MINUTES = SystemProperties.getInteger(AbstractNodeMonitorDescriptor.class.getName() + ".periodMinutes", 60);
```suggestion
    private static long PERIOD = SystemProperties.getLong(AbstractNodeMonitorDescriptor.class.getName() + ".period", TimeUnit.MINUTES.toMillis(5));
```
The type expected for scheduling is long and you avoid converting in both constructors: `AbstractNodeMonitorDescriptor()` and `AbstractNodeMonitorDescriptor(Class<? extends NodeMonitor> clazz)`

2019-07-13 11:29 UTC, MRamonLeon commented on core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
> +        this(TimeUnit.MINUTES.toMillis(PERIOD_MINUTES));
```suggestion
        this(PERIOD));
```

2019-07-13 11:29 UTC, MRamonLeon commented on core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
> +        this(clazz,TimeUnit.MINUTES.toMillis(PERIOD_MINUTES));
```suggestion
        this(clazz,PERIOD);
```

2019-07-14 12:12 UTC, MRamonLeon approved these changes
Thank you!

2019-07-17 09:12 UTC, alecharp approved these changes
Thanks @bozaro, this looks good with keeping the default of 60 minutes.

2019-07-17 09:12 UTC, varyvol approved these changes

2019-07-17 09:47 UTC, oleg-nenashev commented
Will merge tomorrow if no negative feedback

2019-07-18 08:20 UTC, merged

2019-07-22 08:15 UTC, daniel-beck commented
This appears to change _all_ node monitor intervals, not just the disk usage checker as the original comment claims.

2019-07-22 08:16 UTC, daniel-beck commented
Also not documented on the wiki page.

2019-07-22 08:17 UTC, daniel-beck commented
Proposed changelog entries do not match implementation 👎

2019-07-22 08:18 UTC, oleg-nenashev commented
@daniel-beck . I am sure I have edited it, but looks like I forgot to save the change. Sorry about that