[JENKINS-58494] - Remove dependency on Jenkins CLI from the core
jenkinsci/jenkins pull request #4110
Opened 2019-07-15 11:46 UTC by oleg-nenashev

From what I see, such change is required to fix https://issues.jenkins-ci.org/browse/JENKINS-58483 . See [JENKINS-58494](https://issues.jenkins-ci.org/browse/JENKINS-58494) for a proposal. Jenkins core currently includes Jenkins CLI as a dependency, and hence there is no way to split the CLI code and the Core codebase. There is little justification to keep the dependency, and IMHO we should not do so.

With this change, jenkins.py will have just another regression due to the removal of the deprecated `CliTransportAuthenticator` class. But I doubt this code is alive after JEP-200 anyway

What was changed here?

- [x] The dependency was removed from the core
- [x] CLI jar discovery was reworked to avoid dependencies on the class
- [x] Deprecated `CliTransportAuthenticator` was removed
- [x] QuotedStringTokenizer was copy-pasted and added to the core to avoid massive compatibility changes in the downstream plugins

I cannot say for sure that anything except jenkins.py does not depend on the CLI classes. Needs careful reviews

### Proposed changelog entries

* RFE: Remove the dependency on Jenkins CLI from the Jenkins Core

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

2019-07-15 11:52 UTC, oleg-nenashev commented
Not gonna work until `PlainCLIProtocol` is fixed. There are 2 ways:

* Copy-paste `PlainCLIProtocol#EitherSide` so that master and agent have their own implementations
* Introduce a new library which would hold only the relevant classes to be shared between CLI and the core
* Fallback to the original code and just do the dependency exclusions

2019-07-15 13:31 UTC, jglick requested changes
Duplication of `PlainCLIProtocol` seems too dangerous.

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/cli/CliTransportAuthenticator.java
> -public abstract class CliTransportAuthenticator implements ExtensionPoint {
Fine, this was removed in `ssh-cli-auth` 1.5, which we now bundle.

2019-07-15 13:31 UTC, jglick commented on cli/src/main/java/hudson/cli/CLIQuotedStringTokenizer.java
> +    extends StringTokenizer
Make a note of where in Jenkins sources it was copied from.

Did you check for some Commons utility to do something sufficiently similar?

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/cli/DiagnosedStreamCorruptionException.java
> +// TODO COPIED FROM hudson.remoting
So why are we copying it? If it is just not `public` in `remoting`, then file a PR to fix that please…

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/cli/FlightRecorderInputStream.java
> +// TODO COPIED FROM hudson.remoting
ditto

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/cli/HexDump.java
> +// TODO COPIED FROM hudson.remoting
ditto

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/model/Slave.java
> +                // We know that Remoting CLI and Jenkins CLI are located in the same directory.
Not sure I am following where you are making use of that assumption.

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/util/QuotedStringTokenizer.java
> + * This class was originally in the CLI package, but it was moved to the Jenkins Core as a part of
As part of…?

Why is this comment important to a reader? Just omit it.

2019-07-15 13:31 UTC, jglick commented on test/src/test/java/hudson/model/SlaveTest.java
> +       assertJnlpJarUrlIsAllowed(slave, "hudson-cli.jar");
Why the reindentation?

2019-07-15 13:31 UTC, jglick commented on test/src/test/java/hudson/model/SlaveTest.java
> +        // Spot-check correct requests
Why is this test being split in half?

2019-07-15 13:31 UTC, jglick commented on core/src/main/java/hudson/cli/PlainCLIProtocol.java
> +    private enum Op {
Not comfortable with the protocol definition and `EitherSide` being duplicated. Just introduce a new Maven module with `jar` packaging for the common code between `cli` and `jenkins-core`.

2019-07-15 13:33 UTC, jglick commented
> From what I see, such change is required to fix https://issues.jenkins-ci.org/browse/JENKINS-58483 .

#4111 claims to do so, so this PR description is not actually true any more, right?

2019-07-15 13:36 UTC, jglick commented
Also, this does not compile in `core` (`HelpCommand`), and I suppose you will have to adjust POMs to make sure the CLI überjar is still included in the WAR, and the CLI JAR is still a `test`-scoped dependency of the `test` module.

2019-07-15 14:00 UTC, oleg-nenashev commented
> #4111 claims to do so, so this PR description is not actually true any more, right?

This PR is a more aggressive version of #4111 which removes the CLI dependnecy entirely. As you may see, it is not going to work as is, so #4111 is a priority for me ATM. Once that PR is merged, I will consider finalizing this one

2019-07-26 14:26 UTC, oleg-nenashev commented
@jenkinsci/core Would it make sense to have a new `jenkins-cli-base-lib` (or whatever) which stores the code shared between the Master-side and CLI side? It might be a submodule here or a new library repository

2019-07-26 14:46 UTC, fcojfernandez commented
My vote is for an external library with the share code there. Instead of having a dependency on `cli` both parts can have a dependency on that library

2019-07-26 15:12 UTC, jglick commented
> Would it make sense to have a new `jenkins-cli-base-lib` (or whatever) which stores the code shared between the Master-side and CLI side?

That was my recommendation.

> It might be a submodule here or a new library repository

Submodule. There is no reason I can see to move this code to a different repository, unless you plan to move the whole CLI client as well.

2019-09-09 07:59 UTC, ndeloof approved these changes

2019-10-11 22:28 UTC, daniel-beck commented on cli/src/main/java/hudson/cli/CLIQuotedStringTokenizer.java
> +public class CLIQuotedStringTokenizer
`@Restricted`?

2019-11-28 10:53 UTC, varyvol commented
@oleg-nenashev  do you intend to keep working on this? Otherwise we could propose it for close and it can be reopen when necessary.

2019-11-28 11:00 UTC, oleg-nenashev commented
No plans to work on it in the foreseeable future. The implementation will need a full rework anyway, hence closing

2019-11-28 11:00 UTC, closed without merging