Correct package name
jenkinsci/jenkins pull request #4116
Opened 2019-07-17 14:28 UTC by res0nance

- Correct the package name from #4038 

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

2019-07-17 14:40 UTC, oleg-nenashev commented
oops, did not notice it. We cannot just rename it unfortunately. It would impact binary compatibility
But we can introduce a deprecated class in `hudson.os` which just inherits the "new class"

2019-07-17 14:47 UTC, res0nance commented
Makes sense, I'm fixing the references to it in the tests then I can add the deprecated stub after.

2019-07-17 16:13 UTC, daniel-beck requested changes
I would move the file to the specified (`hudson.…`) package and move on. No need to include more code for this simple mistake.

Please do not include unnecessary whitespace changes.

2019-07-26 14:11 UTC, oleg-nenashev commented
@res0nance We do not get GitHub notifications on Force pushes. Please avoid using them, we can always squash commits during merge

2019-07-26 14:14 UTC, oleg-nenashev requested changes
It still causes binary compatibility issues. I am ready to accept a "quick fix" sugestion by @daniel-beck where we just move the code to the right directory so that it stays in `hudson.os`. Not ideal, but we can live with that to save time

2019-07-26 14:14 UTC, oleg-nenashev commented on core/src/test/java/hudson/FilePathTest.java
> - *
All the formatting changes are not related. Please submit refactoring separately

2019-07-26 14:51 UTC, res0nance commented
I just moved the file as per @daniel-beck suggestion

2019-07-26 14:57 UTC, oleg-nenashev approved these changes

2019-08-14 20:05 UTC, jeffret-b approved these changes
It will be good to get this corrected quickly so it makes more sense.

2019-08-16 07:56 UTC, oleg-nenashev approved these changes

2019-08-16 07:56 UTC, merged