[JENKINS-58734] Use SHA-256 for crumbs
jenkinsci/jenkins pull request #4134
Opened 2019-07-30 20:41 UTC by jvz

Signed-off-by: Matt Sicker <boards@gmail.com>

See [JENKINS-58734](https://issues.jenkins-ci.org/browse/JENKINS-58734). I ran all the unit tests locally and had no problems there, and I know there are numerous tests that implicitly exercise crumb issuance. I suppose there's a potentially open question regarding whether or not we should allow a user to fall back to using the old algorithm via a system property feature flag.

### Proposed changelog entries

* Internal: Use SHA-256 instead of MD5 for generating crumbs/CSRF tokens.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@reviewbybees @daniel-beck @Wadeck @jeffret-b @jglick @oleg-nenashev

2019-07-30 21:46 UTC, daniel-beck commented
Cannot find the documentation that made me write https://github.com/jenkinsci/jenkins/blob/f0c5108184a75e589493afe6d54879b5c4b7ed54/core/src/main/java/hudson/model/UpdateCenter.java#L1142 but I'm reasonably sure I found something authoritative.

IOW, this should be fine 👍

2019-07-30 21:46 UTC, daniel-beck approved these changes
as above

2019-08-01 10:24 UTC, Wadeck approved these changes

2019-08-01 22:23 UTC, oleg-nenashev requested changes
`readResolve()` still uses MD5, so the patch will work as aspected only until the first restart and CrumbIssuer reload from the disc

2019-08-02 08:52 UTC, daniel-beck commented
Great find @oleg-nenashev 

Also https://github.com/jenkinsci/jenkins/pull/4134/files#diff-bdef28d2b268ead763f32ed7b011dfbfR58 will need to be adjusted.

2019-08-02 15:55 UTC, jvz commented
Nice catch, @oleg-nenashev. Updated.

2019-08-02 20:58 UTC, daniel-beck approved these changes

2019-08-05 12:34 UTC, oleg-nenashev approved these changes
OK?

2019-08-05 12:34 UTC, oleg-nenashev commented
Will merge tomorrow if no negative feedback

2019-08-16 09:14 UTC, oleg-nenashev commented
retriggering CI

2019-08-16 11:37 UTC, merged