[JENKINS-56217] Require Overall/Read to get Jenkins version
jenkinsci/jenkins pull request #4161
Opened 2019-08-19 18:17 UTC by jvz

This adds a permission check for getting the Jenkins version to avoid
leaking this to unauthenticated users.

See [JENKINS-56217](https://issues.jenkins-ci.org/browse/JENKINS-56217).

This PR is initially for testing purposes, though depending on the test results, this may also be the implementation.

### Proposed changelog entries

* Removed `X-Jenkins` header and other Jenkins version information for unauthenticated users. This now requires the _Overall/Read_ permission.

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

Will update later.

2019-08-19 18:29 UTC, jtnord commented on core/src/main/java/jenkins/model/Jenkins.java
> +    public static void setJenkinsVersion(String version) {
setting the version always seemed like an accident waiting to happen.  do we actually need it?

2019-08-19 19:38 UTC, oleg-nenashev requested changes
Should it be in the Paranoia Plugin instead? In some cases it may also impact the client-side logic (e.g. Tcp Agent Listener change). It should be documented as a breaking change if @jenkinsci/core team agrees it actually makes sense to put it in the core.

I also second @jtnord w.r.t the new public method for setting versions. If this is a test method, it should be annotated accordingly. If it is a new public API, it needs documentation and way more justification

2019-08-19 20:05 UTC, jvz commented
I think putting this in the plugin could work, but it will still require changes in Jenkins to support it. Or, I'll have to update the plugin to be fancier and use some sort of AOP. In order to properly remove the version, it should be done across the board, so there would need to be an SPI for accessing this field.

If there is existing behavior that requires this version number to be present without authentication, then it would seem that this feature is completely pointless.

2019-08-21 01:39 UTC, jglick commented
> it may also impact the client-side logic (e.g. Tcp Agent Listener change)

So will this break `agent.jar` or not?

2019-08-21 16:23 UTC, jvz commented
Closing in favor of https://github.com/jenkinsci/jenkins/pull/4164

2019-08-21 16:23 UTC, closed without merging