Fix counter which is not updated in the loop
jenkinsci/jenkins pull request #4168
Opened 2019-08-23 00:26 UTC by Egor18

The counter `cnt` is not updated inside the loop here, so the condition `cnt<5` is always true.
The code has been this way for a long time, and I don't see why we should iterate only 5 times here, so instead of adding `i++`, I simply removed it. Correct me if I'm wrong.
(I found this issue with data-flow analyzer)

2019-08-23 02:04 UTC, res0nance approved these changes

2019-08-23 08:29 UTC, oleg-nenashev approved these changes
LGTM. Looks to be a historical performance tweak

2019-08-29 09:40 UTC, varyvol approved these changes

2019-08-29 09:51 UTC, alecharp requested changes
Just some suggestion to add spaces but it's good otherwise. Thanks!

2019-08-29 09:51 UTC, alecharp commented on core/src/main/java/hudson/model/AbstractProject.java
> +        for (R b = getLastBuild(); b!=null; b=b.getPreviousBuild()) {
```suggestion
        for (R b = getLastBuild(); b != null; b = b.getPreviousBuild()) {
```

2019-08-29 09:51 UTC, alecharp commented on core/src/main/java/hudson/model/AbstractProject.java
> +        for (R b = getLastBuild(); b!=null; b=b.getPreviousBuild()) {
```suggestion
        for (R b = getLastBuild(); b != null; b = b.getPreviousBuild()) {
```

2019-08-29 23:13 UTC, oleg-nenashev commented
will merge tomorrow if no negative feedback

2019-08-30 08:12 UTC, alecharp approved these changes

2019-08-30 08:13 UTC, merged

2019-08-30 08:13 UTC, oleg-nenashev commented
Thanks @Egor18 !

2019-09-02 08:56 UTC, daniel-beck commented
> I don't see why we should iterate only 5 times here

Probably due to lazy build loading -- if builds are too old, don't force them to be loaded. Same as why weather or estimated build duration only consider the five latest builds.

Anyone willing to amend this?