fixed 2 spotbugs issues (UNSATISFIED_OBLIGATION)
jenkinsci/jenkins pull request #4189
Opened 2019-09-03 05:24 UTC by StefanSpieker

See [JENKINS-36716](https://issues.jenkins-ci.org/browse/JENKINS-36716).

Fixed another Spotbugs type: [unsatisfied-obligation](https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#obl-method-may-fail-to-clean-up-stream-or-resource-obl-unsatisfied-obligation)

### Proposed changelog entries

* Internal: Spotbugs issues fixed

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

2019-09-05 09:07 UTC, rsandell approved these changes

2019-09-05 09:07 UTC, fcojfernandez approved these changes

2019-09-05 09:08 UTC, rsandell commented
Maybe need to rerun CI

2019-09-05 16:07 UTC, StefanSpieker commented
@rsandell: How can I trigger the CI to rerun?

2019-09-05 16:47 UTC, fcojfernandez commented
@StefanSpieker close and re-open the PR

2019-09-12 09:51 UTC, oleg-nenashev approved these changes
LGTM. It looks like it fixes real defects, so we may need to create follow-up issues

2019-09-13 07:50 UTC, oleg-nenashev commented
retriggering CI

2019-09-14 14:21 UTC, StefanSpieker commented on core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
> +                    new File(jenkins.getRootDir(), "secrets/whitelisted-callables.d/default.conf"),
java.io.File doesn't represent an open file, it represents a path in the filesystem.
https://stackoverflow.com/questions/4752266/why-java-io-file-doesnt-have-a-close-method

So no need to take care of the file

2019-09-14 14:21 UTC, StefanSpieker commented on core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
> +                    new File(jenkins.getRootDir(), "secrets/filepath-filters.d/30-default.conf"),
see above comment.

2019-09-19 09:45 UTC, oleg-nenashev commented
@StefanSpieker while I am trying to get CI passing here, could you please crate a bug in Jenkins JIRA for it? Can be a part of the SpotBugs cleanup EPIC, but I think we might want to backport it

2019-09-19 19:51 UTC, StefanSpieker commented
I created a task for that: https://issues.jenkins-ci.org/browse/JENKINS-59451

2019-09-21 01:10 UTC, oleg-nenashev commented
Looks like the test failure is real. I suspect `StandardOutputSwapper` closes something unexpected

2019-09-21 21:35 UTC, StefanSpieker commented
It is quite hard for me to find the really failing test. Have you thought abot integrating the warnings-ng plugin and collecting the results?

I guess the plugin is not installed, but if it would you could add this after the build. At least we are using this in all our jenkins projects and it is quite helpful:

`recordIssues enabledForFailure: true, tools: [mavenConsole(), java(), javaDoc()]`

2019-10-18 09:49 UTC, oleg-nenashev commented
> It is quite hard for me to find the really failing test. Have you thought abot integrating the warnings-ng plugin and collecting the results?

There is https://github.com/jenkinsci/pom/pull/43 by @tomasbjerre  which probably addresses it

2020-01-23 16:30 UTC, StefanSpieker commented
I have problems getting the tests run on my machine at all. All tests that involve the    

>  @Rule
>     public JenkinsRule j = new JenkinsRule();

  does not seem to work on my windows 10 machine, at least not within intelliJ.

Have you an idea how to get these running on Windows?

2020-01-23 16:39 UTC, timja commented
> I have problems getting the tests run on my machine at all. All tests that involve the
> 
> > @rule
> > public JenkinsRule j = new JenkinsRule();
> 
> does not seem to work on my windows 10 machine, at least not within intelliJ.
> 
> Have you an idea how to get these running on Windows?

what's the error?

2020-01-23 17:43 UTC, StefanSpieker commented
@timja: Actually it seems these were missing priviledges and a locale related issue, for what I opened another PR. At least now the tests pass locally.

2020-01-24 09:38 UTC, StefanSpieker commented
@varyvol actually all tests pass on my system. And I'm not sure which test fails on CI/CD because it seems to time out. Can you help me in finding out which tests failed?

2020-01-24 09:44 UTC, timja commented
`startupShouldNotFailOnExceptionOnlineListener`
they appear to be in the build log?

2020-01-24 09:47 UTC, StefanSpieker commented
This test passes locally. Either with all tests running via mvn test or with just this single test from the IDE.

2020-01-24 09:59 UTC, varyvol commented
Maybe it was a temporary infra issue. I'm going to close and reopen to relaunch CI.

2020-02-05 17:24 UTC, oleg-nenashev requested changes
We will need to fix CI before merging

2020-04-30 09:42 UTC, varyvol commented
@StefanSpieker could you maybe dedicate some time to review and fix the test failure? This seems close to be ready once that issue is solved.

2020-04-30 12:55 UTC, StefanSpieker commented
Actually it is really hard to find out for me what the real problem is. Somewhere in jenkins-test. The Errors I get are always:

> jenkins.util.io.CompositeIOException: Unable to delete 'C:\Projekte\jenkins\jenkins\test\target\j h6629989225187982938'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.

I guess, now Jenkins does not release everything. So instead of fixing an unclosed file handlers, it seems I created new ones...

2020-10-01 13:28 UTC, alecharp commented
@StefanSpieker could you have a look at the build error and check whether or not it's caused by the changeset of this PR? Thanks.

2020-10-23 10:38 UTC, MRamonLeon commented
Proposed for close because there is no progress since a long time

2020-11-06 13:34 UTC, rsandell commented
Close since no opposition for 14 days.

2020-11-06 13:34 UTC, closed without merging