Extracted duplicate code
jenkinsci/jenkins pull request #4206
Opened 2019-09-17 16:43 UTC by StefanSpieker

I extracted duplicated code in an unit test and used this function within the class and merged two switch cases in the class under test.

### Proposed changelog entries

No changelog entry needed

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

2019-09-17 17:06 UTC, jvz commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +    private void assertkeyPair(File file, String password) throws IOException, GeneralSecurityException {
Naming consistency nit:

```suggestion
    private void assertKeyPair(File file, String password) throws IOException, GeneralSecurityException {
```

2019-09-19 11:30 UTC, oleg-nenashev approved these changes

2019-09-19 11:50 UTC, oleg-nenashev requested changes
```
13:36:10  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project cli: Compilation failure: Compilation failure: 
13:36:10  [ERROR] /home/jenkins/workspace/Core_jenkins_PR-4206/cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java:[25,8] error: cannot find symbol
13:36:10  [ERROR]   symbol:   method assertkeyPair(File,<null>)
13:36:10  [ERROR]   location: class PrivateKeyProviderTest
```

2019-09-19 11:50 UTC, oleg-nenashev commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +        assertkeyPair(file, null);
```suggestion
        assertkeyPair(file, null);
```
```suggestion
        assertkeyPair(file, null);
```
```suggestion
        assertKeyPair(file, null);
```

2019-09-19 11:50 UTC, oleg-nenashev commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +        assertkeyPair(file, null);
```suggestion
        assertKeyPair(file, null);
```

2019-09-19 11:50 UTC, oleg-nenashev commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +        assertkeyPair(file, password);
```suggestion
        assertKeyPair(file, password);
```

2019-09-19 11:50 UTC, oleg-nenashev commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +        assertkeyPair(file, password);
```suggestion
        assertKeyPair(file, password);
```

2019-09-19 11:50 UTC, oleg-nenashev commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +        assertkeyPair(file, null);
```suggestion
        assertKeyPair(file, null);
```

2019-09-19 13:53 UTC, StefanSpieker commented
Sorry, I just applied the requested changes without noticing that all methods had to be changed too. Thanks for the suggested changes.

2019-09-19 13:58 UTC, oleg-nenashev approved these changes
No worries, and thanks for fixing it!

2019-09-20 09:33 UTC, timja commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +     * Extracted method to assert the keyPair private and public are not null.
```suggestion
     * Asserts the keyPair private and public are not null.
```

2019-09-20 09:34 UTC, timja commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +    private void assertKeyPair(File file, String password) throws IOException, GeneralSecurityException {
```suggestion
    private void assertKeyPairNotNull(File file, String password) throws IOException, GeneralSecurityException {
```

2019-09-22 19:35 UTC, StefanSpieker commented on cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
> +    private void assertKeyPair(File file, String password) throws IOException, GeneralSecurityException {
commited the change as suggested

2019-09-23 05:12 UTC, timja approved these changes

2019-09-27 21:04 UTC, oleg-nenashev approved these changes
I plan to merge it tomorrow if no negative feedback

2019-09-28 08:29 UTC, merged