Annotate ProcessTree with @Nullable/@Nonnull
jenkinsci/jenkins pull request #4236
Opened 2019-09-27 14:53 UTC by slonopotamus

### Proposed changelog entries

* Internal: `ProcessTree` public API is now annotated with @Nullable/@Nonnull annotations

2019-09-28 11:48 UTC, oleg-nenashev requested changes
Please use `@CheckForNull` instead of `Nullable`. CheckforNull will require static analysis tools to actually verify usages of the returned values. `Nullable` is basically NOOP in SpotBugs

2019-09-29 15:56 UTC, timja commented on core/src/main/java/hudson/util/ProcessTree.java
> +    public void killAll(@Nullable Process proc, @Nullable Map<String, String> modelEnvVars) throws InterruptedException {
```suggestion
    public void killAll(@CheckForNull Process proc, @CheckForNull Map<String, String> modelEnvVars) throws InterruptedException {
```

2019-09-29 15:56 UTC, timja commented on core/src/main/java/hudson/util/ProcessTree.java
> +    @Nullable
```suggestion
    @CheckForNull
```

2019-09-29 15:57 UTC, timja commented on core/src/main/java/hudson/util/ProcessTree.java
> +    @Nonnull
```suggestion
    @CheckForNull
```

2019-09-29 15:57 UTC, timja commented on core/src/main/java/hudson/util/ProcessTree.java
> +    @Nullable
```suggestion
    @CheckForNull
```

2019-09-30 06:21 UTC, slonopotamus commented
Replaced `@Nullable` with `@CheckForNull`.

2019-09-30 06:23 UTC, timja approved these changes

2019-09-30 06:46 UTC, slonopotamus commented
Two bugs detected by SpotBugs are fixed by #4231 and #4232.

2019-09-30 09:12 UTC, res0nance commented
Requires the spotbugs fixes first so putting on hold

2019-10-02 20:22 UTC, slonopotamus commented
@res0nance: dependent PRs got merged, so this now passes on CI and on-hold can be removed.

2019-10-02 21:44 UTC, oleg-nenashev approved these changes
We do not always put annotations for overrides, because SpotBugs handles it right.
But yes IDEA grumbles about it...

2019-10-02 21:44 UTC, oleg-nenashev commented
I plan to merge it tomorrow if no negative feedback

2019-10-03 10:27 UTC, merged