set HttpOnly flag to prevent cookie read by a malicious script in browser
jenkinsci/jenkins pull request #4363
Opened 2019-11-17 15:59 UTC by StefanSpieker

This is a finding by [find-sec-bugs](https://github.com/find-sec-bugs/find-sec-bugs).

And I fixed it by setting the HttpOnly flag to prevent cookie read by a malicious script in browser.
I'm not sure if this is really a security threat. But I guess it does not harm to set it correctly.

### Proposed changelog entries

* Set HttpOnly flag for refresh token

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

2019-11-18 07:46 UTC, Wadeck requested changes
@StefanSpieker Thank you for the PR. This change is not security related. If you have a security vulnerability to correct, please ensure you follow the instructions from https://jenkins.io/security/reporting/.

Please apply the proposed modification in order to reduce confusion of people thinking it's a security problem.

2019-11-18 07:46 UTC, Wadeck commented on core/src/main/java/hudson/Functions.java
> +            c.setHttpOnly(true); // The HttpOnly flag is a directive to the browser to make sure that the cookie can not be red by malicious script.
```suggestion
            c.setHttpOnly(true);
```

There is no security impact of this cookie being read or even modified by JavaScript (malicious or not). You only control the fact that the page is automatically refreshed or not.

In addition, this feature will be potentially be removed (see https://github.com/jenkinsci/jenkins/pull/2979 and https://github.com/jenkinsci/jenkins/pull/3894), cc @daniel-beck.

2019-11-18 07:55 UTC, StefanSpieker commented
Thaks for pointing to the instructions. I was not aware of this page.

2019-11-18 09:14 UTC, Wadeck approved these changes
The cookie is only used in HTTP Only context (= only on the server), so this change is acceptable.

2019-11-18 18:34 UTC, jeffret-b approved these changes
This should be fine. It's not strictly necessary and may be removed some day. But for now it's good to get cleanup like this done.

2019-11-19 13:20 UTC, oleg-nenashev approved these changes
Fine with me. I assume @daniel-beck's Pr for removing auto-refresh would be better ( https://github.com/jenkinsci/jenkins/pull/2979 ), but it is closed and I do not know its future

2019-11-21 10:06 UTC, daniel-beck commented
> it is closed and I do not know its future

https://github.com/jenkinsci/jenkins/pull/2979#issuecomment-463712095 links to the recently merged https://github.com/jenkinsci/jenkins/pull/3894

2019-11-21 12:56 UTC, oleg-nenashev commented
I plan to merge it tomorrow if no negative feedback

2019-11-22 09:14 UTC, merged