Export if plugin update is compatible
jenkinsci/jenkins pull request #4385
Opened 2019-12-04 10:48 UTC by LinuxSuRen

We wish I can upgrade all compatible plugins by [jcli](https://github.com/jenkins-zh/jenkins-cli).
See also the [PR link](https://github.com/jenkins-zh/jenkins-cli/pull/258).

### Proposed changelog entries

* Entry 1: Improve, export if a plugin is compatible
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@romenrg

2019-12-09 02:29 UTC, LinuxSuRen commented
@jenkinsci/code-reviewers I was wondering if anyone could take some time to help to review my PR. Thanks!

2019-12-09 07:17 UTC, oleg-nenashev requested changes
The concept is fine per se, but we should think about better field aliases in REST APIs. Not all methods are comprehensible here IMHO

2019-12-09 07:20 UTC, LinuxSuRen commented
@oleg-nenashev , thanks for your response. So, your suggestion is creating a new annotation for Restful API. Right?

2019-12-09 07:44 UTC, oleg-nenashev commented
Nope, @Exported already supports named aliases IIRC

On Mon, Dec 9, 2019, 07:21 Zhao Xiaojie <notifications@github.com> wrote:

> @oleg-nenashev <https://github.com/oleg-nenashev> , thanks for your
> response. So, your suggestion is creating a new annotation for Restful API.
> Right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/jenkins/pull/4385?email_source=notifications&email_token=AAW4RID2SSISH2DDOIFUMKDQXXWV3A5CNFSM4JVGUURKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIDMHA#issuecomment-563099164>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW4RIEO6SYPVKTVYLBCCSDQXXWV3ANCNFSM4JVGUURA>
> .
>

2019-12-09 08:22 UTC, LinuxSuRen commented
I hope that I can get the reason why a plugin is not compatible. All methods here are the potential reason. Does this make sense?

2019-12-09 11:47 UTC, yJunS reviewed
I think if the API can have 2 methods will be very good.

- check all compatible plugins and show them all.
- check if it is a compatible plugin from transfer a plugin name

2019-12-23 01:35 UTC, LinuxSuRen commented
Any updates?

2019-12-29 22:14 UTC, oleg-nenashev requested changes
Sorry, my comment about naming has not been addressed yet. Here is the list of available attributes: https://stapler.kohsuke.org/apidocs/org/kohsuke/stapler/export/Exported.html . Also `Exported` should be removed from the methods with `cache` arguments, parameterized getters are not exported IIRC

2019-12-30 02:51 UTC, LinuxSuRen commented
@oleg-nenashev Thanks for giving the details. I removed the wrong usage of `Export` annotation. In my point, I think it's understandable.
```
      "compatible" : true,
      "compatibleSinceVersion" : null,
      "compatibleWithInstalledVersion" : true,
```
I was wordering if you or other people could suggest a better name.

2020-01-14 10:37 UTC, oleg-nenashev commented
> I removed the wrong usage of Export annotation. In my point, I think it's understandable.

But what about `isForNewerHudson`, `isForNewerJava`, `isNeededDependenciesForNewerJava`? I think it would need some clarification. Also, I doubt we want to expose "Hudson" in newly introduced REST API (can be solved by introducing a new `isForNewerHudson()` method and deprecating the existing one)

2020-01-16 10:51 UTC, fcojfernandez commented
I 100% agree with Oleg.

2020-01-17 08:43 UTC, daniel-beck commented on core/src/main/java/hudson/model/UpdateSite.java
> +        @Exported
Should probably be exported with a `Jenkins` name (or more neutrally, `Core`).

2020-01-20 09:01 UTC, oleg-nenashev requested changes
Requesting the change as per https://github.com/jenkinsci/jenkins/pull/4385#issuecomment-574111762 . Sorry that it takes so long. I feel the PR is almost ready to go

2020-02-02 05:56 UTC, LinuxSuRen commented
Thanks to all you. I just remove the unclear annotation for now.

2020-02-06 10:35 UTC, fcojfernandez approved these changes

2020-02-06 10:36 UTC, varyvol approved these changes

2020-02-06 12:46 UTC, oleg-nenashev approved these changes
Thanks!

2020-02-06 12:47 UTC, oleg-nenashev commented
I plan to merge it tomorrow if no negative feedback

2020-02-07 08:54 UTC, merged

2020-02-07 08:58 UTC, LinuxSuRen commented
Thanks, everyone!