[JENKINS-60926] Upgrade to 4.1 version of Remoting.
jenkinsci/jenkins pull request #4464
Opened 2020-01-30 21:45 UTC by jeffret-b

See [JENKINS-JENKINS-60926](https://issues.jenkins-ci.org/browse/JENKINS-JENKINS-60926).

This corrects a minor regression introduced in Remoting 4.0 and Jenkins 2.217 (2020-01-23). A renaming broke agent Windows service installation. This restores the behavior.

See the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.1). It only contains this one small change.

### Proposed changelog entries

* Fix agent installation as a service on Windows. (regression in 2.217) (issue 60926)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
Tests for this capability would be nice but would involve significant system setup.
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-01-30 21:46 UTC, jvz approved these changes

2020-01-31 00:36 UTC, res0nance approved these changes

2020-02-04 15:12 UTC, Wadeck approved these changes
🐝

2020-02-05 12:20 UTC, oleg-nenashev requested changes
I am fine with this option as Plan B, but I think we should just fix the Windows Agent Installer Module (or Agent Installer module). Remoting 4.0 was for a reason, and breaking API changes were expected. We do not want to drag the technical debt if we can just fix the modules. They can be safely bumped to the recent weekly in terms of the dependencies.

I will merge this change on Friday if other reviewers agree that reverting is the preferred course of action

2020-02-05 18:11 UTC, jeffret-b commented
I'm fine with attempting to move forward with fixing the other usages, if we don't mind a larger delay in fixing this regression.

2020-02-06 09:46 UTC, oleg-nenashev commented
We still have 4 days till the weekly. If there is just one module affected, it should not take much time to deliver the fix

2020-02-06 09:47 UTC, oleg-nenashev commented
If you submit a fix to https://github.com/jenkinsci/slave-installer-module , I will get it released

2020-02-06 15:27 UTC, jeffret-b commented
I'll work on updating slave-installer-module and keeping the renaming.

2020-02-07 09:27 UTC, oleg-nenashev commented
Reopening to keep our options open. I will try to discuss the strategy with @jeffret-b today

2020-02-10 12:24 UTC, closed without merging