Disable failing test in UDP broadcast
jenkinsci/jenkins pull request #4467
Opened 2020-02-02 09:01 UTC by Wadeck

Currently all builds are failing due to failures in UDP broadcast tests. We have a pending PR to remove the feature completely due to security vulnerabilities but before the PR is merged, we need to keep the other PRs passing tests.

Reference for the other one: https://github.com/jenkinsci/jenkins/pull/4460

FYI @jeffret-b

2020-02-02 09:29 UTC, MarkEWaite approved these changes

2020-02-02 10:04 UTC, batmat requested changes
All for the disabling, but I think we should use `@Ignore` so the ignored tests still show up in the reports as such.

Thanks!

2020-02-02 10:04 UTC, batmat commented on test/src/test/java/hudson/UDPBroadcastThreadTest.java
> -    @Test public void legacy() throws Exception {
I think we should use the standard `@Ignore` out is there a compelling reason not to use this?

2020-02-02 15:27 UTC, MarkEWaite commented
> All for the disabling, but I think we should use `@Ignore` so the ignored tests still show up in the reports as such.

I thought that the reason to disable was:

> We have a pending PR to remove the feature completely due to security vulnerabilities but before the PR is merged, we need to keep the other PRs passing tests.

Since the feature is being removed, is the be

2020-02-02 15:41 UTC, markyjackson-taulia commented
This is a non-binding comment but I agree that if #4460 is in flight disabling is more the way to go

2020-02-03 01:57 UTC, res0nance approved these changes
Fully agree since the removal is in flight we should just disable this test instead of spending cycles on it

2020-02-03 09:29 UTC, daniel-beck approved these changes
Whatever works.

2020-02-03 14:59 UTC, jeffret-b approved these changes

2020-02-03 15:11 UTC, jeffret-b commented
I've got lots of approvals on #4460 and only one area of possible concern but haven't heard back from anyone that actually uses it. I'm hopeful we'll get it merged. I've always had failures with these tests on my machine, so I was reluctant to try and fix anything here. I'm in favor of the easiest way to disable the tests until we can get the other PR in.

2020-02-03 19:55 UTC, jglick approved these changes
Prefer to either `@Ignore` or delete, but good enough for now.

2020-02-03 19:57 UTC, jglick commented
FTR

```
java.lang.IllegalAccessException: Can not set static final int field hudson.UDPBroadcastThread.PORT to (int)33848
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:100)
	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticIntegerFieldAccessorImpl.setInt(UnsafeQualifiedStaticIntegerFieldAccessorImpl.java:129)
	at java.base/java.lang.reflect.Field.setInt(Field.java:960)
	at hudson.UDPBroadcastThreadTest.updatePort(UDPBroadcastThreadTest.java:51)
	at hudson.UDPBroadcastThreadTest.forceActivateUDPMulticast(UDPBroadcastThreadTest.java:41)
```

not tied obviously to any SCM commit.

2020-02-03 19:58 UTC, merged