[JENKINS-60926] Upgrade to 4.2 version of Remoting.
jenkinsci/jenkins pull request #4476
Opened 2020-02-06 18:44 UTC by jeffret-b

See [JENKINS-60926](https://issues.jenkins-ci.org/browse/JENKINS-60926).

This corrects a minor regression introduced in Remoting 4.0 and Jenkins 2.217 (2020-01-23). A renaming broke agent Windows service installation. Combined with an upcoming release of slave-installer-module this will fix the issue. Supersedes #4464.

See the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.2). It contains this change plus a couple of minor cleanup PRs.

### Proposed changelog entries

* Fix agent installation as a service on Windows. (regression in 2.217) (issue 60926)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
Tests for this capability would be nice but would involve significant system setup.
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-02-06 18:47 UTC, jeffret-b commented
Need to get an incremental published so that I can make the corresponding change in slave-installer-module.

2020-02-06 22:37 UTC, MarkEWaite approved these changes

2020-02-06 23:44 UTC, oleg-nenashev approved these changes
OK?

2020-02-07 07:07 UTC, fcojfernandez approved these changes

2020-02-07 09:27 UTC, oleg-nenashev requested changes
AFAICT we need a proper fix of https://github.com/jenkinsci/slave-installer-module/pull/7 to be integrated into this PR so that it addresses the issue. If we cannot make it in time, #4464 would be a way to go for the incoming weekly, and this PR would be a final fix for the next one

2020-02-07 18:10 UTC, jeffret-b commented
There's an update to the slave-installer PR that works for both old and new versions of Remoting. Once we get that approved and released, we can update this PR with that version and this should be good to go.

2020-02-07 21:30 UTC, oleg-nenashev commented
@jeffret-b https://github.com/jenkinsci/slave-installer-module/releases/tag/slave-installer-1.7 was released, working on the changelog. But you can update this PR

2020-02-07 21:34 UTC, oleg-nenashev commented
https://github.com/jenkinsci/slave-installer-module/pull/8 for the changelog

2020-02-07 21:37 UTC, oleg-nenashev approved these changes
Thanks @jeffret-b ! +1 for getting this change integrated towards the next weekly.
I might be offline in next 24hrs due to the travel, and it would be great if somebody else merges it

2020-02-07 21:38 UTC, jeffret-b commented
Updated the reference to slave-installer 4.7.

Thanks for the assistance in getting this through!

2020-02-07 21:40 UTC, jeffret-b commented
> I might be offline in next 24hrs due to the travel, and it would be great if somebody else merges it

If you want, I can merge it after CI passes. Anything else we would need before merging?

2020-02-07 21:41 UTC, oleg-nenashev commented
> If you want, I can merge it after CI passes. Anything else we would need before merging?

Would be nice to get few reviews, so I did a mass ping taking time constrains.
Also added the changelog links to the proposed changelog

2020-02-07 21:42 UTC, oleg-nenashev approved these changes
Reapproving, because I was re-requested after the group ping

2020-02-07 21:43 UTC, timja approved these changes

2020-02-08 02:50 UTC, jeffret-b commented
We've got three approvals, which is probably good enough for this one. I'll go ahead and merge it on in so it will be ready for release.

2020-02-08 02:50 UTC, merged