Re-add hudson.UDPBroadcastFragment
jenkinsci/jenkins pull request #4486
Opened 2020-02-10 12:27 UTC by Flowdalic

The class was removed with f10d9f95fc ("[JENKINS-60913] Remove network
discovery services (#4460)") but is required by the swarm client. As
result, swarm clients are unable use Jenkins:

java.lang.NoClassDefFoundError: hudson/UDPBroadcastFragment
        at hudson.plugins.swarm.PluginImpl.getSwarmSecret(PluginImpl.java:262)

This commit re-adds hudson.UDPBroadcastFragment to jenkin's core, to
allow swarm client to the use the master again and hence fixes
JENKINS-61029.

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-02-10 12:36 UTC, oleg-nenashev commented
It does not look like restoring of this particular class will restore the auto-discovery functionality in Swarm clients. I suggest discussion the removal of the feature from Swarm Plugin with @basil .

P.S: We should be much more careful about code removal pull requests

2020-02-10 12:42 UTC, Flowdalic commented
> It does not look like restoring of this particular class will restore the auto-discovery functionality in Swarm clients.

Just to clarify, we are not using the auto-discovery functionality of the swarm clients and are still affected by this.

And while I only see that this particular class is missing in the jenkins master logs, I can't rule out that there are additional removed classes the swarm plugin requires. It appears you have already a hint which classes this could be, could you share that?

2020-02-10 12:53 UTC, oleg-nenashev commented
I do not have hints. I suspect every removal in https://github.com/jenkinsci/jenkins/pull/4460  needs a careful re-review.

2020-02-10 13:48 UTC, jglick requested changes
This was already noted in https://github.com/jenkinsci/jenkins/pull/4460#discussion_r373213090. We agreed on the list to remove this from core and the `swarm` plugin can add this functionality if it still needs it.

2020-02-10 13:50 UTC, daniel-beck commented
I think Swarm Plugin should be updated instead.

2020-02-10 17:39 UTC, jeffret-b requested changes
As we discussed on the email list and the other PR, keeping this in core isn't a good idea and good path forward. Swarm is the only code usage of this we were able to identify. The swarm plugin needs to decide whether to continue supporting discovery, with its issues. If it does, it can take responsibility for proper education on the security and other concerns. If not, then it can drop references to the class and move forward.

If someone else needs the discovery services for a different need, they might want to resurrect the capabilities into a plugin and take responsibility.

2020-02-10 22:14 UTC, oleg-nenashev commented
There are differences between keeping the feature and keeping class skeletons to retain binary compatibility. I agree that fixing the Swarm plugin is a best course of action here even if it means removing the feature from it. If it is not possible in shirt term (e.g. by the next weekly), accepting a small hotfix is reasonable imho.

If anyone suggests a fix for Swarm plugin, it would be a good step forward. @jeffret-b maybe?

2020-02-10 22:22 UTC, jeffret-b commented
I'll toss something together to deal with the compilation / run time issue as a proposed PR for swarm. The bigger questions of what to support, how to deal with the security issues, and whether to handle discovery scenarios are better left to people who use and maintain the plugin.

2020-02-11 00:12 UTC, jeffret-b commented
See jenkinsci/swarm-plugin#179.

2020-02-11 03:59 UTC, jeffret-b commented
My other PR got merged into swarm.

2020-02-15 11:59 UTC, timja commented
@Flowdalic The fix has been released in swarm plugin in https://github.com/jenkinsci/swarm-plugin/releases/tag/swarm-plugin-3.18, thanks for the PR here though.

2020-02-15 11:59 UTC, closed without merging