Static nested classes
jenkinsci/jenkins pull request #4507
Opened 2020-02-19 07:46 UTC by res0nance

Minor cleanups to use static nested classes where possible

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-02-19 09:15 UTC, varyvol commented
@res0nance is the build working for you locally? It failed in CI but the error is quite weird.

2020-02-19 09:43 UTC, oleg-nenashev commented
```
[2020-02-19T07:55:53.695Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project jenkins-test: Compilation failure

[2020-02-19T07:55:53.695Z] [ERROR] An exception has occurred in the compiler (11.0.5). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.

[2020-02-19T07:55:53.695Z] [ERROR] java.lang.NullPointerException
```

2020-02-19 09:50 UTC, oleg-nenashev requested changes
Changing public classes to static ones actually breaks the binary compatibility. Also it may lead to funny results when classes are serialized to the disk via XStream. My recommendation would be to avoid changes in public API unless there are issues associated with that. Changing private and [properly] restricted classes is fine

2020-02-20 00:05 UTC, res0nance commented
> @res0nance is the build working for you locally? It failed in CI but the error is quite weird.

It does compile on my machine(strangely enough) 🤷‍♂ . It seems to be due to tests compiling but I did not run the test suite. I'll since its an ICE I'll file a bug on the java bug tracker for it.

2020-02-20 01:23 UTC, res0nance commented on test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
> +        public static class TestAccessModifier {
Its public here but this is a test class so I just left it

2020-02-27 09:57 UTC, varyvol approved these changes

2020-02-27 10:01 UTC, MRamonLeon approved these changes
If the CI passes

2020-03-26 11:11 UTC, MRamonLeon commented
@oleg-nenashev I guess after the changes done you would be fine with the PR, right?

2020-03-26 11:11 UTC, rsandell approved these changes

2020-03-28 09:04 UTC, merged