Fixed spotbugs NP_NULL_ON_SOME_PATH
jenkinsci/jenkins pull request #4564
Opened 2020-03-11 17:00 UTC by ventojna

Fixed NP_NULL_ON_SOME_PATH in x ExtensionList<T>
See [JENKINS-36720](https://issues.jenkins-ci.org/browse/JENKINS-36720).

### Proposed changelog entries
N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-03-12 08:36 UTC, varyvol approved these changes

2020-03-12 08:59 UTC, oleg-nenashev requested changes
Taking the "can't perform the auto discovery until all plugins are loaded, so just make the legacy instances visible" comment in the code below, I think that the execution should exist fast when Jenkins instance is not initialized

2020-03-12 08:59 UTC, oleg-nenashev commented on core/src/main/java/hudson/ExtensionList.java
> +        if (jenkins != null && jenkins.getInitLevel().compareTo(InitMilestone.PLUGINS_PREPARED) < 0)
```suggestion
        if (jenkins == null || jenkins.getInitLevel().compareTo(InitMilestone.PLUGINS_PREPARED) < 0)
```

2020-03-12 19:53 UTC, StefanSpieker approved these changes

2020-03-13 09:32 UTC, oleg-nenashev approved these changes
Thanks! 
I plan to merge it tomorrow if no negative feedback

2020-03-13 13:48 UTC, res0nance approved these changes

2020-03-14 15:59 UTC, merged