[JENKINS-61453] Jenkins.MANAGE user to access "Prepare for Shutdown"
jenkinsci/jenkins pull request #4572
Opened 2020-03-13 08:58 UTC by escoem

See [JENKINS-61453](https://issues.jenkins-ci.org/browse/JENKINS-61453).

### Proposed changelog entries

JENKINS-61453 _Prepare for Shutdown_ management link is now accessible to users with
Jenkins.MANAGE (as well as the usual
Jenkins.ADMINISTRATOR)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] JIRA issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@daniel-beck @oleg-nenashev 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-03-18 10:28 UTC, amuniz approved these changes
Looks good.

2020-03-18 11:25 UTC, mikecirioli approved these changes
👍

2020-03-18 12:14 UTC, daniel-beck approved these changes

2020-03-18 12:14 UTC, daniel-beck commented on core/src/main/java/jenkins/model/Jenkins.java
>      @RequirePOST // TODO the cancel link needs to be updated accordingly
```suggestion
    @RequirePOST
```

Almost certainly obsolete, or we'd know about it.

2020-03-19 10:50 UTC, fcojfernandez approved these changes

2020-03-19 10:51 UTC, varyvol approved these changes

2020-03-20 13:16 UTC, EstherAF approved these changes

2020-03-20 13:53 UTC, daniel-beck requested changes
Build queue contains a "cancel" link while Jenkins is quieting down, that link is not displayed to Manage users:

https://github.com/jenkinsci/jenkins/blob/450d87491df16598409d26511bcad02978eaa8bb/core/src/main/resources/lib/hudson/queue.jelly#L54

2020-03-24 09:19 UTC, amuniz commented
Looks like requested changes are fixed. @daniel-beck can you please re-review?

2020-03-25 12:56 UTC, Wadeck approved these changes
Not tested manually but seems fine :)

2020-03-30 18:03 UTC, daniel-beck approved these changes

2020-04-01 19:15 UTC, merged