Add section titles to Manage Jenkins context menu
jenkinsci/jenkins pull request #4586
Opened 2020-03-16 12:30 UTC by daniel-beck

Alternative to #4583.

<details>
<summary>Screen shots</summary>

![Screenshot 2020-03-16 at 13 27 58](https://user-images.githubusercontent.com/1831569/76758536-27da7f00-678a-11ea-90cc-35a385f16da4.png)
![Screenshot 2020-03-16 at 13 28 05](https://user-images.githubusercontent.com/1831569/76758542-290bac00-678a-11ea-8746-3817e3ba8dec.png)

</details>

### Proposed changelog entries

* Add section headers to context menu of Manage Jenkins

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [n/a] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [n/a] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

2020-03-16 12:49 UTC, daniel-beck commented
Reworking this to be less of a disgusting hack.

2020-03-16 13:03 UTC, daniel-beck commented
Amended with larger font size (thanks @fqueiruga):

> 
![Screenshot](https://user-images.githubusercontent.com/1831569/76760938-e7c9cb00-678e-11ea-8b21-11bb052ef408.png)

2020-03-16 14:44 UTC, fqueiruga requested changes
Looks great! nice, smart solution. Just added a suggestion to rename the CSS class in order to make it more specific for this component.

2020-03-16 14:44 UTC, fqueiruga commented on core/src/main/resources/lib/layout/breadcrumbs.css
> +#breadcrumb-menu .header {
```suggestion
.breadcrumb-menu__category {
```

2020-03-16 14:44 UTC, fqueiruga commented on core/src/main/resources/lib/layout/breadcrumbs.js
> +                            e.text = makeMenuHtml(e.icon, "<span class='header'>" + e.displayName + "</span>");
```suggestion
                            e.text = makeMenuHtml(e.icon, "<span class='breadcrumb-menu__category'>" + e.displayName + "</span>");
```

2020-03-17 14:19 UTC, jtnord commented
Have we considered how this will negativly effect scrolling...

e.g. it will make situations like the following much more common (and they are annoying)
![image](https://user-images.githubusercontent.com/494726/76865216-4c9e2780-685a-11ea-8bd9-0ea54da73f5f.png)

2020-03-19 10:21 UTC, fcojfernandez approved these changes
Although I agree with James' comment, I think the benefits of having those titles are bigger than the effects on the scroll

2020-03-19 10:22 UTC, varyvol commented
I like the change, I think it improves the visualization a lot. Happy to approve once you review @fqueiruga suggestions.

2020-04-02 13:42 UTC, fqueiruga approved these changes

2020-04-10 07:58 UTC, oleg-nenashev approved these changes
I am fine with both alternatives, leaving the decision to UX experts.

P.S: We could even have both and select one based on the number of items (e.g. this PR when it is below 12 and #4583 when the number is above). But most likely it is an over-complication

2020-04-10 12:00 UTC, daniel-beck commented
Personally I'd prefer this be merged, and the other being left as a workaround if feedback is overly negative for adding ~5 items.

2020-04-11 11:18 UTC, oleg-nenashev commented
I plan to merge it tomorrow if no negative feedback

2020-04-12 09:12 UTC, merged