Add optional layout property to suppress loading of Bootstrap 3 grid
jenkinsci/jenkins pull request #4693
Opened 2020-04-28 22:00 UTC by uhafner

Jenkins bundles the grid of Bootstrap 3 (that has been patched to use 24 columns). It is not compatible with new JS frameworks (see https://issues.jenkins-ci.org/browse/JENKINS-61326) that are based on BS4 and a 12 column grid (see https://github.com/jenkinsci/bootstrap4-api-plugin).

This pull request provides a workaround by adding a new optional property to the `layout.jelly` file until a fix for https://issues.jenkins-ci.org/browse/JENKINS-61326 is available. Using this toggle a plugin can suppress loading of the BS3 grid when using the layout tag. 

### Proposed changelog entries

Not required.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@fqueiruga 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2020-04-29 07:08 UTC, fqueiruga requested changes
Hi Ulli, there's some CSS code that needs to be extracted off the `responsive-grid.less`.

- All rules from the beginning until to https://github.com/jenkinsci/jenkins/blob/ab5616712ab8d79bcabc9a97e10a0edb2f5696c4/war/src/main/webapp/css/responsive-grid.css#L28
- All rules from this one till the end https://github.com/jenkinsci/jenkins/blob/ab5616712ab8d79bcabc9a97e10a0edb2f5696c4/war/src/main/webapp/css/responsive-grid.css#L1714

I also think the `hidden-*` classes need to be backported, as they are used on the header & footer. Otherwise, we can just manually change the `layout.jelly` and `pageHeader.jelly` to remove them, but that may be a bit more work.

2020-04-29 07:43 UTC, timja approved these changes

2020-04-29 08:49 UTC, fqueiruga commented
@uhafner I have created a PR against your branch that migrates essential CSS off the `responsive-grid.css` file: https://github.com/uhafner/jenkins/pull/1.

I have only done a smoke test on the `hidden-*` ones and they work, but it be good to have more confirmation. I haven't found a single use of the `visible-*` classes across the whole ecosystem, but I think it's best to keep them for now.

Please let us know once there's an artifact of the warnings-ng plugin with these changes, I'll make it a priority to test it.

Also, can you create an issue to this one? I think it's a long shot that this is backported but it would be really nice.

2020-04-29 13:38 UTC, uhafner commented
I can split the grid css into the suggested parts, but shouldn't this be in a separate PR?

2020-04-29 13:44 UTC, fqueiruga commented
I can create the PR with the changes if you prefer. The other PR should be merged before this one then.

2020-04-29 14:34 UTC, uhafner commented
For me it makes no difference. If it is ok from a core perspective then I can merge it here. 

BTW: I created an additional issue: https://issues.jenkins-ci.org/browse/JENKINS-62094?filter=-2

2020-04-29 14:37 UTC, fqueiruga commented
Maybe it's indeed best to keep both changes separated. I'll keep the other PR Today.

2020-04-29 16:17 UTC, fqueiruga approved these changes
Approving it but I think it should not be merged before https://github.com/jenkinsci/jenkins/pull/4697

2020-04-29 16:26 UTC, timja commented
I think this might be worth a developer changelog entry?

2020-04-29 18:52 UTC, uhafner commented
Here in core as well? (I will definitely describe the usage in the bootstrap API plugin).

2020-04-29 19:50 UTC, timja commented
Just a minor one liner I think yes

2020-04-29 21:04 UTC, timja commented
Something like:
> Developer: Add `nogrid` option to layout.jelly to allow suppressing the bootstrap 3 grid

2020-04-29 21:43 UTC, uhafner commented
Ok, done.

2020-04-29 21:55 UTC, timja commented
Let's merge this after ~24 hours, (it should be merged together with https://github.com/jenkinsci/jenkins/pull/4697)

2020-04-30 08:48 UTC, fcojfernandez approved these changes

2020-04-30 08:48 UTC, varyvol approved these changes

2020-04-30 10:24 UTC, daniel-beck commented
And once we no longer do this anyway, this would become a no-op? Or what is the long-term plan here? Is it even supported to `nogrid=false`?

2020-04-30 13:53 UTC, uhafner commented
The long term plan is to remove the flag (or make it non functional) when we replace the Bootstrap 3 grid. Once this PR has been merged I can set this flag to `true` in the jelly tag of the bootstrap plugin. So actually no other plugin should care about this flag at all.

2020-04-30 19:33 UTC, merged