Revert "[JENKINS-63014] Stop passing extra -url to agents"
jenkinsci/jenkins pull request #4880
Opened 2020-07-27 14:19 UTC by oleg-nenashev

Submitting it for a discussion - jenkinsci/jenkins#4839 removes the feature which was supposed to be unused, but apparently it caused breaking changes in some configurations: https://issues.jenkins-ci.org/browse/JENKINS-63222 . We need to define which path we take to proceed.

Since WebSocket is an experimental feature, it might be the easiest way to just revert the fix.

Would be happy to consider any alternate fixes which do not break Websockets again. Documentation-only fix might be an option as well

2020-07-27 14:23 UTC, jglick commented
Discussion in Jira. I believe this is a plugin bug.

2020-07-27 14:31 UTC, jglick requested changes
Straight-up revert would itself be a regression. Could extend the test to check the `webSocket` flag, but would rather have `yet-another-docker-plugin` be fixed.

2020-07-29 21:34 UTC, jglick commented on core/src/main/resources/hudson/slaves/SlaveComputer/slave-agent.jnlp.jelly
> +        <j:if test="${rootURL!=app.rootUrlFromRequest}">
Untested but

```suggestion
        <j:if test="${!launcher.webSocket and rootURL!=app.rootUrlFromRequest}">
```

would preserve the fix for WebSocket agents while reverting to the original (IMO dubious) behavior for TCP agents.

2020-10-01 13:14 UTC, varyvol commented
@oleg-nenashev @jglick this was supposed to fix a regression and also seems to have been a candidate for LTS backporting but it has not landed. Is it considered not to be a bug? Was the decision not to close it?

2020-10-01 13:22 UTC, jglick commented
I suggested backporting the amended version from https://github.com/jenkinsci/jenkins/pull/4880#discussion_r462602812 but @olivergondza was not comfortable backporting a code change that was never in weeklies, so we dropped the idea. I think this PR can be closed now.

2020-11-06 13:35 UTC, MRamonLeon commented
@oleg-nenashev feel free to reopen if it's still interesting.

2020-11-06 13:35 UTC, closed without merging