update extensions footer location
jenkinsci/jenkins pull request #4949
Opened 2020-09-27 01:23 UTC by yJunS

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [x] There are at least 2 approvals for the pull request and no outstanding requests for change
- [x] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically

2020-09-27 09:32 UTC, daniel-beck commented
@yJunS Could you provide more context and explanation for this change? For example, is it a regression, and if so, from what change? Where does this show as a bug? How will it impact plugins that add a footer?

2020-09-28 03:57 UTC, yJunS commented
@daniel-beck Yes, It's a regression from [JENKINS-61496](https://github.com/jenkinsci/jenkins/pull/4599). Before the changes, they are together, but they are separate now, like this:
![image](https://user-images.githubusercontent.com/20575981/94389007-30703100-0181-11eb-8d21-67a8297e5e32.png)

2020-09-28 13:11 UTC, daniel-beck commented
@yJunS This looks like a bug that qualifies for LTS backporting. Please file a Jira issue and reference it in this PR, as described in the PR template.

2020-09-28 17:26 UTC, yJunS commented
@daniel-beck Okay. I also filed the [JENKINS-63798](https://issues.jenkins-ci.org/browse/JENKINS-63798)

2020-10-01 13:11 UTC, varyvol approved these changes

2020-10-01 13:11 UTC, alecharp approved these changes
Looks pretty simple and effective. Thanks.

2020-10-01 13:16 UTC, oleg-nenashev approved these changes
👍 
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

2020-10-02 08:44 UTC, fqueiruga commented
I would put them inside of the `#footer` div, because that's where many plugins hook up their stuff.

2020-10-02 08:45 UTC, fqueiruga requested changes
I'd suggest moving this above (see previous comments)

2020-10-02 13:43 UTC, yJunS commented
> I'd suggest moving this above (see previous comments)

@fqueiruga  It will show this location if put them inside of the *#footer* div, It looks weird.
![image](https://user-images.githubusercontent.com/20575981/94929791-23906c00-04f8-11eb-83c8-be8db070c8ab.png)

2020-10-02 14:23 UTC, fqueiruga commented
That's the place for extensions though. I think the translations assitance plugin used that place IIRC

2020-10-03 01:51 UTC, yJunS commented
![image](https://user-images.githubusercontent.com/20575981/94980568-7b14f300-055d-11eb-8613-08186c44a04b.png)
@fqueiruga Do you mean to put it on the same level as the *.page-footer__flex-row* div?

2020-10-05 10:28 UTC, oleg-nenashev commented
@fqueiruga Hi. Regardless of the discussion, are you blocking the current edition of the pull request? AFAICT, you rather suggest a follow-up improvement. Or is it required for a proper issue fix?

2020-10-05 10:55 UTC, fqueiruga commented
I'd say this issue is a won't fix IMO

2020-10-05 10:58 UTC, fqueiruga commented
I think we need screenshots of this actually working with plugins hooking up to it, both desktop and mobile.

2020-10-06 15:47 UTC, yJunS commented
Before the version 2.235.1:
![image](https://user-images.githubusercontent.com/20575981/95224334-20b1b600-082d-11eb-9b7b-b2996178dab9.png)
Since the version 2.235.1:
![image](https://user-images.githubusercontent.com/20575981/95224860-c49b6180-082d-11eb-85d7-0fcebb7f99d2.png)
After update:
![image](https://user-images.githubusercontent.com/20575981/95225384-52774c80-082e-11eb-978f-8952e91ad555.png)

2020-10-07 10:10 UTC, fqueiruga commented
I would put it before the version and rest api link

2020-10-07 13:03 UTC, yJunS commented
> I would put it before the version and rest api link

Okay. I already changed it

2020-10-07 13:47 UTC, fqueiruga approved these changes

2020-10-08 14:08 UTC, MRamonLeon commented
We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

2020-10-09 04:00 UTC, LinuxSuRen approved these changes
LGTM

Thanks a lot for this improvement.

2020-10-10 13:32 UTC, oleg-nenashev commented
Restarted CI

2020-10-12 10:19 UTC, merged

2020-10-12 10:19 UTC, oleg-nenashev commented
Thanks for your contribution @yJunS !

2020-10-12 11:45 UTC, yJunS commented
@oleg-nenashev It's okay. I want to join `jenkinsci` organization. How can I do it?

2020-10-14 13:37 UTC, zbynek commented
Looks like this triggered a display bug (related to `translate` extension?)

![image](https://user-images.githubusercontent.com/1105305/95996621-2f9ef680-0e33-11eb-809c-f059f62bc4cf.png)

2020-10-14 20:39 UTC, timja commented on core/src/main/resources/lib/layout/layout.jelly
> +              <st:include it="${pd}" page="footer.jelly" optional="true" />
Caused https://github.com/jenkinsci/jenkins/pull/5001