Replaced deprecated Configuration with SystemProperties
jenkinsci/jenkins pull request #4962
Opened 2020-10-03 10:15 UTC by StefanSpieker

Replaced deprecated usages of `Configuration` with `SystemProperties`

### Proposed changelog entries

* Internal: N/A

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2020-10-03 11:08 UTC, res0nance approved these changes

2020-10-03 18:37 UTC, daniel-beck requested changes
This is a breaking change, and more than it needs to be.

While we'd necessarily drop the "fallback behavior" of continuing to support old "Hudson" named system properties, this doesn't even add the prefix for Jenkins.

For example, we currently check `hudson.model.Hudson.logStartupPerformance` and `jenkins.model.Jenkins.logStartupPerformance` to control one of these behaviors. With this change, we'll check `logStartupPerformance`.

This seems unnecessary.

2020-10-03 19:36 UTC, StefanSpieker commented
Thanks Daniel for pointing that out. I did not recognize the missing prefix.

2020-10-05 08:32 UTC, oleg-nenashev approved these changes
> While we'd necessarily drop the "fallback behavior" of continuing to support old "Hudson" named system properties, this doesn't even add the prefix for Jenkins.

We could also add support for configuration aliases to `SystemConfiguration`. IMHO it is not mandatory, because we do not guarantee compatibility of properties. At the same time it might be useful for future migrations. Approving the change anyway,

If merged in the current form, I think it deserves being mentioned in the LTS upgrade guidelines

2020-10-08 09:45 UTC, oleg-nenashev commented
@daniel-beck a re-review would be appreciated

2020-10-08 14:27 UTC, rsandell approved these changes

2020-10-08 14:42 UTC, MRamonLeon reviewed
I'm a bit confused here.

The current behavior is to read `Jenkins` prefix, if not found, it tries with `Hudson` one:

```
    public static String getStringConfigParameter(String name, String defaultValue) {
        String value = SystemProperties.getString(Jenkins.class.getName()+"." + name);
        if( value == null )
            value = SystemProperties.getString(Hudson.class.getName()+"." + name);
        return (value==null)?defaultValue:value;
    }
```
If we want to remove the old prefixes, whey don't we just remove that from `Configuration` class? This PR is just removing this support on only several places. For any other configuration we read with `Configuration`, the fallback to `Hudson` still applies

2020-10-15 14:08 UTC, varyvol approved these changes

2020-10-15 14:09 UTC, alecharp approved these changes
LGTM, thanks!

2020-11-12 15:24 UTC, alecharp commented
I'm marking this PR as ready for merge due to the amount to agreement we have on this PR. It should be merge in the next 24hrs unless told otherwise. Thank you for your contribution.

2020-11-16 20:43 UTC, daniel-beck commented
Needs a corresponding PR updating https://www.jenkins.io/doc/book/managing/system-properties/

2020-11-23 23:03 UTC, oleg-nenashev commented
@jenkinsci/core 🚢 🇮🇹 ?

2020-11-29 09:19 UTC, timja commented
> Needs a corresponding PR updating [jenkins.io/doc/book/managing/system-properties](https://www.jenkins.io/doc/book/managing/system-properties/)

has this PR been done?

2020-12-16 20:19 UTC, timja commented
https://github.com/jenkins-infra/jenkins.io/pull/4030 ^^

2020-12-16 20:20 UTC, timja commented
@daniel-beck do you plan to re-review or should we ship?

2020-12-21 09:00 UTC, merged