[JENKINS-62446] adding CasC compatibility to Global tool > Global Maven
jenkinsci/jenkins pull request #5008
Opened 2020-10-16 14:37 UTC by aHenryJard

See [JENKINS-62446](https://issues.jenkins-ci.org/browse/JENKINS-62446).

Global maven configuration was not exported because the symbol `@Symbol("maven")` was used twice.

I keep the `@Symbol("maven")` for the currently CasC exportable part to not break existing configuration, and renamed the one that was not working.

Does anyone know if there is a JCasC compatibility test class in this project ?

### Proposed changelog entries

* Entry 1: JCasC compatibility for Global tool (/configureTools) > Maven Configuration
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2020-10-17 15:41 UTC, timja commented
Jcasc compat tests for core are normally hosted in the jcasc project built against an incremental of core

2020-11-06 14:06 UTC, MRamonLeon approved these changes

2020-11-06 14:42 UTC, timja approved these changes

2020-11-06 14:42 UTC, timja commented
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2020-11-09 09:40 UTC, oleg-nenashev approved these changes
Since the original implementation has never quite worked, I am +1 for it. At the same time, we need an explicit changelog entry to indicate what is what

2020-11-09 09:40 UTC, merged

2020-11-09 09:41 UTC, oleg-nenashev commented
Arguably, the symbol collision is a bug not a feature.
@aHenryJard would you like to see it backported to the 2.263.x LTS baseline

2020-11-09 15:16 UTC, aHenryJard commented
> Arguably, the symbol collision is a bug not a feature.
> @aHenryJard would you like to see it backported to the 2.263.x LTS baseline

Thanks for asking, no I don't have strong will to get it backported, I hit it while playing with JCasC and found it a to be good issue for my hacktober fest.

2020-11-10 10:46 UTC, oleg-nenashev commented
@timja WDYT about backporting? It would also allow to integrate the integration test in JCasC a few months earlier

2020-11-10 12:10 UTC, daniel-beck commented
I distinctly remember being told by someone (@jglick ?) that symbol collisions are only a problem within the same type of object, as users of symbol are expected to filter, or something along those lines. Is this a bug in JCasC?

2020-11-10 12:42 UTC, jglick commented
Yes, sounds like a bug in JCasC, not in core.

2020-11-10 12:44 UTC, jglick requested changes
`@Symbol`s should _not_ include the type of extension in some phrasing. Thus `maven` was correct, `mavenGlobalConfig` incorrect. Recommend closing and solving in `configuration as-code-plugin`.

2023-07-18 12:29 UTC, daniel-beck commented
Noting that I believe the PR description to be wrong, and this affects two different `Descriptor`s with `ToolConfigurationCategory` (the `tool` top-level container in JCasC): `Maven.MavenInstallation.DescriptorImpl` https://github.com/jenkinsci/jenkins/blob/0ce4268d219f249615ced798ed23b1cb3ecce93c/core/src/main/java/hudson/tasks/Maven.java#L665-L666 and `GlobalMavenConfig` (changed to `mavenGlobalConfig` here). That's a more awkward case for something like JCasC to handle.