JENKINS-28022 Fix copy-pasting from build descriptions
jenkinsci/jenkins pull request #5021
Opened 2020-10-21 12:14 UTC by gdubicki

as zero-width spaces cause obscure issues almost everywhere
where they are used.

2020-10-21 12:41 UTC, daniel-beck commented
Thanks for your work on this problem. Unfortunately, this code exists for a reason, and this PR doesn't even attempt to address that use case.

## Before (2.249.2)

![Screenshot](https://user-images.githubusercontent.com/1831569/96720627-4ac9b300-13ab-11eb-9723-8ee4615d892b.png)

## After (PR build)

![Screenshot](https://user-images.githubusercontent.com/1831569/96720477-1950e780-13ab-11eb-90c9-68251343ad22.png)

2020-10-21 12:41 UTC, daniel-beck requested changes
As above.

2020-10-21 16:47 UTC, gdubicki commented
Hey, sorry for that obvious minimal-effort first approach. 😅 My real idea for this is to replace the zws with a <wbr/> tag. I will try and test that.

2020-10-21 17:31 UTC, daniel-beck commented
@gdubicki Yes, sadly it's not quite that easy. It might still be easy (some CSS perhaps?) but not _this_ easy 😁

2020-10-21 23:31 UTC, martinda commented
Work on this was presented and discussed in https://github.com/jenkinsci/jenkins/pull/3377, but was later abandoned. CSS was recommended there too.

2020-10-22 11:09 UTC, fredericrous commented
Looking forward for a fix, keep up the good work! In my opinion having the ui look broken when there is long strings is bad, sure, but it is a lower bug than having an invisible character inserted in the version number

2020-10-22 14:56 UTC, gdubicki commented
We also remove that character in some places already, @fredericrous , but we are being hit by this over and over in new places every now and then. So we would like to finally fix the root cause of the issue.

2020-10-22 15:20 UTC, gdubicki commented
Thanks to @hakubo I fixed the code to use `word-break: break-word;` CSS property.

That property is supported by 96-98% of all the browers, according to https://caniuse.com/?search=word-break .

Preview: 
<img width="500" alt="Screenshot 2020-10-22 at 17 19 11" src="https://user-images.githubusercontent.com/566632/96893179-bafb3600-148a-11eb-98d7-0e89abb58abe.png">

Is this ok everyone?

2020-11-09 12:06 UTC, gdubicki commented
@daniel-beck , @oleg-nenashev : a friendly reminder that this PR awaits your review :)

2020-12-08 15:26 UTC, gdubicki commented
...and another gentle ping for a review. :)

2021-01-13 16:37 UTC, primoz-p commented
> Looking forward for a fix, keep up the good work! In my opinion having the ui look broken when there is long strings is bad, sure, but it is a lower bug than having an invisible character inserted in the version number.
> 
> Anyway, the approach we are taking in my service is to accept that jenkins adds an extra invisible character in the UI and "fix" this by removing this extra character where it is used. As it happens, it's another jenkins job that takes the build version as parameter. I haven't tested this code because I'm not in charge of the resolution but this should do the trick for anyone reading this
> 
> ```
> String versionToUse = params.version.replaceAll("[\\p{Cf}]", "");
> ```

Same problem here.
We spent too much time today searching for a cause of failed build. Later we found out that somebody just copied version from build description and that there was this invisible character at the beginning of parameter.

Hoping you'll find a solution and I'm sure that "technology" was updated from 2014/15 where this zero-space-character was used for work wrapping...

2021-01-14 12:55 UTC, daniel-beck approved these changes
Tested interactively using the core PR tester, and it worked for my test cases.

<img width="516" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/104593392-ed729480-566f-11eb-8cc4-e53db7b54e9d.png">

This looks like a reasonable improvement.

2021-01-15 07:55 UTC, gdubicki commented
Great, thanks @daniel-beck !

Can you take a look too please, @oleg-nenashev ?

2021-01-16 10:14 UTC, timja approved these changes

2021-01-16 10:15 UTC, timja commented
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2021-01-17 14:33 UTC, oleg-nenashev approved these changes
Not sure whether it will work fine for any localization, but a default CSS property looks much better than the manual word break implementation. Thanks for the patch!

2021-01-18 16:06 UTC, merged

2021-01-26 01:08 UTC, jsoref commented
Fwiw, in theory, I think one should try to use [break-all](https://caniuse.com/?search=break-all) ([ref](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#values)) value and fall back to `break-word`