[JENKINS-65386] added some examples on how to archive multiple artifacts
jenkinsci/jenkins pull request #5427
Opened 2021-04-16 15:43 UTC by ciradu2204

See [JENKINS-65386](https://issues.jenkins.io/browse/JENKINS-65386#gid=1087292709]).

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist
- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@MarkEWaite 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2021-04-16 17:28 UTC, aHenryJard reviewed
Looks good to me, I just wonder about the rendering, I think you need to add some html tag for break line.

2021-04-16 17:28 UTC, aHenryJard commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +
```suggestion
<br/>
```
Do you have a screenshot of how is generated this help ? I think that if you want to keep space to format you need a <br> tag or maybe a <p> ...</p>. Not sure on what is the best.

2021-04-16 17:28 UTC, aHenryJard commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +
```suggestion
<br/>
```
same comment as above.

2021-04-16 17:43 UTC, kwhetstone commented
I think I would also include an example of how to archive multiple nested files too since I think that is a pretty common use case as well.  (the `/**/*` type syntax)  I would also add that the `archiveArtifacts` step works from the directory you're currently in.  So if you're invoking `archiveArtificts` from inside the `folder` step, it will search for files within that folder.  That could be a place where someone invoking the step could get confused as to why they're missing test results!

2021-04-16 18:03 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +   <pre>archiveArtifacts: artifacts: 'target/*.jar'</pre>
Note that this syntax is Pipeline-specific, and this help is shown in other contexts (e.g. freestyle). I would limit it to the specific string value specifying what to archive.

(Also, I think this is syntactically invalid, the first colon seems wrong?)

2021-04-16 18:04 UTC, aHenryJard commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +   <pre>archiveArtifacts: artifacts: 'target/*.jar'</pre>
```suggestion
   <pre>archiveArtifacts artifacts: 'target/*.jar'</pre>
```
there is no : at the beginning

2021-04-16 20:04 UTC, MarkEWaite commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +   <pre>archiveArtifacts: artifacts: 'target/*.jar, target/*.war'</pre>
Use the same syntax in both examples (omit the extra ':')
```suggestion
   <pre>archiveArtifacts artifacts: 'target/*.jar, target/*.war'</pre>
```

2021-04-18 15:05 UTC, oleg-nenashev approved these changes

2021-04-19 19:50 UTC, ciradu2204 commented
@MarkEWaite  @daniel-beck  @kwhetstone @aHenryJard 

Here is the screenshot: 
![image](https://user-images.githubusercontent.com/37863089/115294341-c89f2900-a158-11eb-8b7b-d6c14874ab30.png)

2021-04-19 21:04 UTC, timja commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +   <p>Here are some examples of usage for declarative pipeline: </p>
relevant to scripted pipeline as well:
```suggestion
   <p>Here are some examples of usage for pipeline: </p>
```

2021-04-20 08:04 UTC, timja approved these changes

2021-04-20 08:57 UTC, daniel-beck requested changes

2021-04-20 08:57 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help.html
> +  The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator">Pipeline Snippet Generator</a> generates this example
```suggestion
  The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" target="_blank" rel="noopener noreferrer">Pipeline Snippet Generator</a> generates this example
```

2021-04-20 08:57 UTC, daniel-beck commented on core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
> +   <p>Here are some examples of usage for pipeline: </p>
```suggestion
   <p>Here are some examples of usage for Pipeline: </p>
```

Unsure about this one, but I think we generally capitalize it (pipeline being the concept, Pipeline the implementation in Jenkins).

2021-04-23 06:51 UTC, aHenryJard approved these changes
Looks good to me.

2021-04-23 06:54 UTC, timja commented
@daniel-beck are you happy with the changes made?

2021-04-23 09:41 UTC, daniel-beck approved these changes
Use of `pre` is wrong (`code` or both would be more appropriate), but I would be surprised if it's the first case in the codebase, so 🤷

2021-04-23 19:41 UTC, ciradu2204 commented
> Use of `pre` is wrong (`code` or both would be more appropriate), but I would be surprised if it's the first case in the codebase, so 🤷

Thanks, @daniel-beck, I have made changes.

2021-04-23 19:51 UTC, daniel-beck commented
@ciradu2204  Why did you revert the changes to the link to documentation?

2021-04-23 20:07 UTC, ciradu2204 commented
When I do not use pre, it looks like this:

![image](https://user-images.githubusercontent.com/37863089/115924476-0dd89900-a480-11eb-9046-8e14cbbdd9f7.png)
 
So I decided to use both.

2021-04-23 20:39 UTC, daniel-beck commented
@ciradu2204 

> So I decided to use both. What do you think?

That's correct. My comment is about https://github.com/jenkinsci/jenkins/pull/5427/files#diff-0d5a92f41db5ae8e6bce0b400a25bf4db47d82e13b8ad1ea4fd9d519abc57895R16 https://github.com/jenkinsci/jenkins/pull/5427/files#diff-0d5a92f41db5ae8e6bce0b400a25bf4db47d82e13b8ad1ea4fd9d519abc57895R21 and https://github.com/jenkinsci/jenkins/pull/5427/files#diff-0d5a92f41db5ae8e6bce0b400a25bf4db47d82e13b8ad1ea4fd9d519abc57895R26

> Regarding your question about the link to the documentation that I added is to help users know where to find the snippet generator.

In the latest commit you revert some changes done in code review: https://github.com/jenkinsci/jenkins/pull/5427/commits/becb8938684c045702e0a90762dc0913a503d1fc

It's not visible in the diff but that's the result of the merge commit. I am asking why.

2021-04-23 21:30 UTC, ciradu2204 commented
oooh, I apologize for that @daniel-beck.  That's a mistake I made when solving some merge conflicts. Let me commit the changes again

2021-04-23 21:30 UTC, ciradu2204 commented
oooh, I apologize for that @daniel-beck.  That's a mistake I made when solving some merge conflicts. Let me commit the changes again

2021-04-24 07:56 UTC, daniel-beck requested changes
Link needs `target` and `rel` attributes.

2021-04-24 10:18 UTC, ciradu2204 commented
> @ciradu2204 The problem is that you removed them before 😉 The link needs `target` and `rel` attributes.

I have added them again😊

2021-04-24 17:45 UTC, daniel-beck approved these changes

2021-04-25 00:00 UTC, MarkEWaite reviewed
This PR is now ready for merge.  We will merge it after approximately 24 hours if there is no negative feedback.

2021-04-26 16:55 UTC, MarkEWaite approved these changes

2021-04-26 16:55 UTC, merged

2021-04-28 06:45 UTC, oleg-nenashev commented
Thanks for your contribution @ciradu2204 !

2021-04-28 16:06 UTC, ciradu2204 commented
> Thanks for your contribution @ciradu2204 !

You are welcome 😊