[JENKINS-60866] Clean up login and signup page JS
jenkinsci/jenkins pull request #5512
Opened 2021-05-21 20:38 UTC by daniel-beck

See [JENKINS-60866](https://issues.jenkins-ci.org/browse/JENKINS-60866).

Move inline JS out of signup and login pages.

Additionally, set Content-Security-Policy headers to not allow inline content. This is a potentially breaking change for any `SimplePageDecorator` implementations that add inline JS, but #3380 claimed to improve security, so that seems appropriate. The fix is trivial, just load content from files.

Thoughts?

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2021-05-21 20:39 UTC, daniel-beck commented on core/src/main/resources/jenkins/model/Jenkins/login.jelly
> -                  }
This appears to be unused.

2021-05-21 20:39 UTC, daniel-beck commented on core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
> -                        </j:if>
Added during development of #3380 but the supporting code elsewhere was removed before it was merged, so this was always false.

2021-05-24 20:13 UTC, timja submitted a review, later dismissed

2021-05-27 09:01 UTC, Wadeck requested changes
Without CSP enforced, the un-inlining works. With it, it's broken both in signup and in SetupWizard.

2022-02-15 21:35 UTC, closed without merging