Modernise the 'New view' and 'New node' pages
jenkinsci/jenkins pull request #5842
Opened 2021-10-21 11:11 UTC by janfaracik

## What's changed?

This PR updates the appearance of several (not all!) form controls to give Jenkins a more modern, consistent appearance. The main focus of this PR is to modernise the 'New view' and 'New node' pages, however, some of the changes, such as the change in `input` design will ripple throughout Jenkins.

The end goal would be to update all the form controls across Jenkins, ensuring consistency, modernity and better accessibility throughout the service.

## Test this pull request

```command
docker run --rm -ti -p 8080:8080 -e ID=5842 -e MERGE_WITH=master jenkins/core-pr-tester
```

## Screenshots

### Old
<img width="703" alt="image" src="https://user-images.githubusercontent.com/43062514/138264685-96841c37-837d-40a0-923d-f2062d57ac20.png">

### New
<img width="576" alt="image" src="https://user-images.githubusercontent.com/43062514/138264630-0394e2fb-e22d-48cf-82d1-7b9487b36e0a.png">

### Old
<img width="764" alt="image" src="https://user-images.githubusercontent.com/43062514/138265236-3df8115a-e711-4b15-bd9a-e1a937267b3f.png">

### New
https://user-images.githubusercontent.com/43062514/138265559-13998e0d-421d-4a93-81c0-d4a37a7a7260.mov

### Proposed changelog entries

* Modernise the 'New view' and 'New node' pages

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2021-10-21 12:37 UTC, fqueiruga reviewed
I think this is a GREAT PR. Congratulations!!!!! 🎉 I do have a few comments if you don't mind:

- 350px inputs are way too short for. Going for ~700px/43rem is always a solid choice.
- I think you could very well go all in with the configuration. Stuff like padding, label font weight, box shadows, etc.
- Border radius should IMO be 4px to be consistent with the rest of the UI and plugins.

My only -1 would be having custom buttons. I don't think there's any need for that. Existing buttons are widely used and won't probably be changed. And if they need changes, it should be global IMO. This is coming from my personal experience with the buttons revamp last year.

Also, have you tried applying these styles to the `.setting-input` class, just to see what happens? Any long term form strategy to update inputs would be most effective by acting on that class.

2021-10-21 12:47 UTC, timja reviewed
Generally I think this is really good, my main concern is that some pages are going to look weird because the changes only apply to text input currently

Examples where it looks weird:

<details>
<summary>Password input</summary>

![image](https://user-images.githubusercontent.com/21194782/138280269-1c4e140d-3dfc-49bc-91e5-403c61406715.png)

</details>

<details>
<summary>Number / dropdowns</summary>

![image](https://user-images.githubusercontent.com/21194782/138280382-b3f6b2ca-a8e2-4dbb-b583-27f53a53c51a.png)


</details>

<details>
<summary>Configure system page</summary>

![image](https://user-images.githubusercontent.com/21194782/138280102-3e616fa7-60a2-49d0-bed6-60e6ed2fbf59.png)

</details>

2021-10-25 07:52 UTC, uhafner reviewed
I think the design looks great! Since we have so many different places where forms are used this PR might need some more time until we can ensure that we do not break too much forms?

2021-10-27 08:10 UTC, timja approved these changes
Last weirdness is generally just things that haven't been constrained by the max-width, mostly advanced buttons but that will be fixed in a follow-up.

I've fixed the acceptance test harness issues that are causing this build to fail, but that caused lots of other ones to fail which i'm fixing as I get time, (so I haven't released the tests yet).

They are failing because the radio is no longer a real radio button (hidden by opacity: 0) so we have to click the label, the tests have this thing where they navigate by `xpath` and the label doesn't have an xpath so the code needs adjusting to find the input from the label, (which is trivial, it's just finding all the places), and some places need updating to use label text instead of the input name

2021-10-27 08:11 UTC, fqueiruga requested changes
I have some, I think critical, change requests on JS code that I think will break backwards compatibility. Should be an straightforward fix. After that, it's an immediate ✅ from me.

I do suggest flattening out SCSS selectors, especially class definitions done by nesting. These are in my experience very difficult to maintain, especially for non frontend-specialised people.

This is an amazing PR and the forms look so much better live. I also expected the mixed form styles to be way more jarring but it's not that bad for an intermediate step. Cheers!

2021-10-27 09:45 UTC, uhafner reviewed
I general: a big improvement 🎉. Some details are still broken, I'm not sure if that should be fixed before we merge this. One thing that I don't like is the fixed size of the forms which looks kind of odd on my 27'' monitor. But maybe this is a bug because some elements are still on the right side.

Some details I found (description is always after the screenshot).

![Bildschirmfoto 2021-10-27 um 11 16 15](https://user-images.githubusercontent.com/503338/139037474-add9a877-c3c8-45a9-98b7-d1e65198738b.png)

- The section headers are not always correct (orange rectangle).
- The gap after the header text is too small (red rectangle). 

![Bildschirmfoto 2021-10-27 um 11 11 28](https://user-images.githubusercontent.com/503338/139038094-2d771f53-7f57-4093-84b8-814c04a8900a.png)

- Some elements (buttons) float to the right (orange rectangle)
- All blocks do not fill the available space anymore (red rectangle). From the discussion this seems to be intended, but why is the background area still so wide? For people with a monitor most part of the screen is now empty (and large descriptions fill a couple of lines)
- Select form element is not yet styled correctly
- Autocompletion text field is not yet styled correctly

![Bildschirmfoto 2021-10-27 um 11 29 29](https://user-images.githubusercontent.com/503338/139041534-da23478c-f5d2-49c0-826b-d2de41e6d94c.png)

- Custom entries are not yet styled correctly (this can be implemented in the affected plugins step by step)

![Bildschirmfoto 2021-10-27 um 11 39 25](https://user-images.githubusercontent.com/503338/139041390-399d50ac-504e-4381-a8e0-c58698b89f47.png)

- In the pipeline step snippet generator somehow the fonts of descriptions are smaller

2021-10-29 12:33 UTC, fqueiruga approved these changes
@timja it's a go from me then :D congrats @janfaracik

2021-10-29 13:58 UTC, uhafner approved these changes
Fine for me as well now. Thanks for your work!

2021-11-01 09:29 UTC, timja commented
This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2021-11-01 20:36 UTC, timja commented
Some minor test fixups needed:
`lib.form.AdvancedButtonTest.testSectionInsideOfAdvanced`
`lib.form.AdvancedButtonTest.testNestedOptionalBlock`

2021-11-01 22:51 UTC, janfaracik commented
> Some minor test fixups needed:
> `lib.form.AdvancedButtonTest.testSectionInsideOfAdvanced`
> `lib.form.AdvancedButtonTest.testNestedOptionalBlock`

Fixed now :)

2021-11-02 05:52 UTC, oleg-nenashev approved these changes
Looks good to me. IIRC I tested it locally a few weeks ago and new layouts looked really well

2021-11-02 05:53 UTC, oleg-nenashev commented
@timja I suggest merging it into the weekly. the 24hrs timeout expires just one hour after the release should start IIUC

2021-11-02 07:06 UTC, timja commented
> @timja I suggest merging it into the weekly. the 24hrs timeout expires just one hour after the release should start IIUC

There’s a security release on Thursday, delaying bigger merges till after that

2021-11-04 20:12 UTC, merged

2021-11-05 18:56 UTC, daniel-beck commented
[JENKINS-67071](https://issues.jenkins.io/browse/JENKINS-67071) suggests this causes a regression in job config forms.

2021-11-05 19:54 UTC, timja commented
> [JENKINS-67071](https://issues.jenkins.io/browse/JENKINS-67071) suggests this causes a regression in job config forms.

Addressed in https://github.com/jenkinsci/jenkins/pull/5893

2021-11-06 16:11 UTC, timja commented
Spacing is off:

![image](https://user-images.githubusercontent.com/21194782/140616236-33fc8083-9067-4959-9b22-311c79b14404.png)

Validation icon touched the input

2021-11-07 07:54 UTC, timja commented
Disabled project text and icon is mis-aligned:

![image](https://user-images.githubusercontent.com/21194782/140636467-d287e9ca-1b01-4045-bca8-af1cd8884a17.png)

2021-11-08 11:13 UTC, timja commented
Help icon broken for freestyle build Set build status pending github commit (GitHub plugin)

![image](https://user-images.githubusercontent.com/21194782/140732259-8f346eb6-d5e6-4c1f-9497-bb336ab08d9e.png)

(assume it was this PR)

2021-11-10 22:24 UTC, basil commented
After pulling in this commit, I can no longer add a Maven installation via the UI (see [JENKINS-67109](https://issues.jenkins.io/browse/JENKINS-67109)).

2021-11-16 00:38 UTC, basil commented
@janfaracik This PR breaks the following tests and blocks weekly updates to the BOM (cf. jenkinsci/bom#717 and jenkinsci/bom#719):

- `hudson.plugins.throttleconcurrents.ThrottleJobPropertyTest#clearConfiguredCategories`
- `hudson.plugins.throttleconcurrents.ThrottleQueueTaskDispatcherTest#testShouldConsiderTaskAsBlockableStillUponMatchingLabelPairWithLowestMax`
- `hudson.plugins.throttleconcurrents.ThrottleQueueTaskDispatcherTest#testShouldConsiderTaskAsBlockableStillUponMatchingMaxLabelPair`
- `hudson.plugins.throttleconcurrents.ThrottleQueueTaskDispatcherTest#testShouldConsiderTaskAsBlockableStillUponMatchingMaxLabelPairs`
- `hudson.plugins.throttleconcurrents.ThrottleQueueTaskDispatcherTest#testShouldConsiderTaskAsBuildableStillUponMismatchingMaxLabelPairs`
- `org.jenkinsci.plugins.pipeline.modeldefinition.StageInputTest.parametersInInput`

The tests will need to be adapted to this PR and new versions of the abovementioned plugins released.

2021-11-16 07:16 UTC, timja commented
I have changed locally that fixes most of those, there’s one test i’m still debugging

2021-11-16 17:46 UTC, basil commented
Also breaks `hudson.plugins.emailext.ExtendedEmailPublisherDescriptorTest#groovyClassPath`. Has an effort been made to systematically evaluate the impact of this PR and prepare plugins?

2021-11-21 23:20 UTC, uhafner commented
I'm not sure if someone is still is working on the problematic width resolution change within this PR, I created an issue so this will not be forgotten: https://issues.jenkins.io/browse/JENKINS-67198

2021-11-30 13:36 UTC, NathanLindshield commented
The screenshots above even show the fixed minimal width

2021-11-30 13:46 UTC, timja commented
It's being addressed to a degree in https://github.com/jenkinsci/jenkins/pull/5923

There's additional work coming as well that was demoed in the previous UX sig meeting, around here:
https://youtu.be/SxSObgwjwt8?t=3428

Plenty of open PRs in this area:
https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Ajanfaracik

Generally getting held up either adjusting tests to markup or fixing issues, but hopefully we'll get most of them merged in December

2021-11-30 13:48 UTC, NathanLindshield commented
Thanks @timja, appreciate it! Great work!

2021-12-18 14:25 UTC, hankzhao-zp commented
> I'm not sure if someone is still is working on the problematic width resolution change within this PR, I created an issue so this will not be forgotten: https://issues.jenkins.io/browse/JENKINS-67198

Is anyone looking at this question, it really bothers me

2021-12-18 19:52 UTC, janfaracik commented
> > I'm not sure if someone is still is working on the problematic width resolution change within this PR, I created an issue so this will not be forgotten: https://issues.jenkins.io/browse/JENKINS-67198
> 
> Is anyone looking at this question, it really bothers me

I am :) It'll be updated as part of #5923, I've posted a WIP screenshot on the Jira thread if you're interested.

2022-04-12 01:58 UTC, basil commented
Causes [JENKINS-68042](https://issues.jenkins.io/browse/JENKINS-68042)

2022-06-22 14:41 UTC, daniel-beck commented on core/src/main/resources/lib/form/helpLink.jelly
> +      <a href="#" class="jenkins-help-button" tooltip="${altText}" helpURL="${rootURL}${attrs.url}">
Caused [SECURITY-2779](https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2781)

2022-07-16 11:24 UTC, daniel-beck commented
Caused [JENKINS-69030](https://issues.jenkins.io/browse/JENKINS-69030)

2022-09-07 11:48 UTC, daniel-beck commented
Contributed to [JENKINS-69549](https://issues.jenkins.io/browse/JENKINS-69549).

2024-02-26 18:29 UTC, daniel-beck commented
Caused [JENKINS-72749](https://issues.jenkins.io/browse/JENKINS-72749)