Add missing SVG for parameterized jobs
jenkinsci/jenkins pull request #5905
Opened 2021-11-09 18:38 UTC by NotMyFault

### Proposed changelog entries

* Add missing SVG for parameterized jobs

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins-ci.org/issues/?filter=12146)).

2021-11-09 20:48 UTC, timja commented
Can you provide screenshots for UI changes please?

and add a bit of description to the PR

2021-11-09 21:08 UTC, NotMyFault commented
> Can you provide screenshots for UI changes please?
> 
> and add a bit of description to the PR
> 
> Where did the svg come from?

There we go, I hope that makes it a bit more clear. The icon is part of the gnome desktop icons, so the same source like the urgent or shutdown one.

2021-11-10 09:31 UTC, timja approved these changes

2021-11-10 09:52 UTC, uhafner requested changes
Shouldn't we also delete the old ones? I think the other PRs deleted them. 

In general: the new SVG icon looks better than the existing ones. However, when we are changing icons we should not use yet another different icon provider (Gnome). I think for each icon we should stick to either Iconic (or Font Awesome or Material). Otherwise we get a mix of styles and we are currently on a very good way to create a consistent styling.

2021-11-10 10:36 UTC, NotMyFault commented
The next

> Shouldn't we also delete the old ones? I think the other PRs deleted them.
> 
> In general: the new SVG icon looks better than the existing ones. However, when we are changing icons we should not use yet another different icon provider (Gnome). I think for each icon we should stick to either Iconic (or Font Awesome or Material). Otherwise we get a mix of styles and we are currently on a very good way to create a consistent styling.

Pulling in font awesome or material would look out of place in my opinion, considering the majority of (sidebar) icons are either from gnome or tango.
The former has been addressed nevertheless.

2021-11-10 12:55 UTC, uhafner approved these changes
Well, it feels somewhat strange to repair something that I am planning to throw away in the next week. But it is fine for me, it was just a suggestion to accelerate our ongoing  renewal of UI elements. So this PR is just duplicate work if someone else finds the time to replace this icon.

2021-11-10 14:51 UTC, fqueiruga approved these changes

2021-11-10 14:54 UTC, fqueiruga requested changes
The SVG needs to be optimised IMO. Running it through https://jakearchibald.github.io/svgomg/ resulted in a reduction to 47% of the size:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="48" width="48">
  <defs>
    <radialGradient xlink:href="#a" id="l" gradientUnits="userSpaceOnUse" gradientTransform="matrix(-2.77439 0 0 1.9697 112.762 -872.885)" cx="605.714" cy="486.648" fx="605.714" fy="486.648" r="117.143"/>
    <radialGradient xlink:href="#a" id="k" gradientUnits="userSpaceOnUse" gradientTransform="matrix(2.77439 0 0 1.9697 -1891.633 -872.885)" cx="605.714" cy="486.648" fx="605.714" fy="486.648" r="117.143"/>
    <radialGradient id="g" cx="20.892" cy="64.568" r="5.257" fx="20.892" fy="64.568" gradientUnits="userSpaceOnUse">
      <stop offset="0" style="stop-color:#f0f0f0"/>
      <stop offset="1" style="stop-color:#9a9a9a;stop-opacity:1"/>
    </radialGradient>
    <radialGradient id="f" cx="20.892" cy="114.568" r="5.256" fx="20.892" fy="114.568" gradientUnits="userSpaceOnUse">
      <stop offset="0" style="stop-color:#f0f0f0"/>
      <stop offset="1" style="stop-color:#9a9a9a;stop-opacity:1"/>
    </radialGradient>
    <radialGradient xlink:href="#d" id="m" gradientUnits="userSpaceOnUse" gradientTransform="scale(.9605 1.04113)" cx="33.967" cy="35.737" fx="33.967" fy="35.737" r="86.708"/>
    <radialGradient xlink:href="#e" id="n" gradientUnits="userSpaceOnUse" gradientTransform="matrix(.96827 0 0 1.03277 3.354 .646)" cx="8.144" cy="7.268" fx="8.144" fy="7.268" r="38.159"/>
    <radialGradient r="5.256" fy="114.568" fx="20.892" cy="114.568" cx="20.892" gradientTransform="matrix(.2297 0 0 .2297 4.614 3.98)" gradientUnits="userSpaceOnUse" id="o" xlink:href="#f"/>
    <radialGradient r="5.257" fy="64.568" fx="20.892" cy="64.568" cx="20.892" gradientTransform="matrix(.2297 0 0 .2297 4.614 3.98)" gradientUnits="userSpaceOnUse" id="p" xlink:href="#g"/>
    <radialGradient xlink:href="#i" id="q" cx="26.03" cy="24.227" fx="26.03" fy="24.227" r="11.63" gradientTransform="matrix(2.11099 0 0 2.53493 -28.92 -38.044)" gradientUnits="userSpaceOnUse"/>
    <linearGradient id="a">
      <stop style="stop-color:black;stop-opacity:1" offset="0"/>
      <stop style="stop-color:black;stop-opacity:0" offset="1"/>
    </linearGradient>
    <linearGradient id="b">
      <stop style="stop-color:black;stop-opacity:0" offset="0"/>
      <stop offset=".5" style="stop-color:black;stop-opacity:1"/>
      <stop style="stop-color:black;stop-opacity:0" offset="1"/>
    </linearGradient>
    <linearGradient xlink:href="#b" id="j" gradientUnits="userSpaceOnUse" gradientTransform="matrix(2.77439 0 0 1.9697 -1892.179 -872.885)" x1="302.857" y1="366.648" x2="302.857" y2="609.505"/>
    <linearGradient id="i">
      <stop style="stop-color:#000;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#000;stop-opacity:0" offset="1"/>
    </linearGradient>
    <linearGradient id="h">
      <stop style="stop-color:#000;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#000;stop-opacity:0" offset="1"/>
    </linearGradient>
    <linearGradient id="e">
      <stop offset="0" style="stop-color:#fff;stop-opacity:1"/>
      <stop offset="1" style="stop-color:#f8f8f8;stop-opacity:1"/>
    </linearGradient>
    <linearGradient id="c">
      <stop offset="0" style="stop-color:#a3a3a3;stop-opacity:1"/>
      <stop offset="1" style="stop-color:#4c4c4c;stop-opacity:1"/>
    </linearGradient>
    <linearGradient id="d">
      <stop offset="0" style="stop-color:#fafafa;stop-opacity:1"/>
      <stop offset="1" style="stop-color:#bbb;stop-opacity:1"/>
    </linearGradient>
  </defs>
  <g style="display:inline">
    <path style="opacity:.40206185;color:#000;fill:url(#j);fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:1;stroke-linecap:round;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible" d="M-1559.252-150.697h1339.633V327.66h-1339.633z" transform="matrix(.02165 0 0 .01486 43.008 42.685)"/>
    <path d="M-219.619-150.68v478.33c142.874.9 345.4-107.17 345.4-239.196S-33.655-150.68-219.619-150.68z" style="opacity:.40206185;color:#000;fill:url(#k);fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:1;stroke-linecap:round;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible" transform="matrix(.02165 0 0 .01486 43.008 42.685)"/>
    <path style="opacity:.40206185;color:#000;fill:url(#l);fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:1;stroke-linecap:round;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;overflow:visible" d="M-1559.252-150.68v478.33c-142.875.9-345.4-107.17-345.4-239.196s159.436-239.134 345.4-239.134z" transform="matrix(.02165 0 0 .01486 43.008 42.685)"/>
  </g>
  <g style="display:inline">
    <rect style="color:#000;fill:url(#m);fill-opacity:1;fill-rule:nonzero;stroke:url(#radialGradient15656);stroke-width:1;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dashoffset:0;stroke-opacity:1;marker:none;marker-start:none;marker-mid:none;marker-end:none;visibility:visible;display:block;overflow:visible" width="34.875" height="40.92" x="6.604" y="3.646" ry="1.149"/>
    <rect style="color:#000;fill:none;fill-opacity:1;fill-rule:nonzero;stroke:url(#n);stroke-width:1;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dashoffset:0;stroke-opacity:1;marker:none;marker-start:none;marker-mid:none;marker-end:none;visibility:visible;display:block;overflow:visible" width="32.776" height="38.946" x="7.666" y="4.584" ry=".149" rx=".149"/>
    <g style="fill:#fff;fill-opacity:1;fill-rule:nonzero;stroke:#000;stroke-miterlimit:4" stroke="none">
      <path style="stroke:none" d="M23.428 113.07a3.573 3.573 0 1 1-7.145-.001 3.573 3.573 0 0 1 7.145.001zM23.428 63.07a3.573 3.573 0 1 1-7.147 0 3.573 3.573 0 0 1 7.147 0z" transform="matrix(.2297 0 0 .2297 5.614 4.207)"/>
    </g>
    <path style="fill:url(#o);fill-rule:nonzero;stroke:none;stroke-miterlimit:4" d="M9.995 29.952a.82.82 0 1 1-1.641 0 .82.82 0 0 1 1.641 0z" transform="translate(.646 -.038)"/>
    <path style="fill:url(#p);fill-rule:nonzero;stroke:none;stroke-miterlimit:4" d="M9.995 18.467a.82.82 0 1 1-1.642 0 .82.82 0 0 1 1.642 0z" transform="translate(.646 -.038)"/>
    <path style="fill:none;fill-opacity:.75;fill-rule:evenodd;stroke:#000;stroke-width:.98855311;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:.017543854" d="M11.506 5.494v37.907"/>
    <path style="fill:none;fill-opacity:.75;fill-rule:evenodd;stroke:#fff;stroke-width:1;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:.20467831" d="M12.5 5.02v38.018"/>
  </g>
  <g style="display:inline">
    <g transform="matrix(.9091 0 0 1 2.364 0)">
      <rect style="color:#000;fill:#9b9b9b;fill-opacity:.54970759;fill-rule:nonzero;stroke:none;stroke-width:1;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dashoffset:0;stroke-opacity:.081871338;marker:none;marker-start:none;marker-mid:none;marker-end:none;visibility:visible;display:block;overflow:visible" width="22" height="1" x="15" y="9" rx=".152" ry=".065"/>
      <rect style="color:#000;fill:#9b9b9b;fill-opacity:.54970759;fill-rule:nonzero;stroke:none;stroke-width:1;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dashoffset:0;stroke-opacity:.081871338;marker:none;marker-start:none;marker-mid:none;marker-end:none;visibility:visible;display:block;overflow:visible" width="22" height="1" x="15" y="11" rx=".152" ry=".065"/>
      <rect style="color:#000;fill:#9b9b9b [...]

2021-11-10 14:55 UTC, fqueiruga commented
Also, those hardcoded colours make me suspect that it may look bad on dark mode. Was it tested on it?

2021-11-10 16:22 UTC, timja commented
> Well, it feels somewhat strange to repair something that I am planning to throw away in the next week. But it is fine for me, it was just a suggestion to accelerate our ongoing renewal of UI elements. So this PR is just duplicate work if someone else finds the time to replace this icon.

FTR it's the same image as the original just not in a blurry png when zoomed in.

2021-11-10 18:33 UTC, uhafner commented
@fqueiruga A side note: I'm not sure if you have seen https://community.jenkins.io/t/synching-colors-in-user-interface-and-server-side-code. One question of this thread: is it possible to dynamically change the color of our new SVGs? That means can we change those SVGs in a way we can change the color dynamically by themes? Or is that not possible on the client side?

2021-11-10 19:07 UTC, fqueiruga commented
Haven't seen that one. I'll take a look.

The easiest way to handle it, and by far the more maintainable IMO, is to have the SVGs be monochrome, using flat icons, use `fill="currentColor"` and be styled as text.

2021-11-10 19:08 UTC, fqueiruga commented
That does require work in the custom svgs ofc. I do not know if it's possible to use CSS vars within the SVGs, but that would also break icons for IE11

2021-11-12 09:59 UTC, NotMyFault commented
> Well, it feels somewhat strange to repair something that I am planning to throw away in the next week. But it is fine for me, it was just a suggestion to accelerate our ongoing renewal of UI elements. So this PR is just duplicate work if someone else finds the time to replace this icon.

If you have plans for something that supersedes this PR soon, I'd vouch for closing this MR unmerged instead of pushing more changes here, I'm fine with it.

2021-11-12 10:27 UTC, uhafner commented
No, just go ahead - I am fine with merging the PR. I am also not planning anything different, this was a typo or a wrong phrasing from my side. What I wanted to say: in the future it would make more sense if we would replace existing tango style icons with more modern SVG icons from one of our favorite icon providers. I think it is not worth the time to simply convert the existing tango png icon with the (still ugly) tango SVG icon. It will cost the same time to replace it with a modern SVG icon. But since you already spent the time, it is ok. Just for the next time: use a different icon.

2021-11-16 05:14 UTC, oleg-nenashev approved these changes
Looks like a good improvement to me. AFAICT comments from @fqueiruga have been addressed. The icon is likely to look not that great in the dark mode, but definitely it was a case for the previous edition. I am +1 for going ahead

2021-12-17 21:00 UTC, oleg-nenashev commented
Marking it as ready for merge, no response from @fqueiruga in over a month

We may merge it in 24 hours if there is no negative feedback. Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process

2021-12-19 13:49 UTC, merged