[JENKINS-68323] Missing "x" to clear the search bar of the plugin manager on Firefox
jenkinsci/jenkins pull request #6541
Opened 2022-05-05 09:03 UTC by frankie139506

See [JENKINS-68323](https://issues.jenkins.io/browse/JENKINS-68323).
![gif1](https://user-images.githubusercontent.com/97017043/166892292-f203da1d-f1a5-4fde-8a20-cc5fe50f7f02.gif)

### Proposed changelog entries

* Search box can clear by "x" on Firefox.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

2022-05-05 23:14 UTC, basil commented on war/src/main/less/form/search.less
> +	content: "x";
I think [U+1F5D9 CANCELLATION X](https://www.fileformat.info/info/unicode/char/1f5d9/index.htm) is a better Unicode glyph for this character than [U+0078 LATIN SMALL LETTER X](https://www.fileformat.info/info/unicode/char/0078/index.htm).

```suggestion
	content: "\1F5D9";
```

(+ whatever other CSS changes are necessary to vertically align the new glyph in the middle)

2022-05-06 00:02 UTC, NotMyFault reviewed
Am I testing this somehow wrong? On Firefox 100.0, there's no such "x":
![](https://i.imgur.com/88TaZi5.png)

2022-05-06 12:35 UTC, frankie139506 commented
> Am I testing this somehow wrong? On Firefox 100.0, there's no such "x": ![](https://camo.githubusercontent.com/320b7911019b73e4de51d30b28357073e4a91acff3164cd771cada35ecb39156/68747470733a2f2f692e696d6775722e636f6d2f383854615a69352e706e67)



> Am I testing this somehow wrong? On Firefox 100.0, there's no such "x": ![](https://camo.githubusercontent.com/320b7911019b73e4de51d30b28357073e4a91acff3164cd771cada35ecb39156/68747470733a2f2f692e696d6775722e636f6d2f383854615a69352e706e67)

I can run it in my Firefox and my version is 100.0.
![image](https://user-images.githubusercontent.com/97017043/167131954-c2af21f9-fb37-4df4-9c7a-af5065b60043.png)

![gif1](https://user-images.githubusercontent.com/97017043/167132294-cbd065d9-7627-491c-89c1-ba9518b07444.gif)

I can run it in my Firefox and my version is 100.0.

2022-05-06 21:44 UTC, janfaracik commented
Just my view but I don't think that the missing clear button on Firefox is detrimental enough for us to add it and support it ourselves.

2022-05-06 22:27 UTC, timja requested changes
in chrome on MacOS there's a weird square:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/21194782/167223712-0d6fd606-c378-4ecb-a477-37bb724d15f6.png">

Firefox MacOS Monterey can't render the unicode character:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/21194782/167223790-88ccf474-9221-4ae0-beea-58225de10aad.png">

2022-05-06 22:44 UTC, basil commented
> Firefox MacOS Monterey can't render the unicode character:

Ah that's too bad. Perhaps [U+2715 MULTIPLICATION X](https://www.fileformat.info/info/unicode/char/2715/index.htm) would be better supported.

2022-05-07 00:25 UTC, basil commented
> Agreed, Firefox are slowly working on fixing it...

Yeah, I do not feel strongly about this either. If we feel the maintenance burden of this is too high, it may be best to close this PR and leave the Jira ticket open to track confirming that this eventually gets taken care of when Firefox supports this feature.

2022-05-07 19:23 UTC, NotMyFault commented
I'm not too opposed to it, but I agree with Jan:
> Just my view but I don't think that the missing clear button on Firefox is detrimental enough for us to add it and support it ourselves.

This doesn't feel like something we necessarily have to address in core itself, but can close the Jira issue once FF release a fix for it.

2022-05-07 19:57 UTC, basil commented
Since we have reached a clear consensus, let's close this PR. @frankie139506 Thank you for the contribution, but we do not believe the maintenance burden of a custom implementation is worth the benefit.

2022-05-07 19:57 UTC, closed without merging