[JENKINS-68208] "Create a job" button is not hidden to users lacking permission.
jenkinsci/jenkins pull request #6689
Opened 2022-06-23 16:23 UTC by frankie139506

See [JENKINS-68208](https://issues.jenkins.io/browse/JENKINS-68208).

Before: (User without Job/Create permission can see the button)
![Before](https://user-images.githubusercontent.com/97017043/175347451-a75bd4e6-6878-4e55-a57a-69fa2e951a2c.png)

After: (User without Job/Create permission can't see the button now)
![After](https://user-images.githubusercontent.com/97017043/175347589-7e4f219d-962b-48ce-a801-f16a7f6d1af0.png)

### Proposed changelog entries

* Entry 1: Don't show the button to the user without Job/Create permission.

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [X] (If applicable) Jira issue is well described
- [X] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [X] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate. 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

2022-06-28 20:09 UTC, daniel-beck requested changes
This change is incorrect.

Authorization strategies like Project-based Matrix Authorization give users fine-grained control over who is allowed to create items where. To create an item in a folder, you only need permission to create an item inside that folder, not on the root level. That case would be broken by this change.

The problem here is probably related to the view owner being the user (for "My Views"), and a user has full permissions on itself to freely configure all properties. This seems to be a bad interaction not considered by the Groovy view, but the fix would be different from this change.

2022-07-04 15:48 UTC, frankie139506 commented
> This change is incorrect.
> 
> Authorization strategies like Project-based Matrix Authorization give users fine-grained control over who is allowed to create items where. To create an item in a folder, you only need permission to create an item inside that folder, not on the root level. That case would be broken by this change.
> 
> The problem here is probably related to the view owner being the user (for "My Views"), and a user has full permissions on itself to freely configure all properties. This seems to be a bad interaction not considered by the Groovy view, but the fix would be different from this change.

Thanks for your suggestion.

2022-07-05 11:26 UTC, daniel-beck approved these changes

2022-07-05 22:23 UTC, NotMyFault approved these changes

2022-07-05 22:23 UTC, NotMyFault commented
This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

2022-07-07 11:33 UTC, merged