Bring native support for side panel app bars, sticky side bar and changing app bar heading level
jenkinsci/jenkins pull request #7051
Opened 2022-09-01 22:22 UTC by janfaracik

(Apologies for long title - I truly couldn't think of anything shorter).

This PR brings native support for some of the app bar changes introduced in #6485, rather than the 'one-off' implementations in that PR.

**What's changed**
* App bars can now be applied to side panels and main panels
* Side panels can now be sticky (with a new class)
* You can now set the heading level for an app bar (e.g. change it to `h2` from `h1`)

As a result of this the implementation of the app bar has changed, you now need to include it in either side panel or main panel (this may break a couple of plugins - I'll fix them).

This is the `core` change that https://github.com/jenkinsci/design-library-plugin/pull/90 is waiting on, it essentially defines some clearer guidelines for when to use certain page layouts.

### Proposed changelog entries

- N/A (nothing user facing)

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] (If applicable) Jira issue is well described
- [ ] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change) and are in the imperative mood. [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  - Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [ ] Appropriate autotests or explanation to why this change has no tests
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadoc, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")` if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content-Security-Policy directives (see [documentation on jenkins.io](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jenkinsci/sig-ux 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are accurate, human-readable, and in the imperative mood
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

2022-09-06 19:21 UTC, timja commented
This looks great but plugins using it already need adapting

- job-config-history-plugin
- credentials-plugin
- design-library-plugin

2022-09-06 23:20 UTC, janfaracik commented
> This looks great but plugins using it already need adapting
> 
> * job-config-history-plugin
> * credentials-plugin
> * design-library-plugin
> 
> Example of what credentials plugin looks like atm:
> 
> <img alt="image" width="939" src="https://user-images.githubusercontent.com/21194782/188723134-f431a7b5-5bed-4317-9e9a-e28ab47ce67f.png">

Wondering if there's a workaround for this as if we move the app-bars into `main-panel` for plugins it'll only work for this release, older versions of Jenkins will be missing titles.

2022-09-07 06:10 UTC, timja commented
It will given there’s so few plugins we should be able to stage changes by creating a PR and then merge those after this has been released

2022-09-08 09:22 UTC, timja approved these changes
This looks great to me, I've created all the required downstream pull requests

2022-09-08 14:32 UTC, yaroslavafenkin approved these changes

2022-09-11 22:34 UTC, NotMyFault commented
Do you mind adding a changelog entry dedicated to the 'Developer' section?

2022-09-12 07:16 UTC, timja commented
done

2022-09-12 08:09 UTC, NotMyFault approved these changes
🎉

2022-09-12 08:11 UTC, timja commented
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2022-09-13 07:22 UTC, daniel-beck commented
I don't understand why this reuses the `app-bar` element in the sidepanel. Do we expect sidepanel content to also have associated buttons etc?

2022-09-13 07:51 UTC, daniel-beck commented
Is "About Jenkins" broken for anyone else in this PR?

2022-09-13 07:53 UTC, daniel-beck submitted a review, later dismissed
Per above

2022-09-13 08:07 UTC, timja commented on war/src/main/less/base/layout-commons.less
> +  align-items: flex-start;
this line is what breaks the about Jenkins page

2022-09-20 18:30 UTC, uhafner requested changes
I like these new ideas! I would recommend, that those views of this PR that now use these new pattern should be completely adapted before we merge this PR. Otherwise it is totally unclear for plugin developers what to do and what to avoid. These core views should be the template for everybody else on how to move forward!

Some elements that are not adapted:
- The side panel action name should be the same as the app bar title ("Updates", "Available Plugins" vs. "Plugins" or "Log Levels" vs. "Logger Configuration"). Maybe this can be done in the framework so I do not need to repeat
- The app bar does only sometimes contain the buttons (Add new logger is correctly in the app bar, Save button of Logger Configuration is at the bottom)

Some bugs:
- Log Recorders -> All Jenkins Logs break the sidebar completely (there is no sidebar anymore)
- Global Tool Configuration and Configure System (and the other elements of the manage screen) have no sidebar anymore

Missing feature:
One thing that I am totally missing: the new sidebar elements should not scroll if I scroll down the page. These parts should use separate viewpoints. It does not make sense to scroll the new sidebar anymore, it is up to the developer to restrict this size.

2022-09-21 17:56 UTC, daniel-beck commented
> the new sidebar elements should not scroll if I scroll down the page. These parts should use separate viewpoints. It does not make sense to scroll the new sidebar anymore, it is up to the developer to restrict this size.

@uhafner Could you clarify whether this only applies to sidepanels with app-bar, i.e., would there be some (most) sidepanels that scroll, and some that don't?

2022-09-21 20:37 UTC, uhafner commented
> > the new sidebar elements should not scroll if I scroll down the page. These parts should use separate viewpoints. It does not make sense to scroll the new sidebar anymore, it is up to the developer to restrict this size.
> 
> @uhafner Could you clarify whether this only applies to sidepanels with app-bar, i.e., would there be some (most) sidepanels that scroll, and some that don't?

If possible, *all* side panels should not scroll with the content. (I'm not sure if this works for the Dashboard view with the side panel widgets). I see no reason why the "links-only" navigation bars should scroll with the content.

2022-10-01 13:59 UTC, janfaracik commented
> I don't understand why this reuses the `app-bar` element in the sidepanel. Do we expect sidepanel content to also have associated buttons etc?

I don't see why not really, there isn't a use case yet on Jenkins but it wouldn't hurt to share the same component to make updating both easier in the future.

---

> * The side panel action name should be the same as the app bar title ("Updates", "Available Plugins" vs. "Plugins" or "Log Levels" vs. "Logger Configuration"). Maybe this can be done in the framework so I do not need to repeat

That's a very good idea 👍 Not too sure what the best way of doing that right now is, might require a new component I'm not too sure.

> * The app bar does only sometimes contain the buttons (Add new logger is correctly in the app bar, Save button of Logger Configuration is at the bottom)

Not too sure on the best spot for 'Save'/'Apply' buttons right now. Thinking that they make more sense on the bottom as you interact with form elements before interacting with the 'Save' buttons.

> Some bugs:

> * Log Recorders -> All Jenkins Logs break the sidebar completely (there is no sidebar anymore)

> * Global Tool Configuration and Configure System (and the other elements of the manage screen) have no sidebar anymore

Sidepanels have been removed from those pages as part of #6907 :) I've updated the 'All Jenkins Logs' pages to use a one column layout now so it should look better.

> Missing feature: One thing that I am totally missing: the new sidebar elements should not scroll if I scroll down the page. These parts should use separate viewpoints. It does not make sense to scroll the new sidebar anymore, it is up to the developer to restrict this size.

If I'm understanding correctly, you'd want the sidebar to scroll separately to the main page contents/stick to the top if too short? If so I agree, need to sort out which pages should have side panels first before making a change like that though.

2022-10-01 15:27 UTC, timja approved these changes
re-tested, looks good to me

2022-10-01 18:59 UTC, uhafner approved these changes

2022-10-03 13:07 UTC, NotMyFault commented
Thanks for addressing and clarifying the outstanding feedback!

---

This PR is now ready for merge. We will merge it after ~24 hours if there is no negative feedback.
Please see the [merge process documentation](https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#merge-process) for more information about the merge process.
Thanks!

2022-10-13 19:47 UTC, merged