draft: Update link dropdown menus to use new Tippy dropdowns
jenkinsci/jenkins pull request #7474
Opened 2022-12-04 21:47 UTC by janfaracik

Still a draft as I'd like to hear thoughts + fix tests before getting proper reviews on it.

This PR replaces the YUI menus used for link dropdowns with a modern framework, Tippy (introduced in #6408). The menus feel more modern and fit in better with the ongoing Jenkins redesign, as well as cut down on our reliance on YUI.

**Some screenshots**

<img width="266" alt="image" src="https://user-images.githubusercontent.com/43062514/205517054-09cf157c-5bc8-407e-b879-d5da3619e91d.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/43062514/205517024-b9421103-f2d1-4f60-a4dc-dc4bd590943a.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/43062514/205517043-8f5186c1-5a62-40ca-85d0-fbbd1d11a1ed.png">

**What this isn't**
Not all areas have been updated to use the dropdowns, such as the button dropdowns commonly found in Manage Jenkins/Config pages. This will be done in a followup PR to keep this one simpler. 

I'd also like to introduce a simple API for plugin developers to create their own dropdowns with ease, this again will be looked at in a future PR.

### Testing done

On a a page with link dropdown menus (such as Dashboard), click the chevron to open the menu. Notice the new menu pops up in a similar fashion to before. 

On open menus use keyboard up and down arrows to navigate through the items, pressing enter to activate an item.

Interact with dropdown items that aren't links, and are instead actions, such as the Delete item which opens a modal.

Go to the Configure System page and interact with the page's custom breadcrumb, all the sections previously displayed should be there again with a new style.

### Proposed changelog entries

- Update appearance and framework for link dropdown menus

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.

### Desired reviewers

@mention

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).

2022-12-05 10:23 UTC, daniel-beck commented
What happens when you make the window smaller than the dropdown (e.g. Manage Jenkins) would be high, i.e. when the existing dropdowns' scrolling feature is needed?

2022-12-07 19:18 UTC, janfaracik commented
> What happens when you make the window smaller than the dropdown (e.g. Manage Jenkins) would be high, i.e. when the existing dropdowns' scrolling feature is needed?

I hope I'm understanding you correctly, if the browser is too small the dropdown will display a scrollbar:

https://user-images.githubusercontent.com/43062514/206275173-d3841888-071a-4eb8-a6e2-eb7497bdcf21.mov

2022-12-07 20:55 UTC, daniel-beck commented
> > What happens when you make the window smaller than the dropdown (e.g. Manage Jenkins) would be high, i.e. when the existing dropdowns' scrolling feature is needed?
> 
> I hope I'm understanding you correctly, if the browser is too small the dropdown will display a scrollbar:

Thanks, that's what I was asking about. Looks like a great solution, much better than the weird "buttons" we currently have (FWIW I would have run this rather than commented, but it didn't build at the time.)

2022-12-25 21:01 UTC, timja reviewed
I tested in Chrome a number of different pages and dropdowns. I had a fairly simple setup as just using the core-pr-tester, I found one issue for accessibility, happy with the rest of it

----

ATH is passing

----

Keyboard navigation to the right doesn't seem to work, e.g. from the dashboard dropdown menu:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/21194782/209481630-a25c74b1-faeb-4bb7-94d8-c210005ecbbb.png">

This does work correctly on the latest weekly

2022-12-25 23:01 UTC, timja approved these changes
LGTM

2022-12-27 09:37 UTC, NotMyFault approved these changes

2023-01-05 11:32 UTC, yaroslavafenkin approved these changes
Seems fine to me from security perspective. Clicked around for a bit, couldn't break it.

2023-01-05 13:16 UTC, timja commented
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2023-01-05 13:29 UTC, daniel-beck commented
Previously, empty menus weren't rendered, now they are:

> <img width="434" alt="Screenshot 2023-01-05 at 14 12 34" src="https://user-images.githubusercontent.com/1831569/210788234-8c58777c-ea49-4644-b9ea-76ea7a61eb5f.png">

(Arguable there shouldn't be a menu indicator with no menu contents, but that would require requesting all menus beforehand.)

----

The newly added closing animation makes in-page navigation from breadcrumb entries look weird, as the menu moves while closing due to the header disappearing.

(No recording, Quicktime Player is broken for some reason.)

----

Could you explain the rationale for translucency? This seems just distracting for no clear benefit:

> <img width="263" alt="Screenshot 2023-01-05 at 14 14 12" src="https://user-images.githubusercontent.com/1831569/210788358-4fa2da88-4690-4746-be15-87d2f4f38190.png">

----

FTR opening/closing context menus appears to use less CPU than before, so that's a nice improvement for lower powered devices!

2023-01-05 13:32 UTC, daniel-beck requested changes
There's some double-escaping going on:

> <img width="1136" alt="Screenshot 2023-01-05 at 14 30 50" src="https://user-images.githubusercontent.com/1831569/210791563-7b16aa51-1854-4495-b737-10ae06ec740c.png">

Before:

> <img width="704" alt="Screenshot 2023-01-05 at 14 32 02" src="https://user-images.githubusercontent.com/1831569/210791624-1a45ef4a-c920-47cd-9787-6e15a02de449.png">

2023-01-05 15:32 UTC, janfaracik commented
> > <img alt="Screenshot 2023-01-05 at 14 30 50" width="1136" src="https://user-images.githubusercontent.com/1831569/210791563-7b16aa51-1854-4495-b737-10ae06ec740c.png">

Removed Util.escape(..) when setting the display name for a menu item, the escaping is done just on the frontend now. Is that all good with you?

<img width="689" alt="image" src="https://user-images.githubusercontent.com/43062514/210817922-bfffb637-a369-45db-b046-ec02e1ffb1ce.png">

2023-02-19 18:14 UTC, janfaracik commented
> I have not yet confirmed the output isn't used elsewhere where the API response would expect to be provided pre-escaped. While unlikely, it'd be annoying to introduce a vulnerability this way elsewhere.

Hey, not to push - any update on this?

2023-02-21 12:20 UTC, daniel-beck commented
I don't expect to have time for at least several more days. Others are welcome to look into this though.

2023-02-26 16:04 UTC, janfaracik commented
> Perhaps a menu could be opened with a small non-interactive entry saying it's empty? But the weird circle looks broken.

Added - thanks!

> The newly added closing animation makes in-page navigation from breadcrumb entries look weird, as the menu moves while closing due to the header disappearing.

I'm not sure I understand/can't reproduce on my end.

> Could you explain the rationale for translucency? This seems just distracting for no clear benefit:

Just a design decision, it does look a tad odd there due to the extreme contrast between the header and background, but still legible.

2023-02-27 11:08 UTC, uhafner commented
Is it possible that the chevron stays opened while the menu is shown? It is already somewhat disturbing that the breadcrumb text moves horizontally while hovering, this is now even more problematic. When the menu opens the chevron disappears.

2023-03-11 13:15 UTC, janfaracik commented
> Would it be possible that the chevron stays open while the menu is shown? It is already somewhat disturbing that the breadcrumb text moves horizontally while hovering, this is now even more problematic. When the menu opens the chevron disappears.

That's a good idea and I've just implemented it - 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/43062514/224486681-954ab568-703a-4d6d-b23e-08e33e21ec93.png">

Would be good to revisit the breadcrumbs dropdowns in the future as I also agree the movement is problematic.

2023-04-05 19:41 UTC, uhafner approved these changes
This looks better now, when the breadcrumbs stay selected. Thanks for fixing!

2023-04-06 20:50 UTC, janfaracik commented on war/src/main/js/components/dropdowns/jumplists.js
> +            new Ajax.Request(item.url);
This needs to be updated to reflect #7727

2023-04-11 07:08 UTC, timja commented
Lots of test failures

2023-04-16 23:35 UTC, janfaracik commented
> I don't expect to have time for at least several more days. Others are welcome to look into this though.

Doing a cursory search on GitHub yields 1k+ results for usages of `displayName` (not necessarily relating to `MenuItem`) 

https://github.com/search?q=org%3Ajenkinsci+displayName+NOT+repo%3Ajenkinsci%2Fjenkins+language%3Axml&type=code&l=Groovy

https://github.com/search?q=org%3Ajenkinsci+displayName+NOT+repo%3Ajenkinsci%2Fjenkins+language%3Axml&type=code

Is there a better query to search with to find potential usages in plugins? AFAIK there aren't any usages in Jenkins for it outside of the dropdown menu code.

2023-04-20 18:28 UTC, daniel-beck commented
> Is there a better query to search with to find potential usages in plugins? AFAIK there aren't any usages in Jenkins for it outside of the dropdown menu code.

This is more specifically about callers for the context menu. In my own search I was unable to find any.

The issues I mentioned in reviews were addressed. I like the new "no items" one in particular, thanks a lot for that!

2023-04-20 18:28 UTC, daniel-beck approved these changes

2023-04-20 22:03 UTC, timja commented
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2023-04-21 07:41 UTC, timja commented
@janfaracik you able to take a look at this conflict please?

2023-04-21 08:54 UTC, timja commented
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2023-04-25 07:41 UTC, merged

2023-08-17 15:51 UTC, daniel-beck commented
Likely cause of [JENKINS-71846](https://issues.jenkins.io/browse/JENKINS-71846).

2024-02-20 18:38 UTC, daniel-beck commented
Caused [JENKINS-72745](https://issues.jenkins.io/browse/JENKINS-72745)