-added new file
jenkinsci/jenkins pull request #7677
Opened 2023-02-26 15:58 UTC by lifefire1

cli/src/main/resources/hudson/cli/client/Messages_ru.properties
- added Russian language for Messages_en.properties

@mention

2023-02-27 18:32 UTC, lifefire1 commented
![Screenshot_20230227_213143](https://user-images.githubusercontent.com/79930276/221652030-8ac3c4e2-892a-4382-819d-0dd2a7b532a7.png)
this is an example output in bulgarian i made

2023-02-27 20:31 UTC, NotMyFault commented
> Do I need to add the src/main/java/hudson/cli/client/Messages.java file, in which I will have output methods implemented

No, `src/main/java/hudson/cli/client/Messages.java` is generated at compile time and does not exist as a source file. 
You just need to modify the .properties file if you want to contribute a localization, in this case.

2023-03-01 13:10 UTC, NotMyFault commented
@yaroslavafenkin or @Pldi23, would you mind taking a look at the Russian translation proposed if your schedule allows it? You have reviewed a few PRs like these before, hence I'm asking :)

2023-03-01 13:11 UTC, yaroslavafenkin commented
> @yaroslavafenkin or @Pldi23, would you mind taking a look at the Russian translation proposed if your schedule allows it? You have reviewed a few PRs like these before, hence I'm asking :)

Will have a look when time permits

2023-03-02 08:55 UTC, Pldi23 requested changes

2023-03-02 08:55 UTC, Pldi23 commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -webSocket          : Подключится через WebSocket (по умолчанию; хорошо работает с большинством обратных прокси; требуется Jetty)\n\
```suggestion
  \ -webSocket          : Использовать WebSocket соединение (по умолчанию; хорошо работает с большинством обратных прокси; требуется Jetty)\n\
```

2023-03-02 08:55 UTC, Pldi23 commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -http               : Используется соединение HTTP(S), а не WebSocket\n\
```suggestion
  \ -http               : Использовать соединение HTTP(S), а не WebSocket\n\
```

2023-03-02 08:55 UTC, Pldi23 commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -noCertificateCheck : Полностью обойти проверку сертификата HTTPS. Используйте с осторожностью\n\
```suggestion
  \ -noCertificateCheck : Полностью отказаться от проверки сертификата HTTPS. Используйте с осторожностью\n\
```

2023-03-02 08:55 UTC, Pldi23 commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -strictHostKey      : Запросить строгую проверку ключа хоста (для использования с -ssh)\n\
```suggestion
  \ -strictHostKey      : Использовать строгую проверку ключа хоста (для использования с -ssh)\n\
```

2023-03-02 09:49 UTC, yaroslavafenkin commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -s URL              : URL-адрес сервера (по умолчанию используется переменная env JENKINS-URL)\n\
```suggestion
  \ -s URL              : URL-адрес сервера (по умолчанию используется переменная окружения JENKINS-URL)\n\
```

2023-03-02 09:49 UTC, yaroslavafenkin commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -http               : Используется соединение HTTP(S), а не WebSocket\n\
Why are these two swapped? In English version `http` goes first, then `websocket`, would be nice to have consistent order.

2023-03-02 09:49 UTC, yaroslavafenkin commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -http               : Используется соединение HTTP(S), а не WebSocket\n\
English version hints me it's the default connection option, maybe it should be mentioned?

2023-03-02 09:49 UTC, yaroslavafenkin commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  \ -noKeyAuth          : Не пытаться загрузить приватный ключ для SSH. Конфликты с -i\n\
```suggestion
  \ -noKeyAuth          : Не пытаться загрузить закрытый ключ для SSH. Не используйте с -i\n\
```

2023-03-02 09:49 UTC, yaroslavafenkin commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +  смотреть список.
```suggestion
  Доступные команды зависят от сервера. Запустите команду ''help'' чтобы \
  посмотреть весь список.
```

2023-03-02 09:49 UTC, yaroslavafenkin commented on cli/src/main/resources/hudson/cli/client/Messages_ru.properties
> +CLI.BadAuth=Обе переменные env JENKINS_USER_ID и JENKINS_API_TOKEN должны быть установлены или оставлены пустыми.
```suggestion
CLI.BadAuth=Обе переменные окружения JENKINS_USER_ID и JENKINS_API_TOKEN должны быть установлены или оставлены пустыми.
```

2023-03-11 09:05 UTC, NotMyFault commented
Hey @lifefire1,

could you take a moment and address the feedback, please?

Thanks!

2023-06-08 14:46 UTC, NotMyFault commented
I'm going ahead and closing the PR, due to lack of response from the submitter. 
@lifefire1 you are much welcome to reopen the PR, once you have addressed the feedback submitted, thanks!

2023-06-08 14:46 UTC, closed without merging