Revert "[JENKINS-70139] booleanRadio uses non-unique ID (regression in 2.335)"
jenkinsci/jenkins pull request #7734
Opened 2023-03-16 09:07 UTC by NotMyFault

Reverts jenkinsci/jenkins#7631

As described by various reporters in [JENKINS-70739](https://issues.jenkins.io/browse/JENKINS-70739), the changed introduced to mitigate [JENKINS-70139](https://issues.jenkins.io/browse/JENKINS-70139) caused a severe regression, which prevents selecting multiple radio buttons on different surfaces.
This leads to being unable to activate settings shipped by plugins.

The original PR creator endorses revering the PR for now.

2023-03-16 22:23 UTC, timja approved these changes

2023-03-18 22:05 UTC, timja commented
Restore the PR template and add a changelog entry?

2023-03-18 22:15 UTC, NotMyFault commented
> Restore the PR template and add a changelog entry?

There we go.

2023-03-18 22:19 UTC, uhafner requested changes
I did not see various reporters, there are only 4 votes? 

When this change gets reverted then my warnings plugin will break again 😢 (so I am somewhat biased). 

Why is there no action in the plugin that breaks the UI by forgetting to use an ID in radio buttons?

2023-03-18 22:52 UTC, NotMyFault commented
> Why is there no action in the plugin that breaks the UI by forgetting to use an ID in radio buttons?

What would you recommend to do, to ensure repeatable items provided by at least 3 plugins named, work again, if reverting the change is an undesirable approach?

2023-03-19 09:06 UTC, uhafner commented
> > Why is there no action in the plugin that breaks the UI by forgetting to use an ID in radio buttons?
> 
> What would you recommend to do, to ensure repeatable items provided by at least 3 plugins named, work again, if reverting the change is an undesirable approach?

I think the first step should be to create 3 issues for the affected plugins to add an ID to their radios. Then we see, if the authors are willing to help. Then make the ID non-optional in the form.jelly.

2023-03-19 09:08 UTC, uhafner commented on core/src/main/resources/lib/form/repeatable/repeatable.js
> -      }
Maybe a simple untested fix would be to wrap that code in a guard that checks if the `id` is set.

2023-03-25 10:08 UTC, NotMyFault commented
> I think the first step should be to create 3 issues for the affected plugins to add an ID to their radios. Then we see, if the authors are willing to help. Then make the ID non-optional in the form.jelly.

I was under the impression, that a wide range of plugins would be affected by this change, given that's how the issue reporters made it sound like. Realistically, only very specific plugins are impacted, as proven. Not every plugin using boolean radios will stop working.
I'll go ahead and close this PR and create the issues for the plugins mentioned in the original jira issue. I've monitored Jira over the past week and couldn't spot new issues stating plugins are impacted, which have not been mentioned yet.

2023-03-25 10:08 UTC, closed without merging

2023-04-06 21:46 UTC, basil commented
We do not break working plugins and cause disruption and regression for our end users. If a core PR caused plugins that were previously working to stop working, and if new releases of those plugins that adapt to that core PR are not available, then that core PR needs to be reverted.