Fixes: JENKINS-71794 Redesign build queue | UX
jenkinsci/jenkins pull request #8459
Opened 2023-09-03 07:06 UTC by niralmaruda

Fixes: [JENKINS-71794](https://issues.jenkins.io/browse/JENKINS-71794)
The current build queue layout contains a lot of unnecessary free space. Refer [JENKINS-71794](https://issues.jenkins.io/browse/JENKINS-71794) for more details. 

The changes are implemented in both core as well as *PR:*[workflow-durable-task-step-plugin](https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/339) to maintain consistency in design. But if any downgraded version of core is used then user will still see the inconsistency in design as shown in second image. 

### Testing done
![image](https://github.com/jenkinsci/workflow-durable-task-step-plugin/assets/85137760/260043dd-7a3e-4b49-aa2b-2c6b33712fe4)

#### This is how it'll display if used with downgraded core version.
![image](https://github.com/jenkinsci/workflow-durable-task-step-plugin/assets/85137760/b58e8b6e-59bc-42ff-976d-0e07da0eb140)

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-09-05 10:21 UTC, NotMyFault commented
How well does that look with folders¿

2023-09-07 15:55 UTC, jglick commented on core/src/main/resources/lib/hudson/executors.jelly
> +                          <a href="${rootURL}/${exeparent.url}"><l:breakable value="${exeparent.fullDisplayName}"/></a>
```suggestion
                          <a href="${rootURL}/${exeparent.url}"><l:breakable value="${exeparent.fullDisplayName}"/></a>
```
minimize diff please

2023-09-07 15:57 UTC, jglick commented
To avoid confusion, please rename the Jira issue and this PR to clarify that you are patching the executor widget, not the build queue widget.

2023-09-08 10:25 UTC, NotMyFault commented
> > How well does that look with folders¿
> 
> 
> 
> @NotMyFault folders? not sure about that.

I took a look yesterday creating a longer folder name with several names and it seems to push the progress bar below the text and make the breadcrumbs invisible.

Can you take a look? It feels this makes the current implementation worse than improving it, but these are just my thoughts.

2023-09-09 07:47 UTC, niralmaruda commented
> > > How well does that look with folders¿
> > 
> > 
> > @NotMyFault folders? not sure about that.
> 
> I took a look yesterday creating a longer folder name with several names and it seems to push the progress bar below the text and make the breadcrumbs invisible.
> 
> Can you take a look? It feels this makes the current implementation worse than improving it, but these are just my thoughts.

Sure, I'll take a look into it.

2023-09-28 18:19 UTC, abhishekmaity commented
/label web-ui

2025-02-02 20:14 UTC, A1exKH requested changes
@niralmaruda please resolve conflicts for this PR.

2025-06-01 14:26 UTC, NotMyFault commented
I'll go ahead and close this PR, given the changes proposed do no longer align with the redesigned build executor widget, thanks nonetheless!

2025-06-01 14:26 UTC, closed without merging