Update the appearance of the stop button
jenkinsci/jenkins pull request #8780
Opened 2023-12-13 22:48 UTC by janfaracik

Small MR to update the appearance of the stop button component.

**Before**
<img width="346" alt="image" src="https://github.com/jenkinsci/jenkins/assets/43062514/e684fdae-cd80-4325-99c1-971db6f5682e">
<img width="207" alt="image" src="https://github.com/jenkinsci/jenkins/assets/43062514/c6b7e59f-ee1a-4749-9aa4-246b708d2f31">
<img width="340" alt="image" src="https://github.com/jenkinsci/jenkins/assets/43062514/e6a6b509-b659-4d39-a00e-0d62eb428f09">

**After**
<img width="342" alt="image" src="https://github.com/jenkinsci/jenkins/assets/43062514/04939515-4ccc-48ff-a7a5-4da5fa4f04bc">
<img width="208" alt="image" src="https://github.com/jenkinsci/jenkins/assets/43062514/a38d46a0-05e5-4ce2-bfc9-4a30942164a8">
<img width="342" alt="image" src="https://github.com/jenkinsci/jenkins/assets/43062514/e8ae9ba7-8c0e-41dc-9808-6bfe6378c6a7">

### Testing done

* Component works as before, doesn't cause layout shifts

### Proposed changelog entries

- Update the appearance of the stop button

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [x] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@jenkinsci/sig-ux 

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

2023-12-14 07:24 UTC, uhafner requested changes
UI looks good, Thanks!

One localization is broken now.

2023-12-14 07:24 UTC, uhafner commented on core/src/main/resources/lib/hudson/executors.jelly
> +                    <l:stopButton href="${rootURL}/${c.url}${url}/stopBuild?runExtId=${h.urlEncode(exe.externalizableId)}" confirm="${%confirm(exe.fullDisplayName)}" alt="${%Cancel}"  />
This will break the i18n, it would be better to use Cancel in the properties as {en} translation. Or rename all translations.

2023-12-14 19:08 UTC, uhafner approved these changes

2023-12-15 16:36 UTC, timja commented
Tests failing

2023-12-17 12:37 UTC, timja approved these changes

2023-12-19 11:41 UTC, yaroslavafenkin reviewed
Looks OK security wise.

---

![image](https://github.com/jenkinsci/jenkins/assets/91559310/b4dc9ad5-261f-48e0-a3bb-7ddbaa07da37)
Is it just me or alignment is off? Nor aligned with the progress bar, neither with `#1`.

2023-12-19 12:21 UTC, daniel-beck commented
> alignment is off

Not newly introduced per screenshots in PR comment.

2023-12-19 13:10 UTC, timja commented
> > alignment is off
> 
> Not newly introduced per screenshots in PR comment.

similar-ish things noticed here:
https://github.com/jenkinsci/jenkins/pull/8761#pullrequestreview-1785237113

a few things looking a bit funny but they were already in that state.

2023-12-19 13:10 UTC, timja commented
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2023-12-20 21:45 UTC, merged

2023-12-29 00:19 UTC, DuMaM commented
Thanks :D I was waiting so long for this change.