[JENKINS-71326] - Support colored badges in breadcrumb dropdown
jenkinsci/jenkins pull request #8853
Opened 2024-01-10 19:38 UTC by eduardojandre

See [JENKINS-71326](https://issues.jenkins.io/browse/JENKINS-71326).

To solve the problem I had to:
1-Update the backend to expose the badge severity field to the API used by dropdowns.
2-Update the dropdown and side menu to use the badge severity to set the corresponding CSS class.
3-Update the CSS files so that the badge in the dropdown and side menu behaves similarly to the normal menu.

2024-01-10 20:25 UTC, mawinter69 commented
Can you provide a screenshot please how it looks.
Ideally it looks the same as the badges on the manage page.
<img width="229" alt="image" src="https://github.com/jenkinsci/jenkins/assets/17767050/5c3938d8-1b2a-4898-851a-e191b33aa305">

2024-01-10 20:26 UTC, mawinter69 commented
Replaces #8798

2024-01-10 20:44 UTC, eduardojandre commented
Sure.
![sidemenu](https://github.com/jenkinsci/jenkins/assets/2974687/012ecb66-8055-4d0c-a1e8-372265e753ea)
![Dropdown](https://github.com/jenkinsci/jenkins/assets/2974687/f49a25ae-07de-4e5c-9248-ecef9bd7c9a9)

2024-01-10 21:21 UTC, mawinter69 commented
The badges on the manage page have a slightly different styling.
<img width="360" alt="image" src="https://github.com/jenkinsci/jenkins/assets/17767050/f2146370-e322-41f9-aae0-6e1dfbdd5f6a">
<img width="236" alt="image" src="https://github.com/jenkinsci/jenkins/assets/17767050/eabd3cf2-1ecf-4e89-a19b-67fbdfb4648b">
<img width="220" alt="image" src="https://github.com/jenkinsci/jenkins/assets/17767050/7c9a876e-e49a-4311-81b6-47e82bbeeb4e">
<img width="154" alt="image" src="https://github.com/jenkinsci/jenkins/assets/17767050/152f308d-77c7-4dfe-852b-efbfbab876b9">
See https://github.com/jenkinsci/jenkins/blob/2923a7785ea735b0b90a8cfb2cbf67bbf864356e/war/src/main/scss/components/_section.scss#L101 for the styling

Just an idea, we have now 3 files (5 calls) where we render a badge. Maybe we can move that into an own jelly tag e.g. `core/src/main/resources/lib/layout/badge.jelly` so we just call it via `<l:badge badge="${attrs.badge"/>`.
This gets its own styling (under `war/src/main/scss/components/_badge.scss`) which ensures that wherever it is used it looks the same. And when we adjust we have just a single place where we need to do changes. This also allows plugins to easily reuse the badge jelly and directly get it properly styled.

2024-01-10 22:22 UTC, eduardojandre commented
Yes, I did not notice the gradient on my tests, the animation I didn't replicate because I was not sure if this was intentional or not.

But this was something that bothered me a little, having the same component replicated in multiple files, although it was previous behavior. It seemed like a bigger change and I didn't know the best way to do it.

I will try your suggestion. 

Thanks.

2024-01-11 01:58 UTC, eduardojandre commented
I pushed another commit with changes, can you please take a look?

Now there is a jelly that is used on Manage screen and on the side menu, but the dropdown is loaded directly on javascript through ajax so I was not able to use the same jelly view on that one. (but I used the same CSS class on it)

2024-01-11 09:19 UTC, mawinter69 requested changes

2024-01-11 09:19 UTC, mawinter69 commented on war/src/main/scss/components/_badges.scss
> +.badge {
this is a bit too generic. Please see https://weekly.ci.jenkins.io/design-library/Conventions/ for conventions how to name classes.
This means it should be something like `.jenkins-badge`

2024-01-11 09:19 UTC, mawinter69 commented on war/src/main/scss/components/_dropdowns.scss
> +    .badge {
This is not the right way to do it.
This should be `&__badge` (see comment for templates.js)

2024-01-11 09:19 UTC, mawinter69 commented on war/src/main/scss/components/_section.scss
> +     .badge{
This should be `&__badge` and be at original position in line 101

2024-01-11 09:19 UTC, mawinter69 commented on war/src/main/scss/components/_side-panel-tasks.scss
> +  .badge {
the name shouldn't change here

2024-01-11 09:19 UTC, mawinter69 commented on core/src/main/resources/lib/layout/task.jelly
> +                  <l:badge badge="${attrs.badge}"/>
with my proposals this becomes
```
  <l:badge badge="${attrs.badge}" class="task-icon-badge"/>
```

2024-01-11 09:19 UTC, mawinter69 commented on core/src/main/resources/lib/layout/badge.jelly
> +    <span class="badge alert-${attrs.badge.severity}" tooltip="${badge.tooltip}">
use jenkins-badge

2024-01-11 09:19 UTC, mawinter69 commented on core/src/main/resources/lib/layout/badge.jelly
> +    <span class="badge alert-${attrs.badge.severity}" tooltip="${badge.tooltip}">
I would add another optional attribute to the jelly named class, that allows to pass additional classes to the span
`<span class="badge alert-${attrs.badge.severity} ${attrs.class?:''}" tooltip="${badge.tooltip}">

2024-01-11 09:19 UTC, mawinter69 commented on core/src/main/resources/hudson/model/ManageJenkinsAction/index.jelly
> +                      <l:badge badge="${m.badge}"/>
With my proposals this becomes
`<l:badge badge="${m.badge}" class="jenkins-section__item__icon__badge"/>`

2024-01-11 09:19 UTC, mawinter69 commented on war/src/main/js/components/dropdowns/templates.js
> +                        ? `<span class="badge alert-${badgeSeverity}" tooltip="${badgeTooltip}">${badgeText}</span>`
with my proposals this should be
`<span class="jenkins-dropdown__item__badge jenkins-badge alert-${badgeSeverity}" tooltip="${badgeTooltip}">${badgeText}</span>

2024-01-11 11:27 UTC, mawinter69 approved these changes
tested locally and it looks good

2024-01-11 11:43 UTC, NotMyFault reviewed
You forgot to run `cd war/ ; yarn run lint:fix`.

2024-01-11 11:43 UTC, NotMyFault commented on core/src/main/resources/lib/layout/badge.jelly
> +Copyright (c) 2012- CloudBees, Inc.
The year is incorrect and the company name too, unless you work for CloudBees.

2024-01-11 11:43 UTC, NotMyFault commented on core/src/main/resources/lib/layout/badge.jelly
> +<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:d="jelly:define">
```suggestion
<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler">
```
This namespace is unused.

2024-01-11 11:43 UTC, NotMyFault commented on core/src/main/resources/lib/layout/badge.jelly
> +    If a Badge is informed it will be displayed, otherwise nothing is done.
```suggestion
    If a Badge is informed it will be displayed, otherwise nothing is done.
    
    @since TODO
```

2024-01-11 11:43 UTC, NotMyFault commented on core/src/main/resources/lib/layout/badge.jelly
> +      Badge to be displayed, accepts null value.
```suggestion
      Badge to be displayed, accepts null value.
      
      @since TODO
```

2024-01-11 11:43 UTC, NotMyFault commented on core/src/main/resources/lib/layout/badge.jelly
> +      Additional class to be applied
```suggestion
      Additional class to be applied.
      
      @since TODO
```

2024-01-11 14:00 UTC, eduardojandre commented
> You forgot to run `cd war/ ; yarn run lint:fix`.

Sorry, just fixed.

I applied the suggestion of "@since TODO", when the TODO will be replace by the version? Is it in the pipeline?

2024-01-11 15:24 UTC, NotMyFault commented
> > You forgot to run `cd war/ ; yarn run lint:fix`.
> 
> Sorry, just fixed.
> 
> I applied the suggestion of "@SInCE TODO", when the TODO will be replace by the version? Is it in the pipeline?

That happens when a maintainer runs the https://github.com/jenkinsci/jenkins/blob/master/update-since-todo.py

2024-01-12 09:53 UTC, Kevin-CB approved these changes
Looks fine security wise

2024-01-13 15:04 UTC, NotMyFault approved these changes
Thanks, looks nice :)

2024-01-30 19:04 UTC, mawinter69 approved these changes

2024-02-09 10:06 UTC, timja approved these changes
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2024-02-12 13:09 UTC, merged