deps: use commons-lang3 replace commons-lang
jenkinsci/jenkins pull request #8996
Opened 2024-02-27 17:08 UTC by BobDu

A dependency on `commons-lang3` was declared in `commons-compress` version 1.26.
`Jenkins core` version 2.447 upgraded to `commons-compress` 1.26, and from that point onwards, `commons-lang3` has effectively been present in our dependency chain.
Therefore, it is safe to use `commons-lang3` replace `commons-lang` without causing any additional breaking changes.

ref: 

apache commons compress
https://github.com/apache/commons-compress/commit/bf50b7d915ee406298670ceebcaa1e22616a23e0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L214

jenkins core
https://github.com/jenkinsci/jenkins/commit/8d2045bf9caa9649523d7d980d301be83f6da748

### Testing done

N/A

### Proposed changelog entries

- deps: use commons-lang3 replace commons-lang

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

2024-02-27 23:09 UTC, basil requested changes
Shipping `commons-lang3` in core was not intentional, and I am removing it in #8997.

2024-02-28 02:35 UTC, BobDu commented
I understand the design philosophy that we don't want to continue expanding the core API surface.

But, can `commons-lang3` be an exception? Because:

1. `commons-lang3` is very stable and widely used. In the vast majority of Java projects I have come across, it has been a dependency.
2. For a long time now, `commons-lang` has been included in the core. If we switch to `commons-lang3` at this point and recommend that plugin authors use `commons-lang3` instead of `commons-lang`, it could provide the possibility to phase out the dependency on `commons-lang` in future major versions. (This might be the most important.)
3. Shipping `commons-lang3` in jenkins core since version 2.447 is an event has already occurred.
4. A dependency on commons-lang3 was declared in commons-compress version 1.26, even I suspect that there might be other existing dependencies that will include `commons-lang3` in future versions. Rather than identifying and excluding it, it's better to allow it into the core.

ping @basil

2024-02-28 02:49 UTC, basil commented
1. The [Commons Lang 3 Jenkins library plugin](https://plugins.jenkins.io/commons-lang3-api/) is installed on only 67.3% of Jenkins installations and consumed by only [58 plugins](https://plugins.jenkins.io/commons-lang3-api/dependencies/) (out of over 2,000), so this isn't a vast majority. Most of the Jenkins plugin ecosystem is still using Commons Lang 2 (via core).
2. Plugins can already migrate from Commons Lang 2 to Commons Lang 3 by depending on the Commons Lang 3 Jenkins library plugin. There is no need to increase core API surface area to achieve this goal.
3. Yes but only in a weekly release and only by accident. Weekly releases have bugs all the time. This should be corrected in the next weekly release. If this were released in LTS it would be a different story.
4. Only in a code path we never use (Pack200) and I have requested the maintainer reconsider.

Weighing all of the above, I am still a -1 on making a special exception for Commons Lang 3. But I am not the only core maintainer, so if you feel strongly about this, you can start a broader discussion on the developer [mailing list](https://www.jenkins.io/mailing-lists/).

2024-02-28 04:24 UTC, BobDu commented
Maybe we should start the discussion from a different angle.

The `commons-lang` version 2.6 has been out of maintenance for over 13 years.

Regarding the transition from `commons-lang` to `commons-lang3` within the Jenkins ecosystem (including core and plugins), are you in +1 or -1?

I believe that it is more meaningful to reach a consensus on this point first.

ping @basil

2024-02-28 04:37 UTC, jonesbusy commented
Not a core maintainer here but maintaining many plugin (including API ones).

I will be -1 on this PR it's againts all the work started on API plugins and dependency management on plugin side.

I don't think we should do any exception on `commons-lang3`. And even stop shipping `commons-lang` on core and use native Java API 

https://plugins.jenkins.io/commons-lang-api/ also exists already to keep compatibility of plugin that depends from `commons-lang`

2024-02-28 06:46 UTC, BobDu commented
Sorry, I missed the discussion that took place 2 years ago. [JENKINS-67789](https://issues.jenkins.io/browse/JENKINS-67789)

It seems that the community had reached a consensus at that time.

To detached commons-lang from core, and make `commons-lang-api` plugin as an implicit dependency.

If I have misunderstood the consensus reached before, please remind me.

https://www.jenkins.io/doc/book/managing/plugins/#what-is-an-implied-dependency

I believe that it would certainly be the best if this goal could be achieved. Moreover, the community has already made efforts in this direction. like: #6270
However, two years have passed. We haven't been able to make further progress. I believe it is largely related to the extensive use of commons-lang in the current core, which makes it difficult to replace simply.

How do we proceed further now? Continue to use native Java APIs to replace `commons-lang`?
Is the replacement cost high enough to justify a compromise and depends `commons-lang3` in the core as a more pragmatic solution?

2024-02-28 21:23 UTC, NotMyFault commented
I'm with Basil and Valentin.

2024-02-29 14:04 UTC, closed without merging

2024-02-29 14:04 UTC, BobDu commented
closed to support #8997

2024-04-02 23:26 UTC, basil commented
Note that even once consumers are migrated away from the remaining (now deprecated) core APIs that contain Commons Lang 2.x classes in their signatures, there is still the matter of core depending on Stapler, which depends on [our fork of json-lib](https://github.com/jenkinsci/json-lib), which depends on Commons Lang 2.x. That fork of `json-lib` could be improved to use native Java Platform functionality instead of depending on Commons Lang 2.x, but the repository would first need to be seriously modernized, since the last commit was made 10 years ago and there is not even a CI build today.

2024-04-08 03:19 UTC, BobDu commented
> but the repository would first need to be seriously modernized.

Create a new issue to tracking progress:  https://issues.jenkins.io/browse/JENKINS-72981

2025-07-29 08:45 UTC, schiasileon commented
Hi @basil , just a quick question because this is the only thing I stumbled over. Is there any intention to remove commons-lang2 from core/cli/bom? 
https://github.com/jenkinsci/jenkins/blob/235d237f32835ccc1064c95c701f331d7dece7a3/core/pom.xml#L167
https://github.com/jenkinsci/jenkins/blob/235d237f32835ccc1064c95c701f331d7dece7a3/cli/pom.xml#L43
https://github.com/jenkinsci/jenkins/blob/235d237f32835ccc1064c95c701f331d7dece7a3/bom/pom.xml#L126

I see a lot of plugins already using the new api, is there anything that is holding us back? Any progress I can follow?

Asking because of CVE-2025-48924 and I am unsure on how we could narrow down our attack surface or at least narrow down what plugins are still using the old library.

2025-07-29 15:13 UTC, basil commented
@schiasileon As of #9044 the CLI is no longer using Commons Lang 2, so https://github.com/jenkinsci/jenkins/blob/52b70d980638b2ae8627e474e0c410104b8c951e/cli/pom.xml#L41-L45 can simply be deleted. Core needs to continue to ship Commons Lang 2 as long as critical plugins depend on it. Usages of Commons Lang 2 in plugins can be found with [usage-in-plugins](https://github.com/jenkins-infra/usage-in-plugins).