Use standard dropdowns for autocomplete
jenkinsci/jenkins pull request #9453
Opened 2024-07-11 20:06 UTC by zbynek

Further reduces usage of YUI by switching autocomplete fields to the dropdown component.

![image](https://github.com/user-attachments/assets/eacba8c0-9d08-4e85-8ad4-2bbc4cbb43e6)

### Testing done

Manual testing with the job trigger for freestyle jobs (see screenshot)

### Proposed changelog entries

- Use dropdown component for autocomplete fields (instead of YUI framework)

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

2024-07-13 14:11 UTC, timja approved these changes
LGTM worked in testing on a freestyle project and on the design library

2024-07-15 21:08 UTC, janfaracik commented
Looks good to me - any thoughts on making the dropdown full width?

2024-07-15 21:09 UTC, janfaracik approved these changes

2024-07-15 21:10 UTC, NotMyFault approved these changes

2024-07-15 22:50 UTC, zbynek commented
> any thoughts on making the dropdown full width?

I don't have a preference. @timja @NotMyFault WDYT?

![image](https://github.com/user-attachments/assets/05fc58a9-d8aa-4a6e-8ae6-8d317631bdb4)

2024-07-16 08:07 UTC, timja commented
> > any thoughts on making the dropdown full width?
> 
> I don't have a preference. @timja @NotMyFault WDYT?
> 
> ![image](https://private-user-images.githubusercontent.com/1105305/348874056-05fc58a9-d8aa-4a6e-8ae6-8d317631bdb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTc0NDgsIm5iZiI6MTcyMTExNzE0OCwicGF0aCI6Ii8xMTA1MzA1LzM0ODg3NDA1Ni0wNWZjNThhOS1kOGFhLTRhNmUtOGFlNi04ZDMxNzYzMWJkYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDgwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg3ZjAzNzdhMTdmN2QxMmZmNTQ3YjBjNTYxZjBkODQ2ODJlMmM3M2IyMTE5ZGM2NjIyOGE2NmU2ZmVhNzIxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5BmwrM3jTRnOzhXb66Bm5W_agQwLddTEccdZm3sOuZY)

is that after or before?

2024-07-16 08:36 UTC, zbynek commented
The last screenshot is potential after (not implemented), screenshot of the current implementation is in the PR description.

2024-07-16 08:52 UTC, timja commented
Current one is cut-off though so can't really see the impact of the change unless I'm misunderstanding

2024-07-16 19:32 UTC, zbynek commented
Without cutoff:
![image](https://github.com/user-attachments/assets/2c0f31b3-fb2b-4666-b232-a6cfd889933b)
The upside is that there is that with more suggestions the narrow popup covers fewer UI elements, the  downside is that validation of partial input may be visible below (as shown in the screenshot in description).

2024-07-16 20:46 UTC, timja commented
Ah I see, I think full width is better but no strong preference

2024-07-16 21:02 UTC, zbynek commented
Full width pushed, this is now ready from my side, thanks for the feedback.

2024-07-26 10:21 UTC, daniel-beck requested changes
This unfavorably interacts with browser built-in autocompletion based on form history.

https://github.com/user-attachments/assets/35a10350-c1fe-4cc5-a59e-d8656c137504

https://github.com/user-attachments/assets/94e765d6-f3a1-4fc8-8348-a14c6634593a



Additionally, it seems error-prone and bad UX for the popup to immediately close when you click anywhere (else), rather than staying open.

2024-07-29 18:29 UTC, zbynek commented
@daniel-beck thanks for pointing those out, both fixed in the last commit

2024-07-29 21:12 UTC, timja commented on war/src/main/js/components/dropdowns/utils.js
> +      hideOnClick: element.dataset["hideOnClick"] != "false",
```suggestion
      hideOnClick: element.dataset["hideOnClick"] !== "false",
```

2024-08-02 23:10 UTC, mawinter69 commented
I created JENKINS-73562 to track the removal of YUI from autocomplete

2024-08-10 20:49 UTC, zbynek commented
@daniel-beck will you have time to check if my last changes address the issues you mentioned?

2024-08-12 16:33 UTC, daniel-beck approved these changes
The current state addresses both previous issues I've identified.

2024-08-13 07:26 UTC, timja commented
@daniel-beck does this still need a security review?

2024-08-13 08:11 UTC, daniel-beck commented
@timja Thanks, forgot.

2024-08-13 08:34 UTC, timja commented
/label ready-for-merge

----

This PR is now ready for merge, after ~24 hours, we will merge it if there's no negative feedback.

Thanks!

2024-08-14 06:27 UTC, merged

2026-01-16 21:12 UTC, jglick commented on war/src/main/js/components/autocomplete/index.js
> +    }
This prevents you from offering completions on an empty textbox even if you want to. That seems to have been the case before this change, though. Deliberate?

2026-01-17 08:09 UTC, zbynek commented on war/src/main/js/components/autocomplete/index.js
> +    }
Besides the `Autocomplete` component there is `ComboBox` which has similar features (shows a limited number of suggestions as you type) with the difference that `ComboBox` provides options also when the input is empty. Maybe that's a better fit for your usecase?

I think the `Autocomplete` behavior makes sense when the set of possible completions is so big that suggestions  for an empty string are likely useless.

2026-01-20 20:00 UTC, jglick commented on war/src/main/js/components/autocomplete/index.js
> +    }
> the `Autocomplete` behavior makes sense when the set of possible completions is so big that suggestions for an empty string are likely useless

Only if the set of possible completions _up to the next delimiter_ is hopelessly large. But there is a large middle ground where a dropdown is impractical (because the total number of possible values is huge, or expensive to compute) yet it is practical to offer completions for each path segment individually. For example with https://github.com/jenkinsci/pipeline-build-step-plugin/blob/dba2cc3ad07a3595988db371f989f8d5a967dc36/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly#L29-L31 https://github.com/jenkinsci/pipeline-build-step-plugin/blob/dba2cc3ad07a3595988db371f989f8d5a967dc36/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java#L237-L292 it would make sense to offer top-level jobs and folders when the text field is blank, rather than waiting for type in some characters.

2026-01-20 22:26 UTC, timja commented on war/src/main/js/components/autocomplete/index.js
> +    }
Jan and I sketched out some requirements for an autocomplete v2 overhaul in https://github.com/jenkinsci/design-library-plugin/issues/349.

We tried to do a bit of a PoC to implement some of the above last year some time using: https://developer.chrome.com/blog/a-customizable-select but at least at the time safari did not fallback well.

2026-07-29 18:13 UTC, jglick commented on war/src/main/js/components/autocomplete/index.js
> +    }
> Besides the `Autocomplete` component there is `ComboBox` which has similar features (shows a limited number of suggestions as you type) with the difference that `ComboBox` provides options also when the input is empty.

A `f:combobox` control only calls the `doFillXxxItems` method and not `doAutoCompleteXxx`, so it cannot be used directly as a replacement for `f:textbox` when there is a potentially large number of final completions.

You _can_ apparently add a `@QueryParameter String xxx` argument which will let the completions be (re)computed as text is typed, which I guess could be used to produce a similar effect.

**Edit**: no, I tried and it does not really work, contra my earlier experiments. `doFillXxxItems` is not consistently called when the combo box is not empty. When it is, sometimes it passes just the first letter of the current selection. Sometimes it passes the proper selection, but then the response is not honored. Most of the time no dropdown is displayed at all.