[JENKINS-73278] Migrate core from EE 8 to EE 9
jenkinsci/jenkins pull request #9672
Opened 2024-08-27 23:16 UTC by basil

### Context

See [JENKINS-73255](https://issues.jenkins.io/browse/JENKINS-73255).

### Problem

Jenkins bundles an outdated copy of Spring Security 5.x, with [official end of open source support on August 31, 2024](https://spring.io/blog/2024/03/01/support-timeline-announcement-for-spring-framework-6-0-x-and-5-3-x). Spring Security 6.x requires Spring Framework 6.x, which requires EE 9.

### Solution

- Update dependencies in `pom.xml` to align with Jetty 12 (EE 9)
- Migrate imports
- Add compatibility layer for EE 8 to support Jenkins plugins

At a high level, we add `StaplerRequest2` and `StaplerResponse2` classes, the Jakarta equivalents of the old versions (now deprecated). The `RequestImpl` and `ResponseImpl` implementations are now based on EE 9 rather than EE 8, but support for plugins is maintained by converting to and from the interfaces as needed.

### Testing done

Full PCT and ATH (Jenkins public version and CloudBees internal version)

### Proposed changelog entries

Upgrade Spring Framework from 5.3.39 to 6.1.12, upgrade Spring Security from 5.8.14 to 6.3.3, and upgrade Java EE from 8 to 9.

### Proposed upgrade guidelines

Users of the LDAP plugin must upgrade it to a compatible version in lockstep with upgrading Jenkins core.

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

2024-08-27 23:19 UTC, basil commented on core/pom.xml
> +        </exclusion>
Excluded to avoid increasing API surface area, as this seems to be unused.

2024-08-29 11:42 UTC, MarkEWaite approved these changes
I've been testing versions of this for months with good results.  Thanks!

2024-08-30 05:55 UTC, vwagh-dev approved these changes
LGTM

2024-08-31 08:07 UTC, NotMyFault approved these changes

2024-09-01 21:22 UTC, Kevin-CB commented on core/src/main/java/hudson/search/Search.java
> +    @Deprecated
```suggestion
    @Deprecated
    @StaplerNotDispatchable
```
No need to route it.

2024-09-02 06:44 UTC, Kevin-CB requested changes
The View/doCreateItem method is now defined and should either require POST request or be made non-routable to prevent a CSRF vulnerability.

Additionally, there are several deprecated methods that no longer need to be routable, however, AFAIK they don't pose any security risk.

2024-09-02 15:21 UTC, basil commented
> GitHub won't let me comment on individual lines while I have an in-progress review

@daniel-beck Is that review going to consist of untested suggestions?

> `ParameterizedJobMixin.ParameterizedJob#doBuildWithParameters` was changed incompatibly.

commit b68c552ff3

2024-09-02 15:49 UTC, basil commented on core/src/main/java/hudson/model/View.java
> +    public /* abstract */ Item doCreateItem(StaplerRequest2 req, StaplerResponse2 rsp) throws IOException, ServletException {
I have reverted this suggestion, as it breaks ATH. Can you provide a suggestion that satisfies security requirements and passes ATH?

2024-09-02 16:23 UTC, basil commented on core/src/main/java/hudson/model/View.java
> +    public /* abstract */ Item doCreateItem(StaplerRequest2 req, StaplerResponse2 rsp) throws IOException, ServletException {
I have found a fix that passes ATH by using `@RequirePOST` instead of `@StaplerNotDispatchable`. I am re-resolving this conversation.

2024-09-02 17:18 UTC, basil commented
I have implemented all requested changes and retested this PR in PCT/ATH successfully.

2024-09-03 06:42 UTC, Kevin-CB approved these changes
I tested locally the changes, I'm not able to reproduce the CSRF anymore. 

LGTM, security wise

2024-09-03 11:11 UTC, daniel-beck commented
Another out of place line comment due to GH limitations:

`CrumbIssuer#validateCrumb` does not follow the usual convention of having the new signature call into the deprecated one for overridable methods. As a result, this is incompatible with https://github.com/jenkinsci/strict-crumb-issuer-plugin/blob/1dd2368b98c3e8eca69bf9a3caf20561afd31e35/src/main/java/org/jenkinsci/plugins/strictcrumbissuer/StrictCrumbIssuer.java#L299 and users of the plugin will not have a valid (at least with default options, haven't tried further).

2024-09-03 11:25 UTC, daniel-beck commented
With this PR, https://github.com/jenkinsci/strict-crumb-issuer-plugin/blob/1dd2368b98c3e8eca69bf9a3caf20561afd31e35/src/main/java/org/jenkinsci/plugins/strictcrumbissuer/StrictCrumbIssuer.java#L283-L293 no longer works, as it is not an `HttpServletRequest` anymore, just a `ServletRequest`.

https://github.com/jenkinsci/jenkins/blob/b536707187e0b175c4c495b619df297aa8ae0f75/core/src/main/java/hudson/security/csrf/CrumbIssuer.java#L166-L178 doesn't do what, e.g., [`CompatibleFilter` does, where `instanceof` is checked](https://github.com/jenkinsci/stapler/blob/jakarta/core/src/main/java/org/kohsuke/stapler/CompatibleFilter.java).

Should this be addressed in the plugin, or should this PR be amended to also cast to the subtype when it's `instanceof`, consistent with `CompatibleFilter`?

2024-09-03 17:04 UTC, basil commented
> Should this PR be amended to also cast to the subtype when it's `instanceof`, consistent with `CompatibleFilter`?

commit 520776a0ff0e7294f11277cc8461c6dadefb2af2

2024-09-03 18:30 UTC, daniel-beck reviewed
`BasicHeaderAuthenticator` and `ParameterizedJobMixIn#doBuildWithParameters` look like bugs.

There are a few cases of seemingly wrong override direction in overridable methods, which should be looked at. In addition to the line comments below, there are several additional occurrences in `AbstractProject` in which the old method calls the new method.

The rest of the findings are things that look off enough to warrant a mention, mostly just inconsistencies in the code with no obvious reason.

Otherwise this looks good. I was unable to find security issues, and no further compatibility issues other than those I posted as individual top comments.

2024-09-03 18:38 UTC, basil commented on core/src/main/java/hudson/PluginManager.java
> +        SC_FILE2 {
commit 9de8590183

2024-09-03 18:38 UTC, basil commented on core/src/main/java/hudson/model/ParametersDefinitionProperty.java
> +    public void buildWithParameters(StaplerRequest2 req, StaplerResponse2 rsp, @CheckForNull TimeDuration delay) throws IOException, ServletException {
Yes we should deprecate the plugin.

2024-09-03 18:41 UTC, basil commented on core/src/main/java/hudson/model/ItemGroupMixIn.java
> +    public synchronized TopLevelItem createTopLevelItem(StaplerRequest2 req, StaplerResponse2 rsp) throws IOException, ServletException {
Yes exactly. There are no overrides anywhere in the ecosystem, so simpler this way.

2024-09-03 18:43 UTC, basil commented on core/src/main/java/jenkins/security/ApiTokenProperty.java
> -        public HttpResponse doChangeToken(@AncestorInPath User u, StaplerResponse rsp) throws IOException {
commit fc12e7a703

2024-09-03 18:48 UTC, basil commented on core/src/main/java/jenkins/security/BasicHeaderAuthenticator.java
> +                    + BasicHeaderAuthenticator.class.getSimpleName() + ".authenticate2 methods");
I suppose? I don't really understand this.

commit f735fdcce8

2024-09-03 18:55 UTC, basil commented on core/src/main/java/jenkins/util/HttpSessionListener.java
> +            sessionDestroyed(HttpSessionEventWrapper.toJakartaHttpSessionEvent(httpSessionEvent));
Probably unnecessary, but there for completeness.

2024-09-03 18:56 UTC, basil commented on core/src/main/java/hudson/util/DescribableList.java
> +    }
"Might run into problems" isn't a strong enough reason for me to take action at this point.

2024-09-03 18:57 UTC, basil commented on core/src/main/java/hudson/util/DescribableList.java
> +    public void rebuild(StaplerRequest2 req, JSONObject json, List<? extends Descriptor<T>> descriptors, String prefix) throws FormException, IOException {
commit de295587b8

2024-09-03 19:00 UTC, basil commented on core/src/main/java/hudson/util/FormFieldValidator.java
> +    protected FormFieldValidator(StaplerRequest2 request, StaplerResponse2 response, boolean adminOnly) {
commit 10f333fda8

2024-09-03 19:03 UTC, basil commented on core/src/main/java/jenkins/model/ParameterizedJobMixIn.java
>              getParameterizedJobMixIn().doBuildWithParameters(req, rsp, delay);
commit 96797e92e8

2024-09-03 19:08 UTC, basil commented on core/src/main/java/hudson/util/DescribableList.java
> +        rebuildHetero(StaplerRequest.toStaplerRequest2(req), formData, descriptors, key);
The only subclass is https://github.com/jenkinsci/yaml-project-plugin which has been dead for 9 years, so I am inclined not to bother.

2024-09-03 19:13 UTC, daniel-beck commented on core/src/main/java/hudson/util/DescribableList.java
> +        rebuildHetero(StaplerRequest.toStaplerRequest2(req), formData, descriptors, key);
Fair.

2024-09-03 19:21 UTC, basil commented
> `BasicHeaderAuthenticator` and `ParameterizedJobMixIn#doBuildWithParameters` look like bugs.

Thanks, this is fixed in the most recent revision.

> There are a few cases of seemingly wrong override direction in overridable methods, which should be looked at. In addition to the line comments below, there are several additional occurrences in `AbstractProject` in which the old method calls the new method.

In cases where I couldn't find any overrides or felt that overrides were unlikely, I kept things simple and had the old implementation call the new. This was a bit of a subjective choice to favor simplicity at a slight risk of incorrectness rather than polluting the code with (likely unnecessary) complexity to completely eliminate risk.

> The rest of the findings are things that look off enough to warrant a mention, mostly just inconsistencies in the code with no obvious reason.

Thanks, I have fixed these oversights.

> Otherwise this looks good. I was unable to find security issues, and no further compatibility issues other than those I posted as individual top comments.

Great! Thank you very much.

2024-09-03 19:50 UTC, basil commented
@daniel-beck Can you look at this final set of changes and let me know if this is ready to ship?

2024-09-03 20:17 UTC, daniel-beck approved these changes
:shipit:

2024-09-03 21:59 UTC, merged

2024-09-04 21:41 UTC, daniel-beck commented on core/src/main/java/hudson/model/ParametersDefinitionProperty.java
> +    public void buildWithParameters(StaplerRequest2 req, StaplerResponse2 rsp, @CheckForNull TimeDuration delay) throws IOException, ServletException {
https://github.com/jenkins-infra/update-center2/pull/795