Added test from CLIAction
jenkinsci/jenkins pull request #9992
Opened 2024-11-18 21:41 UTC by lifefire1

## See [JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464)

## Testing done

I added a comprehensive set of unit tests for the `CLIAction` class, which include the following scenarios:

- **Test for the `doCommand()` method**: Verifies that a 404 error is returned when an invalid command is requested.
- **Test for the `doCommand()` method with a valid parameter**: Checks that the correct view dispatcher is called and forwarded when a valid command is provided.
- **Tests for WebSocket-related behavior**:
  - Verifies that a WebSocket connection is not supported.
  - Checks the behavior when the origin header is invalid.
  - Ensures that WebSocket connections are allowed only if both conditions (WebSocket support and allowed origin) are met.
  - Verifies that a `Forbidden` response is returned when WebSocket connections are not allowed.

All tests were executed successfully on a local Jenkins instance.

## Proposed changelog entries

- Added unit tests for `CLIAction` class methods and WebSocket handling.
- Improved test coverage for CLI commands and WebSocket connection handling.

## Proposed upgrade guidelines

N/A

---

## Pull Request Template

```markdown
[tasklist]
### Submitter checklist
- [x] The Jira issue, if it exists, is well-described.
- [x] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood.
- [x] There is automated testing or an explanation as to why this change has no tests.
- [x] New public classes, fields, and methods are annotated with @Restricted or have @since TODO Javadocs, as appropriate.
- [x] New deprecations are annotated with @Deprecated(since = "TODO") or @Deprecated(forRemoval = true, since = "TODO"), if applicable.
- [x] New or substantially changed JavaScript is not defined inline and does not call eval to ease future introduction of Content Security Policy (CSP) directives.
- [x] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [x] For new APIs and extension points, there is a link to at least one consumer.

2024-11-19 09:11 UTC, daniel-beck requested changes

2024-11-19 09:11 UTC, daniel-beck commented on core/pom.xml
> +    </dependency>
Remove and move the test to `test/src/test/`

2024-11-19 09:12 UTC, daniel-beck commented
> See JENKINS-70464

The ticket seems unrelated to this PR, could you explain how they relate?

2024-11-19 11:23 UTC, lifefire1 commented
Perhaps you are right and I really indicated the wrong ticket. I wanted to improve test coverage as a first step

2024-12-26 20:25 UTC, A1exKH requested changes
@lifefire1 code in this PR LGTM. 
Please update description of this PR, because it doesn't match with code now.

2025-06-01 14:22 UTC, NotMyFault commented
I'll go ahead and close this PR, given the changes requested haven't been addressed in a decent amount of time. However, you're welcome to reopen a fixed version of this PR at a later point.

2025-06-01 14:22 UTC, closed without merging